### ISSUE TITLE
No documentation for hiding the entity of an automation

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant.github.io#1002]
I don't have time right now to find a good place to integrate this into the docs. Please someone pick this up 👍 

Introduced in 0.29 via https://github.com/home-assistant/home-assistant/pull/3442

Example config that uses it (see `hide_entity: true`)

```yaml
- alias: Door alarm
  hide_entity: True
  trigger:
    - platform: state
      entity_id: binary_sensor.contact_door
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: 'armed_away'
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.alarm
```

We should also add a link to where ever this info is added from 0.29 release notes.
