### ISSUE TITLE
service: light.toogle doesnt take atributes like service: light.turn_on

### ISSUE THREAD

**Issue by hellcry37** [home-assistant/home-assistant.github.io#10134]
I believe service: light.toggle doesn't take any data that is provided is provided.

docs:
```
Service light.toggle
Toggles the state of one or multiple lights using groups. Takes the same arguments as turn_on service.
```
If i change the color from HA to blue or red for example and use the switch to toggle after it keeps the settings I've selected in HA, doesn't take any of the data provided.

Bulb used: Xiaomi Yeelight model: YLDP02YL
Automation used is one of those:
```yaml
- id: lights_kitchen_toggle
  alias: lights - kitchen toggle
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        event: 1002
        id: wall_switch_1
  action:
    - service: light.toggle
      data:
        entity_id: light.yeelight_bulb3
        brightness: 210
        rgb_color: [255,199,153]
```
or this:
```yaml
- id: lights_kitchen_toggle
  alias: lights - kitchen toggle
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        event: 1002
        id: wall_switch_1
  action:
    - service: light.toggle
      data:
        entity_id: light.yeelight_bulb3
        brightness: 210
        kelvin: 4100
```

if i try the automation with service: light.turn_on works as expected.

note: need toggle because my switch knows how to do only one event linked to deCONZ ConBee II
