### ISSUE TITLE
Trend binary sensor examples unlikely to work

### ISSUE THREAD

**Issue by thompsa** [home-assistant/home-assistant.github.io#10648]
**Home Assistant release with the issue:**
Home Assistant 0.99.0

**Last working Home Assistant release (if known):**

**Operating environment (Hass.io/Docker/Windows/etc.):**
Hass.io

**Integration:**
https://www.home-assistant.io/integrations/trend

**Description of problem:**
The trend component defaults to max_samples of two and creates a deque object to hold the samples with a `maxlen` of `max_samples` elements long. 

In trend_sensor_state_listener() when a new sample is appended the deque library automatically pop off any samples if it is now over `maxlen`.  The documentation and examples suggest that the samples are taken over `sample_duration` and gives a `...collects samples over a two hour period...` example for temperature. The example doesnt set `max_samples` so this is going to be two, whenever a sensor sample is taken it is going to drop the third sample off automatically in the deque library, the example will only work if the entity_id referenced has a 2 hour refresh, any more frequent and the sample set will not be two hours. 

The trend sensor will still work but will be calculating the gradient on a much shorter sample duration than requested and will give odd results. Essentially `sample_duration` is ignored and it will always be comparing the current and previous sample.

This could be fixed in documentation by extending the paragraph.

> Each time the state changes, a new sample is stored along with the sample time. Samples older than sample_duration seconds will be discarded. The max_samples parameter must be large enough to store sensor updates over the requested duration. If you want to trend over two hours and your sensor updates every 120s then then max_samples must be at least 60, eg 7200/120 = 60. 

Also update the example to show max_samples must be larger,
```yaml
binary_sensor:
  - platform: trend
    sensors:
      temp_falling:
        entity_id: sensor.outside_temperature
        sample_duration: 7200
        max_samples: 120
        min_gradient: -0.0008
        device_class: cold

      temp_rising:
        entity_id: sensor.outside_temperature
        sample_duration: 7200
        max_samples: 120
        min_gradient: 0.0008
        device_class: heat
```

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml
- platform: trend
  sensors:
    cylinder_top_heating:
      entity_id: sensor.cylinder_top_temp
      sample_duration: 600
      min_gradient: 0.0014
      device_class: heat
    cylinder_middle_heating:
      entity_id: sensor.cylinder_middle_temp
      sample_duration: 600
      min_gradient: 0.0014
      device_class: heat
    cylinder_bottom_heating:
      entity_id: sensor.cylinder_bottom_temp
      sample_duration: 600
      min_gradient: 0.0014
      device_class: heat
```

**Traceback (if applicable):**
```

```

**Additional information:**

**Comment by frenck** [comment]
I've moved this issue over to the documentation repository.

**Comment by frenck** [comment]
### 🆘 Marked as "Help wanted"

If you want to help out on this, go ahead, it is really appreciated!

Please leave a comment if you started working on this, so we can avoid multiple people working on the same things. Thanks! 👍

**Comment by Jsifontez** [comment]
I want to help with this :smiley:

**Comment by Jsifontez** [comment]
I need to add the following entries the `configuration.yaml` example?:

```
- platform: trend
  sensors:
    cylinder_top_heating:
      entity_id: sensor.cylinder_top_temp
      sample_duration: 600
      min_gradient: 0.0014
      device_class: heat
    cylinder_middle_heating:
      entity_id: sensor.cylinder_middle_temp
      sample_duration: 600
      min_gradient: 0.0014
      device_class: heat
    cylinder_bottom_heating:
      entity_id: sensor.cylinder_bottom_temp
      sample_duration: 600
      min_gradient: 0.0014
      device_class: heat
```
