### ISSUE TITLE
Icons, input_boolean as a custom switch and lights

### ISSUE THREAD

**Issue by Alex9779** [home-assistant/home-assistant.github.io#11219]
Sorry but to describe I have to explain a little.
What I wanted was a custom on/off switch in my lovelace UI to activate a time and on the other hand a so called "nightmode" which are then used in automations or Node-Red to change the behaviour of the system.
I started with an input_boolean integration and placed it with an entity card on my UI, rednered as a on/off switch, nice with a generic icon.
What I then wanted was a custom icon. The input_boolean can have a custom icon so I set that. Well but I wanted an icon acting like the icon for a light which turns yellow when activated and normal when not to be able to use an entity card which just shows the icon and the name.
I found that I have to use a template light controlling the input_boolean like this:
```
input_boolean:
  nh_2_venta_night_mode:
    name: Nachtmodus
light:
  - platform: template
    lights:
      nh_2_venta_night_mode:
        friendly_name: Nachtmodus
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.nh_2_venta_night_mode
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.nh_2_venta_night_mode
```
But then the light shows the normal light bulp.
I read further in the docs and found I have to use an icon_termplate.

The problem here is that it seems for me the docs are somehow outdated because using the documented way to have different icons for on and offf just shows me one icon but turning yellow if activated and normal if deactivated.
Is used this (just an example):
```
icon_template: >-
        {% if is_state('input_boolean.nh_2_venta_night_mode', 'on') %}
          mdi:folder-clock
        {% else %}
          mdi:link
        {% endif %}
```
But all I see in the UI is the link icon turning from normal to yellow.

I ended up with:
```
icon_template: >-
        mdi:weather-night
```
That is not a template anymore just one icon, which turns yellow if I activate the switch. So I got what I wanted but documentation was not helpful and it seems not to work anymore like it is documented...

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Considering your question, it is not about changing the icons itself, but the color of the icon. There is no feature for doing that.

Thanks! 👍

**Comment by Alex9779** [comment]
Just to add, I realized that I don't need the input_boolean if I just want a dummy light to switch on and off and to get the state from:
```
light:
- platform: template
  lights:
    nh_2_venta_night_mode:
      friendly_name: Nachtmodus
      icon_template: >-
        mdi:weather-night
      turn_on:
      turn_off:
```
This is also valid though turn_on and turn_off are required but the action is optional, so both can be optional too IMHO...
