### ISSUE TITLE
Device ID gets truncated when used in sensor template.

### ISSUE THREAD

**Issue by tpressure** [home-assistant/home-assistant.github.io#11579]
Hi,

I am using the following configuration [1] to read valve state of my thermostat.

```yaml
sensor:
- platform: template
  sensors:
    valve_living_room:
        value_template: '{{ states.climate.heating_living_room.attributes.level }}'
        friendly_name: 'Valve - Living Room'
        unit_of_measurement: '%'
```

It works great for named devices, but does not work for devices that only appear as device ID because the ID gets truncated.

E.g. when I replace
```yaml
value_template: '{{ states.climate.heating_living_room.attributes.level }}'
```

with 

```yaml
value_template: '{{ states.climate.002018a99c1e7c.attributes.level }}'
```

I get the following error message:

```
Invalid config for [sensor.template]: invalid template (TemplateSyntaxError: expected token 'end of print statement', got 'a99c1e7c') for dictionary value @ data['sensors']['valve_work']['value_template']. Got '{{ states.climate.002018a99c1e7c.attributes.level }}'. (See ?, line ?). Please check the docs at https://home-assistant.io/integrations/template/
```

From what this looks to me, the ID gets trunctated to an 32bit integer which cannot represent the number of the ID.
