### ISSUE TITLE
pi-hole documentation: single pi-hole install expects dictionary

### ISSUE THREAD

**Issue by gsacre** [home-assistant/home-assistant.github.io#11880]
## The problem
The pi-hole documentation shows the following examples for single pi-hole deployment:
```yaml
pi_hole:
  - host: 'pi.hole'
    api_key: !secret pi_hole_api_key
```

However, this returns in error in Home Assistant:
```
2020-01-26 12:20:31 ERROR (MainThread) [homeassistant.config] Invalid config for [pi_hole]: expected a dictionary for dictionary value @ data['pi_hole']. Got [OrderedDict([('host', '<REMOVED>'), ('name', 'Primary Pi-Hole'), ('api_key', '<REMOVED>')])]. (See /config/configuration.yaml, line 45). Please check the docs at https://home-assistant.io/integrations/pi_hole/
```

Removing the leading dash resulted in a successful integration:
```yaml
pi_hole:
  host: 'pi.hole'
  api_key: !secret pi_hole_api_key
```

Not having two pi-holes installation, I don't know if the dashes are needed for listing more than one instance...
