### ISSUE TITLE
greeneye_monitor temperature sensor documentation does not match the example

### ISSUE THREAD

**Issue by ptr727** [home-assistant/home-assistant.github.io#12099]
## The problem

The greeneye_monitor temperature sensor documentation does not match the example.
See: https://www.home-assistant.io/integrations/greeneye_monitor/

Per example:
```yaml
greeneye_monitor:
  port: 8000
  monitors:
    - serial_number: "YOUR_SERIAL_NUMBER"
      temperature_sensors:
        - number: 1
          name: back_porch_temperature
```

Per docs, and passes validation:
```yaml
greeneye_monitor:
  port: 8000
  monitors:
    - serial_number: "YOUR_SERIAL_NUMBER"
      temperature_sensors:
        temperature_unit: "C"
        sensors:
          - number: 1
            name: back_porch_temperature
```
