### ISSUE TITLE
binary_sensor.updater (beta) pointing to incorrect release notes

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/home-assistant.github.io#12134]
## The problem

as title

## Environment

- Home Assistant release with the issue: 105.5
- Last working Home Assistant release (if known): none
- Operating environment (Hass.io/Docker/Windows/etc.): Hass.io
- Integration causing this issue: updater
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/updater/

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

## Additional information

while the binary_sensor.updater should point to the beta release notes when system settings Supervisor is in beta mode, it currently points to:
```
release_notes: 'https://www.home-assistant.io/latest-release-notes/'
```

<img width="863" alt="Schermafbeelding 2020-02-19 om 23 00 27" src="https://user-images.githubusercontent.com/33354141/74880496-a3a00200-536b-11ea-9bdc-7eaf68350a98.png">

please note that the current.version rest sensor, 

```
  - platform: rest
    name: Ha current version
    resource: https://www.home-assistant.io/version.json
    value_template: >
      {{ value_json.current_version }}
    json_attributes:
#      - current_version
      - release_date
      - release_notes
      - release_notes_path
      - release_title
      - release_description
      - patch_version_notes
      - root_url
      - semantic_version
```
while at 0.105.5, points to an incorrect 
```
https://www.home-assistant.io/blog/2020/02/11/android-16-17-release/
```
too.

<img width="366" alt="Schermafbeelding 2020-02-19 om 23 05 02" src="https://user-images.githubusercontent.com/33354141/74880798-4e182500-536c-11ea-8d8a-337b71eedf35.png">
