### ISSUE TITLE
history_stats refers to from and to, which are not accessible

### ISSUE THREAD

**Issue by lindsaymarkward** [home-assistant/home-assistant.github.io#12949]
## The problem

On the page https://www.home-assistant.io/integrations/history_stats/ at the bottom, it says:
> If you want to check if your period is right, just click on your component, the from and to attributes will show the start and end of the period, nicely formatted.

I am unable to find this. It is unclear what "click on your component" means and what page you can find that. I have clicked on the history_stats UI element in the main Lovelace frontend, in the dev tools > states page and the configuration > entities page.  
In none of these can I find a "from" and "to" (or a start and end).

Can this be reworded, corrected or removed please?
Thank you!

**Comment by akasma74** [comment]
I can add that the only attributes I can see for this config
```yaml
- platform: history_stats
  name: tst
  entity_id: switch.combi_boiler
  type: time
  state: 'on'
  start: >-
    {% set ts = state_attr('input_datetime.tst', 'timestamp') %}
    {% set ts_str = ts | timestamp_custom("%Y-%m-%d %H:%M:%S %z") %}
    {% set dt_aware = strptime(ts_str, "%Y-%m-%d %H:%M:%S %z") %}
    {{ dt_aware }}
  end: "{{ now() }}"
```
are

> value: 1h 45m
> unit_of_measurement: h
> friendly_name: tst
> icon: mdi:chart-line

and the [code](https://github.com/home-assistant/core/blob/0.108.3/homeassistant/components/history_stats/sensor.py#L166) (I'm on 0.108.3 atm) returns only `value` (ATTR_VALUE), no sign of ATTR_FROM/TO (seems like the docs were not updated for quite a while) so the easiest way is to remove it from the docs completely **but** it would be much better to add these attributes to `device_state_attributes` result - a PR to HA core? ;)
