### ISSUE TITLE
Scene transition example of automation does not work

### ISSUE THREAD

**Issue by haagar** [home-assistant/home-assistant.github.io#13251]
## Scene transition example of automation does not work

The example shows the following, which does not work for me:

```
action:
    service: scene.turn_on
    data:
      entity_id: scene.romantic
      transition: 2.5
```

while editing through the automation ui moves the entity_id out of the   data section and does work:

```
action:
    service: scene.turn_on
    entity_id: scene.bathroom_lights_off
    data:
      transition: 2.5
```
