### ISSUE TITLE
[ISS] Map in Documentation doesn't work

### ISSUE THREAD

**Issue by minchinweb** [home-assistant/home-assistant.github.io#13284]
The [documentation of the ISS sensor](https://www.home-assistant.io/integrations/iss/) has a handy example of how to include a map of the station's location at the bottom of the page:

```yaml
# Example configuration.yaml entry
camera:
  - platform: generic
    name: ISS
    still_image_url: http://staticmap.openstreetmap.de/staticmap.php?center={{ state_attr('binary_sensor.iss', 'lat') }},{{ state_attr('binary_sensor.iss', 'long') }}&zoom=4&size=865x512&maptype=mapnik&markers={{ state_attr('binary_sensor.iss', 'lat') }},{{ state_attr('binary_sensor.iss', 'long') }},lightblue
    limit_refetch_to_url_change: true
```

However, the server won't produce an image, instead demanding a referrer header:

![image](https://user-images.githubusercontent.com/1548809/80934957-b7161300-8d87-11ea-83d1-aa362c2cb2b8.png)

It seems that it should be simple to provide a referrer, but I can't figure out how to do it, and maybe it's not possible with a simple URL.

My preferred solution would be to update the URL so it works. Alternately, maybe the camera platform could be extended to optionally provide a referrer. If neither of those two are possible, then may the example should be removed (but that would be sad...).

I would love to get this to work. Thanks for all your help.
