### ISSUE TITLE
Add SQLite "Database size" example

### ISSUE THREAD

**Issue by Moonbase59** [home-assistant/home-assistant.github.io#13715]
## The problem

On the [HA SQL page](source/_integrations/sql.markdown), there are some examples for the database size. **An example for SQLite is missing.** Since I’ve seen a lot of [bad examples](https://community.home-assistant.io/t/calculate-home-assistant-v2-db-size-without-whitelisting-entire-config-dir/195808), it might be nice to include my version:

```yaml
sensor:
  # HA database size
  - platform: sql
    # Not needed when using recorder, because we already have a connection.
    # Absolute path begins after the 3rd "/" (location for Hassbian).
    #db_url: sqlite:////home/homeassistant/.homeassistant/home-assistant_v2.db
    scan_interval: 300
    queries:
      - name: DB Size
        # This is the fastest solution, available since sqlite 3.16.
        # It’s the same info as returned by ".dbinfo" in the sqlite3 cmdline client.
        query: 'SELECT ROUND(page_count * page_size / 1024 / 1024, 1) as size FROM pragma_page_count(), pragma_page_size();'
        column: 'size'
        unit_of_measurement: 'MiB'
```

(Might need some changes, i.e. move explanations from code to text …)
