### ISSUE TITLE
Broadlink documentation does not seem to be up to date

### ISSUE THREAD

**Issue by Dinth** [home-assistant/home-assistant.github.io#14132]
## The problem
The documentation of Broadlink says in "HOW TO OBTAIN IR/RF PACKETS" section:
`Choose Call Service from the Developer Tools. Choose the service broadlink.learn from the list of Available services:, write in “Service Data” JSON with 1 field “host”:“your_broadlink_IP” and hit CALL SERVICE. Press the button on your remote with in 20 seconds. The packet will be printed as a persistent notification in the States page of the web interface.`
But there's no broadlink.learn service after setting up broadlink.
I believe it was replaced with remote.learn sensor, but i believe it works differently. Since i am struggling with capturing ir codes, i cannot update the documentation myself.

**Comment by Thunderbird2086** [comment]
Did you add your broad link to `switch`? 

Here is mine,
```
switch:
  - platform: broadlink 
    host: !secret broadlink_rm3_addr_03
    mac: !secret broadlink_rm3_mac_03
    #type: rm3_pro
    friendly_name: 'rm3 pro(Master room)'

  - platform: broadlink 
    host: !secret broadlink_rm4_addr_01
    mac: !secret broadlink_rm4_mac_01
    type: rm4_pro
    friendly_name: 'rm4 pro(Living room)'
```

and I am able to invoke `broadlink.learn` as below.
![Screen Shot 2020-08-15 at 20 17 47](https://user-images.githubusercontent.com/37539914/90311341-eca8cb80-df34-11ea-8a22-fd9cfd8b7904.png)
