### ISSUE TITLE
The Automation Trigger page should specify that you can use multiple entity_id properties for the same state trigger

### ISSUE THREAD

**Issue by melyux** [home-assistant/home-assistant.github.io#14304]
## The problem

The [Automation Trigger](https://www.home-assistant.io/docs/automation/trigger/) documentation page's section on state triggers is quite brief, and doesn't specify that you can use multiple entities under a list of `entity_id`, as can be seen in this example in [this blog post about version 0.113](https://www.home-assistant.io/blog/2020/07/22/release-113/#automations--scripts-chooser):

```yaml
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.button1
          - binary_sensor.button2
          - binary_sensor.button3
```
