### ISSUE TITLE
Error in value_template: {{ states.sensor.furnace.state > 2.5 }}

### ISSUE THREAD

**Issue by Genestealer** [home-assistant/home-assistant.github.io#1441]
I believe the line "value_template: {{ states.sensor.furnace.state > 2.5 }}" is incorrect.

**Comment by Genestealer** [comment]
I believe it should change from:
```yaml
sensor:
  - platform: template
    sensors:
      furnace_on:
        value_template: {{ states.sensor.furnace.state > 2.5 }}
        friendly_name: 'Furnace Running
        sensor_class: heat`
```
to
```yaml
binary_sensor:
  - platform: template
    sensors:
      furnace_on:
        value_template: '{{ states.sensors.furnace | float > 2.5}}'
        friendly_name: 'Furnace Running'
        sensor_class: heat
```

Changes:
- sensor to binary_sensor
- ".furnace.state" is now ".furnace"
- convert "states.sensors.furnace" to flote
