### ISSUE TITLE
State triggers on attributes as described in the docs validate, but fail to load

### ISSUE THREAD

**Issue by rccoleman** [home-assistant/home-assistant.github.io#14460]
## The problem

I'm trying to follow the example for attribute-based triggers and I'm finding some strange behavior.  Some of it may be code and some documentation, so I'm lumping them together here.

This is from the docs:

> When the attribute option is specified, all of the above works, but only applies to the specific state value of that attribute.
> 
> For example, this trigger only fires if the boiler was heating for 10 minutes:

```yaml
automation:
  trigger:
    platform: state
    entity_id: climate.living_room
    attribute: hvac_action
    state: "heating"
```

First, that code doesn't actually do what the description says :).  Adding the following would help, if that's the intention:

```yaml
    for:
      minutes: 10
```

If I follow that model for one of my automations, like this:

```yaml
  trigger:
    - platform: state
      entity_id: remote.bedroom
      attribute: current_activity
      state: "Watch Shield"
      for:
        seconds: 2
```

it validates successfully with `ha core check`, but reloading automations chokes on it with this:

`2020-09-10 09:59:48 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: [state] is an invalid option for [automation]. Check: automation->state. (See /config/configuration.yaml, line 242). `

So it doesn't like the new `state:` tag.  If I change it to `to:`, it both validates and loads fine, but I have yet to see if it actually works as expected.

Either way, in my opinion, `state:` is a confusing way to specify the value of an attribute, even if it's ultimately a "state" trigger.  I can see people getting confused and using `state:` to specify an actual state, rather than the `to:`/`from:` that are expected.  The answer would be to read the docs, but I can certainly see many making that mistake, especially since a "state" condition *does* use `state:` for an actual "state".

## Environment

- Home Assistant Core release with the issue: 0.115.0b4
- Last working Home Assistant Core release (if known): N/A
- Operating environment (OS/Container/Supervised/Core): OS
- Integration causing this issue: automation trigger
- Link to integration documentation on our website: https://rc.home-assistant.io/docs/automation/trigger/

## Problem-relevant `configuration.yaml`

See above.

## Traceback/Error logs

When reloading automations with the above YAML, I get this:

```txt
2020-09-10 09:59:48 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: [state] is an invalid option for [automation]. Check: automation->state. (See /config/configuration.yaml, line 242). 
```
