### ISSUE TITLE
Missing configuration alternative for ZHA

### ISSUE THREAD

**Issue by prilly-dev** [home-assistant/home-assistant.github.io#15307]
## The problem

There are multiple configurations parameters that can be see in regards to the ZHA integration with zigpy.

See here: https://github.com/zigpy/zigpy/issues/154

```
zha:
  zigpy_config:
    database_path: /path/to/your/zigbee.db

    device:
      path: /dev/serial/by-id/yourPort
      #baudrate: 12345         # Most radios have a default for this
      #flow_control: software  # Optional for some radios


    #################################################
    # Everything past this point is set by default. #
    #  You probably don't need to change anything.  #
    #################################################


    # OTA config. Nothing is enabled by default
    ota:
      ikea_provider: false                       # Auto update Trådfri devices
      ledvance_provider: false                   # Auto update LEDVANCE devices
      #otau_directory: /path/to/your/ota/folder  # Utilize .ota files to update everything else

    # Default network settings
    network:
      channel: 15             # What channel the radio should try to use.
      channels: [15, 20, 25]  # Channel mask
      extended_pan_id: null   # Will be set to a random value if not provided
      key: null
      key_sequence_number: 0  # Used by some radios to indicate that the key has been updated
      pan_id: null            # Will be set to a random value if not provided
      tc_address: null
      tc_link_key: [0x5A, 0x69, 0x67, 0x42, 0x65, 0x65, 0x41, 0x6C, 0x6C, 0x69, 0x61, 0x6E, 0x63, 0x65, 0x30, 0x39]
      update_id: 0            # Used by some radios to indicate that the network config has been updated

    # Used by zigpy-znp
    znp_config:
      tx_power: 0  # Max is +19
      sync_request_timeout: 5
      auto_reconnect_retry_delay: 5
    
    # Used by bellows
    source_routing: false
    ezsp_config: {}  # Tons and tons of options
                     # See https://github.com/zigpy/bellows/blob/dev/bellows/config/ezsp.py
```

It would have been nice to update the documentaion regarding the possibility of channel change,

**Comment by Gamester17** [comment]
@prilly-dev  #15310 by @atxbyea only adds some of the channel and network configuration that you would like added, right?

There is already a section about "OTA FIRMWARE UPDATES" which could be extended with anything missing for OTA config:

https://www.home-assistant.io/integrations/zha/

After that, only things missing then are the radio-library specific (hardware-specific) configs for zigpy-znp and bellows, or?

**Comment by prilly-dev** [comment]
Thanks guys, i feel the most important was the possibility to do channel change, as i have seen alot of questions regarding that and multiple ways of doing it, including code changes. Ofcourse the best is to highlite that this is the right way.

In regards to OTA there is a section mentioning it, but the configuration is not complete. currently there is some error in the IKEA firmware repository used by ota: https://github.com/zigpy/zigpy/issues/497

It might be a good thing to mention how to use the BETA firmware repository for IKEA devices:

```
zha:
  zigpy_config:
    ota:
      ikea_provider: true
      ikea_update_url: http://fw.test.ota.homesmart.ikea.net/feed/version_info.json

```

Device specific configurations is probably best to leave out, but maybe give a hint and point to the zigpy github for advance configuration options.
