### ISSUE TITLE
The manual alarm integration machin state doc is nolonger valide.

### ISSUE THREAD

**Issue by poofyteddy** [home-assistant/home-assistant.github.io#15305]
## The problem

on [this page](https://www.home-assistant.io/integrations/manual#state-machine), the doc say

> Note that code_template never receives “arming” in the to_state variable; instead, to_state contains the state which the user has requested

But with this automation i can the that it's no-longer true.
```
- id: test_alarm_state
  trigger:
    - platform: state
      entity_id: alarm_control_panel.test_alarm
  action:
    - service: system_log.write
      data_template:
        message: 'alarm to state: {{ trigger.to_state }}'
        level: warning
```
i get
```
state arming, expecting to_state armed_away

oct. 18 19:26:28 ap-univm-016 hass[120772]: 2020-10-18 19:26:28 WARNING (MainThread) [homeassistant.components.system_log.external] alarm to state: <state alarm_control_panel.house_alarm=arming; code_format=number, changed_by=None, code_a
rm_required=False, previous_state=disarmed, next_state=armed_away, friendly_name=House_Alarm, supported_features=31 @ 2020-10-18T19:26:28.934244+02:00>

state armed_away
oct. 18 19:27:28 ap-univm-016 hass[120772]: 2020-10-18 19:27:28 WARNING (MainThread) [homeassistant.components.system_log.external] alarm to state: <state alarm_control_panel.house_alarm=armed_away; code_format=number, changed_by=None, co
de_arm_required=False, friendly_name=House_Alarm, supported_features=31 @ 2020-10-18T19:27:28.936074+02:00>
```
I liked the old state maching because it enabled to do stuff based on what the used whanted, without having to make the workaround for activation without delay (that don't have a "next_state" to use)
but that not the issue here.

I have no idea when it changed, but if the person in charge of the integration (who is best at knowing how it should work) could update the doc it would be very sweet :)
