### ISSUE TITLE
Howto display statistics

### ISSUE THREAD

**Issue by mbbs1024** [home-assistant/home-assistant.github.io#16571]
**Feedback**

Is it possible to add some more information on how to display statistics information in the help page ?
There is an example on how to put statistics in configuration.yaml, and below there is a picture of the stats from the cpu sensor.
But it is not described how you create this statistics view

I am trying to create statistics on energy usage, but I don't know how to display the statistics on the sensor kwartierpiek.
I would like to display the maximum and mean value over a year.

```yaml
# HomeWizard P1 meter
  - platform: template
    sensors:
      kwartierpiek_t1t2:
        friendly_name: kwartierpiek
        unit_of_measurement: kWh
        value_template: "{{ (states('sensor.kwartierpiek_t1')|float + states('sensor.kwartierpiek_t2')|float) | round(3)}}"

  - platform: statistics
    entity_id: sensor.kwartierpiek
    max_age:
      days: 365

utility_meter:
  kwartierpiek_t1:
    source: sensor.p1_meter_total_power_import_t1
    cycle: quarter-hourly
  daily_energy_peak:
    source: sensor.p1_meter_total_power_import_t1
    cycle: daily
  daily_injection_peak:
    source: sensor.p1_meter_total_power_export_t1
    cycle: daily
  kwartierpiek_t2:
    source: sensor.p1_meter_total_power_import_t2
    cycle: quarter-hourly
  daily_energy_offpeak:
    source: sensor.p1_meter_total_power_import_t2
    cycle: daily
```

**URL**

https://www.home-assistant.io/integrations/statistics/

**Version**

2021.2.3
