### ISSUE TITLE
I have Fibaro HC3 and would love to use this integration

### ISSUE THREAD

**Issue by dkcsn** [home-assistant/home-assistant.github.io#16581]
**Feedback**

First Thank you for providing and creating this integration - i really appreciate this work

I need a little extra help :-) dont understand these examples. 

Is it a whitelist for devices being synced?
The syntex is light_device_name_123
Where "light" is device role or Category
"device" is the number for the device
and name is - the Hc3 device name ?

or it it something else?
could you put an example where i could see the HC3 device and HA yaml ?

Second - is there a way to control devices being synced - eg if i only wanted door and windows sensors synced.

```yaml
   device_config:
        light_device_name_123:
          color: false
          white_value: false
          reset_color: true
        binary_device_name_123:
          device_class: "garage_door"
          icon: mdi:open
```

**URL**

https://www.home-assistant.io/integrations/fibaro/

**Version**

2021.2.3
