### ISSUE TITLE
Scripting page does not provide reading arguments howto 

### ISSUE THREAD

**Issue by a-x-** [home-assistant/home-assistant.github.io#16654]
**Feedback**

Alongside, at the [template light page](https://www.home-assistant.io/integrations/light.template/) scripts accept arguments 

for example:
```yaml

        set_level:
          service: script.theater_lights_level
          data:
            brightness: "{{ brightness }}"
```

**URL**

https://www.home-assistant.io/docs/scripts/

**Version**

2021.2.3
