### ISSUE TITLE
Separate config entries for command_line switches

### ISSUE THREAD

**Issue by robbieh** [home-assistant/home-assistant.github.io#16814]
### Feedback

I'd like to be able to use "style 2" to define command_line switches, as documented here:
https://www.home-assistant.io/docs/configuration/devices/

But I cannot get that to work. Here's what I'm trying:

```
switch test_solenoid:
  platform: command_line
  command_on: '/usr/bin/usbrelay BITFT_1=1'
  command_off: '/usr/bin/usbrelay BITFT_1=0'
  command_state: '/usr/local/bin/check_usbrelay_state BITFT_1'
```

The result of doing that is: "Invalid config for [switch.command_line]: [command_on] is an invalid option for [switch.command_line]."

### URL

https://www.home-assistant.io/integrations/switch.command_line/

### Version

2021.2.3

**Comment by frenck** [comment]
That is correct, as per command_line switch documentation, it needs a switches key:

```yaml
switch test_solenoid:
  platform: command_line
  switches:
    some_command:
      command_on: '/usr/bin/usbrelay BITFT_1=1'
      command_off: '/usr/bin/usbrelay BITFT_1=0'
      command_state: '/usr/local/bin/check_usbrelay_state BITFT_1'
```

**Comment by robbieh** [comment]
I'm not sure you understood the question.

How do I break up multiple command_line switches when I have a more complex configuration?

**Comment by frenck** [comment]
```yaml

switch first_one:
  platform: command_line
  switches:
    some_command:
      command_on: '/usr/bin/usbrelay BITFT_1=1'
      command_off: '/usr/bin/usbrelay BITFT_1=0'
      command_state: '/usr/local/bin/check_usbrelay_state BITFT_1'
      
switch second_one:
  platform: command_line
  switches:
    some_command:
      command_on: '/usr/bin/usbrelay BITFT_2=1'
      command_off: '/usr/bin/usbrelay BITFT_2=0'
      command_state: '/usr/local/bin/check_usbrelay_state BITFT_2'
      
switch third_one:
  platform: command_line
  switches:
    some_command:
      command_on: '/usr/bin/usbrelay BITFT_3=1'
      command_off: '/usr/bin/usbrelay BITFT_3=0'
      command_state: '/usr/local/bin/check_usbrelay_state BITFT_3'
```

**Comment by willyum2n** [comment]
@frenck - The example you provided doesn't quite seem to work but is very close. With the example you provided, you end up with a single switch entity called "some_command". However, if you change your example to the following it works:

```yaml
switch first_one:
  platform: command_line
  switches:
    first_one:
      command_on: '/usr/bin/usbrelay BITFT_1=1'
      command_off: '/usr/bin/usbrelay BITFT_1=0'
      command_state: '/usr/local/bin/check_usbrelay_state BITFT_1'
      
switch second_one:
  platform: command_line
  switches:
    second_one:
      command_on: '/usr/bin/usbrelay BITFT_2=1'
      command_off: '/usr/bin/usbrelay BITFT_2=0'
      command_state: '/usr/local/bin/check_usbrelay_state BITFT_2'
      
switch third_one:
  platform: command_line
  switches:
    third_one:
      command_on: '/usr/bin/usbrelay BITFT_3=1'
      command_off: '/usr/bin/usbrelay BITFT_3=0'
      command_state: '/usr/local/bin/check_usbrelay_state BITFT_3'
```

I noticed that you must add the name at the top of each stanza or each switch declaration will be overwritten by the next stanza. This works:
```yaml
switch name1:
  platform: command_line
  switches:
    name1:
    ...
switch name2:
  platform: command_line
  switches:
    name2:
    ...
switch name3:
  platform: command_line
  switches:
    name3:
    ...
```

But this **_will not_** work. You'll only end up with a single "name3" switch

```yaml
switch:
  platform: command_line
  switches:
    name1:
    ...
switch:
  platform: command_line
  switches:
    name2:
    ...
switch:
  platform: command_line
  switches:
    name3:
    ...
```

The name for each switch must be in the top-level switch declaration, and then also in the switches list with the name being unique or it will be overwritten by any subsequent declaration with the same name
