### ISSUE TITLE
Please provide some examples 

### ISSUE THREAD

**Issue by oywino** [home-assistant/home-assistant.github.io#16877]
### Feedback

The page contains several configuration.yaml examples, and that's good. But once a universal media player is created, how could it be used?  Please provide som examples on automations were this "virtual player" is used, and perhaps also front end card sample showing how it can be used.

### URL

https://www.home-assistant.io/integrations/universal/

### Version

2021.3.1

**Comment by frenck** [comment]
As any normal media player in Home Assistant. Every integration in Home Assistant provides a standard set of entity types (platforms). In this case; the result is a normal media player.

**Comment by oywino** [comment]
But wherein lies the benefit (savings)?  Looking at the Harmony example, here is a snap-shot from a button card I currently have working:

```
    tap_action:
      action: call-service
      service: remote.turn_on
      service_data:
        activity: 'Listen to Music'
        entity_id: remote.harmony
```
How would this look different if I had a universal media player created ?
