### ISSUE TITLE
System log as trigger

### ISSUE THREAD

**Issue by Madlost87** [home-assistant/home-assistant.github.io#16937]
### Feedback

I need to use warning system-log as a trigger in automation

### URL

https://www.home-assistant.io/integrations/system_log/

### Version

2021.3.3

Grazie

**Comment by SeanPM5** [comment]
There's already an example automation of that on the page, see the "Counting Number of Warnings" section under [Examples](https://www.home-assistant.io/integrations/system_log/#examples). The trigger would look like this:

```
trigger:
  platform: event
  event_type: system_log_event
  event_data:
    level: WARNING
```

For support questions like this, you can use the [Discord chat](https://discord.gg/c5DvZ4e) server or the [community forum](https://community.home-assistant.io/). Huge community of folks that will be able to assist you.
