### ISSUE TITLE
Actions documentation is missing the new `target` key for calling services

### ISSUE THREAD

**Issue by denilsonsa** [home-assistant/home-assistant.github.io#16992]
### Feedback

It is now possible to pass `target` to service calls: https://github.com/home-assistant/home-assistant.io/pull/15891/files

This feature is already supported in the actions themselves (I've only tested with `tap_action`, though), but the documentation is missing.

### URL

https://www.home-assistant.io/lovelace/actions/

### Version

2021.3.4

Sample lovelace code:

```yaml
type: entities
entities:
  - type: buttons
    entities:
      - entity: light.bedroom_lights
        name: 1min
        icon: 'mdi:lightbulb-on'
        tap_action:
          action: call-service
          service: light.turn_on
          service_data:
            transition: 60
            color_temp: 450
            brightness_pct: 100
          target:  # ← This is missing in the documentation!
            entity_id:
              - light.bedroom_lights
              - light.foobar
```
