### ISSUE TITLE
Maybe wrong variable name?

### ISSUE THREAD

**Issue by TomMajer** [home-assistant/home-assistant.github.io#17136]
### Feedback

I'm not sure whether variable "sensor" is correct. Shouldn't it be a "model" instead? With examples from page I'm getting yaml error: [sensor] is an invalid option for [sensor.dht].

### URL

https://www.home-assistant.io/integrations/dht/

### Version

2021.3.4

Hello.
I'm not sure If I'm not doing something wrong but using examples from page I get to problem with yaml syntax and get errors before uploading using esphome. Problem is in "sensor" variable. 

Error is: [sensor] is an invalid option for [sensor.dht]
Now working config (copied from page):
```
# Example configuration.yaml entry
sensor:
  platform: dht
  sensor: DHT22
  pin: 23
  monitored_conditions:
    - temperature
    - humidity
```

Page shows:
**sensor** string REQUIRED
The sensor type, supported devices are DHT11, DHT22, and AM2302.

After many attempts I found page https://community.home-assistant.io/t/dht22-random-fake-temperature/83415/14 where someone replaced "sensor" with "model" like this:
```
 - platform: dht
    pin: D5
    model: DHT22
```
Suddenly it works for me.
