### ISSUE TITLE
The script examples for choosing a group of actions, doesnt show script examples, but automation.

### ISSUE THREAD

**Issue by TheQue42** [home-assistant/home-assistant.github.io#17208]
### Feedback

I am trying to understand how to use OR conditions together with CHOOSE for scripts. But the examples on the page, shows the syntax for automations, which causes somewhat different datastrutures for choose and condition objects.

When trying to understand how I can add to conditions that are OR:ed together instead of AND:ed, the difference is quite vital.

When choose/condition objects vary between map or list-element, its difficult to understand how to add the "condition: or"
to the below example:

```
choose:
  - conditions:
      - condition: template
        value_template: '{{option1a == "option1a"}}'
      - condition: template
        value_template: '{{option1b == "option1b"}}'
    sequence:
      - service: homeassistant.turn_on
        target:
          device_id: d46c720c7465b01df123180f577aef40
  - conditions:
      - condition: template
        value_template: '{{option2 == "option2"}}'
    sequence:
      - service: homeassistant.turn_on
        target:
          device_id: d46c720c7465b01df123180f577aef40
default:
  - service: automation.reload
```
 

### URL

https://www.home-assistant.io/docs/scripts/

### Version

2021.3.4
