### ISSUE TITLE
Islamic Prayer time feedback / Request for clarification

### ISSUE THREAD

**Issue by wilpernig** [home-assistant/home-assistant.github.io#17275]
### Feedback

The Prayer Time integration shows the time past and in how many hours / minutes the event was, or will be.
I like to set the display output to the actual time in the local time zone. 
Please provide feedback on how to set this output parameter to get time vs. Delta time to the event.

### URL

https://www.home-assistant.io/integrations/islamic_prayer_times/

### Version

2021.3.4

**Comment by ubbeus** [comment]
Also it still has the problem of only showing prayer time in UTC regardless of local time.

**Comment by najamshah1** [comment]
Below will give you local time and not in terms of hours and events
    'format: time'


type: entities
entities:
  - entity: sensor.fajr_prayer
    format: time
    name: Fajr - الفجر
    icon: 'mdi:islam'
  - entity: sensor.sunrise_time
    format: time
    icon: 'mdi:white-balance-sunny'
  - entity: sensor.dhuhr_prayer
    format: time
    icon: 'mdi:islam'
    name: Dhuhr - الظهر
  - entity: sensor.asr_prayer
    format: time
    icon: 'mdi:islam'
    name: Asr - العصر
  - entity: sensor.maghrib_prayer
    format: time
    icon: 'mdi:islam'
    name: Maghrib - المغرب
  - entity: sensor.isha_prayer
    format: time
    icon: 'mdi:islam'
    name: Isha - العشاء
title: Namaz Times

**Comment by wsb4331** [comment]
Below configuration I made hope that helps:

```
cards:
  - entities:
      - entity: automation.adhan_fajr_2
      - entity: automation.adhan_dhuhr_and_asr
      - entity: automation.adhan_maghrib_and_isha
      - entity: sensor.sunrise_time
        format: time
      - entity: sensor.fajr_prayer
        format: time
      - entity: sensor.dhuhr_prayer
        format: time
      - entity: sensor.asr_prayer
        format: time
      - entity: sensor.maghrib_prayer
        format: time
      - entity: sensor.isha_prayer
        format: time
    title: AZAN
    footer:
      type: picture
      image: http://x.x.x.x:8123/local/Azan_001.png
      tap_action:
        action: none
      hold_action:
        action: none
    show_header_toggle: false
    state_color: false
    type: entities
type: vertical-stack
```
