### ISSUE TITLE
https://www.home-assistant.io/integrations/homematic/#detecting-lost-connections issue

### ISSUE THREAD

**Issue by mtthsbrd** [home-assistant/home-assistant.github.io#17282]
### Feedback

binary_sensor:
  - platform: template
    sensors:
      homematic_up:
        friendly_name: "Homematic is sending updates"
        entity_id:
          - sensor.office_voltage
          - sensor.time
        value_template: >-
          {{as_timestamp(now()) - as_timestamp(states.sensor.office_voltage.last_changed) < 600}}

automation:
  - alias: "Homematic Reconnect"
    trigger:
      platform: state
      entity_id: binary_sensor.homematic_up
      to: "off"
    action:
      # Reconnect, if sensor has not been updated for over 3 hours
      service: homematic.reconnect

Entity_id section is deprecated and I had to supply the sensor state as  {{as_timestamp(now()) - as_timestamp(states.sensor["office_voltage"]last_changed) < 600}} instead of  {{as_timestamp(now()) - as_timestamp(states.sensor.office_voltage.last_changed) < 600}}

### URL

https://www.home-assistant.io/integrations/homematic/

### Version

2021.3.4

**Comment by frenck** [comment]
Hi there @mtthsbrd!

It seems like you want to report an issue with an Home Assistant Core integration, however, you created documentation feedback. There is no amount of documentation I can adjust to fix an issue with an integration.

Please raise an issue here:

<https://github.com/home-assistant/core/issues>

Thanks 👍

**Comment by mtthsbrd** [comment]
Hi @frenck !

Thanks for the extremely quick reply.

It's really the documentation that I am reporting.

The section under the link https://www.home-assistant.io/integrations/homematic/#detecting-lost-connections is using a binary_sensor example with outdated / incorrect options:

Currently it's

```binary_sensor:
  - platform: template
    sensors:
      homematic_up:
        friendly_name: "Homematic is sending updates"
        entity_id:
          - sensor.office_voltage
          - sensor.time
        value_template: >-
          {{as_timestamp(now()) - as_timestamp(states.sensor.office_voltage.last_changed) < 600}}

automation:
  - alias: "Homematic Reconnect"
    trigger:
      platform: state
      entity_id: binary_sensor.homematic_up
      to: "off"
    action:
      # Reconnect, if sensor has not been updated for over 3 hours
      service: homematic.reconnect
```



And it should instead be

```
binary_sensor:
  - platform: template
    sensors:
      homematic_up:
        friendly_name: "Homematic is sending updates"
        value_template: >-
          {{as_timestamp(now()) - as_timestamp(states.sensor["office_voltage"].last_changed) < 600}}

automation:
  - alias: "Homematic Reconnect"
    trigger:
      platform: state
      entity_id: binary_sensor.homematic_up
      to: "off"
    action:
      # Reconnect, if sensor has not been updated for over 3 hours
      service: homematic.reconnect
```

So states.**sensor.office_voltage**.last_changed becomes states.**sensor["office_voltage"]**.last_changed

Let me know if that makes sense and apologies for completely screwing up the formatting in my first attempt.
