### ISSUE TITLE
Script Example causes log error in scripts.yaml

### ISSUE THREAD

**Issue by bigbemme** [home-assistant/home-assistant.github.io#17287]
### Feedback

When using the provided example for starting netflix from section "media_player.select_source" of the documentation, a config error is being generated. The provided example works when using the services tab from GUI but will generate a config error (see below) after the next restart when added to the scripts.yaml. (Occured on core-2021.3.4 with explicit testing of the below code)

Error message after reboot:
Invalid config for [script]: not a valid value for dictionary value @ data['sequence'][0]['target']['entity_id']. Got None. (See /config/configuration.yaml, line 87).

(Please note: yaml line 87 of configuration.yaml is the following:

Line 86: switch: !include switches.yaml
Line 87:
Line 88: script: !include scripts.yaml

I tracked down the error by uncommenting all scripts and add them piece by piece until the netflix example turned out as root cause.)

### URL

https://www.home-assistant.io/integrations/androidtv/

### Version

2021.3.4

Code used (only adjusted media player to actual existing one):
`
```
start_netflix:
  sequence:
  - service: media_player.select_source
    target:
      entity_id: media_player.media_player.androidtv
    data:
      source: "com.netflix.ninja"
```
`
