### ISSUE TITLE
Next steps after changing configuration.yaml? Also clarify what ID is on thermostat

### ISSUE THREAD

**Issue by tmanpdx** [home-assistant/home-assistant.github.io#17289]
### Feedback

After modifying the configuration.yaml to include the climate section as outlined, what is the next step? Eg, how do I get this to show up in the configuration/integration section? 

Also - the doc says you can include the thermostat ID. Is this the MAC ID or the MAC CRC of the thermostat or something different? 

### URL

https://www.home-assistant.io/integrations/honeywell/

### Version

2021.3.4

**Comment by frenck** [comment]
Setting:

```yaml
climate:
# Example configuration.yaml entry
  - platform: honeywell
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
```

Should be enough. Please note, you need to restart Home Assistant after adding integration to YAML configuration in order to make it pick up.

The configuration -> integration screen is only to manage integrations configured via the UI. This integration will not show up there.
