### ISSUE TITLE
Not clear how to use select_tariff

### ISSUE THREAD

**Issue by efficiencynerd** [home-assistant/home-assistant.github.io#17321]
### Feedback

The only automation example shows how to use next_tariff, but select_tariff seems to function differently. In particular, it does not work with the "target:" as specified in the example. I'm not sure it this is also true for next_tariff, just that it doesn't work for select_tariff.

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2021.3.4

**Comment by dgomes** [comment]
what do you mean it does not work with target: ?

This works perfectly:

```yaml
service: utility_meter.select_tariff
target:
  entity_id: utility_meter.daily_energy
data:
  tariff: offpeak
```

**Comment by efficiencynerd** [comment]
Aha, that particular combo is not something I tried.

This doesn't work:
 ```yaml
 service: utility_meter.select_tariff
 target:
   entity_id: utility_meter.daily_energy
 tariff: offpeak
 ```

And this also doesn't work:
```yaml
 service: utility_meter.select_tariff
 data:
   target:
     entity_id: utility_meter.daily_energy
   tariff: offpeak
 ```

But your example makes sense. I also got it to work like this:

```yaml
service: utility_meter.select_tariff
data:
  tariff: 'onpeak'
  entity_id: utility_meter.whole_house_daily
```

Maybe my issue was just a lack of understanding with how the `target:` and `data:` selectors work. Perhaps a quick example in the docs would be helpful?
