### ISSUE TITLE
Cannot find configuration variables for automations

### ISSUE THREAD

**Issue by ugleatle** [home-assistant/home-assistant.github.io#17338]
### Feedback

Maybe I am looking the wrong place, but I am struggling with finding the configuration variables for automations. What variables are actually possible to use? (example from scripts: https://www.home-assistant.io/integrations/script/#-configuration-variables)

### URL

https://www.home-assistant.io/docs/automation/yaml/

**Comment by frenck** [comment]
All, that is free-form.

You decide on what variables to pass into the script.

**Comment by ugleatle** [comment]
I don't understand that answer? You can obviously not use any configuration variable you choose in automations? Not in scripts either? There is a set specific amount of configuration variables to choose from, but I couldn't find a list for automations, where for instance scripts have a list.

**Comment by frenck** [comment]
Those variables are user variables, you can define and re-use in your automations.
They are really free-form and up to you.

**Comment by ugleatle** [comment]
I still don't understand. Take the script example.

The configuration variables "icon", " mode" and "max" does something. They are in a list of the possible configurations varaibles. If just add "random" as a configuration variable it will do nothing (except throw and error if you do check config), so there is a list of possible configuration variables for scripts. But I couldn't find a similar list for automations.

**Comment by frenck** [comment]
Variables don't do anything, they are just available as you have set them. E.g., for re-use.

```yaml
script:
  my_script:
    alias: "My script that uses variables"
    variables:
      my_variable: "This variable contains my message"
      ugleatle: true
    sequence:
      - alias: "Only continue if ugleatle is true"
        condition: template
        value_tempalte: "{{ ugleatle }}"
      - alias: "Example notification"
        service: notify.notify
        data:
          message: "{{ my_variable }}"
      - alias: "Another example, re-using that variable again"
        service: notify.notify
        data:
          message: "{{ my_variable }}"
```

(Please note; the above is an example, quickly typed out just for the sake of the example. It has not been tested so it may contain an error.)

**Comment by ugleatle** [comment]
Look at the script documentation, they have a list of "legal" configuration variables. Like you are using there "variables:" "sequence" and "alias".

If i make the following 

```yaml
script:
my_script:
    alias: "My script that uses variables"
    ugleatle:
        my_variable: "This variable contains my message"`
```

That will not work. In the script, the available configuration variables are listed here: https://www.home-assistant.io/integrations/script/#-configuration-variables

Automation doesn't seem to have the same.
