### ISSUE TITLE
Example of Entity Card causes "No card type found"

### ISSUE THREAD

**Issue by robiecz** [home-assistant/home-assistant.github.io#17374]
### Feedback

The example:

```yaml
- type: entity
  entity: cover.kitchen_window
- type: entity
  entity: light.bedroom
  attribute: brightness
  unit: "%"
- type: entity
  entity: vacuum.downstairs
  name: Vacuum
  icon: "mdi:battery"
  attribute: battery_level
  unit: "%"
```

shows "No card type found".

### URL

https://www.home-assistant.io/lovelace/entity/

### Version

2021.4.3
