### ISSUE TITLE
How does group name equate to entity_id?

### ISSUE THREAD

**Issue by ChrisWeiss** [home-assistant/home-assistant.github.io#17408]
### Feedback

The example code block for a "Kitchen Lights" group is the following:

```
# Example configuration.yaml entry
light:
  - platform: group
    name: Kitchen Lights
    entities:
      - light.kitchen_ceiling_lights
      - light.kitchen_under_cabinet_lights
      - light.kitchen_spot_lights
      - light.pendant_lights
```

The example code block for leveraging that group is the following:

```
script:
  turn_on_kitchen_lights:
    alias: "Kitchen lights on"
    sequence:
      service: light.turn_on
      target:
        entity_id: light.kitchen_lights
      data:
        brightness: 100
```

How does the name of the group defined in the configuration.yaml entry equate the `target/entity_id: light.kitchen_lights` being called in the script? Is the `name` lower cased and spaces turned to underscores?

### URL

https://www.home-assistant.io/integrations/light.group/

### Version

2021.4.3
