### ISSUE TITLE
MJPEG IP Camera

### ISSUE THREAD

**Issue by cdrom1028** [home-assistant/home-assistant.github.io#17415]
### Feedback

Please include an example for MotionEye Cameras. I had to figure this out on my own as this is not documented properly even though there is an Add-on in the Home Assistant Community Add-on store. Considering there is a Blue Iris example I do not think this is to much to request. 

```
camera:
  - platform: mjpeg
    name: motionEye Camera
    mjpeg_url: http://<ip_address>:<streaming_port>/mjpeg.cgi
```

### URL

https://www.home-assistant.io/integrations/mjpeg/

### Version

2021.4.3
