### ISSUE TITLE
Filter window_size does not accept template

### ISSUE THREAD

**Issue by 0x3333** [home-assistant/home-assistant.github.io#17455]
### Feedback

I need to pass a template to a `window_size` in `filter`, but it is not accepting.

```
2021-04-13 22:54:48 ERROR (MainThread) [homeassistant.components.homeassistant] Invalid config for [sensor.filter]: expected int for dictionary value @ data['filters'][0]['window_size']. Got "{{ state('input_datetime.hall_temperature_average_window') }}"
not a valid value for dictionary value @ data['filters'][0]['filter']. Got 'time_simple_moving_average'. (See ?, line ?).
```

Config:

```
input_datetime:
  hall_temperature_average_window:
    has_date: false
    has_time: true
    initial: "24:00:00"
    icon: mdi:thermometer

sensor:
  - platform: filter
    name: hall temperature average
    entity_id: sensor.hall_temperature
    filters:
      - filter: time_simple_moving_average
        window_size: "{{ state('input_datetime.hall_temperature_average_window') }}"
```

I tried using `[:5]` after the state in the template to limit to `"24:00"`, but didn't work.

### URL

https://www.home-assistant.io/integrations/filter/

### Version

2021.4.4
