### ISSUE TITLE
Can't get public IPv6 address

### ISSUE THREAD

**Issue by mbloms** [home-assistant/home-assistant.github.io#17452]
### Feedback

I tried using this to get what ip addresses the host has:
```yaml
sensor:
  - platform: systemmonitor
    resources:
      - type: ipv6_address
        arg: eth0
      - type: ipv6_address
        arg: wlan0
```

But this only gives me local addresses, not the global ones. My guess is that the script doesn't accommodate multiple IPv6 addresses, which basically all IPv6 enabled interfaces has.

### URL

https://www.home-assistant.io/integrations/systemmonitor/

### Version

2021.4.4
