### ISSUE TITLE
scan_interval moved?

### ISSUE THREAD

**Issue by jacopsd** [home-assistant/home-assistant.github.io#17479]
### Feedback

Please see [this question](https://community.home-assistant.io/t/modbus-scan-interval-configuration/299772/3)

Was scan_interval moved?
Is it not valid anymore at "switch" level?

e.g.: 

```
    switch:
        platform: modbus
        scan_interval: 2
        registers:
        - name: my_light1
          slave: 1
```

In my test, it seems to be ignored now while it was working in previous releases.

### URL

https://www.home-assistant.io/integrations/modbus/

### Version

2021.4.4
