### ISSUE TITLE
Is there Something Missing

### ISSUE THREAD

**Issue by DavidWhitley** [home-assistant/home-assistant.github.io#17522]
### Feedback

Setup:
Raspberry Pi 4 with SD Card Hass.io
Home Assistant Version: core-2021.4.5
Xiaomi Temp Sensor 2 Info: Firmware 1.0.0_0109; Hardware B1.4

I've followed the steps and added everything to my configuration.yaml file, as stated in the example for temperature, humidity and battery life.  I have used the bluetoothctl method to ensure the Pi can see the devices.  I cross-referenced the MAC address via the Xiaomi Home App, after setting them all up on my phone.  An example of my YAML is: 

```
sensor.Family_Bathroom_Temp:
  - platform: mitemp_bt
    mac: "A4:C1:38:78:D7:D0"
    name: Kitchen Temperature & Humidity
    force_update: true
    median: 1
    monitored_conditions:
      - temperature
      - humidity
      - battery
## Xiaomi Token: b96911009932a0a76a14c06e
```
I've modified the sensor.XX name, the MAC address, and the Name to create unique devices.  However when I reset my Pi completely, Home Assistant complains that this is invalid:
```
Logger: homeassistant.setup
Source: setup.py:164
First occurred: 14:27:52 (4 occurrences)
Last logged: 14:27:52

Setup failed for sensor.Living_Room_Temp: Integration not found.
Setup failed for sensor.Master_Bedroom_Temp: Integration not found.
Setup failed for sensor.Family_Bathroom_Temp: Integration not found.
Setup failed for sensor.Kitchen_Temp: Integration not found.
```

### URL

https://www.home-assistant.io/integrations/mitemp_bt/

### Version

2021.4.5
