### ISSUE TITLE
group.all_lights still mentioned

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/home-assistant.github.io#17642]
### Feedback

Current text under https://www.home-assistant.io/integrations/light/#default-turn-on-values still references the no longer existing `group.all_lights`

```
To define a default for all lights, the identifier group.all_lights.default can be used. Individual settings always supercede the all_lights default setting.
```

maybe it would be better changed in to:
```
To define a default for several lights in a group, the identifier of that group.your_group_of_lights.default can be used. Individual settings always supercede the all_lights default setting.
```

### URL

https://www.home-assistant.io/integrations/light/

### Version

2021.4.6

**Comment by frenck** [comment]
This is actually correct, this still applies to light profiles. Although not actually used as a group, light profile still use the name to look it up in the csv.

```py
    def apply_default(self, entity_id: str, params: dict) -> None:
        """Return the default turn-on profile for the given light."""
        for _entity_id in (entity_id, "group.all_lights"):
            name = f"{_entity_id}.default"
```

https://github.com/home-assistant/core/blob/183220008d2ac80567cd15884e22dbc426ff65fa/homeassistant/components/light/__init__.py#L522-L525

**Comment by Mariusthvdb** [comment]
now this is confusing.... the entity doesn't exist in the states machine,

<img width="1081" alt="Schermafbeelding 2021-04-29 om 14 12 21" src="https://user-images.githubusercontent.com/33354141/116548721-f1f84b80-a8f4-11eb-8b07-a25ce8d44ddf.png">

 but it is used in the backend python? What does it reference in this case? or put differently, where is this group.all_lights created?

**Comment by frenck** [comment]
> now this is confusing.... 

100% agree 💯 

> the entity doesn't exist in the states machine

That is correct.

> but it is used in the backend python? What does it reference in this case? or put differently, where is this group.all_lights created?

It isn't used anywhere, it isn't created, it is nothing but a lookup/reference in the CSV.

**Comment by Mariusthvdb** [comment]
ok, ha, final 2 questions in that case:

if I use group.all_lights in the `light_profiles.csv`, it would still work, even though it doesn't exist?

can I also use other groups? I came across this because I wanted to set a default profile to my handmade `group.all_lights_only`, which itself contains other groups:

```
group:

  all_lights_only:
    name: All lights only
    icon: mdi:lightbulb-group
    entities:
      - group.all_inside_lights
      - group.all_outside_lights

  all_outside_lights:
    name: All outside lights
    icon: mdi:spotlight-beam
    entities:
      - group.outside_lights
      - group.terrace_outdoors_spots

  outside_lights:
    name: Outside flood lights
    icon: mdi:spotlight-beam
    entities:
      - light.backdoor_outdoors
      - light.gate_outdoors
      - light.porch_floodlight
      - etc etc

  all_inside_lights:
    name: All inside lights
    icon: mdi:lightbulb-outline
    entities:
      - group.main_inside_lights
      - group.guest_inside_lights
      - group.living_ceiling_spots


 ``` 

and is what I was referring to in my opening remark by handmade `your_group_of_lights`....
