### ISSUE TITLE
Breaking change PR46591

### ISSUE THREAD

**Issue by rostislav-palivoda** [home-assistant/home-assistant.github.io#17658]
### Feedback

I did not found how after https://github.com/home-assistant/core/pull/46591 to split modbus configuration in to packages. 

https://www.home-assistant.io/docs/configuration/packages/
https://www.home-assistant.io/integrations/modbus

For example I have set of similar devices. Each has its configuration in package. After PR46591 each modbus sensor or switch had to have connection definition, like:

```
modbus:
  name: hub_r4d8a08_02
  type: serial
  method: rtu
  port: !secret modbus0_port
  baudrate: !secret modbus0_baudrate
  stopbits: !secret modbus0_stopbits
  parity: !secret modbus0_parity
  bytesize: !secret modbus0_bytesize
  switches:

```
Ok, I moved common values to secrets.yaml and some how it works, but the log file is full of messages, like:

```
2021-05-01 13:51:49 WARNING (SyncWorker_13) [pymodbus.client.sync] Cleanup recv buffer before send: 0x4 0x38 0xb4 0x1e
2021-05-01 13:52:14 WARNING (SyncWorker_10) [pymodbus.client.sync] Cleanup recv buffer before send: 0x34 0x11 0x3 0x24 0x0 0x0 0x34 0x6 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x34 0x6 0x8 0xf3 0x0 0x75 0x1 0x4 0x0 0x45 0x3 0xc4 0x13 0x86 0x8f 0x34
2021-05-01 13:53:09 WARNING (SyncWorker_6) [pymodbus.client.sync] Cleanup recv buffer before send: 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x42 0x47 0xf3 0x81 0x29 0xd1
2021-05-01 13:54:09 WARNING (SyncWorker_6) [pymodbus.client.sync] Cleanup recv buffer before send: 0x79 0x0 0x0 0xa 0x46 0x8 0xe0 0x0 0x4 0x0 0x3 0x0 0x8 0x1 0x62 0x13 0x89 0x10 0x48
2021-05-01 13:55:29 WARNING (SyncWorker_0) [pymodbus.client.sync] Cleanup recv buffer before send: 0xe 0xa2 0x31 0x50 0xf9

```
I suspect there is no concurrency lock for workers if in the end each of them works with same hardware /dev/ttyUSB0. 

Please review possibility to allow setup of modbus hub  by reference in new "modbus:" configuration (as it was before) and add automated concurrency tests for modbus (or workers) to avoid data loss messages "Cleanup recv buffer ".

Thank you. 

### URL

https://www.home-assistant.io/integrations/modbus/

### Version

2021.4.6

## System Health

version | core-2021.4.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.109
arch | x86_64
timezone | 

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.0
docker_version | 19.03.15
disk_total | 30.8 GB
disk_used | 3.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Visual Studio Code (3.3.0), Log Viewer (0.10.2), SQLite Web (3.1.0), Terminal & SSH (9.1.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 1
views | 10
mode | storage

</details>

**Comment by frenck** [comment]
Modbus has changed to a different configuration format. This was documented and noted in the release notes. Integration configuration can be split across packages but on a different level.

For example:

```yaml
modbus:
  - name: hub_r4d8a08_02
    type: serial
    method: rtu
    port: !secret modbus0_port
    baudrate: !secret modbus0_baudrate
    stopbits: !secret modbus0_stopbits
    parity: !secret modbus0_parity
    bytesize: !secret modbus0_bytesize
    switches: !include_dir_merge_list my_modbus_switches/
```

Or, if you want to split even more:

```yaml
modbus: !include_dir_merge_list my_modbus_configs/
```

This is not a bug, but a different method of configuration, which basically applies to all configurations on the integration level.

**Comment by janiversen** [comment]
@frenck thanks, you explained it better than I was able to.

This method of configuration is a step on the road to use config_flow, which are planned around end of the year.

**Comment by janiversen** [comment]
The pymodbus entries in your log, is probably because you have enabled debug, I do not see these on my production system, but from time to time on my development system.

Pymodbus tries to tell that the receive buffer is not empty, which happens when a modbus message is sent as multiple packages, which are legal and causes no problem.

**Comment by rostislav-palivoda** [comment]
Then as I understand split by package is not possible any more. I mean each package includes everything necessary for the device to work -  sensor or switch, values post processing by template and required automations for this device. 
To reduce RS485 traffic I make single request per device - "custom" format for sensors. Then all values are post processed with "template".  

Here are my log levels:
```
logger:
  default: warning
  logs:
    homeassistant.components.serial: warning
    homeassistant.components.modbus: warning
    pymodbus.client: warning

```
