### ISSUE TITLE
Panasonic Viera example WoL turn_on_action does not specify that "wake_on_lan:" needs to be added to configuration.yaml

### ISSUE THREAD

**Issue by circa1665** [home-assistant/home-assistant.github.io#17739]
### Feedback

This example is provided in documentation:

```
# Example turn_on_action configuration.yaml entry with Wake-on-LAN
panasonic_viera:
  host: YOUR_TV_IP
  name: Living Room TV
  turn_on_action:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: "AA:BB:CC:DD:99:1A"
```

However this causes an error and does not work unless:

`wake_on_lan:`

is added to configuration.yaml. This should be made explicit in the documentation.

### URL

https://www.home-assistant.io/integrations/panasonic_viera/

### Version

2021.5.0
