### ISSUE TITLE
Multiple entity IDs not clear

### ISSUE THREAD

**Issue by brantlk** [home-assistant/home-assistant.github.io#17766]
### Feedback

Doesn't this only apply to the state trigger? If so it should be in the State Trigger section.
Also, it's not clear what happens when there's multiple entities. If I have:

```
automation:
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.one
        - binary_sensor.two
        - binary_sensor.three
      to: 'on'
```

Does this fire when any sensor turns to 'on', or only if all 3 are on?

### URL

https://www.home-assistant.io/docs/automation/trigger/

### Version

2021.5.1
