### ISSUE TITLE
Sun Elevation Example

### ISSUE THREAD

**Issue by NZRob** [home-assistant/home-assistant.github.io#17885]
### Feedback

```yaml
template:
  - sensor:
      - name: Sun Angle
        unit_of_measurement: "°"
        state: "{{ '%+.1f'|format(state_attr('sun.sun', 'elevation')) }}"
```

Fails check config in package file but removing the hyphen on the sensor does not:

```yaml
template:
  sensor:
    - name: Sun Angle
      unit_of_measurement: "°"
      state: "{{ '%+.1f'|format(state_attr('sun.sun', 'elevation')) }}"
```

Not sure why but if this if expected then example will need changed

### URL

https://www.home-assistant.io/integrations/template/

### Version

2021.5.4
