### ISSUE TITLE
Statistics Sensor does not describe binary_sensor behavior

### ISSUE THREAD

**Issue by tylerszabo** [home-assistant/home-assistant.github.io#17882]
### Feedback

The `statistics` sensor behavior is very different when the entity is a `binary_sensor` rather than a `sensor`. In a `binary_sensor` no attributes are present and the `max_age` should be explicitly configured to avoid a sensor that outputs `sampling_size` forever.

The configuration example does show an appropriate `binary_sensor` configuration that specified `max_age` but the surrounding documentation does not make any mention of it.

```
# Example configuration.yaml entry
sensor:
  - platform: statistics
    entity_id: sensor.cpu
  - platform: statistics
    entity_id: binary_sensor.movement
    max_age:
      minutes: 30
```

### URL

https://www.home-assistant.io/integrations/statistics/

### Version

2021.5.4

**Comment by fabaff** [comment]
Adding attributes for a binary sensors doesn't make much sense as they are not helpful for automations...well, it would allow to check if the state distribution of a binary sensor is optimal but a light switch will never be 50 % off and 50 % on and for those kind of questions a [Jupyter notebook](https://data.home-assistant.io/) would be the better approach.

The documentation says that for binary sensors only the state changes are counted. So, I guess that we covered that topic.

All configuration settings have a description and it's mentioned that `sampling_size` has a default.

**Comment by tylerszabo** [comment]
I think I should clarify: `max_age` is important for a `binary_sensor` since the default means that the `statistics` sensor will forever read the default `sample_size` of `20` making it just report `20`, `20`, `20` ad-infinitum. Removing `max_age` from the example would be going in the wrong direction. It was my primary confusion when creating one of these sensors that it wouldn't count the transitions (because it was always accumulating 20 over a huge default `max_age` period).

**Comment by tylerszabo** [comment]
I suppose if the `statistics` sensor didn't handle `binary_sensor` at all and there were another sensor like `interval_counter` then it would be more clear but since `statistics` is pulling double-duty having the documentation for it's other behavior is useful.

**Comment by tylerszabo** [comment]
I realize a screenshot and config example might help clarify the problem with documentation's defaults.

```yaml
# configuration.yaml
sensor:
  - platform: simulated
    name: simulated_a
    amplitude: 0.25
    period: 200
  - platform: simulated
    name: simulated_b
    amplitude: 0.25
    period: 100
  - platform: simulated
    name: simulated_c
    amplitude: 0.25
    period: 50
  - platform: simulated
    name: simulated_d
    amplitude: 0.25
    period: 25

  - platform: statistics
    name: statistics_defaults
    entity_id: binary_sensor.simulated_binary
  - platform: statistics
    name: statistics_1_min
    entity_id: binary_sensor.simulated_binary
    max_age:
      minutes: 1
  - platform: statistics
    name: statistics_2_min
    entity_id: binary_sensor.simulated_binary
    max_age:
      minutes: 2
  - platform: statistics
    name: statistics_3_min
    entity_id: binary_sensor.simulated_binary
    max_age:
      minutes: 3
  - platform: statistics
    name: statistics_4_min
    entity_id: binary_sensor.simulated_binary
    max_age:
      minutes: 4

  - platform: statistics
    name: statistics_100_samples
    entity_id: binary_sensor.simulated_binary
    sampling_size: 100
  - platform: statistics
    name: statistics_1_min_100_samples
    entity_id: binary_sensor.simulated_binary
    sampling_size: 100
    max_age:
      minutes: 1
  - platform: statistics
    name: statistics_2_min_100_samples
    entity_id: binary_sensor.simulated_binary
    sampling_size: 100
    max_age:
      minutes: 2
  - platform: statistics
    name: statistics_3_min_100_samples
    entity_id: binary_sensor.simulated_binary
    sampling_size: 100
    max_age:
      minutes: 3
  - platform: statistics
    name: statistics_4_min_100_samples
    entity_id: binary_sensor.simulated_binary
    sampling_size: 100
    max_age:
      minutes: 4

template:
  - sensor:
      - name: simulated_sum
        state: >
          {{
              states("sensor.simulated_a")|float
            + states("sensor.simulated_b")|float
            + states("sensor.simulated_c")|float
            + states("sensor.simulated_d")|float
          }}
        unit_of_measurement: value

  - binary_sensor:
      - name: simulated_binary
        state: '{{ states("sensor.simulated_sum")|float > 0.0 }}'
```

As you can see with the defaults for a `binary_sensor` the count will accumulate to `sampling_size` and stay there forever unless it's limited with `max_age`.

![Screenshot_2021-05-23 Overview - Home Assistant](https://user-images.githubusercontent.com/315343/119274974-6017f180-bbc7-11eb-8daf-c6068f69e5ef.png)

That's why I see the documentation fix as noting this caveat when using `statistics` for a `binary_sensor`. I think an additional sentence on the description of the `max_age` property that states something like "When the source is a binary sensor state change count will accumulate indefinitely unless `max_age` is specified."

For `sampling_size` property it might also help to note something akin to "When the source is a binary sensor state changes will continue to be counted until ` sampling_size` is reached."

This is because the behavior for `binary_sensor` sources is quite different (as shown).
