### ISSUE TITLE
image_processing.scan example

### ISSUE THREAD

**Issue by kifort** [home-assistant/home-assistant.github.io#17927]
### Feedback

Hi,

I was not able to test my sighthound integration:

```
image_processing:
  - platform: sighthound
    save_file_folder: /config/www/
    save_timestamped_file: True
    api_key: "..."
    source:
      - entity_id: camera.g4_doorbell
```

There is only one sighthound entity generated: camera.sighthound

I suggest the followings:

1. Mention how to verify the successful configuration.
E.g. "Check if a new entity appears as image_processing.sighthound_camera_my_cam"
2. add a simple automation example like this:
```
alias: Entrance Motion Image Processing
description: ''
trigger:
  - type: motion
    platform: device
    device_id: ...
    entity_id: binary_sensor.motion_g4_doorbell
    domain: binary_sensor
condition: []
action:
  - service: image_processing.scan
    target:
      entity_id: camera.sighthound
mode: single
```

I tried many entity_id in action / target, but none of them worked:
- camera.sighthound
- sighthound.camera
- sighthound.g4_doorbell
- image_processing.sighthound_camera_g4_doorbell

With camera.sighthound entity ID, I get this error log:

Entrance Motion Image Processing: Executing step call service
2021-05-22 17:32:07 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities camera.sighthound

### URL

https://www.home-assistant.io/integrations/sighthound/

### Version

2021.5.5
