### ISSUE TITLE
Unclear where to fetch additional departure times

### ISSUE THREAD

**Issue by steveroch-rs** [home-assistant/home-assistant.github.io#17929]
### Feedback

It is not clear from the documentation where to put the `state_attr(‘sensor.ENTITY_NAME’, ‘departures’)[1].time` part.

It says: 

> To retrieve the time until the second departure, you would use `state_attr(‘sensor.ENTITY_NAME’, ‘departures’)[1].time`.

So where do I put it?

### URL

https://www.home-assistant.io/integrations/mvglive/

### Version

2021.5.5

**Comment by steveroch-rs** [comment]
Had to define a template in configuration.yaml

```
template:
  - sensor:
    - name: "MVG second stop"
      unit_of_measurement: "min"
      state: "{{state_attr('sensor.hochschule_munchen_lothstrasse', 'departures')[1].time}}"
```
