### ISSUE TITLE
Google Cast Integration Docs: Error in path?

### ISSUE THREAD

**Issue by quaec** [home-assistant/home-assistant.github.io#17977]
### Feedback

Hello everyone,

I've read the documentation to the Google cast integration and I'm not sure if I don't understand it correctly or if there's a small error in this section: https://www.home-assistant.io/integrations/cast/#home-assistant-cast

Specifically this part:

> The `dashboard_path` is the part of the Lovelace UI URL that follows the defined `base_url` Typically “lovelace”. The following is a full configuration for a script that starts casting the `downstairs` tab of the `lovelace-cast` path (note that `entity_id` is specified under `data` and not for the service call):

```
cast_downstairs_on_kitchen:
  alias: "Show Downstairs on kitchen"
  sequence:
    - data:
        dashboard_path: lovelace
        entity_id: media_player.kitchen
        view_path: downstairs
      service: cast.show_lovelace_view
```

But there is no `lovelace-cast` path in the example configuration? The path there is called just `lovelace` if I'm correct?

Also I think I just found another typo. I think there's a dot or a comma missing:
>[...] defined `base_url` Typically “lovelace”. [...]

Shouldn't it be _"[...] defined `base_url`. Typically “lovelace”. [...]"_ or _"[...] defined `base_url`, typically “lovelace”. [...]"_?

What do you guys think? If you agree I would create a pull request.

### URL

https://www.home-assistant.io/integrations/cast/#home-assistant-cast

### Version

2021.5.5
