### ISSUE TITLE
2021.6.1 Modbus breaking change not listed

### ISSUE THREAD

**Issue by marc-romu** [home-assistant/home-assistant.github.io#18080]
### Feedback

After upgrading to 2021.6.1, I got this message related to Modbus integration:

```Invalid config for [modbus]: [input_type] is an invalid option for [modbus]. Check: modbus->modbus->0->switches->0->input_type. (See /config/configuration.yaml, line 313).```

My configuration was:

```
modbus:
  type: tcp
  host: !secret modbus
  port: 2020
  switches:
    - name: Switch 01
      address: 32768
      input_type: coil
```
I checked docs and I realized that `input_type` has changed into `write_type` for `switches`. I'm not sure whether it is a breaking change, but at least it broke my configuration.

After updating my configuration to the following, everything works fine:
```
modbus:
  type: tcp
  host: !secret modbus
  port: 2020
  switches:
    - name: Switch 01
      address: 32768
      write_type: coil
```
I suppose it should be included in the breaking changes' list.

### URL

https://www.home-assistant.io/blog/2021/06/02/release-20216/#breaking-changes

### Version

2021.6.1
