### ISSUE TITLE
Get an error when following the manual.

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#18096]
### Feedback

If I follow the manual...

```yaml
# Example configuration.yaml entry
switch:
  - platform: broadlink
    mac: MAC_ADDRESS
    switches:
      - name: Philips TV
        command_on: JgAcAB0dHB44HhweGx4cHR06HB0cHhwdHB8bHhwADQUAAAAAAAAAAAAAAAA=
        command_off: JgAaABweOR4bHhwdHB4dHRw6HhsdHR0dOTocAA0FAAAAAAAAAAAAAAAAAAA=
```

And I do "Check Configuration" before rebooting, I get this error:

Invalid config for [switch.broadlink]: [True] is an invalid option for [switch.broadlink]. Check: switch.broadlink->switches->0->True. (See ?, line ?).

Is the documentation still valid or am I doing something wrong?
I have an Broadlink Universal Remote3, with a AEG airco (oneway IR remote) connected.

### URL

https://www.home-assistant.io/integrations/broadlink/

### Version

2021.6.2

### Additional information

This is the code I added to my configyaml:

```
switch:
  - platform: broadlink
    mac: a1:42:b2:31:68:1a
    switches:
      - name: Airco
        on: power on
        off: power off
        sleep: sleep
        swing: swing
        mode auto: mode auto
        mode cool: mode cool
        mode dry: mode dry
        mode fan: mode fan
        mode heat: mode heat
        speed auto: speed auto
        speed high: speed high
        speed mid: speed mid
        speed low: speed low
        16: 16
        17: 17
        18: 18
        19: 19
        20: 20
        21: 21
        22: 22
        23: 23
        24: 24
        25: 25
        26: 26
        27: 27
        28: 28
        29: 29
        30: 30
```

Maybe the preview of this code breaks on github, so don't bother about that, In reality it's specified like mentioned here: https://www.home-assistant.io/integrations/broadlink/

**Comment by ghost** [comment]
And Further on there is this passage in the beginning: 

**Learning commands**
_Use remote.learn_command to learn IR and RF codes. These codes are grouped by device and stored as commands in the storage folder. They can be sent with the remote.send_command service later._

I managed to learn the codes. But where is the storage folder??

If I connect with SMB to the Raspberry Pi4b, the only folders I see are:
```
addons
backup
config
media
share
ssl
```

And when I use File Editor, the folders within config I can see are:

```
blueprints
custom_components
deps
image
tts
www
   automations.yaml
   configuration.yaml
   customize.yaml
   groups.yaml
   home-assistant_v2.db
   home-assistant_v2.db-shm
   home-assistant_v2.db-wal
   home-assistant.log
   known_devices.yaml
   scenes.yaml
   scripts.yaml
   secrets.yaml
```

No .storage folder. :-(

**Comment by frenck** [comment]
Part of your example:

```yaml
switch:
  - platform: broadlink
    mac: a1:42:b2:31:68:1a
    switches:
      - name: Airco
        on: power on
        off: power off
        sleep: sleep
        swing: swing
```

This not what is documented, there are no "on", "off", "sleep", "swing" (and all the other listed) configuration variables. See: <https://www.home-assistant.io/integrations/broadlink/#switches>

> But where is the storage folder??

`/config/.storage`

That said, it seems like you are looking for support in general, however, that is not what we use GitHub for..

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
