### ISSUE TITLE
oscillating template state does not work

### ISSUE THREAD

**Issue by cmd-sam** [home-assistant/home-assistant.github.io#18170]
### Feedback

The template fan won't show the correct oscillating_template state. It defaults to false after closing the popup window, even if the corrospind entity is true

example code:

```
  fan:
    - platform: template
      fans:
        sz:
          friendly_name: Ventilator Schlafzimmer
          value_template: "{{ states('binary_sensor.sz_ventilator') }}"
          oscillating_template: "{{ states('input_boolean.sz_status_ventilator_oscillating') }}"
          percentage_template: "{{ states('input_number.sz_status_ventilator_speed_percentage') }}"
          turn_on:
            - service: script.sz_ventilator_turn_on
          turn_off:
            - service: script.sz_ventilator_turn_off
          set_oscillating:
            - service: script.sz_ventilator_oscillate
              data:
                oscillating: "{{ oscillating }}"
          set_percentage:
            service: script.sz_ventilator_set_speed
            data:
              percentage: "{{ percentage }}"
          speed_count: 12
```
```
  input_boolean:
    sz_status_ventilator_oscillating:
```
```
  script:
    sz_ventilator_oscillate:
      alias: SZ Ventilator Oszillieren
      sequence:
        - service: input_boolean.toggle
          entity_id: input_boolean.sz_status_ventilator_oscillating
        - service: script.sz_ventilator_light
        - delay:
            milliseconds: 300
        - service: remote.send_command
          data:
            device: sz_ventilator
            command: oscillate
            num_repeats: 1
          target:
            entity_id: remote.sz_ir
        - delay:
            milliseconds: 300
        - service: script.sz_ventilator_light
      mode: single
```

### URL

https://www.home-assistant.io/integrations/fan.template/

### Version

2021.6.4
