### ISSUE TITLE
Screenlogic Integration Documentation Improvement

### ISSUE THREAD

**Issue by pongolo** [home-assistant/home-assistant.github.io#18191]
### Feedback

Hello,

I have tried to use the `SCREENLOGIC.SET_COLOR_MODE` service but being new to HA, I'm having a hard time getting the service to work.  Adding an example of how to call the `SCREENLOGIC.SET_COLOR_MODE` service would be helpful.

Thanks!

### URL

https://www.home-assistant.io/integrations/screenlogic/

### Version

2021.6.4

**Comment by frenck** [comment]
All services can be tested and called from the frontend, which also allows you to peek at the code it used (in YAML format) to make that call.

[![Open your Home Assistant instance and show your service developer tools.](https://my.home-assistant.io/badges/developer_services.svg)](https://my.home-assistant.io/redirect/developer_services/)

**Comment by dieselrabbit** [comment]
@frenck makes a good suggestion, the services UI makes it really easy to build a service call and see the YAML equivalent.

That said, playing with YAML mode made me realize that the documentation is actually really confusing when it comes to using the `target` service data attribute.

Based on the documentation, I might try to craft the service call as:
```
service: screenlogic.set_color_mode
data:
  color_mode: color_swim
  target: backyard
```

In reality, the service call should be:
```
service: screenlogic.set_color_mode
data:
  color_mode: color_swim
target:
  area_id: backyard
```
or, more simply:
```
service: screenlogic.set_color_mode
data:
  color_mode: color_swim
  area_id: backyard
```

I'll take a stab at updating the documentation to remove this confusion.
Thanks for the feedback @pongolo.

**Comment by pongolo** [comment]
Hello!

Thanks for feedback.  The code below is exactly how I tried it and wasn't
able to get it to work.
service: screenlogic.set_color_mode data: color_mode: color_swim target:
backyard I did use the suggestion from Franck and that helped me understand
the YAML format which ended up being like you showed:
service: screenlogic.set_color_mode data: color_mode: color_swim
target: area_id:
backyard
Thanks again for your help!

**Comment by pongolo** [comment]
Hello!

Thanks for feedback.  The code below is exactly how I tried it and wasn't able to get it to work.

```
service: screenlogic.set_color_mode
data:
  color_mode: color_swim
  target: backyard
```

I did use the suggestion from @frenck and that helped me understand the YAML format which ended up being like you showed:

```
service: screenlogic.set_color_mode
data:
  color_mode: color_swim
target:
  area_id: backyard
```

Thanks again for your help!
