### ISSUE TITLE
Discovery / Manual

### ISSUE THREAD

**Issue by michaelsage** [home-assistant/home-assistant.github.io#18301]
### Feedback

Hi,
Is it possible to leave discovery on and provide a manual entry too? I have a number of devices that are onsite, and one that is contactable over a VPN. I'd love to manually add the VPN device, but leave discovery for local devices, is this possible? Should I post this request on the github page or is this the right place? Thanks

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2021.6.6

**Comment by frenck** [comment]
Yes, this is possible and also documented.

For example:

```yaml
tplink:
  discovery: true
  light:
    - host: 192.168.200.1
    - host: 192.168.200.2
  switch:
    - host: 192.168.200.3
    - host: 192.168.200.4
  dimmer:
    - host: 192.168.200.5
    - host: 192.168.200.6
  strip:
    - host: 192.168.200.7
    - host: 192.168.200.8
```
