### ISSUE TITLE
Feature Request? Use icon instead of first letter(s) of entity's name on Map Cards in Lovelace

### ISSUE THREAD

**Issue by smizles** [home-assistant/home-assistant.github.io#18383]
### Feedback

I don't see a GitHub repository linked to this card, so I'm not sure where to submit feature requests. If it can be forwarded to the right place or person, I would ***extremely*** appreciate the ability for the map card to use the device tracker's icon instead of the letter(s) of its name.

### URL

https://www.home-assistant.io/lovelace/map/

### Version

2021.6.6

### Additional information

I tried the code below and I got no errors in the UI, but it still uses letters on the map instead of the icon specified :disappointed: 
```
  - type: map
    entities:
      - entity: device_tracker.ben_s_keys
        icon: mdi:key
      - entity: device_tracker.ben_s_wallet
        icon: mdi:wallet
      - entity: device_tracker.ben_sims_galaxy_s20_ultra_5g
        icon: mdi:phone
```

P.S. I have also tried specifying the icon for each device tracker through the UI, but it doesn't propagate to the map card.
