### ISSUE TITLE
Please would you like to update the information for TTNv3

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#18428]
### Feedback

Dear,

Would you please update the information to match with the current situation of TTNv3.

The setup part about the API key does not match.

The sensor part of the TTN does not match. I've added the "storage" thing but for example _"You could check the output after clicking on go to platform in an interactive web interface."_ does "go to platform" does not seems to excist.

Below that part _"Select Devices to get the ID of your device that you want to use."_
Do you mean "end devices?"

The pictures don't match the current situation with TTNv3. I can't get it to work either. See below.

Would it be possible for you to re-evaluatie the procedure and update documentation? :-)
Thanks!

### URL

https://www.home-assistant.io/integrations/thethingsnetwork/

### Additional information

I added to the configyaml

```
thethingsnetwork:
  app_id: hagpstrackerbla
  access_key: NBLAS.QKLONGBLAKY.PFYETANOTHERLONGBLAQetc

sensor:
  - platform: thethingsnetwork
    device_id: MYENDDEVICEIDsecret-etc
    values:
      latitude: degrees
      longitude: degrees
      roll: roll
      pitch: pitch
      batV: volt
      alarm: alarm
      altitude: meter
```

But when rebooting HA to make it effective I get the error

2021-07-08 11:00:49 ERROR (MainThread) [homeassistant.components.thethingsnetwork.sensor] Application ID is not available: hagpstrackerbla

I don't know if i'm seeking support, or that I have a valid case that this documentation is intended for TTNv2. Since most problems I encounterd before is about the documentation is not valid voor TTNv3 which recently become active. I think I really filled in the right values in configyaml, but I can't tell for shure because V2 TTN and current V3 TTN example pictures do not match....
