### ISSUE TITLE
Light Groups Expanded Detail

### ISSUE THREAD

**Issue by RobJ835** [home-assistant/home-assistant.github.io#18480]
### Feedback

The documentation shows a single light group being defined in the configuration.yaml

However, I'm not seeing how to create multiple groups without the yaml being deemed invalid.

Not sure the solution to this, and i'll keep looking online, but I feel this should be something in the base documentation.

### URL

https://www.home-assistant.io/integrations/light.group/

### Version

2021.7.1

**Comment by frenck** [comment]
The example shows each light group being an item in the list. You can add more items if you like, as it is a list. This is basic YAML logic. I suggest reading into YAML basics if this raises questions for you.

As for an example:

```yaml
# Example configuration.yaml entry
light:
  - platform: group
    name: Kitchen
    entities:
      - light.kitchen_ceiling
      - light.kitchen_cabinet
  - platform: group
    name: Office
    entities:
      - light.office_ceiling
      - light.office_window
      - light.office_desk
```

Hopefully, that makes things more clear.
