### ISSUE TITLE
climate.set_temperature Heat_cool not working.

### ISSUE THREAD

**Issue by TKpizza** [home-assistant/home-assistant.github.io#18562]
### Feedback

I can set my nest thermostat to heat cool but when i try to do it through a service call of climate.set_temperature it doesnt work.

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2021.7.3

**Comment by allenporter** [comment]
@TKpizza Thank you for the report.  Would you mind including details of the call you're making and the expected result? This will help make sure I understand the issue, since this is not something I regularly do

**Comment by TKpizza** [comment]
service: climate.set_temperature
data:
  hvac_mode: heat_cool
  target_temp_high: 71
  target_temp_low: 66
target:
  entity_id: climate.guest_main_floor

im trying to set the thermostat to Heat Cool with a high of 71 and low of 66

[http://imgur.com/a/io7P5D9](url)

**Comment by allenporter** [comment]
Hi,

I was playing with this and observed that it worked for me, but only when the thermostat is already in the heat_cool HVAC mode.

This behavior is consistent with the Nest SDM API documentation for the set point:
https://developers.google.com/nest/device-access/traits/device/thermostat-temperature-setpoint which says `The thermostat must be in the mode that corresponds to the command being called prior to changing the temperature setpoints.`.

So here's what I did:

Attempt #1, device is off.
---
```
service: climate.set_temperature
target:
  entity_id: climate.loft
data:
  target_temp_high: 75
  target_temp_low: 66
  hvac_mode: heat_cool
```
And that did nothing.
---

Attempt #2 where device is off
---
I first set the hvac mode to `heat_cool`:
```
service: climate.set_hvac_mode
data:
  hvac_mode: heat_cool
target:
  entity_id: climate.loft
```

Then changed the temperature:
```
service: climate.set_temperature
target:
  entity_id: climate.loft
data:
  target_temp_high: 75
  target_temp_low: 66
  hvac_mode: heat_cool
```
And it worked.
---

Are you seeing that this works if the device is already in the correct state or are we talking about a different issue where it doesn't work at all?
