### ISSUE TITLE
secrets integration

### ISSUE THREAD

**Issue by BBE128** [home-assistant/home-assistant.github.io#18611]
### Feedback

I would be helped by examples: what exactly do i need to replace and how?
Adding text to yaml files always turns out to result in errors.
In the instructions i read this:

```yaml
homeassistant:
  auth_providers:
   - type: legacy_api_password
     api_password: YOUR_PASSWORD
```

however on https://www.home-assistant.io/integrations/toon/ it's just a little different:

```yaml
# Example configuration.yaml entry
toon:
  client_id: YOUR_CONSUMER_KEY
  client_secret: YOUR_CONSUMER_SECRET
```

### URL

https://www.home-assistant.io/docs/configuration/secrets/

### Version

2021.7.4
