### ISSUE TITLE
Issue with Total Connect Comfort (Honeywell) US

### ISSUE THREAD

**Issue by marioawe** [home-assistant/home-assistant.github.io#18679]
### Feedback

Hey!

I'm trying to set up my thermostat so I can control it through HA, but I seem to be running into issues getting it to work. I do not see any errors in my log, but when looking for `climate.thermostat` nothing appears. I've restarted multiple times over, double and triple checked that the email and password are correct, and I seem to be at a loss as to what I'm doing wrong

Here is my config:

```
climate:
    - platform: honeywell
      username: email@email.com
      password: MyP@ss
```

### URL

https://www.home-assistant.io/integrations/honeywell/

### Version

2021.7.4
