### ISSUE TITLE
Entities Register OK - Cannot Control Them

### ISSUE THREAD

**Issue by GazTheGeek** [home-assistant/home-assistant.github.io#18836]
### Feedback

HI all,

So I have taken the plunge and started a project to integrate my Dynalite system into HA.

I bought an [EByte E810-DTU](https://www.ebyte.com/en/product-view-news.html?id=825) Ethernet to RS485 converter

[More details here](https://community.home-assistant.io/t/philips-dynalite-lighting-switches/89213/143?u=gazthegeek
)
I am getting a solid link light when HA connects.

I also get a very quick blink when a light is turned on or off.

Socket A: Shows "connect"

I have 4 wires coming from the Dynalite system but I am only using the 2 data wires not VCC or GND.

I am getting devices added in HA now as lights are turned on and off.

eg: "Area 10 Preset 2" this turns Study lights to half brightness.

I cannot yet control any lights with this information in HA. Added the Areas to the YAML but no response on the lights. I can't seem to figure out the minimum config for a basic turn on/off.

If I turn lights on at the wall then HA updates the state.

Here is my entry in configuration.yaml:

```
dynalite:
  bridges:
    - host: 10.0.0.150
      port: 12345
      autodiscover: true #Turn this off when you have things working
      name: dynalite
      active: on
      polltimer: 1
      area:
        '5':
          name: Kitchen
        '6':
          name: Range
        '10':
          name: Study
          preset:
            '2':
              name: Faded
        '15':
          name: Dining
        '80':
          name: Balcony
```

Any help appreciated. Thanks

### URL

https://www.home-assistant.io/integrations/dynalite/

### Version

2021.8.3
