### ISSUE TITLE
Hygrostat bugs

### ISSUE THREAD

**Issue by llukezz** [home-assistant/home-assistant.github.io#18951]
### Feedback

The dry_tolerance settings is acting up.  When I put in a value of 10 it appears to ignore it and goes back to the last number used.  If I put in 9 or less it appears to take it correctly.  Can the maximum number be higher than 9 or put that limitation in the literature somewhere?

The lovelace card also always says "On" for me, even after the dehumdifier is turned off, picture below:
![image](https://user-images.githubusercontent.com/76849221/129573977-51fa433e-910f-4600-8ff2-672936a577d4.png)

### URL

https://www.home-assistant.io/integrations/generic_hygrostat/

### Version

2021.8.0

**Comment by llukezz** [comment]
More data points for the hygrostat.  I have been running it all morning.  I changed the code to 9 (code is below) shortly after my post, around 9:30 this morning.  The hygrostat has gradually moved back to 3 as the dry_tolerance.  It has a mind of it's own...
![image](https://user-images.githubusercontent.com/76849221/129589786-032507b7-124d-42ea-8213-8154f7fbb2a4.png)

```
#Create a Humidistat for the Pool HRV
generic_hygrostat:
  - name: Pool Room HRV
    humidifier: switch.shelly1pm_b90bbd
    target_sensor: sensor.pool_probe_humidity
    min_humidity: 30
    max_humidity: 100
    target_humidity: 80
    dry_tolerance: 9
    wet_tolerance: 0
    device_class: "dehumidifier"
    min_cycle_duration:
      seconds: 60
    initial_state: false
    #away_humidity: 35
    #away_fixed: True
    #sensor_stale_duration: 00:15:00
```
