### ISSUE TITLE
Workday sensor requires "holiday" exclude to observe added holidays

### ISSUE THREAD

**Issue by jofotoo** [home-assistant/home-assistant.github.io#18999]
### Feedback

for default includes and excludes: "Days are specified as follows: mon, tue, wed, thu, fri, sat, sun. The keyword holiday is used for public holidays identified by the holidays module."

I added my birthday  (today :) ) as an added holiday to my wife's workday sensors and it did not reflect her being off until i added 'holiday' to excludes:
```
  - platform: workday
    country: US
    name: Liza Workday 2021
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sun, sat, holiday]
    add_holidays:
      - '2021-08-19'
      - '2021-12-25'
      - 
```

My birthday is not yet a national holiday (haha), nor are the other custom days I've added (not shown here) so I wouldn't expect to need the 'holidays' exclude to add my own custom dates based on the docs.

I may consider submitting a bug report/feature request as well since this shouldn't be a requirement for adding exceptions. My working and not-working holidays change each year (and as is common, company holidays sometimes fall on weekends so the actual day off is not the actual holiday) so for my sensors, I wanted leave out  holidays from excludes and just enter all the dates manually.

Thank you for your time and consideration :) 

### URL

https://www.home-assistant.io/integrations/workday/

### Version

2021.8.8
