### ISSUE TITLE
documentation improvement proposal 

### ISSUE THREAD

**Issue by phsdv** [home-assistant/home-assistant.github.io#19011]
### Feedback

Proposal to add text explaining what code is actual doing, The code now shows:
```
service: homeassistant.turn_on
target:
  area_id: livingroom
  device_id:
    - ff22a1889a6149c5ab6327a8236ae704
    - 52c050ca1a744e238ad94d170651f96b
  entity_id:
    - light.hallway
    - light.landing
```
proposal is to add text below this as follows:

> 
> This code will turn on all devices in the area called livingroom and the two devices with the given device_ids and the 2 lamps (hallway and landing), all with a single service call. This is more efficient than having  multiple service calls which you would need if you would not use the homeassistant.turn_on service.
> 
This might sound obvious, however for a beginner it is not.

### URL

https://www.home-assistant.io/docs/scripts/service-calls#targeting-areas-and-devices

### Version

2021.8.8

### Additional information

Further down in the text, at https://www.home-assistant.io/docs/scripts/service-calls#using-the-services-developer-tool
a link is missing it now says:  `(See [groups] for more info). ` This should be `(See [group](https://www.home-assistant.io/integrations/group/) for more info)`
