### ISSUE TITLE
homeassisant.turn_on/off documentation improvement proposal

### ISSUE THREAD

**Issue by phsdv** [home-assistant/home-assistant.github.io#19010]
### Feedback

We could make the documentation a bit more clear by explaining why this functionality exists.
For example "Service homeassistant.turn_on" only shows switching on a light, which can also be done with "light.turn_on". It is not not explained when to use _light.xxx_ or when to use _homeassistant.xxx_.
As it is not fully clear to me either, it is difficult to propose a better text. I suspect that if you want to switch on a light and a switch in one action you cannot do that in a single service, except when using "service: homeassistant.turn_on".
If this is the case, I would change the example to:
```
action:
  service: homeassistant.turn_on
  target:
    entity_id:
      - light.living_room    # living room light
      - switch.plug_tv_1    # switch for light next to TV
```
And text above it change to:
```
Generic service to turn devices on under any domain. Same usage as the light.turn_on, switch.turn_on, etc. services. 
However with this service you can mix different domains, for example light and switch. What otherwise would not be possible.
```
Similar changes for turn_off as well.

### URL

https://www.home-assistant.io/integrations/homeassistant/

### Version

2021.8.8
