### ISSUE TITLE
More detailed explanation requested for "The data is only shown when choosing device scope."

### ISSUE THREAD

**Issue by Toffi32** [home-assistant/home-assistant.github.io#19042]
### Feedback

Can you explain, the meaning of this sentence: "The data is only shown when choosing device scope."

How ot set the parameters "scope" and "device", to get all available data for "inverter" and "meter"?

### URL

https://www.home-assistant.io/integrations/fronius/

### Version

2021.8.8

**Comment by nielstron** [comment]
This depends on your device, but https://github.com/nielstron/pyfronius/issues/30 might contain some useful explanations and trials.

**Comment by frenck** [comment]
The `monitored_conditions` list can contain those settings.

<https://www.home-assistant.io/integrations/fronius/#monitored_conditions>

For example:

```yaml
sensor:
  - platform: fronius
    resource: FRONIUS_URL
    monitored_conditions:
    - sensor_type: inverter
      scope: system
```
