### ISSUE TITLE
For the script using fields, a Text field needs a selector of type text to be displayed

### ISSUE THREAD

**Issue by TheQue42** [home-assistant/home-assistant.github.io#19072]
### Feedback

The documentation says:

"Please note: In order for this description to be displayed in the Services tab of the Developer Tools, the script description must be defined as well."

For a text field such as:
```
fields:
  msg:
    name: Text message
    required: true
    description: Text message to send
```

Will not show a text field when using the UI mode.

If you add the **selector** it _will_ work though, and it would be good if this was clarified.
```
fields:
  msg:
    name: Text message
    required: true
    description: Text message to send
    selector:
      text: 
```

### URL

https://www.home-assistant.io/integrations/script/

### Version

2021.8.8
