### ISSUE TITLE
Date/time helper set

### ISSUE THREAD

**Issue by MickW69** [home-assistant/home-assistant.github.io#19104]
### Feedback

The yaml script examples show the order in configuration to be service, target, data
```
- service: input_datetime.set_datetime
  target:
    entity_id: input_datetime.XXX
  data:
    datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
```

When I copy this into a yaml script I get the error: "Message malformed: expected dictionary @ data['sequence'][0]"

Rearranging to be service, data, target
```
service: input_datetime.set_datetime
data:
  datetime: '{{ now().strftime(''%Y-%m-%d %H:%M:%S'') }}'
target:
  entity_id: input_datetime.absorption_charge
```

makes the script work.

In a closely related note, if the visual editor was able to support a "now()" function, this would be awesome.

### URL

https://www.home-assistant.io/integrations/input_datetime/

### Version

2021.8.8
