### ISSUE TITLE
Which properties does the sensor need to have, to appear in the dropdown

### ISSUE THREAD

**Issue by royvanmanen** [home-assistant/home-assistant.github.io#19196]
### Feedback

I can't find why I cannot add the gas usage. I have sensors with the right properties (I think) but where can I find which properties are exactly necessary?

### URL

https://www.home-assistant.io/docs/energy/gas/

### Version

2021.9.2

### Additional information

gas sensor:
- platform: mqtt
  name: "dsmr_gas_meterreading"
  unique_id: "dsmr_gas_meterreading"
  state_topic: "dsmr/gas_meterreading"
  unit_of_measurement: m3
  icon: "mdi:fire"
  value_template: "{{ value_json.gas_meterreading | round(2) }}"
  device_class: gas
  state_class: total_increasing

**Comment by csacca** [comment]
I think this is related to https://github.com/home-assistant/frontend/issues/9900

**Comment by piltous** [comment]
Try this, worked for me:
name: "Gas Consumed"
unit_of_measurement: 'm³'

**Comment by rjulius23** [comment]
I have teh same issue but with a Shelly Plug:
sensor:
  - platform: mqtt
    name: Konyhai LED Power Consumption
    state_topic: "shellies/shellyplug-s-xxxxxx/relay/0/power"
    availability_topic: "shellies/shellyplug-s-xxxxxx/online"
    unit_of_measurement: W
    value_template: "{{ value|float|round(1) }}"
    device_class: power
    payload_available: 'true'
    payload_not_available: 'false'
    force_update: 'False'
    qos: 1
    **state_class: measurement**
  - platform: mqtt
    name: Konyhai LED Energy Consumption
    state_topic: "shellies/shellyplug-s-xxxxxx/relay/0/energy"
    availability_topic: "shellies/shellyplug-s-xxxxxx/online"
    unit_of_measurement: W
    value_template: "{{ value|float|round(1) }}"
    device_class: power
    payload_available: 'true'
    payload_not_available: 'false'
    force_update: 'False'
    qos: 1
    **state_class: measurement**

**Comment by klacol** [comment]
This workes for me:

```yaml
sensor:
  - platform: mqtt
    name: "Hauptgaszähler"
    state_topic: "My/Topic/Path/MainGasVolume"
    json_attributes_topic: "My/Topic/Path/MainGasVolume"
    value_template: "{{ value_json.Value | float | round(2) }}"
    unit_of_measurement: m³
    device_class: gas
    state_class: total_increasing
    last_reset_value_template: "2021-08-26T00:00:00+00:00"
    last_reset_topic: "My/Topic/Path/DummyResetTopic"
```

see also here: https://community.home-assistant.io/t/adding-a-mqtt-gas-meter-to-the-energy-page-but-getting-no-matching-statistics-found/335527/3

**Comment by royvanmanen** [comment]
I've added a topic in mqtt with 1-1-1970 and added

last_reset_topic: "fake/lastreset"

to the properties of the sensor.

it would be nice if there was a simple list of necessary properties that each  sensor has to have to be an option in the energy dashboard.

**Comment by bachya** [comment]
I agree, this is very confusing. I have two MQTT energy sensors (one for electricity and one for gas):

```yaml
sensor:
  - platform: mqtt
    state_topic: amr/reading/SCMplus/110/100583244/message
    name: Electricity Meter
    unique_id: electricity_meter_01
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    availability_topic: amr/status/availability
    last_reset_topic: amr/status/last_reset
    value_template: "{{ value_json.Message.Consumption | float / 1000 }}"
    json_attributes_template: "{{ value_json.Message | tojson }}"
    json_attributes_topic: amr/reading/SCMplus/110/100583244/message

  - platform: mqtt
    state_topic: amr/reading/SCM/12/51643176/message
    name: Gas Meter
    unique_id: gas_meter_01
    unit_of_measurement: "m³"
    device_class: gas
    state_class: total_increasing
    availability_topic: amr/status/availability
    last_reset_topic: amr/status/last_reset
    value_template: >
      {{ value_json.Message.Consumption | float / 100 * 2.83168 }}
    json_attributes_template: "{{ value_json.Message | tojson }}"
    json_attributes_topic: amr/reading/SCM/12/51643176/message
```

The electricity one shows up as an option in the Energy panel just fine; the gas one does not.

**Comment by loopy321** [comment]
Same issue here with electricity working, but gas does not show up in the config dropdown.

I have tried many different gas sensors, but none work.  Maybe has to do with use of templates which is needed to convert from the raw ft3 to m3....  But, I tried just setting the raw reading to units of m3 with no luck. 

```
sensor:
  - platform: mqtt
    state_topic: "rtl_433/ERT-SCM/4000003/consumption_data"  
    name: "Gas Meter"
    unit_of_measurement: ft³
    device_class: gas
    state_class: total_increasing
    expire_after: 3600 
    force_update: true
    icon: mdi:fire

  - platform: mqtt
    name: "Gas meter m3"
    state_topic: "rtl_433/ERT-SCM/4000003/consumption_data"  
    unit_of_measurement: m³
    value_template: "{{ (value | float)/35.315 | round(2) }}"
    device_class: gas
    state_class: total_increasing

  - platform: mqtt
    name: "gas metric"
    state_topic: "rtl_433/ERT-SCM/4000003/consumption_data"  
    value_template: "{{ ( value | float ) / 35.315 | round(2) }}"
    unit_of_measurement: m³
    device_class: gas
    state_class: total_increasing
    #last_reset: 2021-08-26T00:00:00+00:00  # Is not valid for templates
    last_reset_value_template: "2021-08-26T00:00:00+00:00"
    last_reset_topic: "My/Topic/Path/DummyResetTopic"

template:
  - sensor:
      name: Gas Meter CuMeters
      state: >-
        {{ states('sensor.gas_meter') | float /35.315 }}
      state_class: total_increasing
      unit_of_measurement: m3
      device_class: gas

```
