### ISSUE TITLE
RFlink integration via ESPHome serial bridge

### ISSUE THREAD

**Issue by jeroen85** [home-assistant/home-assistant.github.io#19207]
### Feedback

Following up on the description in the current documentation:
> Tested with Wifi serial bridge esp-link V2.2.3 running on a NodeMCU (ESP8266 Wifi module) with ESP8266 TXD0 (pin D10) and RXD0 (pin D9) connected to Arduino MEGA 2560 RX (Pin 2) and TX (Pin 3) respectively.

It is also very easy to create an serial bridge esp-link with use of ESPHome, by use of the following custom component: [ESPHome stream server](https://github.com/oxan/esphome-stream-server/)

Add this to your ESPhome yaml
```
external_components:
  - source: github://oxan/esphome-stream-server  

logger:
  baud_rate: 0

uart:
  - rx_pin: RX
    tx_pin: TX
    baud_rate: 57600
    data_bits: 8
    parity: NONE
    stop_bits: 1
    id: uart_rflink

stream_server:  
  uart_id: uart_rflink
  port: 1234  
```

I might be worth to add this description to the documentation.

### URL

https://www.home-assistant.io/integrations/rflink/

### Version

2021.9.2
