### ISSUE TITLE
Need to update the recommended templates for new Energy page

### ISSUE THREAD

**Issue by jschwerdlin** [home-assistant/home-assistant.github.io#19406]
### Feedback

The existing examples need to be updated to the new template format to be usable in the Energy page.  Otherwise the device class and state class aren't correct and won't show up as available options

### URL

https://www.home-assistant.io/integrations/pvoutput/

### Version

2021.9.7

**Comment by jschwerdlin** [comment]
This is what I've got implemented now and it seems to generally be working

```
template:
  - sensor:
    - name: "PVOutput Energy Used"
      unit_of_measurement: 'kWh'
      state: '{{ "%0.2f"|format(state_attr("sensor.pvoutput", "energy_consumption")|float/1000) }}'
      device_class: energy
      state_class: total_increasing
    - name: "PVOutput Energy Generated"
      unit_of_measurement: 'kWh'
      state: '{% if is_state_attr("sensor.pvoutput", "energy_generation", "NaN") %}0{% else %}{{ "%0.2f"|format(state_attr("sensor.pvoutput", "energy_generation")|float/1000) }}{% endif %}'
      device_class: energy
      state_class: total_increasing
    - name: "PVOutput Power Used"
      unit_of_measurement: "Watt"
      state: '{% if is_state_attr("sensor.pvoutput", "power_consumption", "NaN") %}0{% else %}{{ state_attr("sensor.pvoutput", "power_consumption") }}{% endif %}'
      device_class: power
    - name: "PVOutput Power Generated"
      unit_of_measurement: "Watt"
      state: '{% if is_state_attr("sensor.pvoutput", "power_generation", "NaN") %}0{% else %}{{ state_attr("sensor.pvoutput", "power_generation") }}{% endif %}'
      device_class: power

```
