### ISSUE TITLE
Minor mistake in an example of input_number being used as a delay in an automation

### ISSUE THREAD

**Issue by uherting** [home-assistant/home-assistant.github.io#19404]
### Feedback

In the section "Here’s an example of input_number being used as a delay in an automation." the example says the following:
```
  seconds:
    name: seconds
    icon: mdi:clock-start
    initial: 30
    min: 0
    max: 60
```
I the value 'max: 60' should IMHO set to 'max: 59'.

### URL

https://www.home-assistant.io/integrations/input_number/

### Version

2021.9.7
