### ISSUE TITLE
MJPEG support and HomeKit

### ISSUE THREAD

**Issue by BarryMar** [home-assistant/home-assistant.github.io#19474]
### Feedback

Hi there.

(Still learning out how HA works, so bear with me if this seems obvious or I'm missing something.)

Maybe it's worth a note in here to be aware of the info in the HomeKit page (https://www.home-assistant.io/integrations/homekit/) that MJPEG can't be directly passed to the Apple Home application (iOS) and that 

a) MJPEG camera feed needs to be converted through ffmpeg first
b) The camera needs to be setup as an isolated HomeKit Accessory
c) send only the ffmpeg stream and not mjpeg to HomeKit 

Sending MJPEG to HomeKit gave me a working thumbnail, but the movie stream just wouldn't go and I got the spinning circle of frustration.

The opposite happened with the Dashboard Card and Home Assistant iOS app though.  I couldn't get the ffmpeg stream to work with either of those, but had no issues with MJPEG there.

In the end I just created two representations of the same stream and just excluded the ones I couldn't make work.  I also tried tying it it to another random sensor I had to make it pop on-screen on the Apple TV 4K Gen2 (iOS 15) as a Door Bell and that worked fine too.

For another example to add to the docs, attached below is a sample of my configuration.yaml that works for this old DLink DCS-932L camera I had kicking around to try out.

### URL

https://www.home-assistant.io/integrations/mjpeg/

### Version

2021.9.7

### Additional information

```
ffmpeg:

camera:
  - platform: mjpeg
    name: "DLink Camera MJPEG"
    still_image_url: "http://192.168.0.199/image/jpeg.cgi"
    mjpeg_url: "http://192.168.0.199/video/mjpg.cgi"
    
  - platform: ffmpeg
    name: "DLink Camera ffmpeg"
    input: http://192.168.0.199/video/mjpg.cgi
    
homekit:
  name: DLink Doorbell Camera
  mode: accessory

  filter:  
    include_domains:
      - camera
    include_entities:
      - camera.dlink_camera_ffmpeg
    exclude_entities:
      - camera.dlink_camera_mjpeg
      
  entity_config:
    camera.dlink_camera_ffmpeg:
      linked_doorbell_sensor: binary_sensor.i_o_linc_53_41_ba_sensor
      max_width: 640
      max_height: 480
      max_fps: 30
```
