### ISSUE TITLE
Example with multiple hosts

### ISSUE THREAD

**Issue by DJF3** [home-assistant/home-assistant.github.io#19490]
### Feedback

It woud be nice to see a simple example of a config that scans 2 or 3 IP addresses.

### URL

https://www.home-assistant.io/integrations/ping/

### Version

2021.9.7

**Comment by frenck** [comment]
`binary_sensor` is a list, as shown in the example:

```yaml
binary_sensor:
  - platform: ping
    host: 192.168.0.1
    name: "device name"
    count: 2
    scan_interval: 30
```

Just add more to the list (as applies to all lists in Home Assistant, which is more a YAML concept).
