### ISSUE TITLE
Documentation is unclear for my use case: 2 inverters connected via datcom

### ISSUE THREAD

**Issue by tobox** [home-assistant/home-assistant.github.io#19613]
### Feedback

I have 2 inverters, but only one of them has the communications module with ethernet/wifi. The other inverter is connected via datcom. The first inverter shows all information for both devices using the API. But what is the proper configuration in home assistant? I have already tried this:

```
sensor:
  - platform: fronius
    resource: http://fronius.fritz.box
    monitored_conditions:
      - sensor_type: logger_info
      - sensor_type: inverter
        scope: system
      - sensor_type: meter
        device: 1
      - sensor_type: inverter
        scope: device
      - sensor_type: meter
        device: 1
        scope: device
      - sensor_type: meter
        device: 2
```

I receive the "total/system" values and the values for device 1, but no entities show up for device 2. Any ideas?

### URL

https://www.home-assistant.io/integrations/fronius/

### Version

2021.9.7
