### ISSUE TITLE
Generic thermostat

### ISSUE THREAD

**Issue by pacoso81** [home-assistant/home-assistant.github.io#19699]
### Feedback

i have used generic thermostat whit thermostat card and it is great, but i have one problem.
I'm using home made ESP12-F device for sensor and relay acting as stand alone water heater thermostat running on Tasmota.
My idea is to have thermostat that doesn't relay on wifi and is more safe to use but can be configured by Home Assistant.
So i want to parse the tempsetpoint from current setting of the card to tasmota by MQTT and occasionally send memorized set-point from Tasmota to the Lovelace card set-point.
The problem is that i can't find and parse the set-point try MQTT, also i can't set the set-point by MQTT.
So for now i'm using input number slider, the problem whit this is i can't set the mode: AUTO or OFF (i have to use other MQTT commands in tasmota - not tested yet).
Please, add entity for tempsetpoint.

my Configuration config:
```
input_number:
  target_perea_boiler:
    name: 'Perea Boiler Slider'
    min: 10
    max: 90
    step: 5
    unit_of_measurement: "°C"
    icon: mdi:target
```

Automations config:
```
- id: '1633779624125'
  alias: Perea Boiler send Setpoint to Tasmota
  trigger:
  - entity_id: input_number.target_perea_boiler
    platform: state
  action:
    service: script.perea_boiler_setpoint
  initial_state: true
- id: '1633820356897'
  alias: Set temp slider
  trigger:
    platform: mqtt
    topic: stat/Perea_boiler_thermostat/setpoint
  action:
    service: input_number.set_value
    target:
      entity_id: input_number.target_perea_boiler
    data:
      value: '{{ trigger.payload }}'
```

Script config:
```
perea_boiler_setpoint:
  alias: Perea_Boiler_Setpoint
  sequence:
  - service: mqtt.publish
    data_template:
      topic: cmnd/Perea_boiler_thermostat/TEMPTARGETSET
      payload: '{{ states.input_number.target_perea_boiler.state | int }}'
  mode: single
```

### URL

https://www.home-assistant.io/integrations/generic_thermostat/

### Version

2021.10.2
