### ISSUE TITLE
State trigger "to:" default semantics unclear

### ISSUE THREAD

**Issue by defl** [home-assistant/home-assistant.github.io#19707]
### Feedback

I have a case whereby I'm waiting for a trigger with value '9', which in this case can happen multiple times.

```
- id: s1_scene_ledstrip
  alias: S1 scene ledstrip
  trigger:
    - platform: state
      entity_id: sensor.knx_scene_s1
      to: '9'
  action:
    - service: script.s1_licht_ledstrip
```

However if the value already is '9', the above trigger doesn't trigger. It only triggers when the value was not what's in the "to:" field. This is unexpected as you can argue that in the absence of a "from:" there is nothing defined about the transition and hence a 9->9 should also be valid.

It can be fixed by changing the code to use conditions:

```
- id: s1_scene_ledstrip
  alias: S1 scene ledstrip
  trigger:
    platform: state
    entity_id: sensor.knx_scene_s1
  condition:
    condition: state
    entity_id: sensor.knx_scene_s1
    state: '9'
  action:
    - service: script.s1_licht_ledstrip
```

Probably good to add the implicit "not the to value" to the state trigger "to" field documentation.

This was discussed in https://github.com/home-assistant/core/issues/57160.

### URL

https://www.home-assistant.io/docs/automation/trigger/

### Version

2021.10.3
