### ISSUE TITLE
workday sensor usage if not using sensors in configuration.yaml

### ISSUE THREAD

**Issue by danielccm** [home-assistant/home-assistant.github.io#19838]
### Feedback

There's only an example of how to code the "workday" sensor using the configuration.yaml file.

In my case I have a few xyz_sensor.yaml files and they all work except for this one, that I get the following error while verifying the server config:

`Platform error sensor.workday - No module named 'homeassistant.components.workday.sensor'`

Ideas?

### URL

https://www.home-assistant.io/integrations/workday/

### Version

2021.10.6

**Comment by frenck** [comment]
`sensor.workday`

Its a binary sensor, not a sensor.

```yaml
# Example configuration.yaml entry
binary_sensor:
  - platform: workday
    country: DE
```
