### ISSUE TITLE
Could this be made clearer?

### ISSUE THREAD

**Issue by GrizzlyAK** [home-assistant/home-assistant.github.io#19832]
### Feedback

On [this ](https://www.home-assistant.io/docs/automation/trigger/) page, it appears that the following text and example is true ONLY after an entity's state has changed following a restart or automation reload. If the entity's state hasn't changed since a restart, this trigger will never fire. Based upon reading the text, I believed that it would. We might want to make that clear, or even better, add this capability to the Core.

```
In this example, the trigger fires if the state value of the entity remains the same for for the time specified, regardless of the current state value.

automation:
  trigger:
    - platform: state
      entity_id: media_player.kitchen
      # The media player remained in its current state for 1 hour
      for: "01:00:00"
```

### URL

https://www.home-assistant.io/docs/automation/trigger/

### Version

2021.10.4
