### ISSUE TITLE
notify.notify service data target parameter is unclear

### ISSUE THREAD

**Issue by kingo55** [home-assistant/home-assistant.github.io#20075]
### Feedback

It's not clear which entities to use here for the service data `target` parameter.

It sounds like it would support `notify.{{mobile app reference}}` but that doesn't work. E.g.:

```yaml
    service: notify.notify
    data:
      title: Hello
      message: World.
      target:
        - notify.mobile_app_id
```

### URL

https://www.home-assistant.io/integrations/notify/

### Version

2021.10.6
