### ISSUE TITLE
Yeelight service YEELIGHT.SET_COLOR_TEMP_SCENE will switch off the 'moonlight' mode

### ISSUE THREAD

**Issue by cofw2005** [home-assistant/home-assistant.github.io#20148]
### Feedback

I was creating an automation that set the Yeelight Ceiling light (ceiling2, YLXD03YL):
1. first step to 'moonlight' mode with service YEELIGHT.SET_MODE.
2. then I want to set to a specifc brightness with service YEELIGHT.SET_COLOR_TEMP_SCENE.
```
- service: yeelight.set_color_temp_scene
  target:
    entity_id: light.myceilinglight
  data:
    kelvin: 1700
    brightness: 30
```
It turns out this service also set the mode back to 'normal'.
I choose back to use light.turn_on service instead, but I would like to report this bug.
```
- service: light.turn_on
    target:
      entity_id: light.myceilinglight
    data:
      color_temp: 370
      brightness: 74
```
The light.turn_on works well.

### URL

https://www.home-assistant.io/integrations/yeelight/

### Version

2021.11.0
