### ISSUE TITLE
The climate service CLIMATE.SET_TEMPERATURE didn't set temperature after turned the heating on.

### ISSUE THREAD

**Issue by cofw2005** [home-assistant/home-assistant.github.io#20150]
### Feedback

I want to call the service to turn on the heating and in the mean time to set the temperature to 25.
But below service will not work as expected, no matter in automation or directly call service in Development Tool.
```
  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.radiator
      data:
        temperature: 25
        hvac_mode: heat
```
The problem is, if the radiator was in 'off' mode, this service will only turn it to 'heat' mode, but not set the temperature. I have to call the service again after it is on to set the temperature.
My device is Eurotronics Z-wave Thermostatic Valve Spirit.

### URL

https://www.home-assistant.io/integrations/climate/

### Version

2021.11.0

### Additional information

Here is my guess and my tries:
The attribute "temperature" of the entity "climate.radiator" is 'null' when it is in 'off' mode. When the service called to turn in to 'heat' mode, the valve physically needs to turn the gear inside and so it take 1-3 seconds, the state also updates after 1-3 second after service called. So I guess, the "set_temperature" command called in same time was ignored.
I tried to use two service call:
```
service: climate.turn_on
target:
  entity_id: climate.radiator
service: climate.set_temperature
data:
  temperature: 25
target:
  entity_id: climate.radiator
```
It didn't work either, I guess it is because the time is also too short. Then I tried further:
```
  - service: climate.turn_on
    target:
      entity_id: climate.radiator
  - wait_for_trigger:
    - platform: state
      entity_id: climate.radiator
      to: heat
    timeout: '10'
  - service: climate.set_temperature
    target:
      entity_id: climate.radiator
    data:
      temperature: 25
```
I use wait_for_trigger to wait until the state is updated to 'heat' and then set temperature. This now works.

But I just want to report this, maybe there is something can be improved. Thanks!
