### ISSUE TITLE
Failed to call service climate/set_hvac_mode. 'val' when using lovelace

### ISSUE THREAD

**Issue by AeroV95** [home-assistant/home-assistant.github.io#20307]
### Feedback

When try to power on or change the hvac mode from the lovelace dashboard, the following error is displayed. 
Failed to call service climate/set_hvac_mode. 'val'

However, pressing the button a second time works and the hvac mode is correctly set. However, this cannot be used in automation and outputs an error 'val' each time. 

Device is a gree Pular Series.

### URL

https://www.home-assistant.io/integrations/gree/

### Version

2021.11.3

**Comment by cmroche** [comment]
@AeroV95 I'm sorry, but the description of the issue here isn't really clear to me, additionally there are no logs to go by. Please enable debug logging and copy the relevant lines to the issue. Thank you.

```yml
logger:
  default: warning
  logs:
    homeassistant.components.gree: debug
    greeclimate: debug
```
