### ISSUE TITLE
Apprise page

### ISSUE THREAD

**Issue by maynardpa** [home-assistant/home-assistant.github.io#20376]
### Feedback

Hi, it might be a simple or silly question. Is apprise pre-installed in the Raspberry Pi system image or is there a need to install it manually via the command line (SSH)? Also, for the configuration files, do they need to be next to the HA configuration.yaml file or in a separate folder?

I have checked the integration and supervisor menus and can't find a way to toggle it on so my original point might be true.

Thanks!

### URL

https://www.home-assistant.io/integrations/apprise/

### Version

2021.11.5

**Comment by caronc** [comment]
Hi,

So out of the box apprise will just work, but if you need help constructing your URL, you can install the Apprise CLI on your local machine (or sure... even in the raspberry pi too).  Get your URL right so you can do the following:
```bash
apprise -vvv -t test -b message schema://the/url/you/need/to/get/right
```

Personally, i like keeping my configuration secured in a config file that i can share with other things, so my Apprise Declaration looks like this:
```yaml
notify:
  name: apprise
  platform: apprise
  config: /etc/homeassistant/apprise.yaml
```

With respect to the above, i keep my configuration (specific to apprise) in it's own file (` /etc/homeassistant/apprise.yaml`) which in my case might look like this:
```yaml
#
# Our Apprise Configuration File
#

urls:
  # Email notification
  - mailtos://user:password@gmail.com:
    - tag: alarm, email
      to: some.email.address@example.com

  # Pushbullet notification
  - pbul://token:
    - tag: alarm, pushbullet

  # Setup our KODI instances and assign them both to the
  # tv tag
  - kodi://mykodi-server01.example.local:
    - tag: tv

  - kodi:/mykodi-server02.example.local:
    - tag: tv

```
The above is a bit of a complex example, but what you should take away from it is:
- I'm leveraging tagging by assigning one or more tags to my Apprise URLs.
- I'm specifying lots of ways to send notifications.
- With respect to the above example... if i sent my `target` to `tv`, i would notify everything tagged with it
- You don't need to do all of this complexity... your HA configuration can look as simple as:
   ```yaml
     notify:
       name: apprise
       platform: apprise
       url: mailtos://user:password@gmail.com
   ```

   You can also specify more then one URL by separating each entry above with a comma, `,`... hence:
   ```yaml
     notify:
       name: apprise
       platform: apprise
       url: mailtos://user:password@gmail.com, kodi://myserver.hostname
   ```

Once your messages are sending correctly, you can set up your notifications like so... (as an example):
 ```yaml
# some sort of automation:
#
# Send a notification if outside interaction is detected
#
- alias: "[Detect] - Outside Interaction via Front Door"
  initial_state: true

  trigger:
    platform: state
    entity_id: sensor.ultrasync_zone1state
    from: 'Ready'
    to: 'Not Ready'

  condition:
    - condition: state
      entity_id: input_boolean.home_monitor
      state: "on"

  action:
  - service: notify.apprise
    data_template:
      target: pushbullet
      title: Arrival
      message: >-
        'Arrival {{ now().strftime('%Y-%m-%d') }}'
```

In the above example, I've configured a `pushbullet` tag (as you would have saw in my original configuration above).  I can set the `target` to this.  If you don't specify a `target`, all of your notifications will be notified.  If you do specify a `target`, it's implied you're also leveraging tagging. 

Here is just a simple notification (HA Automation) that triggers on a sunset:
```yaml
- alias: "[Interactive] - Sunset Apprise Notice"
  trigger:
    platform: sun
    event: sunset
  
  action:
    service: notify.apprise
    data:
      target: email
      title: "Good evening"
      message: "This sun is setting."
```

In the above, `target` is specified again, so it's important I'm leveraging tagging again, but if you were to just not include that line, all Apprise URL's you defined would receive the notice.

Hopefully this all makes sense; please feel free to ask anymore questions! :slightly_smiling_face:
