### ISSUE TITLE
Play TTS incident on Sonos

### ISSUE THREAD

**Issue by NeuzNL** [home-assistant/home-assistant.github.io#20404]
### Feedback

On the site there is an example how to create a tts ffor a incident. This example is working on a google device (not tried alaxa) but not on a sonos device.. The reason for this issue probebly is the delay of the mp3 file of the incident, most of the time my sonos device already started (and ended) the automation before the mp3 file was live. 

To make the TTS incident work on sonos is to make a service like google_say.
For example:
`
- alias: TTS Incident Report
  trigger:
    platform: state
    entity_id: sensor.incidents
  mode: single
  action:
    - service: tts.google_say
      data:
        entity_id: media_player.sonos
        message: "{{states('sensor.incidents')}}"
        language: nl #choose your own language
`

### URL

https://www.home-assistant.io/integrations/fireservicerota/

### Version

2021.11.5

**Comment by frenck** [comment]
This looks like a bug, as the example seems correct.

**Comment by jjlawren** [comment]
Does sending an audio file to the Sonos speaker using `media_player.play_media` work as expected?

If this only affects Sonos devices, it's likely related to the URL or perhaps an SSL issue. Can you explicitly set your `base_url` in the `tts` configuration to a base address that the Sonos speakers can directly resolve/reach?

configuration.yaml example:
```yaml
tts:
  - platform: google
    base_url: 'https://<unique_cloud_id>.ui.nabu.casa'
```

**Comment by NeuzNL** [comment]
> This looks like a bug, as the example seems correct.

@frenck ,
I use the example for quit some time now and it's working fine for me.


> Does sending an audio file to the Sonos speaker using `media_player.play_media` work as expected?
> 
> If this only affects Sonos devices, it's likely related to the URL or perhaps an SSL issue. Can you explicitly set your `base_url` in the `tts` configuration to a base address that the Sonos speakers can directly resolve/reach?
> 
> configuration.yaml example:
> 
> ```yaml
> tts:
>   - platform: google
>     base_url: 'https://<unique_cloud_id>.ui.nabu.casa'
> ```

@jjlawren,
Sending a mp3 audio file to the sonos is working great. The error seems to be the delay between the mp3 file uploaded from
fireservicerota (brandweerrooster) and the trigger from that same integration. 

The upload from the mp3 file is not finised when the trigger already started the automation.
When i try to play the mp3 file from fireservicerote some time later (5 minutes or couple of hours) it's working fine.

**Comment by jjlawren** [comment]
Okay, I think I understand better now. The `sensor.incidents` entity provides the message text in its state but also provides a separate `message_to_speech_url` attribute. Your example appears to be taking the text string and forwarding it to Google TTS, ignoring the built-in TTS MP3 provided by the `fireservicerota` integration.

If the Google TTS method is failing, perhaps the state text is not updated/available on the entity. You could probably track this down by looking through an automation trace ([docs](https://www.home-assistant.io/docs/automation/troubleshooting/)).

Alternatively, have you tried using `media_player.play_media` with the provided MP3 directly?:
```yaml
alias: TTS Incident Report
id: tts-incident-to-sonos
trigger:
    platform: state
    entity_id: sensor.incidents
    mode: single
action:
    service: media_player.play_media
    data:
        entity_id: media_player.sonos
        media_content_id: "{{state_attr('sensor.incidents', 'message_to_speech_url')}}"
        media_content_type: music
```
