### ISSUE TITLE
In Automation Trigger how can use "for:" with input_datetime

### ISSUE THREAD

**Issue by vespadj** [home-assistant/home-assistant.github.io#20410]
### Feedback

Having a **_input_datetime_**:
```yaml
# in configuration.yaml 
input_datetime:
  my_time:
    name: Input with only time
    has_date: false
    has_time: true
```
it may set in hh:mm e.g.: "01:15"
Where:
`"{{ states('input_datetime.my_time') }}"`
return
`"01:15:00"`

But, this isn't supported yet:
```yaml
automation:
  trigger:
    - platform: numeric_state
      above: 80
      for: "{{ states('input_datetime.my_time') }}"  # doesn't work yet
```
So, the **workaround** is split it in an array ["01", "15", "00"]:
```yaml
automation:
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.temperature_1
        - sensor.temperature_2
      above: 80
      for:
        hours: "{{ states('input_datetime.my_time').split(':')[0] | int }}"
        minutes: "{{ states('input_datetime.my_time').split(':')[1] | int }}"
        # seconds: "{{ states('input_datetime.my_time').split(':')[2] | int }}"
```

--> This trick should be reported in the guide.

**_Bonus_**:
if user intends to use "My time (mm:ss)" e.g.: 02:30,
the code becomes:
```yaml 
for:
  # hours: "{{ states('input_datetime.my_time').split(':')[0] | int }}"
  # in format mm:ss states however returns "hh:mm:ss", so force parsing
  minutes: "{{ states('input_datetime.my_time').split(':')[0] | int }}"
  seconds: "{{ states('input_datetime.my_time').split(':')[1] | int }}"
```

### URL

https://www.home-assistant.io/docs/automation/trigger/#numeric-state-trigger

### Version

2021.11

**Comment by frenck** [comment]
You can't use datetime with the `numeric_state` conditions or triggers, as its is not a numeric value... This can only be done using template trigger/condition.

However, we use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by vespadj** [comment]
Docs in https://www.home-assistant.io/docs/automation/trigger/#numeric-state-trigger
reports
```yaml
for:
        minutes: "{{ states('input_number.high_temp_min')|int }}"
        seconds: "{{ states('input_number.high_temp_sec')|int }}"
```
using n.2 `input_number`.

I do the same with only one `input_datetime`, look workaround in my first post.
