### ISSUE TITLE
Reconnect example for homematic integration not working

### ISSUE THREAD

**Issue by eikowagenknecht** [home-assistant/home-assistant.github.io#20432]
### Feedback

The reconnect example is not working. It says:

```
template:
  - binary_sensor:
    - name: "Homematic is sending updates"
      state: >-
        {{ now() - as_timestamp(state_attr('sensor.office_voltage', 'last_changed'), 601) < 600 }}
```

This has three problems:
1. It leads to Home Assistant complaining that datetimes (now) can not be compared with integers.
2. state_attr('sensor.office_voltage', 'last_changed' does not get the time but a null value.
3. last_changed is suboptimal because when the actual value doesn't change then only last_updated is renewed and not last_changed

My proposed (and for me working) fix would be:

```
template:
  - binary_sensor:
      - name: "Homematic is sending updates"
        state: >-
          {{ as_timestamp(now()) - as_timestamp(states.sensor.office_voltage.last_updated, 0) < 600 }}
```

This fixes:
1. Compare two float values (time in seconds)
2. Use the correct syntax to get the last_* value (see examples on https://www.home-assistant.io/docs/configuration/templating/)
3. use last_updated instead of last_changed

What I'm not sure about: Is there a moment where last_updated is not known? If so, is putting a default of 0 here the right thing to do? This would lead to a very high value and thus this sensor as false, triggering a reconnect. Or should this sensor show true in this case?

Since I'm new to Home Assistant I'd like some feedback if this is the optimal solution before creating a PR.

### URL

https://www.home-assistant.io/integrations/homematic/

### Version

2021.11.5
