### ISSUE TITLE
Detecting lost connections template incorrect

### ISSUE THREAD

**Issue by patman15** [home-assistant/home-assistant.github.io#20481]
### Feedback

Hi!

The chapter _Detecting lost connections_ suggest to use the following template for detecting lost connections to CCU:
```
template:
  - binary_sensor:
      - name: "Homematic is sending updates"
        state: >-
          {{ now() - as_timestamp(state_attr('sensor.office_voltage', 'last_changed'), 601) < 600 }}
```
In my opinion there are two issues:
1. the now() function does not give an integer value so if you try to evaluate the template HA returns
`TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'int'`
2. I suggest to replace `last_changed` with `last_updated` as the value could stay constant although the sensor updates

My approach/suggestion would be:
```
template:
  - binary_sensor:
      - name: "Homematic is sending updates"
        state: >-
          {{ 'unavailable' if is_state('sensor.office_voltage', 'unavailable') else (now() - states.sensor.office_voltage.last_changed).total_seconds() < 600}}
```

### URL

https://www.home-assistant.io/integrations/homematic/

### Version

2021.11.5
