### ISSUE TITLE
POSSIBLE BUG: Space in 'destination'

### ISSUE THREAD

**Issue by richardjlyon** [home-assistant/home-assistant.github.io#20605]
### Feedback

Hello. This works:

```
- platform: uk_transport
  app_id: xx
  app_key: xx
  queries:
  - mode: bus
    origin: 6200203610 # Clermiston Drive Bus Stop
    destination: Edinburgh # 43
```

This does not:
```
- platform: uk_transport
  app_id: xx
  app_key: xx
  queries:
  - mode: bus
    origin: 6200203610 # Clermiston Drive Bus Stop
    destination: 'Kings Buildngs' # 41
```

I’ve verified on the portal that there are buses. But the integration returns a zero-length list of buses:
```
atcocode: 6200203610
locality: Barnton, Edinburgh
stop_name: Clermiston Drive
request_time: 2021-12-07T11:18:14+00:00
next_buses: 
unit_of_measurement: min
friendly_name: Next bus to Kings Buildngs
icon: mdi:bus
```

Could the space in the destination field be tripping up the code?

### URL

https://www.home-assistant.io/integrations/uk_transport/

### Version

2021.11.5
