### ISSUE TITLE
Support for Turning the Receiver Off and Switching Sources

### ISSUE THREAD

**Issue by MisterOneTwo** [home-assistant/home-assistant.github.io#20619]
### Feedback

Thanks for all of the hard work here!

For some quick background, I have two HA scripts that turn my entire media room on and off.  'On' turns on some lights, turns on my projector, turns on my Nvidia Shield, sets it to Plex, turns on my receiver, sets it to the shield, turns off some lights.

This was all with an Onkyo receiver and I just upgraded to an Anthem MRX 740.  I was able to turn the Onkyo on and off in home assistant using media_player.turn_on/off.  media_player.turn_on simply turned on my receiver, no other actions.  Same for off.

With the anthemav AV platform, I am currently using CEC from my Nvidia Shield to turn the Anthem on, by turning on the shield media_player, since turning the anthem entity on directly with media_player.turn_on sets it to the Anthem streaming input instead of just powering on the device.  I am turning the Anthem off the same way, by turning off the Shield in the script, which then turns off the Anthem via CEC.  media_player.turn_off for the anthem entity does nothing.

With the Onkyo, I was also able to map sources in the YAML like this:

```
  - platform: onkyo
    host: 192.168.2.188
    name: Receiver
    sources:
      dvd: "XBOX"
      video2: "SWITCH"
      strm-box: "SHIELD"
```

And then create a script that I can use on a button to change the source like this:

```
alias: Receiver Select Source Shield
sequence:
  - service: media_player.select_source
    target:
      entity_id: media_player.receiver
    data:
      source: SHIELD
mode: single
```

Do you have any thoughts on the possibility of the anthemav platform supporting simple on and off of the anthem receiver, and the ability to simply select the source?  I'd be happy to make a small donation!

### URL

https://www.home-assistant.io/integrations/anthemav/

### Version

2021.11.5
