### ISSUE TITLE
Map Card dark_mode

### ISSUE THREAD

**Issue by pex81** [home-assistant/home-assistant.github.io#20622]
### Feedback

In type: map card is not possible use [jinja2 templates ](https://www.home-assistant.io/docs/configuration/templating/)
```
dark_mode: >
  {% if is_state('sun.sun', 'below_horizon') %}
    true
  {% else %}
    false
  {% endif %}  
```

### URL

https://www.home-assistant.io/lovelace/map/

### Version

2021.11.5

**Comment by pex81** [comment]
The card map unfortunately still there is no way to change the dark_mode based on the sun sensor. The only way is to create a conditional card.

```
type: conditional
conditions:
  - entity: sun.sun
    state: "above_horizon"
card:
  type: map
  aspect_ratio: 16:9
  default_zoom: 8
  dark_mode: true     <-----
  entities:
    - sensor.my_sensor

type: conditional
conditions:
  - entity: sun.sun
    state: "below_horizon"
card:
  type: map
  aspect_ratio: 16:9
  default_zoom: 8
  dark_mode: false       <----
  entities:
    - sensor.my_sensor
```
