### ISSUE TITLE
Example to Select Source for Spotify Media Player

### ISSUE THREAD

**Issue by anthonyjacques20** [home-assistant/home-assistant.github.io#20704]
### Feedback

I think the documentation would benefit from an explanation of how `media_player.select_source` can be used with `media_player.spotify`. Since Spotify is considered its own media_player that chooses which input to use (choosing from its own `capabilities.source_list`), I think adding an optional `service` to the `Playing Spotify Playlists` section would be really helpful! Also adding some explanation of how to know Spotify's `source_list`, taking it either from Spotify's `Available Devices` section in the Spotify app or taking it from the `core.entity_registry` file and searching for the Spotify entity.

Something along the lines of:
```
# Example script to select spotify source and play playlist
script:
  play_jazz_guitar_on_home_theater:
    sequence:
      - service: media_player.select_source
        target:
          entity_id: media_player.spotify
        data:
          source: Home Theater
      - service: media_player.play_media
        target:
          entity_id: media_player.spotify
        data:
          media_content_id: "https://open.spotify.com/playlist/5xddIVAtLrZKtt4YGLM1SQ?si=YcvRqaKNTxOi043Qn4LYkg"
          media_content_type: playlist
```

I also think it would be worth noting that the `media_player` isn't called `spotify` but rather `spotify_xxx` and should be found in the `entity` page. (Or maybe this is obvious and since I'm new to Home Assistant, this is clear?)

Most of this information I found from [this post](https://community.home-assistant.io/t/lovelace-card-to-turn-avr-on-and-play-spotify-music-with-one-button/325252/7)

### URL

https://www.home-assistant.io/integrations/spotify/

### Version

2021.12.1
