### ISSUE TITLE
Help falls short of explaining what is needed for mjpeg video streams.

### ISSUE THREAD

**Issue by Bazmundi** [home-assistant/home-assistant.github.io#20731]
### Feedback

The reader is left hanging when directed to consider Camera MJPEG Streams.  The example suggests HA needs to communicate with camera ports of cameras attached to motioneye but fails to explain how to set that up.  Does that mean setting up ports in motioneye docker container to allow the ports allocated to the camera to be accessed?   Is the following section on stream URL templates that means?   

### URL

https://www.home-assistant.io/integrations/motioneye/#Camera MJPEG Streams

### Version

2021.12.2

### Additional information

I have motioneye running in a docker container on the same RPi3 as I am running HA, also as a docker container.

In HA, the integration for motioneye reports ip cameras as existing but forever unavailable.   I assumed it may be this idea of having to "see" the camera port via motioneye.  Finding the guidance on MJPEG cameras, I assumed I was to ensure motioneye was streaming video on the same port as the camera(?).

With an IP camera streaming on port 8800, I have taken the instruction to do something like this in my docker-compose file:

 ```
 motioneye:
    container_name: motioneye
    image: ccrisan/motioneye:master-armhf
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/motioneye:/etc/motioneye
      - /var/lib/motioneye:/var/lib/motioneye
    ports:
      - "8765:8765"
      - "8800:8800"
    restart: always

```

That has not helped, as the camera is still seen as unavailable.   However, the help has lead to the conclusion it should.   If this is not the means to allow HA to "see" the camera port then what other interpretations are there?
