### ISSUE TITLE
`transition` deprecated?

### ISSUE THREAD

**Issue by GrizzlyAK** [home-assistant/home-assistant.github.io#20897]
### Feedback

Why am I getting the following warning in my logs when using scene.apply with light entities?

```
The use of other attributes than device state attributes is deprecated and will be removed in a future release. 
Invalid attributes are ['brightness_pct', 'transition']. 
Read the logs for further details: https://www.home-assistant.io/integrations/scene/
```
There is no mention of pending deprecation in the docs referenced.

### URL

https://www.home-assistant.io/integrations/scene/

### Version

2021.12.6

**Comment by frenck** [comment]
Correct, documentation reflects the latest state of Home Assistant. Release notes provide information about changes.

This is not an bug or error; but actually correct.

Both `brightness_pct` and  `transition` are not valid anymore.

**Comment by GrizzlyAK** [comment]
So, documentation will continue to list deprecated features until they stop working then? Because these may not be valid, but hey do work (as described in the docs). I guess I just figured the documentation would either _not list_ or mark as deprecated  any features that are affected (now or in the future), kind of like this:

![image](https://user-images.githubusercontent.com/4411963/147518542-ad020d78-9e4d-4819-a851-b983d09966c3.png)

**Comment by frenck** [comment]
> So, documentation will continue to list deprecated features until they stop working then? 

No, deprecations are generally removed from the documentation; Unless the whole integration is deprecated, as in the screenshot you've posted. In those cases a warning is added to the top of the page.

> Because these may not be valid, but hey do work (as described in the docs)

Deprecated items may stop working any time; as deprecated functionality is pending removal.
I'm not sure what you mean by "described in the docs"? I don't see deprecated functionality on the scenes page you left this documentation feedback on?

**Comment by GrizzlyAK** [comment]
OK, so perhaps I'm not understanding the message being provided in the logs. This is related to the following service call:

```
            service: scene.apply
            data:
              entities:
                light.hue_lr_lights_lgrp:
                  brightness_pct: "{{ states('input_number.lr_accent_brightness_in') | float }}"
                  hs_color:
                    - "{{ states('input_number.lr_accent_hue_in') | float }}"
                    - "{{ states('input_number.lr_accent_saturation_in') | float }}"
                  state: 'on'
                  transition: "{{ states('input_number.hue_light_transition_time_in') }}"
```
Even tho I AM calling the `scene.apply` service, the data being provided is related to the `light` entity, which I assume must be relevant to a `light`, right? In the documentation for `light`, both of these, along with a host of others, are suitable parameters to use for controlling a light. I thought a scene was just another way of controlling a group of similar or disparate entities at one time. It doesn't make sense that transition isn't valid in setting a scene for lighting. 

What am I missing?

**Comment by frenck** [comment]
See: <https://www.home-assistant.io/integrations/scene/#using-scene-transitions>

```yaml
            service: scene.apply
            data:
              entities:
                light.hue_lr_lights_lgrp:
                  brightness_pct: "{{ states('input_number.lr_accent_brightness_in') | float }}"
                  hs_color:
                    - "{{ states('input_number.lr_accent_hue_in') | float }}"
                    - "{{ states('input_number.lr_accent_saturation_in') | float }}"
                  state: 'on'
              transition: "{{ states('input_number.hue_light_transition_time_in') }}"
```

That fixes the transition, transition is not a state, but an option to apply a scene in a way. (You can't walk up to a light bulb and say: Wow, this bulb is emitting a nice 2.5 seconds transition).

`brightness_pct` needs to be replaced by `brightness`.
