### ISSUE TITLE
Update template fan documentation to include the script examples

### ISSUE THREAD

**Issue by cosyd** [home-assistant/home-assistant.github.io#20978]
### Feedback

The template fan https://www.home-assistant.io/integrations/fan.template/  references several scripts to update the entity attributes and perform the actions, but they are not included in the example. 
https://community.home-assistant.io/t/guide-template-fan-and-broadlink/323488 explains this including script examples. 
An expanded example including the referenced scripts like this one would be helpful.

### URL

https://www.home-assistant.io/integrations/fan.template/

### Version

2021.12.7

**Comment by frenck** [comment]
You mean the things like input booleans?

**Comment by cosyd** [comment]
Yes, that would be 
1) definition of the input entities to keep track of the status (input_number, input_boolean, input_select) which is currently not in the example, 
2) then the actual fan template (as it currently is in the documentation example) 
3) then the scripts which the fan template calls to update the input entities and the fan entity which are currently not in the example

**Comment by frenck** [comment]
But, those are done in the UI, you don't need code for that.

**Comment by cosyd** [comment]
If the fan template uses
```
percentage_template: "{{ states('input_number.fan_percentage') }}"
set_percentage:
      service: script.fan_set_percentage
      data:
         percentage: "{{ percentage }}"

```
then I need to put this right before the fan template into the configuration.yaml :
```
input_number:
  fan_percentage:
    name: fan speed percentage
    min: 0
    max: 100
```
otherwise the fan percentage wouldn't update when I later define in scripts.yaml :
```
fan_set_percentage: # Set speed via percentage. Home Assistant new standard method.
  alias: Set fan percentage 0..100
  sequence:
   # update fan entity percentage through the defined input in the percentage template
   - service: input_number.set_value 
     target:
        entity_id: input_number.fan_percentage
      data:
        value: "{{ percentage }}"
    # now turn the actual fan on
    - service:  [...] 
```
Wasn't obvious to me and it seems others in the forum. Not sure where in the UI this would be performed, but when using yaml editing it would be helpful to have these hints.
