### ISSUE TITLE
Shelly RGBW2 Color Automatisation?

### ISSUE THREAD

**Issue by winconlin** [home-assistant/home-assistant.github.io#21028]
### Feedback

Hi I tried to configure my LED RGB strip so that it sets its color to red during a given time. Unfortunately it just turns on but does not change the color.
automatisations.yaml

```yaml
- id: '1641380941677'
  alias: Rotes Licht
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 865af2c8ea1855c560dd971c8c41d859
    entity_id: binary_sensor.bewegungsmelder_schlafzimmerbett_ias_zone
    domain: binary_sensor
  condition:
  - condition: time
    after: '22:00'
    before: 06:00
  action:
  - type: turn_on
    device_id: 7a4ce77ea3b968372870256a4364ded4
    entity_id: light.shellyrgbw2_f435c8
    domain: light
    brightness_pct: 100
  mode: single`
```

there is no option to add the color of the strip...
if i add it manually with rgbcolor : [255,0,0] nothing happens

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2021.12.8
