### ISSUE TITLE
Sun condition

### ISSUE THREAD

**Issue by peterfares** [home-assistant/home-assistant.github.io#21071]
### Feedback

Documentation regarding the sun condition is a little confusing

An example is given and later it is shown that it can not be done as shown in the example.

```yaml
condition:
  - condition: sun
    after: sunset
    before: sunrise
```

> This is ‘when dark’ - equivalent to a state condition on sun.sun of below_horizon.

I would suggest removing this example. The correct way of doing this is shown right below it. 

### URL

https://www.home-assistant.io/docs/scripts/conditions/

### Version

2021.12.8
