### ISSUE TITLE
Code Snippeds are missing

### ISSUE THREAD

**Issue by S04fab** [home-assistant/home-assistant.github.io#21139]
### Feedback

Hey,
first of all i am very thankfull, for adding musiccast.
But, i can not code like u ;) so without code snippeds like how to group and ungroup speakers, i can not use the whole power of your implementation.

And in your code you are typing SONOS? But shouldn't this be yamaha?

So it would be great if you could please give me and the other musiccast users some help ;)

BG
Fabian

### URL

https://www.home-assistant.io/integrations/yamaha_musiccast/

### Version

2021.12.8

**Comment by micha91** [comment]
Hi, I am not sure, if I understand your problem, but I will do my very best to resolve it.

Regarding your sonos note, are you talking about these [examples](https://www.home-assistant.io/integrations/yamaha_musiccast/#examples)? The entity_id of a media_player, which is 'media_player.sonos' in one of the examples, can freely be set by the user. So a yamaha media_player could also be named 'media_player.sonos'.

Regarding the grouping, we only inplement the services, which are defined in the media_player component. The service to generate/extend a group is named join and the service to leave a group is named unjoin. The documentation is available [here](https://www.home-assistant.io/integrations/media_player#service-media_playerjoin). If you would like to use them from the UI, I would highly recomment taking a look into [mini-media-player](https://github.com/kalkih/mini-media-player). The platform you need to select for the grouping is media_player.

**Comment by S04fab** [comment]
Hey Micha91,
thanks for your very quick reply.

![image](https://user-images.githubusercontent.com/84475406/149221280-46e5729b-cd79-47b5-aace-e633cc5bd0b6.png)

`type: custom:mini-media-player
entity: media_player.wohnzimmer
hide:
  power: true
speaker_group:
  platform: MusicCast
  show_group_count: true
  entities:
    - entity_id: media_player.wohnzimmer
      name: Wohnzimmer
    - entity_id: media_player.kuche
      name: Küche
entities:
  - type: custom:mini-media-player
    entity: media_player.multiroom_player
    group: true
    source: icon
    artwork: cover
    info: short
    hide:
      volume: true
      power: true
  - type: custom:mini-media-player
    entity: media_player.wohnzimmer
    group: true
    hide:
      controls: true
  - type: custom:mini-media-player
    entity: media_player.kuche
    group: true
    hide:
      controls: true
`

I could create a Card with my Musiccast Entities, but i still get the Error:
"Fehler beim Aufrufen des Diensts MusicCast/join. Unable to find service musiccast.join"

But i have no idea how to add the service Join / Unjoin
And i saw, that you seem to be an expert for yamaha and musiccast ;)

So if you could help me out, i would be very thankful!

BG
Fabian

**Comment by micha91** [comment]
You just have to set platform to media_player. E.g.
```yaml
    type: custom:mini-media-player
    group: true
    entity: media_player.buro
    name: Büro
    toggle_power: false
    artwork: cover
    hide:
      icon: true
      power_state: false
    speaker_group:
      platform: media_player
      expanded: true
      entities:
        - entity_id: media_player.wohnzimmer_2
          name: Wohnzimmer
        - entity_id: media_player.buro
          name: Büro
        - entity_id: media_player.schlafzimmer
          name: Schlafzimmer
        - entity_id: media_player.badezimmer
          name: Bad
        - entity_id: media_player.kuche
          name: Küche
        - entity_id: media_player.wohnzimmer_zone2
          name: Terrasse
```
