### ISSUE TITLE
youtube cast: playlist_id not working

### ISSUE THREAD

**Issue by mytasker** [home-assistant/home-assistant.github.io#21158]
### Feedback

Frist, I can't be thankful enough for your guys amazing working 

I would like your guy's opinion if I'm doing something wrong or the Youtube cast option using "playlist_id" isn't working.

When running the bellow scrip, I can connect to the Chromecast device, but it does not play the playlist_id. It works if I use media_id, but it is a single video per time.  

alias: 'TEST: YouTube to My Chromecast'
sequence:
  - data:
      media_content_type: cast
      media_content_id: ' { "app_name": "youtube", "playlist_id": "PLSlWCUnZ5deDcEWu50m_I-iCgIfm0jqv9", "enqueue": "true"}'
    service: media_player.play_media
    target:
      device_id: 2351a1ea30223268a26c49e70ec94199
mode: single

So, am I doing anything wrong? Would the documentation be able to explain with an example the right way to use playlist_id if my scrip above is wrong?

Much appreciate your hard work. Looking forward to your reply. 

### URL

https://www.home-assistant.io/integrations/cast/

### Version

2021.12.9

**Comment by emontnemery** [comment]
To play a playlist, you need to include both an entry in the playlist and the playlist itself, similar to how the youtube site behaves when you play a video in a playlist:
https://www.youtube.com/watch?v=CoHD4weW5NI&list=PLSlWCUnZ5deDcEWu50m_I-iCgIfm0jqv9&index=1

For example:
```yaml
service: media_player.play_media
data:
  media_content_id: '{ "app_name": "youtube", "media_id": "CoHD4weW5NI", "playlist_id": "PLSlWCUnZ5deDcEWu50m_I-iCgIfm0jqv9"}'
  media_content_type: cast
target:
  entity_id: media_player.nesthub43ad
```
