### ISSUE TITLE
Multiple Instances need setup to SMS different recipients

### ISSUE THREAD

**Issue by markus99** [home-assistant/home-assistant.github.io#21165]
### Feedback

Recently setup this platform, but had to do so using multiple instances in order to text a variety of #s / combinations thereof.  

Ie. I could NOT specify a 'target' in the service call, as the configuration.yaml **recipient** controlled where the SMS(es) actually were sent.  To this end, I had to setup multiple instances in configuration.yaml in order to text different people / combinations of people.  This created multiple notify services that then work correctly.  Believe the document should reflect the need to setup multiple instances of `platform: clicksend` in order to send to different people / combinations thereof.  

Here's my setup, fwiw:

**configuation.yaml:**
```
notify:
  - name: clicksend_sms_x_and_y
    platform: clicksend
    username: CLICKSEND_USERNAME
    api_key: CLICKSEND_API_KEY
    recipient: [PHONE_NO1, PHONE_NO2]
  - name: clicksend_sms_x
    platform: clicksend
    username: CLICKSEND_USERNAME
    api_key: CLICKSEND_API_KEY
    recipient: [PHONE_NO1]
  - name: clicksend_sms_y
    platform: clicksend
    username: CLICKSEND_USERNAME
    api_key: CLICKSEND_API_KEY
    recipient: [PHONE_NO2]
  - name: clicksend_sms_z
    platform: clicksend
    username: CLICKSEND_USERNAME
    api_key: CLICKSEND_API_KEY
    recipient: [PHONE_NO3]  
```

### URL

https://www.home-assistant.io/integrations/clicksend/

### Version

2021.12.9
