### ISSUE TITLE
name variable sets entity name not friendly name

### ISSUE THREAD

**Issue by metbril** [home-assistant/home-assistant.github.io#21190]
### Feedback

The documentation states that [the `name:` variable](https://www.home-assistant.io/integrations/utility_meter/#name) would only set the UI name for the entity. 

> The friendly name to use in the GUI.

This is not true.
If specified, it will set the entity_id (e.g. replace the original id).

This config will create `sensor.appliance_daily_energy` with `friendly_name` 'Appliance Daily Energy':
```yaml
utility_meter:
  applicance_daily_energy:
    source: sensor.appliance_energy
    cycle: daily
```

This config will create `sensor.appliance_friendly_daily_energy` with `friendly_name` 'Appliance Friendly Daily Energy':
```yaml
utility_meter:
  applicance_daily_energy:  # <-- expected sensor name
    source: sensor.appliance_energy
    name: Appliance Friendly Daily Energy
    cycle: daily
```

I'm not sure if this is a documentation error or a bug in the component.

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2021.12.9

### Additional information

A workaround is, to use customization:

```yaml
homeassistant:
  customize:
    sensor.appliciance_daily_energy:
      friendly_name: Appliciance Friendly Daily Energy

utility_meter:
  applicance_daily_energy:
    source: sensor.appliance_energy
    cycle: daily
```

**Comment by dgomes** [comment]
Well the documentation does not say **only** :)

Name is optional, if it exists it takes precedence over the slug used to define the utility_meter.

I hope that In the future the slug can be considered a unique_id (that would enable name setting through the UI) - but this is future work pending the architecture of HA allowing for it

**Comment by metbril** [comment]
You really should consider updating the docs. And this way doesn't really make me want to help improve HA and spend  time to submitting issues.

**Comment by dgomes** [comment]
If you feel documentation is not clear enough, you can also open Pull Requests towards improving the said documentation, it will be highly appreciated

**Comment by frenck** [comment]
This is generic Home Assistant behavior, entity IDs are based on their name. This is not specific to this integration.

**Comment by metbril** [comment]
@frenck This is not how helpers (`input_xxx`) behave. If you give them an entity id, then the name will be used as the friendly name. For example (from the [docs](https://www.home-assistant.io/integrations/input_text/)):

```yaml
# Example configuration.yaml entries
input_text:
  text1:
    name: Text 1

# etc
```

This will create an entity `input_text.text1` with a friendly name "Text 1". 
And **not** an entity `input_text.text_1` with friendly name "Text 1".
Which I was expecting from the utility meter, too.

I use this to have english entity names with local (Dutch) friendly names. Of course the workaround is to add a customization, but having it included in the entity configuration is much more convenient.

And both utility meter and input text cannot be edited through the UI anyway.
