### ISSUE TITLE
Details for success using iOS & Home Assistant App

### ISSUE THREAD

**Issue by sugarpines** [home-assistant/home-assistant.github.io#21292]
### Feedback

Thanks for providing this platform.

Home Assistant 2021.12.10 on Raspberry Pi 3b v1.2.
Synology Router RT2600ac.

I accessed Home Assistant via iOS App on iPhone "MyPhone". This created a device named "MyPhone" and many entities including one named "MyPhone" with entity id "device_tracker.myphone".

I later configured synology_srm device_tracker platform in configuration.yaml per instructions:
```
device_tracker:
  - platform: synology_srm
    host: !secret srm_host
    port: !secret srm_port
    username: !secret srm_un
    password: !secret srm_pw
    interval_seconds: 30
    consider_home: 180
    new_device_defaults:
      track_new_devices: true
```

Many device_tracker entities were created (perhaps one for each DHCP client) but the device_tracker.royphone is associated with integration "Mobile App" while the others are associated with integration "Device tracker".

After some research I realized the phone was not appearing on the router's DHCP Clients and I came across [this article](https://kb.synology.com/en-ca/SRM/tutorial/What_can_I_do_if_router_cant_recognize_mac_addresses) indicating that the phone was not registering with my Synology Router. I followed the instructions for the phone to appear but was still unable to find the new device_tracker entity until I saw that it was listed using the phone's MAC address "device_tracker.2e_ae_d5_82_a5_81" instead of the expected "device_tracker.myphone".

Ideally these details would be documented to avoid hours of effort by the next user.

As an enhancement request, it may be desirable to use a different naming convention (perhaps "device_tracker.myphone_2" or similar. It doesn't look like the entity id "device_tracker.6e_ae_d5_82_a5_81" is editable making it difficult to maintain for multiple phones and people.

Thanks again!
-Roy

### URL

https://www.home-assistant.io/integrations/synology_srm/

### Version

2021.12.10
