### ISSUE TITLE
telegram bot doesn't send messages containing "_" when using markdown

### ISSUE THREAD

**Issue by depuits** [home-assistant/home-assistant.github.io#21433]
### Feedback

This issue is a followup on https://github.com/home-assistant/core/issues/45290. When including a markdown special character in a telegram message the message just is not send. I found lots of other people having issues with this, especially when including entity id's or names containing an underscore. The suggestion in the linked issue is to change the `parse_mode` for the bot but I can't find any documentation about this option.

```
telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_token
    parse_mode: html
    allowed_chat_ids:
      - chat_id
```

I'm also not sure if the `parse_mode` also applies to the telegram notification or only the bot. In any case the markdown parsing and other parsing options should be documented and made clear to the user. 

The markdown is also not used on all notification platforms.

### URL

https://www.home-assistant.io/integrations/telegram/

### Version

2021.12.10
