### ISSUE TITLE
Insufficient info

### ISSUE THREAD

**Issue by macf0x** [home-assistant/home-assistant.github.io#21564]
### Feedback

Seems this page could be greatly improved. If your Individual device does not appear, there should be clear instructions on why.

In my case I had a dozen Tasmota powerplugs that refused to be listed, despite the state_class and device_class and native_unit_of_measurement being set correctly as per https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics, the powerplugs would not show.

Looking at other Zwave devices revealed it was necessary for the Entity to include '_kwh' in the ID to make it show.

### URL

https://www.home-assistant.io/docs/energy/individual-devices/

### Version

2022.2.5

**Comment by frenck** [comment]
> In my case I had a dozen Tasmota powerplugs that refused to be listed, despite the state_class and device_class and native_unit_of_measurement being set correctly as per [developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics), the powerplugs would not show.

That sounds like a bug, not something that needs to be documented.

> Looking at other Zwave devices revealed it was necessary for the Entity to include '_kwh' in the ID to make it show.

That is not related at all.

Based on the above posted, it sounds like you are experiencing an issue and not lack of documentation.

**Comment by macf0x** [comment]
Thanks Frenck,

Probably so. I couldn't see any documentation or reference to the entity name needing to include '_kwh', but I could reproduce this across the ZwaveJS and Tasmota integrations. Tasmota and ZWave being popular components, I assumed this must be known behaviour, just not documented.


 Simply renaming the entity dictated if it will show in the individual (energy) devices list. Assuming the device and state classes were set correctly, which both integration do.  The Zwave Integration adds the the _kwh suffix to the entities by default, where as Tasmota doesn't. Perhaps this is why it hasn't gained much visibility.

Happy to troubleshoot further or see if someone else can reproduce.

**Comment by CloCkWeRX** [comment]
This is a little tricky to work out what criteria is considered supported, even for say custom component developers or people using the Integration plugin.

Examples from forums:

- https://community.home-assistant.io/t/adding-kwh-integration-sensors-to-energy-panel-some-work-some-dont-im-stumped/387900
- https://community.home-assistant.io/t/converting-watt-unit-to-kwh-for-individual-devices-energy-dashboard/359730/2 (here they figured out the missing last_reset)

For example (note: I am **not** looking for support, just documenting the process I went through), reading through:
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

* Added what _should_ be the correct behaviours to a sensor component to make sure it collects statistics (https://github.com/rospogrigio/localtuya/pull/721)
* Added template sensors ontop of that to convert W to kW
* Added integration sensors to produce kWh, from both W values and calculated kW values.
* Checked the various sensors are producing at least some kind of data via history (many are 0, but there is data)

```
  - platform: template
    sensors:
      localtuya_pc287ha_current_consumption:
        value_template: '{{ states.switch.pc287ha.attributes.current_consumption }}'
        unit_of_measurement: 'W'
        device_class: energy
      localtuya_pc191ha_current_consumption:
        value_template: '{{ states.switch.pc191ha.attributes.current_consumption }}'
        unit_of_measurement: 'W'
        device_class: energy
      localtuya_pc191ha_current_consumption_kw:
        unit_of_measurement: "kW"
        value_template: "{{ states('localtuya_pc191ha_current_consumption') | float * 0.001 }}"
      localtuya_pc287ha_current_consumption_kw:
        unit_of_measurement: "kW"
        value_template: "{{ states('localtuya_pc287ha_current_consumption') | float * 0.001 }}"
  - platform: integration
    name: "Washing machine current consumption (template integration)"
    source: sensor.localtuya_pc191ha_current_consumption
    unit_prefix: k
    round: 2
  - platform: integration
    name: "Fridge current consumption (template integration)"
    source: sensor.localtuya_pc287ha_current_consumption
    unit_prefix: k
    round: 2
  - platform: integration
    name: "Washing machine current consumption (template integration, calculated)"
    source: sensor.localtuya_pc191ha_current_consumption_kw
  - platform: integration
    name: "Fridge current consumption (template integration, calculated)"
    source: sensor.localtuya_pc287ha_current_consumption_kw
```

It's only by spying on the websocket behaviour itself that I see my sensors are *probably* right; just missing some filtering criteria like name:
```
{"type":"history/list_statistic_ids","id":27}
```

```
{"id":27,"type":"result","success":true,"result":[{"statistic_id":"sensor.co2_intensity","name":null,"source":"recorder","unit_of_measurement":"gCO2eq/kWh"},{"statistic_id":"sensor.power_production_now","name":null,"source":"recorder","unit_of_measurement":"W"},{"statistic_id":"sensor.power_production_now_2","name":null,"source":"recorder","unit_of_measurement":"W"},{"statistic_id":"sensor.localtuya_fridge_voltage","name":null,"source":"recorder","unit_of_measurement":"V"},{"statistic_id":"sensor.fridge_voltage_non_sensor","name":null,"source":"recorder","unit_of_measurement":"V"},{"statistic_id":"sensor.sensor_localtuya_pc287ha_current_consumption_integral","name":null,"source":"recorder","unit_of_measurement":"Wh"},{"statistic_id":"sensor.fridge_ma_integration","name":null,"source":"recorder","unit_of_measurement":"mAh"},{"statistic_id":"sensor.fridge_current_consumption_template_integration","name":null,"source":"recorder","unit_of_measurement":"kWh"},{"statistic_id":"sensor.washing_machine_current_consumption_template_integration","name":null,"source":"recorder","unit_of_measurement":"kWh"},{"statistic_id":"sensor.bentley_energy_meter","name":null,"source":"recorder","unit_of_measurement":"kWh"},{"statistic_id":"sensor.bentley_power_meter","name":null,"source":"recorder","unit_of_measurement":"W"},
```

**From a documentation point of view**, having a better idea of the filtering criteria - even if it were a link to relevant bits in github - this would probably lead to more insights.

At the moment, you can start with the integration plugin and get some historical statistics showing up from the documentation, in combination with the statistics card; but you don't get good insights why those statistics aren't suitable for the energy dashboard.
