### ISSUE TITLE
Script editor docs don't explain how to list commands

### ISSUE THREAD

**Issue by ellisharmony** [home-assistant/home-assistant.github.io#21577]
### Feedback

Within the script editor, under sequence/command it says, "A single command or a list of commands to send".  How do you do a list. Are the commands just concatenated or is there a separator like a semicolon?

I have multiple 'b64' commands for a remote control and nothing seems to work, except my own yaml which gets wiped out everytime I edit the script in the editor. My only workaround is multiple actions and then I have to insert delays instead of using the "Delay Seconds" option within the action.

### URL

https://www.home-assistant.io/docs/scripts/editor/

### Version

2022.2.5

### Additional information

Here's the yaml of the kind of thing I'm doing and the docs don't help me do it efficiently.

```yaml
alias: Turn Off Movies
sequence:
  - service: remote.send_command
    data:
      command: >-
        b64:JgDQAgABJ5ETNxI3FhEUERQRFBEUEhM2EjgSExU1E...
    target:
      entity_id: remote.broadlink_remote
  - service: remote.send_command
    data:
      command: >-
        b64:JgCAAAABI5MSExI3EjcSNxI3EjcSNxITEjcTEhITEx...
    target:
      entity_id: remote.broadlink_remote
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: remote.send_command
    data:
      command: >-
        b64:JgDQAgABJ5ETNxI3FhEUERQRFBEUEhM2EjgSExU1EhMVNRIUFDYRFBQRFBITEhMSEzYSFBMSEzYSOBI4EjkROREUEzcUNhIUEgAFPwABKJMROBI4EhQTEhMSEhQRFBE4EjgSExI3FRIRORMSEjgTEhIUERQRFBEUETgUEhEUETgUNxM3EzcTNxM...
    target:
      entity_id: remote.broadlink_remote
  - service: androidtv.adb_command
    data:
      command: POWER
    target:
      entity_id: media_player.android_tv_10_50_30_82
mode: single
```

**Comment by mdegat01** [comment]
I'm guessing by your entity ID that you have a broadlink remote. They have lots of examples of how to use the services provided by that integration, including [this one](https://www.home-assistant.io/integrations/broadlink/#sending-a-sequence-of-commands) showing how to send multiple commands with `remote.send_command`.

Also for future reference, any time you are sharing config please wrap it triple backticks. It looks like your YAML is formatted incorrectly but I'm not really sure because its being treated like markdown. If you aren't sure what I mean take a look [here](https://community.home-assistant.io/t/how-to-help-us-help-you-or-how-to-ask-a-good-question/114371#oneone-format-it-properly-16). It's for the forum but same thing applies here.

**Comment by frenck** [comment]
>  "A single command or a list of commands to send". How do you do a list. Are the commands just concatenated or is there a separator like a semicolon?

By making it a list... as written exactly in that instruction...

```yaml
  - service: remote.send_command
    data:
      command: 
        - >-
          b64:JgDQAgABJ5ETNxI3FhEUERQRFBEUEhM2EjgSExU1E...
        - >-
          b64:JgCAAAABI5MSExI3EjcSNxI3EjcSNxITEjcTEhITEx...
    target:
      entity_id: remote.broadlink_remote
```
