### ISSUE TITLE
SwitchBot integration documentation needs reference to manual configuration.yaml code block

### ISSUE THREAD

**Issue by cannondale0815** [home-assistant/home-assistant.github.io#21580]
### Feedback

When following the HA SwitchBot documentation to add the integration via the UI, the error "Aborted - Failed to connect” is shown.

The only way to successfully add the SwitchBot integration to HA (at least for some people, including myself) is to add something like the following to the configuration.yaml:

```
switch:
- platform: switchbot
  mac: 'xx:xx:xx:xx:xx:xx'
  name: "My Switchbot Button Press"
  password: !secret my_switchbot_password
```

Please update the documentation accordingly.

This issue (and the workaround) are also described in this thread: https://community.home-assistant.io/t/switchbot-integration-aborted-failed-to-connect/355734

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2022.2.5
