### ISSUE TITLE
Incorrect / Missing information on Ring Intergration Documentation

### ISSUE THREAD

**Issue by reefland** [home-assistant/home-assistant.github.io#21599]
### Feedback

The documentation states:

Then you can use the following automation, with the entities from your system, which will save the video file under `<config>/downloads/ring_<camera_name>/`:

Based on example code, it will NOT create a file starting with name `ring_`, the filename only is based on the camera name such as:

`-rw-r--r-- 1 root root 2574316 Feb 2 20:12 'Front Door'`

In addition, the resulting filename, created as documented, is not viewable in HA Media Browser since it lacks a file extension. I thought I could add a `.mp4` to the sample code as follows:
```
service: downloader.download_file
data:
  url: '{{ state_attr(''camera.front_door'', ''video_url'') }}'
  subdir: '{{state_attr(''camera.front_door'', ''friendly_name'')}}'
  filename: '{{state_attr(''camera.front_door'', ''friendly_name'')}}.mp4'
```
This results with the file now having a double-dot, and also not playable in HA Media Browser such as:
```
-rw-r--r-- 1 root root 2106661 Jan 22 17:40 'Front Door_2..mp4'
-rw-r--r-- 1 root root 2885086 Jan 27 18:26 'Front Door_3..mp4'
-rw-r--r-- 1 root root 2023197 Jan 29 14:51 'Front Door_4..mp4'
-rw-r--r-- 1 root root 4381205 Jan 29 15:36 'Front Door_5..mp4'
-rw-r--r-- 1 root root 4781411 Jan 29 17:10 'Front Door_6..mp4'
-rw-r--r-- 1 root root 3506638 Feb  3 09:55 'Front Door_7..mp4'
-rw-r--r-- 1 root root 3033811 Feb  4 20:09 'Front Door_8..mp4'
```
I had to manually rename them to a single dot to make them playable in HA Media Browser.

### URL

https://www.home-assistant.io/integrations/ring/#saving-the-videos-captured-by-your-ring-door-bell

### Additional information

As files are being created, it does not seem to be a bug with the integration.  I assume its just an issues with code samples provided in the documentation.
