### ISSUE TITLE
Adding image to media does not work

### ISSUE THREAD

**Issue by rpartapsing** [home-assistant/home-assistant.github.io#21630]
### Feedback

Hi,

I am following the guidelines on displaying media to the media player.

When I try
```
service: media_player.play_media
data:
  media_content_type: image/png
  media_content_id: media-source://media_source/local/snapshot.png
target:
  entity_id: media_player.tv_samsung_q950_series_75
```

It does not work.
while if I would do `media_content_id: http://example.com/test.png` it does work

The url https://xxx.duckdns.org:8123/local/test.png also does give me the image.
setting `media_content_id: https://xxx.duckdns.org:8123/local/test.png` also does not work

### URL

https://www.home-assistant.io/integrations/media_source/#local-media

### Version

2022.2.5
