### ISSUE TITLE
How to configure meter in Consumption path (1)?

### ISSUE THREAD

**Issue by GianlucaCollot** [home-assistant/home-assistant.github.io#21804]
### Feedback

Hi, 
I am using the Fronius integration that seems well written and works well for production and consumption.
Unfortunately, if the meter is in the consumption path, it does not provide the value of Energy "returned to grid".
So there is noway to configure this value in the energy dashboard.
Could you add to the documentation this case and explain possible workarounds?

Thank you in advance

Gianluca

### URL

https://www.home-assistant.io/integrations/fronius/

### Version

2022.2.9

**Comment by farmio** [comment]
Hi 👋!

I don't know which entities are even available with a consumption path meter. If you have power_flow entities you could do something like this
```yaml
# positive values are from grid
from_grid: {{ max(states('sensor.power_grid_fronius_power_flow_0_http_192_168_68_10') | float, 0) }}
# negative values are to grid
to_grid: {{ max((0 - states('sensor.power_grid_fronius_power_flow_0_http_192_168_68_10') | float), 0) }}
```
and use these as source for a Riemann sum integration. 

There is a fantastic forum thread explaining such calculations regarding batteries - I'm sure you can get some inspiration from it: https://community.home-assistant.io/t/howto-fronius-integration-with-battery-into-energy-dashboard/376329

When you've got it working it would be awesome if you'd add a high-level explanation to the documentation (I think more detailed information fits the forums better since template stuff can change/update in the future).

**Comment by GianlucaCollot** [comment]
Thank you,I prefer to use the values already calculated by the meter
I have available 2 energy values: 

- Consumed Energy (from meter in consumption path):  `sensor.energy_real_consumed_fronius_meter_0_http_192_168_1_xxx`
- Produced Energy (from the inverter): `sensor.energy_total_fronius_inverter_1_http_192_168_1_xxx`

So I built a Template entity with the difference:
```
 - name: "energy_to_grid"
            # friendly_name: 'Energia immessa in rete (neg se consumata)'
            unit_of_measurement: Wh
            state: >-
               {{ (states("sensor.energy_total_fronius_inverter_1_http_192_168_1_103") | float) - (states("sensor.energy_real_consumed_fronius_meter_0_http_192_168_1_103") | float) | int }}
            device_class: energy
            state_class: total
```
I am waiting to see the statistics update and confirm this solution works.
I will eventually update the documetnation for meter in the consumption path.

**Comment by farmio** [comment]
This will decrease its value when you import energy from grid. I think the energy panel expects a `total_increasing` value for grid export and import. 

You'd also need a second one to get an ever-increasing `from-grid` state. 

Also for some extra resilience you could add an `available` template based on both used states being numeric (not "unknown"/"unavailable").

**Comment by GianlucaCollot** [comment]
Thank you very much. I confirm that the panel expects only increasing positive values.
With the meter in the consumption path I need to derive everything from power values.
I followed your first suggestion using the max operator on the power values and then integrating with the riemann sum.
It works perfectly.

**Comment by luixal** [comment]
Hi @GianlucaCollot , could you share your configuration?

I'm struggling with this and I'm not getting it to work.

Thanks!

**Comment by GianlucaCollot** [comment]
Hi, @luixal,
the chofigursation is quite easi and it comes in 2 parts.
Firs you configure the templates for the "power" entities in your configure.yaml file:
```
template:
    - sensor:
    # positive values are from grid
          - name: "power_bought"
            # friendly_name: 'Solar power production'
            unit_of_measurement: W
            state: >-
              {{ max(states('sensor.power_grid_fronius_power_flow_0_http_192_168_x_xxx') | float, 0) }}
            device_class: power
            
      # negative values are to grid
          - name: "power_sold"
            # friendly_name: 'Solar power production'
            unit_of_measurement: W
            state: >-
              {{ max((0 - states('sensor.power_grid_fronius_power_flow_0_http_192_168_x_xxx') | float), 0) }}
            device_class: power
```
then you insert the 2 "energy" entities to be used in the Energy dashboard:
```
sensor:
  - platform: integration
    source: sensor.power_sold
    name: energy_sold
    round: 2
    # device_class: energy
  - platform: integration
    source: sensor.power_bought
    name: energy_bought
    round: 2
```

The trick, as suggested by @farmio, is to use the `max()` operator inside the template for power entities to avoid negative values.
In the dashboard use the 2 new energy entities `energy_bought`, `energy_sold` + the solar production of your inverter:
![immagine](https://user-images.githubusercontent.com/907658/162144660-7d03190b-c541-41e4-9a3d-37f3ce18e50c.png)

Best regards

Gianluca
