### ISSUE TITLE
Need example for tracking amount of time a person spent in a zone

### ISSUE THREAD

**Issue by BobBob9999** [home-assistant/home-assistant.github.io#21860]
### Feedback

The documentation states that an example of what can be tracked is "How long you were at home this week", but fails to provide any example configuration for such a thing.

### URL

https://www.home-assistant.io/integrations/history_stats/

### Version

2022.2.9

**Comment by dannytsang** [comment]
Hi @BobBob9999 

I suspect the examples are ideas you could use the integration for because it also doesn't show an example of **How long you watched TV today**.

Make sure you have set up your profile in **Configuration > People & Zones > [your profile]** and associated devices.
![image](https://user-images.githubusercontent.com/567982/157762377-a5c5fcd2-01ff-491c-bfb0-2ca0b49aec6f.png)

Get the entity ID for your profile. You can do this using the **Developer tools > States**, expand the **Set state** section and in the entity box start typing **person.** (note the dot after *person*). A list of profiles should appear and you want to make a note **person.xxxx** under the name.
![image](https://user-images.githubusercontent.com/567982/157763121-c625a79a-b7db-4138-afdd-19b458ff89d2.png)


The go to your configuration.yaml file and add the below, remember to replace **entity_id: person.danny** with your ID.
```

sensor:
  - platform: history_stats
    name: Danny At Home This Week
    entity_id: person.danny
    state: "home"
    type: time
    start: "{{ as_timestamp( now().replace(hour=0, minute=0, second=0) ) - now().weekday() * 86400 }}"
    end: "{{ now() }}"
```
