### ISSUE TITLE
HomeKit documentation not accurate

### ISSUE THREAD

**Issue by jmcollin78** [home-assistant/home-assistant.github.io#21951]
### Feedback

The HomeKit documentation is not accurate. The example given don't works:
1. homekit.filter homekit.name and homekit.port are not a list (no - expected),
2. homekit.entity_config.<entityId>.type is not accepted

`"Invalid config for [homekit]: [type] is an invalid option for [homekit]. Check: homekit->homekit->0->entity_config->type. (See /config/configuration.yaml, line 31)."`

So the first complete example seems wrong.

Complete tested configuration is:
```
homekit:
  name: haserver-homekit
  mode: bridge
  filter:
    include_domains:
      - light
      - camera
      - cover
      - person
      - fan
      - humidifier
      - media_player
      - switch
      - water_heater
      - scene
    include_entities:
      - binary_sensor.chauffe_eau_overheating
      - binary_sensor.chauffe_eau_overpowering
      - binary_sensor.detecteur_fumee_sam
  entity_config:
    binary_sensor.chauffe_eau_overheating:
      type: opening
    binary_sensor.chauffe_eau_overpowering:
      type: opening
    binary_sensor.detecteur_fumee_sam:
      type: smoke
```

### URL

https://www.home-assistant.io/integrations/homekit/

### Version

2022.3.3
