### ISSUE TITLE
Yaml template code is missing data label

### ISSUE THREAD

**Issue by dustrat** [home-assistant/home-assistant.github.io#22048]
### Feedback

The switch template is missing the "data:" label for the turn_on option. It should be:
```yaml
switch:
  - platform: template
    switches:
      ac:
        friendly_name: "AC"
        value_template: "{{ is_state('climate.ac', 'cool') or is_state('climate.ac', 'heat') or is_state('climate.ac', 'dry') or is_state('climate.ac', 'fan_only') }}"
        turn_on:
          service: climate.set_hvac_mode
          target:
            entity_id: climate.ac
          data:
            hvac_mode: cool
        turn_off:
          service: climate.set_hvac_mode
          target:
            entity_id: climate.ac
          data:
            hvac_mode: off
```

### URL

https://www.home-assistant.io/integrations/sensibo/

### Version

2022.3.5
