### ISSUE TITLE
Statistics doc: Missing important details

### ISSUE THREAD

**Issue by jgclark** [home-assistant/home-assistant.github.io#22161]
### Feedback

I'd like to see some extra info added, after I had to get info off a kind soul on Discord.

My goal was to make a graph of outside temperature drawn from the built-in weather component.  I'd found out how to make its State into a Sensor:
```
template:
  - sensor:
      - name: Outdoor temperature
        state: "{{ state_attr('weather.home','temperature') }}"
        unit_of_measurement: "°F"
```
But by itself that didn't became a Statistic capable of graphing over time.
Discord pointed me to https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics and the need to have a `state_class: measurement` line, at least to make it a long-term statistic.

The page also doesn't, AFAICT, explain the difference between short- and long-term statistics.

### URL

https://www.home-assistant.io/integrations/statistics/

### Version

2022.3.7
