### ISSUE TITLE
[variables] is an invalid option for [automation]

### ISSUE THREAD

**Issue by jLynx** [home-assistant/home-assistant.github.io#22274]
### Feedback

It wont let me add a variable to the triggers as I keep getting the error: ``[variables] is an invalid option for [automation]``

```
- id: "1649302980480"
  alias: Energy tariff switcher
  description: ""
  trigger:
    - platform: time
      at: "23:00:00"
      variables:
        tariff: peak
    - platform: time
      at: 00:00:00
      variables:
        tariff: offpeak
  condition: []
  action:
    - service: select.select_option
      target:
        entity_id: utility_meter.daily_energy
      data:
        option: "{{ tariff }}"
  mode: single
```

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2022.4.0
