### ISSUE TITLE
History Graph Card entities syntax

### ISSUE THREAD

**Issue by shadehugger** [home-assistant/home-assistant.github.io#22356]
### Feedback

What is the correct syntax for adding "name" to an entity?
I have tried the following but they both produce errors:
```
entities:
  - entity: sensor.lounge_temperature
    name: "Lounge"
```
and
```
entities:
  - entity: sensor.lounge_temperature
  - name: "Lounge"
```

### URL

https://www.home-assistant.io/dashboards/history-graph/

### Version

2022.4.2

**Comment by klaasnicolaas** [comment]
```yaml
entities:
  - entity: sensor.lounge_temperature
    name: Lounge
```
As it is also described in the examples, what error message do you get?
