### ISSUE TITLE
Microsoft TTS Hebrew support broken?

### ISSUE THREAD

**Issue by aniceberg** [home-assistant/home-assistant.github.io#22539]
### Feedback

Microsoft TTS services won't render Hebrew text to speech ( and I can confirm that **en-US** renders just fine). My config is as follows:

```
# Text to speech
tts:
  - platform: microsoft
    api_key: XXXXXXXXXXXXXXXXXXXXXXXXXX
    language: he-il
    gender: Male
    type: he-IL-AvriNeural
```

Example:
![image](https://user-images.githubusercontent.com/646958/165519227-754fb175-2126-489c-9b68-b1b2d65de528.png)

### URL

https://www.home-assistant.io/integrations/microsoft/

### Version

2022.4.7
