### ISSUE TITLE
Xiaomi Mi Robot Vacuum documentation correction

### ISSUE THREAD

**Issue by kryptonitecb3** [home-assistant/home-assistant.github.io#22540]
### Feedback

[#59110](https://github.com/home-assistant/core/issues/59110)

The Xiaomi Mi Robot Vacuum documentation (https://www.home-assistant.io/integrations/xiaomi_miio#xiaomi-mi-robot-vacuum) states that:
"The original app for Xiaomi vacuum has a nice feature of room cleaning with repetition, you can achieve the same result with repeating segments:"

When service: xiaomi_miio.vacuum_clean_segment is used Roborock vacuums will make one pass:
```service: xiaomi_miio.vacuum_clean_segment
data:
  segments: [17,17]
target:
  entity_id: vacuum.rosie
```

However when service: vacuum.send_command is called with the repeat parameter, the vacuum will make multiple passes.
```
service: vacuum.send_command
target:
  entity_id: vacuum.rosie
data:
  command: app_segment_clean
  params:
    - segments:
        - 17
      repeat: 2
```

### URL

https://www.home-assistant.io/integrations/xiaomi_miio/

### Version

2022.4.7
