### ISSUE TITLE
Clarify Badges documentation

### ISSUE THREAD

**Issue by pedolsky** [home-assistant/home-assistant.github.io#22667]
### Feedback

In the HA forum, posts keep popping up that users are trying unsuccessfully to set up badges. This is because the documentation starts with 

_Badges are widgets that sit at the top of a panel, above all the cards._ 

followed later by a section called Entity Filter _Badge_

so that users (rightly!) assume that they are dealing with the top badges.

In my opinion this could be easily clarified by adding 

some code examples together with 2 sentences:

Section Badges:

_To add entity-filter badges to your views, open the raw config editor (klick on the 3 vertical dots at the top right corner, klick on the pencil, klick again on the 3 vertical dots, choose 'raw config editor') and search for the view you want them to be displayed. Then add the badges below the line `badges` (remove the `[]`). Examples:_

```

# raw config example
views:
- title: Home
  badges:
    - type: entity-filter
      entities:
        - entity: light.bed_light
          name: Bed
        - light.kitchen_lights
        - light.ceiling_lights
      state_filter:
        - "on"

# raw config example
views:
- title: Home
  badges:
    - type: entity-filter
      state_filter:
        - "on"
        - operator: ">"
          value: 90
      entities:
        - sensor.water_leak
        - sensor.outside_temp
        - entity: sensor.humidity_and_temp
          state_filter:
            - operator: ">"
              value: 50
              attribute: humidity

```

Section Entity Filter Badge:

Replace the title with 'Entity Filter in Dashboards'

Just my 2 cents.

### URL

https://www.home-assistant.io/dashboards/badges/

### Version

2022.5.2
