### ISSUE TITLE
For Each Script Example Typo

### ISSUE THREAD

**Issue by kschlichter** [home-assistant/home-assistant.github.io#22710]
### Feedback

The script example for [For Each](https://www.home-assistant.io/docs/scripts/#for-each) has a typo where "hello: Hallo Wereld" should be "message: Hallo Wereld" to achieve the intended results:

```
    - language: English
      message: Hello World
    - language: Dutch
      hello: Hallo Wereld
```

```
repeat:
  for_each:
    - language: English
      message: Hello World
    - language: Dutch
      message: Hallo Wereld
  sequence:
    - service: notify.mobile_app_kevin_phone
      data:
        title: Message in {{ repeat.item.language }}
        message: '{{ repeat.item.message }}!'
```

### URL

https://www.home-assistant.io/docs/scripts/

### Version

2022.5.3
