### ISSUE TITLE
A Great Example To Add To Docs

### ISSUE THREAD

**Issue by alex-bristol** [home-assistant/home-assistant.github.io#22715]
### Feedback

Any chance we could have a great and very realistic example following this example listed:

```yaml
condition:
  condition: numeric_state
  entity_id: climate.living_room_thermostat
  attribute: temperature
  above: input_number.temperature_threshold_low
  below: input_number.temperature_threshold_high
```

From the Numeric State Condition section.

The current temperature compared with the setpoint temperature (the temperature the user has set on the device).  Examples where this would be used: freezer, fridge, radiator thermostat, air conditioner, boiler, electric fire; they all would have both temperatures.  I am trying to workout when an HA condition section with a radiator thermostat needs to turn on/off the boiler, the "above" and "below" value could change any time by the user on the device, and all the examples given are hardcode numbers or an HA input_number, nothing from the device.  Thanks.

### URL

https://www.home-assistant.io/docs/scripts/conditions/

### Version

2022.5.3
