### ISSUE TITLE
Melcloud out of sync with remote 

### ISSUE THREAD

**Issue by Tazzios** [home-assistant/home-assistant.github.io#22742]
### Feedback

At the Melcloud integration there is missing documentation how to refresh from melcloud. Because If you also use the remote or melcoud app some times the device status gets out of sync.

I now have setup an automation which seem to work. It would be nice to mention it in the docs. create an option in the integration to setup a sync would be even beter. (assuming that my solution really works :) )
```
alias: update airco status
description: ''
trigger:
  - platform: time_pattern
    minutes: /5
condition: []
action:
  - service: homeassistant.update_entity
    data: {}
    target:
      device_id:
        - 793cf8233e7e2f6486ffbb4351b02429
        - 08414cdd4874dde04f0f4f72c7af3971
      entity_id: climate.airco_slaapkamer
mode: single
```

### URL

https://www.home-assistant.io/integrations/melcloud

### Version

2021.5.4
