### ISSUE TITLE
value_template not work

### ISSUE THREAD

**Issue by nm20220210** [home-assistant/home-assistant.github.io#22757]
### Feedback

Example not allowed in 2022.5.4
![1](https://user-images.githubusercontent.com/99388521/168467429-98930e70-0020-4654-aba3-4a1f8b5fbfd4.JPG)
![2](https://user-images.githubusercontent.com/99388521/168467433-44f2907d-74ce-47b5-982b-db0202f3dbf8.JPG)
![3](https://user-images.githubusercontent.com/99388521/168467848-d78e5423-00e4-4bb9-aad7-8666c643b582.JPG)

### URL

https://www.home-assistant.io/docs/automation/condition/

### Version

2022.5.4

### Additional information

Test Conditions are not only strings. Value_template not worked with numeric

**Comment by dannytsang** [comment]
I have tried to re-create this and also got the same error message as your second screenshot when i press the **Test** button on the condition.
![image](https://user-images.githubusercontent.com/567982/168472914-8d0d44eb-6183-40ad-902a-625b1603f5c3.png)

The automation I created saved without any validation issue so not sure why it's giving the error message.

This is what it generated in my YAML file:
```
- id: '1652617644447'
  alias: New Automation
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.office_motion
    to: 'on'
  condition:
  - condition: template
    value_template: '{{ state_attr(''sun.sun'', ''elevation'') < 4 }}'
  action:
  - service: scene.turn_on
    data: {}
    target:
      entity_id: scene.office_main_light_on
  mode: single
```
