### ISSUE TITLE
HydroQuebec Sensor: Some sensor does not report any values

### ISSUE THREAD

**Issue by godloth** [home-assistant/home-assistant.github.io#2279]
hey there,
Thanks for this sensor for us in Quebec :) 

a few things though does not seems to be working properly. I have a few sensors that does not report anything and that since the beginning.

One prticularity though, i'm on a monthly plan with them ( equal payment each month) which i don't know if it can cause something to your scrapper.

see print screen.

![image](https://cloud.githubusercontent.com/assets/22320005/24039660/6017755c-0adc-11e7-8d43-7245998580e5.png)

![image](https://cloud.githubusercontent.com/assets/22320005/24039683/72977060-0adc-11e7-8978-9eddc1fed263.png)

Config and logs are ok

```
  - platform: hydroquebec
    username: xxxxxxxxx
    password: !secret hydroquebec_pass
    contract: 'xxxxxxxxx'
    monitored_variables:
      - period_total_bill
      - period_length
      - period_total_days
      - period_mean_daily_bill
      - period_mean_daily_consumption
      - period_total_consumption
      - period_lower_price_consumption
      - period_higher_price_consumption
      - yesterday_total_consumption
      - yesterday_lower_price_consumption
      - yesterday_higher_price_consumption
```
Running HA 4.01 with AIOinstaller + PI3

let me know if i can be of any help resolving this as this is a great sensor for Quebec :)
