### ISSUE TITLE
Docs on template alarm panel implement alarms requiring no code

### ISSUE THREAD

**Issue by BVollmerhaus** [home-assistant/home-assistant.github.io#23124]
### Feedback

I am currently trying to set up a template alarm panel (that checks whether all sensors are closed before allowing alarms to be armed) and found two mistakes in the documentation (and implementation?) for said panel, one minor and one fairly major.

First, the YAML example contains a typo in that the disarm action is a service call to `alarm_control_panel.alarm_arm_home`, rather than `alarm_control_panel.alarm_disarm`. This results in the alarm not being disarmable, but that should be a fairly obvious issue for people initially configuring their alarm.

Second, and more importantly, all `alarm_control_panel` service calls in the example get passed `code: !secret alarm_code` as `data`. Requiring a code is especially critical for disarming; however, this does not actually appear to work as stated. Following the example, the alarm can be disarmed without _any_ code. Interestingly, specifying a code explicitly results in it always being rejected.

**No code required to disarm, even though `alarm_code` is defined and works with the normal panel:**
```yaml
alarm_control_panel:
  - platform: template
    panels:
      safe_alarm_panel:
        [...]

        disarm:
          - service: alarm_control_panel.alarm_disarm
            target:
              entity_id: alarm_control_panel.main_alarm
            data:
              code: !secret alarm_code
```

**An explicit code ("123" in this case) is being rejected outright (`Invalid code given for disarmed`):**
```yaml
disarm:
  - service: alarm_control_panel.alarm_disarm
    target:
      entity_id: alarm_control_panel.main_alarm
    data:
      code: "123"
```

Maybe someone more familiar with the template alarm panel can chime in; perhaps I'm the one using it incorrectly.

### Edit: Workaround for the Code Being Ignored

To anyone facing the same issue, the following can be used as a workaround:

In your `secrets.yaml` file:
```yaml
evaluate_code: "{{ code == '1234' }}"
```

In your `disarm` action:
```yaml
disarm:
  - condition: template
    value_template: !secret evaluate_code
  - service: alarm_control_panel.alarm_disarm
    [...]
```

The fact that this works implies that it's not an issue of not being able to use `!secret` variables, but rather the `code` in `data` being ignored for some reason.

### URL

https://www.home-assistant.io/integrations/alarm_control_panel.template/

### Version

First encountered in 2022.6.6, still present in 2022.10.5.

### Additional information

Someone appears to have already encountered the second issue quite some time ago and [posted about it](https://community.home-assistant.io/t/template-alarm-control-panel-code-not-needed/351311) on the HA forum.
