### ISSUE TITLE
Change icon for rachio iframe

### ISSUE THREAD

**Issue by kghandi** [home-assistant/home-assistant.github.io#23122]
### Feedback

I suggest changing the icon in the iframe sample code from mdi:water-pump to mdi:sprinkler-variant.

```
panel_iframe:
  rachio:
    title: Rachio
    url: "https://app.rach.io/"
    icon: mdi:sprinkler-variant
```

### URL

https://www.home-assistant.io/integrations/rachio/

### Version

2022.6.6
