### ISSUE TITLE
Code example for periodic backup

### ISSUE THREAD

**Issue by Torpedro1978** [home-assistant/home-assistant.github.io#23340]
### Feedback

Wouldn't it be better to add code example that can be just pasted in a new automation in:
config/automation/edit/

Your example needsd to be reformated to work.

config/automation/edit/

like this:
```
alias: "Backup Home Assistant every night at 3 AM"
description: ''
mode: single
trigger:
  - platform: time
    at: "03:00:00"
action:
  - alias: "Create backup now"
    service: backup.create
```

### URL

https://www.home-assistant.io/integrations/backup/

### Version

2022.7.2
