### ISSUE TITLE
disable jemalloc syntax on docker compose still incorrect

### ISSUE THREAD

**Issue by abochmann** [home-assistant/home-assistant.github.io#23383]
### Feedback

As previously reported in [#21381](https://github.com/home-assistant/home-assistant.io/issues/21381), the syntax used in the docker compose example is wrong, at least for current versions of docker compose. Using the example code results in:

```
$ docker compose up
services.homeassistant.environment.0 must be a string
```

Apparently the correct syntax now is:

```
version: '3'
services:
  homeassistant:
    container_name: homeassistant
[..]
    environment:
      - DISABLE_JEMALLOC=true
```

### URL

https://www.home-assistant.io/installation/linux#exposing-devices

### Version

2022.7.3
