### ISSUE TITLE
Automation example doesn't seem to be working

### ISSUE THREAD

**Issue by Guesch** [home-assistant/home-assistant.github.io#23627]
### Feedback

When copy/pasting verbatim the code, HA provides the following error message:
Message malformed: extra keys not allowed @ data['automation']

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2022.7.7

**Comment by dgomes** [comment]
What code did you copy&paste ?

**Comment by Guesch** [comment]
Sorry I thought I added a better description in my feedback.

Tried to use the automation code. Sorry if I'm being dense here, learning as I go.

```
automation:
  trigger:
    - platform: time
      at: "09:00:00"
      variables:
        tariff: "peak"
    - platform: time
      at: "21:00:00"
      variables:
        tariff: "offpeak"
  action:
    - service: select.select_option
      target:
        entity_id: select.daily_energy
      data:
        option: "{{ tariff }}"
    - service: select.select_option
      target:
        entity_id: select.monthly_energy
      data:
        option: "{{ tariff }}"
```
