### ISSUE TITLE
Using input_number as a CONDITION in an automation

### ISSUE THREAD

**Issue by blackequine** [home-assistant/home-assistant.github.io#23684]
### Feedback

There is no example of using an input_number as a condition in an automation, yet the opening sentence the page says they can be used withing conditions. How? I've been unable to make it work.  I've tried:

condition: numeric_state
entity_id: input_number.poolheatpump
above: "100.0"

and when I test nothing happens.

### URL

https://www.home-assistant.io/integrations/input_number/

### Version

2022.8.1

**Comment by frenck** [comment]
>  How? 

Just like any other entity providing a numeric value (e.g., sensors).

See out conditions documentation for more information on the use of conditions.

https://www.home-assistant.io/docs/scripts/conditions/#numeric-state-condition

```yaml
condition: numeric_state
entity_id: input_number.poolheatpump
above: "100.0"
```

> and when I test nothing happens.

Please note that `above` expects a number, not a string.


```yaml
condition: numeric_state
entity_id: input_number.poolheatpump
above: 100.0
```

Otherwise, your example is correct.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
