### ISSUE TITLE
New MQTT config.yaml

### ISSUE THREAD

**Issue by herculesstrydom** [home-assistant/home-assistant.github.io#24040]
### Feedback

Please add what the configuration for multiple binary sensors would look like?

so using your example:

mqtt:
  binary_sensor:
    - name: Bathroom
      state_topic: "home/bathroom/switch/button"
      payload_on: "1"
      payload_off: "0"

Would the second device be a new start with "mqtt:" OR would a new device start at "binary_sensor:"

Thank you

### URL

https://www.home-assistant.io/integrations/binary_sensor.mqtt/

### Version

2022.9.0

**Comment by LindsayReid** [comment]
I too can get only one binary sensor working with the revised mqtt form in 2022.9.0 but cannot work out how I would now define my multiple binary sensors. I thought I had tried most possibilities but to no avail!

**Comment by frenck** [comment]
From the docs:

```yaml
# Example configuration.yaml entry
mqtt:
  binary_sensor:
    - state_topic: "home-assistant/window/contact"
```

As you can see above, the `binary_sensor` key has a list as its value. List can be extended with more items.

For example:

```yaml
# Example configuration.yaml entry
mqtt:
  binary_sensor:
    - state_topic: "home-assistant/window/contact"
    - state_topic: "home-assistant/door/contact"
```

This is not specific to this integration or anything. You might want to read up into to some YAML guides.

../Frenck
