### ISSUE TITLE
Turn_off service not working 

### ISSUE THREAD

**Issue by cowboysdude** [home-assistant/home-assistant.github.io#24103]
### Feedback

The input_boolean.turn_on works perfectly but upon trying to run the input_boolean.turn_off service it does not toggle the boolean off as it should.

I have to use homeassistant.toggle to turn the input_boolean off

```yaml
action:
    - service: homeassistant.toggle
      entity_id: input_boolean.out_of_bed
    - service: media_player.volume_set
      data:
        volume_level: 0.60
      target:
        entity_id: media_player.sonos_five
    - service: tts.cloud_say
      entity_id: media_player.sonos_five
      data_template:
        message: > 
```

Here is where I'm asking the boolean to turn off.... the only way it works is with homeassistant.toggle service.
It seems that the input_boolean_turn_off service is not working.

### URL

https://www.home-assistant.io/integrations/input_boolean/

### Version

2022.9.2
