### ISSUE TITLE
No instruction on how to implement

### ISSUE THREAD

**Issue by Alekisan** [home-assistant/home-assistant.github.io#24116]
### Feedback

You have information about what the helper does but no examples on how to use it.

### URL

https://www.home-assistant.io/integrations/schedule/

### Version

2022.9.2

**Comment by clydefrog76** [comment]
Yeah, I am struggling with this too. Do I use automations, scenes, scripts? Where can I select the schedule I just created for the device I want to control? It's a bit of a mystery at the moment. Thanks!

**Comment by guitarmanusa** [comment]
Agreed.  I have switch that I would like to turn on at the begin of the scheduled time, and turn off at the end.  It is not obvious how to use the entity next_event in an Automation, and even when using the UI to make a new automation, there are no options for Schedules in the Trigger section, where as a user I would expect this to be.

**Comment by guitarmanusa** [comment]
Found the following in the user forums, apparently you're supposed to use a 'state' trigger, even though the doc has no mention of a state with values of 'on' and 'off' listed.

[Question: How to Use the Scheduler / Helper Function in the 2022.9 Release](https://community.home-assistant.io/t/question-how-to-use-the-scheduler-helper-function-in-the-2022-9-release/459188)

I should note, I haven't gotten the following to work yet:

```
- id: control-hot-water-heater-with-schedule
  trigger:
    - platform: state
      entity_id: schedule.hot_water_schedule
  condition: "{{ trigger.to_state.state in ['on', 'off'] }}"
  action:
    - service: 'switch.turn_{{ trigger.to_state.state }}'
      target:
        entity_id: switch.hot_water_heater_switch
```
