### ISSUE TITLE
How to Use Color Mode

### ISSUE THREAD

**Issue by NickDorak** [home-assistant/home-assistant.github.io#24123]
### Feedback

Please let us know how to use Color Mode.
I can change colors by going into services, but wife and kids aren't going to figure that out. When they open the light in the dashboard, there is only an option to turn on/off and nothing about color. 

### URL

https://www.home-assistant.io/integrations/screenlogic/

### Version

2022.8.7

**Comment by frenck** [comment]
Sounds like you are experiencing a bug. When clicking an light entity in Home Assistant, you should be able to change colors of the light directly from the UI (if the light is turned on).

If not, that would be a bug. There is no need to use services for this.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by dieselrabbit** [comment]
The Pentair controllers (and thus the ScreenLogic interface device) do not report or track the current color mode of any color-capable lights controlled by the system, yet provide a way to _set_ the mode. This is why we cannot cleanly support colors or effects in the light entities and instead have to rely on a service call. (this was pre-Button entities, IIRC).

@NickDorak In this case, you would use a Button _Card_ and set the `tap_action` to `call-service` of `screenlogic.set_color_mode` for each color mode button you wanted (with the appropriate `service_data`).

If you (or anyone) can point me to an example of where an integration's documentation provides an example Lovelace config (so I can follow formatting), I can add a simple explanation along with my config as an example.

**Comment by frenck** [comment]
It would need to assume state of the color mode in such cases. The above confirm me this is a bug. A user should be able to control a light as expected directly from the UI.

**Comment by bdraco** [comment]
I wrote a PR at one point to add color support for the light entity but didn't end up moving it forward:

- The device only support 5 actual colors.  (its not RGB, it 5 fixed values)
- Color is not reported by the device so everything is lost on restart
- Changing the color changes the color for ALL devices connected to the controller not just a single light

The UX was just not so great considering all that.

**Comment by NickDorak** [comment]
> The Pentair controllers (and thus the ScreenLogic interface device) do not report or track the current color mode of any color-capable lights controlled by the system, yet provide a way to _set_ the mode. This is why we cannot cleanly support colors or effects in the light entities and instead have to rely on a service call. (this was pre-Button entities, IIRC).
> 
> @NickDorak In this case, you would use a Button _Card_ and set the `tap_action` to `call-service` of `screenlogic.set_color_mode` for each color mode button you wanted (with the appropriate `service_data`).
> 
> If you (or anyone) can point me to an example of where an integration's documentation provides an example Lovelace config (so I can follow formatting), I can add a simple explanation along with my config as an example.

Does that mean I would need individual buttons for each different color mode supported?

**Comment by NickDorak** [comment]
> I wrote a PR at one point to add color support for the light entity but didn't end up moving it forward:
> 
> * The device only support 5 actual colors.  (its not RGB, it 5 fixed values)
> * Color is not reported by the device so everything is lost on restart
> * Changing the color changes the color for ALL devices connected to the controller not just a single light
> 
> The UX was just not so great considering all that.

Do you have a link to that PR so I can go upvote it?

**Comment by dieselrabbit** [comment]
@NickDorak Yes. Here is my lovelace config for all the buttons. Replace `[your_screenlogic_device_id]` with the device ID of your ScreenLogic device. You can get it by going to Services in the Developer Tools menu, building a `screenlogic.set_color_mode` service call through the UI, selecting your ScreenLogic device as the Target, then switching to YAML view.

```
type: vertical-stack
cards:
  - type: horizontal-stack
    title: Color Lights
    cards:
      - type: button
        tap_action:
          action: call-service
          service: screenlogic.set_color_mode
          service_data:
            color_mode: party
          target:
            device_id: [your_screenlogic_device_id]
        name: Party
        icon: mdi:party-popper
        show_name: false
        icon_height: 45px
      - type: button
        tap_action:
          action: call-service
          service: screenlogic.set_color_mode
          service_data:
            color_mode: romance
          target:
            device_id: [your_screenlogic_device_id]
        name: Romance
        icon: mdi:heart
        show_name: false
        icon_height: 45px
      - type: button
        tap_action:
          action: call-service
          service: screenlogic.set_color_mode
          service_data:
            color_mode: american
          target:
            device_id: [your_screenlogic_device_id]
        name: Patriotic
        icon: mdi:firework
        show_name: false
      - type: button
        tap_action:
          action: call-service
          service: screenlogic.set_color_mode
          service_data:
            color_mode: caribbean
          target:
            device_id: [your_screenlogic_device_id]
        name: Caribbean
        icon: mdi:island
        show_name: false
      - type: button
        tap_action:
          action: call-service
          service: screenlogic.set_color_mode
          service_data:
            color_mode: royal
          target:
            device_id: [your_screenlogic_device_id]
        name: Royal
        icon: mdi:crown
        show_name: false
      - type: button
        tap_action:
          action: call-service
          service: screenlogic.set_color_mode
          service_data:
            color_mode: sunset
          target:
            device_id: [your_screenlogic_device_id]
        name: Sunset
        icon: mdi:weather-sunset
        show_name: false
      - type: button
        tap_action:
          action: call-service
          service: screenlogic.set_color_mode
          service_data:
            color_mode: save
          target:
            device_id: [your_screenlogic_device_id]
        name: Save
        icon: mdi:content-save
        show_name: false
  - type: horizontal-stack
    cards:
      - type: button
        tap_action:
          action: call-service
          service: screenlogic.set_color_mode
          service_data:
            color_mode: recall
          target:
            device_id: [your_screenlogic_device_id]
        name: Recall
        icon: mdi:folder-open
        show_name: false
        icon_height: 45px
      - type: button
        tap_action:
          action: call-service
          service: screenlogic.set_color_mode
          service_data:
            color_mode: red
          target:
            device_id: [your_screenlogic_device_id]
        name: Red
        icon: mdi:alpha-r-circle
        show_name: false
      - type: button
        tap_action:
          action: call-service
          service: screenlogic.set_color_mode
          service_data:
            color_mode: green
          target:
            device_id: [your_screenlogic_device_id]
        name: Green
        icon: mdi:alpha-g-circle
        show_name: false
      - type: button
        tap_action:
          action: call-service
          service: screenlogic.set_color_mode
          service_data:
            color_mode: blue
          target:
            device_id: [your_screenlogic_device_id]
        name: Blue
        icon: mdi:alpha-b-circle
        show_name: false
      - type: button
        tap_action:
          action: call-service
          service: screenlogic.set_color_mode
          service_data:
            color_mode: white
          target:
            device_id: [your_screenlogic_device_id]
        name: White
        icon: mdi:alpha-w-circle-outline
        show_name: false
      - type: button
        tap_action:
          action: call-service
          service: screenlogic.set_color_mode
          service_data:
            color_mode: magenta
          target:
            device_id: [your_screenlogic_device_id]
        name: Magenta
        icon: mdi:alpha-m-box
        show_name: false
```
