### ISSUE TITLE
Updating the Apple TV integration examples: How to deal with a turned off remote entity

### ISSUE THREAD

**Issue by Someone0nEarth** [home-assistant/home-assistant.github.io#24171]
### Feedback

Sometimes the Apple TV remote entity is not turned on, so the scripts in the examples are not working (at least for me on tvOS 16.0 and Apple TV 4K 2. Gen). 

Fix: Ensuring in the scripts, that the remote entity is turned on.

Maybe updating the examples on the integration page?

Example:

```
apple_tv_sleep:
  alias: "Make the Apple TV sleep"
  sequence:
  - if:
    - condition: device
      type: is_off
      device_id: <lounge_appletv_device_id>
      entity_id: remote.lounge_appletv
      domain: remote
    then:
    - type: turn_on
      device_id: <lounge_appletv_device_id>
      entity_id: remote.lounge_appletv
      domain: remote
    - wait_for_trigger:
      - platform: device
        type: turned_on
        device_id: <lounge_appletv_device_id>
        entity_id: remote.lounge_appletv
        domain: remote
  - service: remote.send_command
      target:
        entity_id: remote.lounge_appletv
      data:
        delay_secs: 1
        command:
          - home_hold
          - select
  - service: media_player.turn_off
      target:
        entity_id: media_player.lounge_appletv
  mode: single
```

Thanks for the integration!

Best regards,
 Someone

### URL

https://www.home-assistant.io/integrations/apple_tv/

### Version

2022.8.7
