### ISSUE TITLE
systemmonitor using legacy YAML syntax

### ISSUE THREAD

**Issue by bgala** [home-assistant/home-assistant.github.io#24220]
### Feedback

Documentation for System Monitor shows following example:
```
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: memory_free
```
      
Should this not be updated to format used in other places with sensors
```
{platform_name}:
     - sensor:
          etc...
```

### URL

https://www.home-assistant.io/integrations/systemmonitor/

### Version

2022.9.6
