### ISSUE TITLE
Examples need to be improved

### ISSUE THREAD

**Issue by KL2001** [home-assistant/home-assistant.github.io#24221]
### Feedback

I have multiple covers, which in the past could be configured like this:
```
cover: 
  - platform: mqtt
    name: "garage"
  - platform: mqtt
    name: "garage2"
```

When I try this:
```
mqtt:
  cover:
    -name: "garage"
  cover:
    -name: "garage2"
```

or this:
```
mqtt:
  cover:
    -name: "garage"
 
    -name: "garage2"
```

It fails to parse the configuration. Are we only allowed one cover now?

### URL

https://www.home-assistant.io/integrations/cover.mqtt/

### Version

2022.9.6

**Comment by homeassistant** [comment]
Hey there @emontnemery, mind taking a look at this feedback as it has been labeled with an integration (`mqtt`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L390) for? Thanks!

**Comment by calebmah** [comment]
You are missing a space in your config in `- name`, this should work:
```
mqtt:
  cover:
    - name: "garage"
    - name: "garage2"
```
