### ISSUE TITLE
Explain `config_entry` in the docs for the Google Sheets integration

### ISSUE THREAD

**Issue by LucaBoschetto** [home-assistant/home-assistant.github.io#24417]
### Feedback

I find it is not clear for whoever is not very skilled at HA what the field `config_entry` should be populated with.

I'm quite a noob myself, and in the end I found out what it should have been populated with by selecting _Integration* = Google Sheets_ in a button card I was creating to test this integration.

I suggest you explain a bit better where to find the value for this.

### URL

https://www.home-assistant.io/integrations/google_sheets/

### Version

2022.10.0

**Comment by homeassistant** [comment]
Hey there @tkdrob, mind taking a look at this feedback as it has been labeled with an integration (`google_sheets`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L245) for? Thanks!

**Comment by tkdrob** [comment]
Explanation was not really thought of as needed since we expect most people to use the UI for writing service calls in automations. The applicable config entry ids are the one's available from the drop-down in automations or developer tools.

**Comment by tkdrob** [comment]
When you try to use this in an automation from the UI, please explain what about it is confusing.

**Comment by LucaBoschetto** [comment]
If I use the automation from the UI, I can see the config entry, so nothing confusing there. But not everybody uses this integration from the UI, and not everybody knows what a config entry is (even googling it on home-assistant.io is not very straightforward).

**Comment by tkdrob** [comment]
I still don't see a need for it. The config entry id is what is put there in yaml which is a long set of characters. Same goes with device and entity ids for targets. That's not something I think we should explain. Just use the UI at first and then go into yaml for those who prefer it. Throwing more details in there will cause more confusion for the common user then will help.

**Comment by LucaBoschetto** [comment]
I think that what you are writing would be a sufficient explanation: «A 32-digit hex identifier of the integration. To find what config_entry to use, use the UI where you can find it listed under "Integration*" as "Google Sheets"».

**Comment by flemmingss** [comment]
at least it should be explained on the integration page that this integration can be added via ui.
I will try that.


(YAML should be documented anyway btw, my opinion)

**Comment by tkdrob** [comment]
[](url)> at least it should be explained on the integration page that this integration can be added via ui. I will try that.
> 
> (YAML should be documented anyway btw, my opinion)
![Screenshot 2022-10-07 123606](https://user-images.githubusercontent.com/21083073/194603748-aa8f97bf-b01f-49f3-9965-682ab07c8c8e.png)

**Comment by AgentFalcon** [comment]
@tkdrob 

> When you try to use this in an automation from the UI, please explain what about it is confusing.

I found the data input part to be explained wrongly on the integration page.
It says to put in ["foo"], but actually you need to put in something like: ColumnName: Row1

or more specifically, if you want some usable data in there you have to put something like: TemperatureValue: "{{ states.sensor.tempsensor1.state }}"

Putting in the template brackets forces you to leave the UI mode and go to YAML.
So for UI there should ideally be an option to add data source with a dropdown box to select device and which data you want to input.  Would make the whole thing a lot easier to use for most people.

**Comment by tkdrob** [comment]
> @tkdrob
> 
> > When you try to use this in an automation from the UI, please explain what about it is confusing.
> 
> I found the data input part to be explained wrongly on the integration page. It says to put in ["foo"], but actually you need to put in something like: ColumnName: Row1
> 
> or more specifically, if you want some usable data in there you have to put something like: TemperatureValue: "{{ states.sensor.tempsensor1.state }}"
> 
> Putting in the template brackets forces you to leave the UI mode and go to YAML. So for UI there should ideally be an option to add data source with a dropdown box to select device and which data you want to input. Would make the whole thing a lot easier to use for most people.

That's not possible yet at this time to have easy data sources without templating. The "foo" example is just that, an example. It can be whatever the user wants it to be. Since the possibilities are endless, it's not for people who are just starting out. For anyone else reading this, check out: https://www.home-assistant.io/integrations/template

Additionally, config entry selector is also already explained in the docs here: https://www.home-assistant.io/docs/blueprint/selectors/#config-entry-selector

**Comment by Hellis81** [comment]
Just to give some clarity here, this is my automation that (should) writes all TRV actions to sheets:

My setup is that I have Climate TRV entities and generic thermostat climate entities.
I trigger on the TRV entity and use templates to get values from the generic thermostat entity also, so that is the reason for all the replaces.



```
alias: TRV to Google Sheets
description: ""
trigger:
  - platform: state
    entity_id:
      - climate.trv_kok_thermostat
      - climate.trv_vardagsrum_thermostat
      - climate.trv_david_thermostat
      - climate.trv_matilda_thermostat
      - climate.trv_sovrum_thermostat
    attribute: temperature
action:
  - service: google_sheets.append_sheet
    data:
      config_entry: 927e50ef6b3c6946d426cfd41c7d5de3
      worksheet: >-
        {{ (trigger.to_state.entity_id | replace("climate.", "")|
        replace("_thermostat", ""))[0:5] | upper ~ (trigger.to_state.entity_id |
        replace("climate.", "")| replace("_thermostat", "")|
        replace("kok","kök"))[5:] }}
      data:
        room_temp: >-
          {{ state_attr(trigger.to_state.entity_id | replace("trv_", "") |
          replace("_thermostat", "") | replace("kok", "vardagsrum"),
          "current_temperature") }}
        set_temp: >-
          {{ state_attr(trigger.to_state.entity_id | replace("trv_", "") |
          replace("_thermostat", "") | replace("kok", "vardagsrum"),
          "temperature") }}
        set_temp_TRV: "{{ trigger.to_state.attributes.temperature }}"
        outside_temp: "{{ state_attr('weather.smhi_home', 'temperature') }}"
        wind_speed: "{{ state_attr('weather.smhi_home', 'wind_speed') | float / 3.6 }}"
        wind_bearing: "{{ state_attr('weather.smhi_home', 'wind_bearing') }}"
mode: queued
max: 15
```
