### ISSUE TITLE
No mention of scan_interval on the Scrape page

### ISSUE THREAD

**Issue by higbyk** [home-assistant/home-assistant.github.io#24442]
### Feedback

scan_interval is not mentioned on the page, but I see it in example configurations in the forums. Is this an optional parameter? How else can I define when the sensor updates?

### URL

https://www.home-assistant.io/integrations/scrape/

### Version

2022.10.1

**Comment by homeassistant** [comment]
Hey there @fabaff, mind taking a look at this feedback as it has been labeled with an integration (`scrape`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L544) for? Thanks!

**Comment by gjohansson-ST** [comment]
All sensors based on the "old" yaml syntax has the optional parameter to set `scan_interval`. It's just not mentioned perhaps on every integration page which still has this syntax for configuration.
Ex:
```yaml
sensor:
  - platform: scrape
    resource: http://www.google.com
    name: Name
    select: "p"
    scan_interval: 180
```
