### ISSUE TITLE
Goodwe Inverter integration - Inverter operation mode

### ISSUE THREAD

**Issue by Rotif** [home-assistant/home-assistant.github.io#24541]
### Feedback

Hi,
entity select.inverter_operation_mode doesn't work for me. I tried to use it in automation but it doesn't work. The button in the main panel doesn't work either. Pleas is there a way how to switch the operating mode of the inverter using HA?
Thank you
Fitor

### URL

https://www.home-assistant.io/integrations/goodwe

### Version

2022.10.2

### Additional information

In the older versions it doesn't work either. Inverter GW10K-ET Plus, firmware version 070719

Sample of automation:

```
action:
  - if:
      - condition: numeric_state
        entity_id: sensor.battery_state_of_charge
        below: 90
      - condition: and
        conditions:
          - condition: numeric_state
            entity_id: sensor.battery_state_of_charge
            above: 30
    then:
     - condition: state
        entity_id: select.inverter_operation_mode
        state: Off grid mode
    else:
      - condition: state
        entity_id: select.inverter_operation_mode
        state: General mode 
```
