### ISSUE TITLE
Cannot set external_url

### ISSUE THREAD

**Issue by hannahdiels** [home-assistant/home-assistant.github.io#24669]
### Feedback

After enabling advanced mode for my user, I do not see a way to set the external_url in Settings > System > General. I also tried adding the following to `configuration.yaml`:

```yaml
homeassistant:
  external_url: 'https://my.domain.com:8123'
  internal_url: 'https://my.domain.com:8123'
```

but seems the URLs remain unchanged. In developer tools I saw "Configuration invalid!" and

```
Integration error: external_url - Integration 'external_url' not found.
Integration error: internal_url - Integration 'internal_url' not found.
```

### URL

https://www.home-assistant.io/docs/configuration/basic/

### Version

2022.10.5
