### ISSUE TITLE
Google Calendar failing with 2022.11.2

### ISSUE THREAD

**Issue by jarrah31** [home-assistant/home-assistant.github.io#24901]
### Feedback

My Google Calendar integration was working ok with 2022.10.x, but after I upgraded to 2022.11.2, the logs show the following error during startup:

```
2022-11-11 19:57:07.419 ERROR (MainThread) [homeassistant.components.automation.away_schedule] Error setting up trigger away_schedule
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/homeassistant/components/calendar/trigger.py", line 177, in async_attach_trigger
    component: EntityComponent[CalendarEntity] = hass.data[DOMAIN]
KeyError: 'calendar'
```
I see 9 entries with this error for each of my calendar automations.

The automations look like this:
```
  - alias: away_schedule
    id: away_schedule
    mode: queued
    trigger:
      - platform: calendar
        event: start
        entity_id: calendar.myemail_gmail_com
        offset: "12:00:00"
      - platform: calendar
        event: end
        entity_id: calendar.myemail_gmail_com
        offset: "-20:00:00"
    condition:
      - condition: template
        value_template: "{{ 'Holiday' in trigger.calendar_event.summary }}"
    action:
      - if:
          - "{{ trigger.event == 'start' }}"
        then:
          - service: input_boolean.turn_on
            entity_id: input_boolean.holiday
        else:
          - service: input_boolean.turn_off
            entity_id: input_boolean.holiday
```
I've tried to delete the Google Calendar Integration from the Integrations page by selecting the 3-dot menu and choosing Delete, but the entry remains there, even after a restart as well.

<img width="276" alt="image" src="https://user-images.githubusercontent.com/3072303/201424198-0b02ebed-5b22-46d1-b124-44d2d331890a.png">

### URL

https://www.home-assistant.io/integrations/google/

### Version

2022.11.2
