### ISSUE TITLE
Example shows old style MQTT sensor Yaml

### ISSUE THREAD

**Issue by Stan-Gobien** [home-assistant/home-assistant.github.io#24913]
### Feedback

```
sensor:
  - platform: mqtt
    state_topic: "sensor/topic"
  - platform: mqtt
    state_topic: "sensor2/topic"
```

The example on the page showing MQTT sensors is using a deprecated syntax.
See: https://www.home-assistant.io/integrations/sensor.mqtt/

### URL

https://www.home-assistant.io/docs/configuration/yaml
