### ISSUE TITLE
Multiple timers

### ISSUE THREAD

**Issue by A-JdH** [home-assistant/home-assistant.github.io#25069]
### Feedback

It would be helpfull to give an example of configuring **multiple** timers in the config yaml. I aspected that I could do that as a list but that did not work.

### URL

https://www.home-assistant.io/integrations/timer/

### Version

2022.11.4

**Comment by frenck** [comment]
It is a map, not a list; as documented in the YAML configuration section:

![CleanShot 2022-11-28 at 08 31 32](https://user-images.githubusercontent.com/195327/204219221-77ac60c4-5a60-4fab-ae03-600cdf97ab40.png)

```yaml
# Example configuration.yaml entry
timer:
  laundry:
    duration: "00:01:00"
  another:
    duration: "00:01:00"
```

../Frenck
