### ISSUE TITLE
Utility Meter - Advance configuration automation exemple didn't work

### ISSUE THREAD

**Issue by MelodicPrompt** [home-assistant/home-assistant.github.io#25105]
### Feedback

I followed the documentation to the letter. 

I copied the automation presented in the documentation into automation.yaml.
When I execute this one, I have an error on the select option

in automation.yaml
```
- id: "1669757091775"
  alias: kwh
  description: ""
  trigger:
    - platform: time
      at: 09:00:00
      variables:
        tariff: peak
    - platform: time
      at: "21:00:00"
      variables:
        tariff: offpeak
  condition: []
  action:
    - service: select.select_option
      target:
        entity_id: select.daily_energy
      data:
        option: "{{ tariff }}"
    - service: select.select_option
      target:
        entity_id: select.monthly_energy
      data:
        option: "{{ tariff }}"
  mode: single
```

In configuration.yaml
```
utility_meter:
  daily_energy:
    source: sensor.energy
    name: Daily Energy
    cycle: daily
    tariffs:
      - peak
      - offpeak
  monthly_energy:
    source: sensor.energy
    name: Monthly Energy
    cycle: monthly
    tariffs:
      - peak
      - offpeak
```

![image](https://user-images.githubusercontent.com/109700532/204779080-769256ea-992f-4c9e-a1c2-da7010a4f6ee.png)

if I force the options with the `peak offpeak` values, my `entity_meter` is well updated
![image](https://user-images.githubusercontent.com/109700532/204779176-dc6dab35-1108-41d8-8208-a1b7b5ef42ca.png)

![image](https://user-images.githubusercontent.com/109700532/204779411-6068c178-a25f-4ecb-a1ac-a61082b04e5c.png)

![image](https://user-images.githubusercontent.com/109700532/204779442-f97d1171-fdb1-4f6b-a556-37f28067be58.png)

Regard

### URL

https://www.home-assistant.io/integrations/utility_meter/#advanced-configuration

### Version

2022.11.4
