### ISSUE TITLE
Is the example yaml correct?

### ISSUE THREAD

**Issue by laithsaid** [home-assistant/home-assistant.github.io#25120]
### Feedback

If the data read in Watt, and the unit_prefix is k and time is h, then it calculated the energy in kWh
But it seems that it is not calculating the energy and dividing the result 1000 to return kWh.

I thought that I have to set "unit_prefix: k" only if I'm receiving the power in kW and not W.

```yaml
sensor:
  - platform: integration
    source: sensor.current_power
    name: energy_spent
    unit_prefix: k
    round: 2
```

### URL

https://www.home-assistant.io/integrations/integration/
