### ISSUE TITLE
Component iframe does not allow full-screen video to be displayed

### ISSUE THREAD

**Issue by mad-ady** [home-assistant/home-assistant.github.io#2515]
If I point the iframe component to a html page which uses a ```<video>``` element, the video player loses the ability to display video fullscreen. This is due to the following missing iframe attributes:

```<iframe allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true">```

More details here: http://stackoverflow.com/questions/15276929/how-to-make-a-video-fullscreen-when-it-is-placed-inside-an-iframe

Can you enable those attributes when creating an iframe with the iframe component?
Sample configuration (though you'd need to point it to a page with ```<video>``` elements):
```
panel_iframe:
  webcam_recordings:
    title: Webcam Recordings
    icon: mdi:video
    url: !secret webcam_recordings_url
```
