### ISSUE TITLE
Scrape sensor description

### ISSUE THREAD

**Issue by Yari117** [home-assistant/home-assistant.github.io#25232]
### Feedback

On the webpage https://www.home-assistant.io/integrations/scrape/
it is advised to configure the scrape sensor as follows:
```
scrape:
  - resource: https://hasspodcast.io/feed/podcast
    sensor:
      - name: Home Assistant Podcast
        select: "enclosure"
        index: 1
        attribute: url
```
This however leads to an error when restarting HA

As far as I understand, the correct way of configuring the scrape sensor now is to use
```
sensor:
  platform: scrape
  resource:
  name:
  select:
```

### URL

https://www.home-assistant.io/integrations/scrape/

### Version

2022.12.1
