### ISSUE TITLE
Utility Meter: No clue how to add multiple tariffs

### ISSUE THREAD

**Issue by daniestermann** [home-assistant/home-assistant.github.io#25348]
### Feedback

I am trying to enter a utility meter helper with 2 tariffs **via ui** that results in something like in the yaml example below.

```
utility_meter:
    monthly_energy:
      source: sensor.power_usage
      cycle: monthly
      tariffs:
        - peak
        - offpeak  
 ```

Problem:
But whatever I add in the tariffs field is ignored. The ui seems to expect "A list of supported tariffs", but I have no clue how to enter a list in a single text field. I tried entering one tariff at a time and then hitting return, but nothing happened. So does is expect some yaml-like list syntax? 

_I think this worked in an earlier release but I don't remember how. 
What's also unexpected: When I press tab to advance to the next field, the tariffs field is cleared. 
Is this maybe a UI bug?_

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2022.12.7

### Additional information

Frontend 20221213.1
Tried both latest Safari and Chrome on macOS 13.0.1
