### ISSUE TITLE
[Feature Request] Include a print.css

### ISSUE THREAD

**Issue by ioangogo** [home-assistant/home-assistant.github.io#2537]
This would enable people to print off the pages without the messiness from removed styles. and saves paper when people decide to waste paper by printing it.

If you try to print the docs at the moment it looks like this (well the first page)
![screenshot from 2017-04-30 14-21-02](https://cloud.githubusercontent.com/assets/7449028/25564676/88ef4af8-2db0-11e7-92ed-6df8da64cabc.png)

I feel like we dont need the rest of the page so just have the artical element in the page and possibly have a simple header with the logo in

**Comment by ioangogo** [comment]
My current idea for this is in the css for the docs include this media query

```css
@media print {
    html body * {display:none;
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif; /* this isn't inherited by default */
    }
   .ha-title{display: inline-block;}
   .page{display: block;}
}
```
