### ISSUE TITLE
Could you tell a bit more about the day/night switching of the theme?

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#25401]
### Feedback

Could you please elaborate, or provide an example how to I get these self made themes to switch from day(happy) to night(sad). For example I made this in the configyaml:

```
frontend:
  themes:
    day_and_night:
      primary-color: "#3593bc"
      modes:
        light:
          lovelace-background: 'center / cover no-repeat url("/local/day-morecontrast.png") fixed'
        dark:
          lovelace-background: 'center / cover no-repeat url("/local/night-morecontrast.jpg") fixed'
```
And this works. But it is unclear if Home Assistant automatically switches my themes from day to night, or not. Could you provide information about this meganism or an official example how to proceed since the user formum shows so many different opinions.

I have made this automation from the forum (and similar other examples from the forum) but they all give the same error as shown below.

```
alias: Auto theme change
description: Auto theme change
trigger:
  - platform: state
    entity_id: sun.sun
condition: []
action:
  - service_template: frontend.set_theme
    data_template:
      name: |
        {% if is_state('sun.sun', 'above_horizon') %}
          light
        {% else %}
          dark
        {% endif %}
    alias: Verander theme met zon op of onder
mode: single
```

but it gives me the error:

```
Logger: homeassistant.components.frontend
Source: components/frontend/__init__.py:437
Integration: Home Assistant Frontend (documentation, issues)
First occurred: 15:12:01 (5 occurrences)
Last logged: 15:20:01

Theme light not found
```
Many times. While I did defined a theme called "light" in the configyaml. So i'm probably missing the point somewhere with the documentation. Would it be possible to enhance the explanation somewhat there?

### URL

https://www.home-assistant.io/integrations/frontend/#defining-themes

### Version

2022.12.8

### Additional information

Sorry if i'm in the wrong place for this request. Don't want to be unpolite.
