### ISSUE TITLE
Group and  unique_id in the configuration yaml

### ISSUE THREAD

**Issue by JokerGermany** [home-assistant/home-assistant.github.io#25513]
### Feedback

The documentation states that you can use `unique_id`, and home assistant says
> Invalid config for [group]: [unique_id] is an invalid option for [group]. Check: group->group->heizung-xyz->unique_id. (See /config/configuration.yaml, line 51). 

### URL

https://www.home-assistant.io/integrations/group/

### Version

2022.12

### Additional information

```
heizung-xyz:
    name:   Heizung-XYZ
    unique_id: 1c376c9e-8acd-11ed-a1eb-0242ac120002
    entities:
        - person.abc
        - person.def
        - person.ghi
```
