### ISSUE TITLE
please provide more detailed setup guide for hddtemp

### ISSUE THREAD

**Issue by gregewing** [home-assistant/home-assistant.github.io#25573]
### Feedback

Please provide a configuration example that shows configuring hddtemp to monitor temps from several remote hosts.

https://www.home-assistant.io/integrations/hddtemp

### URL

https://www.home-assistant.io/integrations/hddtemp

**Comment by gregewing** [comment]
Also, the hddtemp integration works in containers of you assume that the data is coming from a separate container on the same host and you treat it like its a remote host ( I have this working )  but now I want o add in monitoring for additional remote hosts.

**Comment by fabaff** [comment]
The `hddtemp` supports `host` and `port` which needs to be adjusted if you want to monitor multiple instances.

**Comment by gregewing** [comment]
yeah, I understand that, but what I don't understand is the syntax in yaml to provide host and port so that it will monitor multiple instances.  Can you provide an example ?

**Comment by frenck** [comment]
It is a YAML list (as shown in the current documentation), extend the list with as many instances as you like.

For more information on YAML see here: <https://www.home-assistant.io/docs/configuration/yaml/>, and otherwise Google can provide you with tons of resources on how YAML works :)

For example:

```yaml
# Example configuration.yaml entry
sensor:
  - platform: hddtemp
    disks:
      - /dev/sda1
  - platform: hddtemp
    disks:
      - /dev/sda2
  - platform: hddtemp
    disks:
      - /dev/sda2
  - platform: hddtemp
    name: "something else"
    disks:
      - /dev/sda3
  - platform: hddtemp
    host: external-machine.local
    port: 1337
```
