### ISSUE TITLE
MQTT sensor: cannot change "payload_available"

### ISSUE THREAD

**Issue by OldSurferDude** [home-assistant/home-assistant.github.io#25636]
### Feedback

not matter value I give **payload_available:** it only indicates the device is available if the payload is "**online**"
eg.
```
    availability:
      - topic: SIP
    payload_available: "UP"
    payload_not_available: "DOWN"

```
will always be unavailable unless "online" is sent to the topic **SIP**

### URL

https://www.home-assistant.io/integrations/sensor.mqtt/#payload_available

### Version

2023.1.1 (my version 2022.12.9)

**Comment by jbouwh** [comment]
Can you give your full configuration?

**Comment by OldSurferDude** [comment]
I added four spaces before each _**payload**_ the code to:
```
    availability:
      - topic: SIP
        payload_available: "UP"
        payload_not_available: "DOWN"

```
and it woks as expected.  

So this is a documentation error which you can fix (right?). Someone forgot to indent appropriately

(Note: The sensor that provides the status publishes "UP", that is, four characters that are <double quote>UP<double quote> and this is not recognized.  Fortunately, I can compensate with '"UP"' (<single quote><double quote>UP<double quote><single quote> and similarly for DOWN) in the statement so my yaml code looks like:
```
    availability:
      - topic: SIP
        payload_available: '"UP"'
        payload_not_available: '"DOWN"'

```

**Comment by jbouwh** [comment]
Why do you use a double pair of quotes?

**Comment by OldSurferDude** [comment]
The payload provided by the sensor in the status topic is the four characters <quote><U><P><quote>.  The yaml code parses both "UP" and UP as UP and therefore does not match the four characters "UP".  Putting the single pair of quotes around the four characters "UP" (six characters in total) is rendered as "UP" and does match. 

Is this the correct explanation?  I do not know.  What I do know is that putting the single quotes in works but does not work without them.

OSD

**Comment by jbouwh** [comment]
`availability` requires a list like:

```yaml
mqtt:
  sensor:
    - name: "Some sensor"
      availability:
        - topic: SIP
          payload_available: UP
          payload_not_available:  DOWN
        - topic: second_topic
          payload_available: ONLINE
          payload_not_available:  OFFLINE
```
(You can use quotes if you like)
or...
```yaml
mqtt:
  sensor:
    - name: "Some sensor"
      availability_topic:
      payload_available: UP
      payload_not_available:  DOWN
```
