### ISSUE TITLE
Script arguments limiation

### ISSUE THREAD

**Issue by Ed-Ross** [home-assistant/home-assistant.github.io#25663]
### Feedback

Hi, unless I am mistaken, passing arguments to a script can be done from an automation or another script, but not from a dashboard element. If that is indeed the case, it might be worth indicating it in the "PASSING VARIABLES TO SCRIPTS" section of the documentation.
Thank you,
Ed

### URL

https://www.home-assistant.io/integrations/script/#full-configuration

**Comment by frenck** [comment]
Scripts are services, they can be called from anything that supports services (including their arguments). The suggested limitation doesn't exist.

../Frenck

**Comment by Ed-Ross** [comment]
Wow you are quick ! 
Okay my bad, I have finally found the way. Maybe worth adding to the documentation, as I really struggled to find the solution in the forums: 

YAML code for a button calling a script with an argument

```
type: custom:button-card #or anything else in a dashboard
tap_action:
  action: call-service
  service: script.my_script_name
  service_data:
    arg1: input_boolean.my_boolean
```

arg1 being the argument expected in the script.


Thank you, keep up the great work ! :+1: 
Ed
