### ISSUE TITLE
customize can be used on any attribute, not only the ones mentioned

### ISSUE THREAD

**Issue by llamafilm** [home-assistant/home-assistant.github.io#25676]
### Feedback

This documentation page suggests that `customize` can be used to adjust certain attributes such as icon, device_class, etc.  But I discovered that it can also adjust _any_ entity attribute.  I suggest editing this page to make that clear.  You could also include a YAML example.  One example is a Mysa baseboard thermostat which appears to support both heating and cooling modes.  I customized it to support heat only:
```yaml
  customize:
    climate.mysa_baseboard_thermostat:
      hvac_modes:
        - 'off'
        - heat
```

### URL

https://www.home-assistant.io/docs/configuration/customizing-devices/

### Version

2023.1.2
