### ISSUE TITLE
Process for importing old scenes in the new UI

### ISSUE THREAD

**Issue by TurboKid** [home-assistant/home-assistant.github.io#25962]
### Feedback

I am writing this as feedback, but currently upgrading to the new scenes editor broke the color temperature selection of one of my scenes. At this time no matter what I have tried I cannot set my scene with color temperature, only the default RGB colors. 

On to the actual feedback for the process. 

I created a new scenes_old.yaml file and added the appropriate config: portion for scenes old:
```
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene old: !include scenes_old.yaml
scene: !include scenes.yaml
```
I proceeded to convert my scenes from my old naming scheme to the new with the id being a randomly generated number.
OLD
```
- id: working_at_desk
  name: Working at Desk
  entities:
    light.desk_light:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: xy
      brightness: 255
      hs_color:
      - 0
      - 0.392
      rgb_color:
      - 255
      - 254
      - 254
      xy_color:
      - 0.323
      - 0.329
```

NEW
```
- id: '2679462782702'
  name: Working at Desk
  entities:
    light.desk_light:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      mode: normal
      dynamics: none
      friendly_name: Desk Light
      supported_features: 40
      icon: mdi:led-strip-variant
      color_mode: xy
      brightness: 254
      hs_color:
      - 0
      - 0.392
      rgb_color:
      - 255
      - 254
      - 254
      xy_color:
      - 0.323
      - 0.329
```
Now every time I set my scene, I have to correct to color temperature instead of RGB.

### URL

https://www.home-assistant.io/docs/scene/editor/

### Version

2023.01.1
