### ISSUE TITLE
Please add detailed description how to connect LD2410

### ISSUE THREAD

**Issue by Korte68** [home-assistant/home-assistant.github.io#26070]
### Feedback

As I know the LD2410 device communicating over serial interface with ESPHome. Or is there any other way to integrate?

### URL

https://www.home-assistant.io/integrations/ld2410_ble/

### Version

2023.2.0

**Comment by 930913** [comment]
Bluetooth variants (B & C) models will be automatically picked up when a suitable Bluetooth adapter or proxy is configured. In Devices & Services, you should see it discovered and be able to click configure to connect.

**Comment by Korte68** [comment]
Hi,
I have an LD2410B. Connected it to 5V. Have an esp32 with esphome software and activated the bluetooth_proxy.
But HA not detected the sensor. What should I do? Thank you

**Comment by 930913** [comment]
Please could you `Download diagnostics` from the ESPHome integration in Home Assistant and share it so we can try identify the issue.

**Comment by 930913** [comment]
Oh, also have you got active proxy enabled?
```yaml
bluetooth_proxy:
  active: true
```

**Comment by Korte68** [comment]
> Oh, also have you got active proxy enabled?
> 
> ```yaml
> bluetooth_proxy:
>   active: true
> ```

yes

I have a few xiaomi temp sensor and a scale connected to the ESP. 

 ```
esp32:
  board: ${board}
  framework:
    type: esp-idf

logger:

api:

wifi:
  ssid: !secret wifi_ssid1
  password: !secret wifi1_pass 
  reboot_timeout: 5min

  ap:
    password: !secret wifi2_pass

ota:
  password: !secret ota_pass

esp32_ble_tracker:

bluetooth_proxy:
  active: true

sensor:
  - platform: xiaomi_miscale
 ```
