### ISSUE TITLE
Frontier Silicon integration works with Pure Evoke C-F6 (with caveats)

### ISSUE THREAD

**Issue by raphv** [home-assistant/home-assistant.github.io#26138]
### Feedback

Hi, I have a smart radio from Pure <https://www.pure.com/> the Evoke C-F6, which mostly works with the Frontier Silicon integration.
There is a small caveat, which is that the Evoke C-F6 is also seen as a DLNA renderer of the same name and if you activate both, the entity names will both be `media_player.evoke_c_f6`.
To avoid this, make sure to rename the media player in your `configuration.yaml`:
```
media_player:
  - platform: frontier_silicon
    host: 192.168.1.123
    name: My Pure Radio
```
I have not managed to make the "local media" feature work yet though (it does require a DLNA UPnP server, which I have set up with minidlna, but I get an error with the `play_media` service.

### URL

https://www.home-assistant.io/integrations/frontier_silicon/

### Version

2023.2.2
