### ISSUE TITLE
Code example on "Creating scenes on the fly" doesn't work

### ISSUE THREAD

**Issue by sorenlouv** [home-assistant/home-assistant.github.io#26218]
### Feedback

The code example for "Creating scenes on the fly" doesn't work. I'm aware that identifiers needs to be updated to the specific use case but there seems to be a syntax error in the example.

## Reproduce

1. Copy the example

```yml
# Example automation using snapshot
- alias: "Window opened"
  trigger:
  - platform: state
    entity_id: binary_sensor.window
    from: "off"
    to: "on"
  condition: []
  action:
  - service: scene.create
    data:
      scene_id: before
      snapshot_entities:
      - climate.ecobee
      - light.ceiling_lights
  - service: light.turn_off
    target:
      entity_id: light.ceiling_lights
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.ecobee
    data:
      hvac_mode: "off"
- alias: "Window closed"
  trigger:
  - platform: state
    entity_id: binary_sensor.window
    from: "on"
    to: "off"
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.before
```

2. Insert into automation as YAML

3. The error shows up as a toast `Message malformed: extra keys not allowed @ data['0']`

## Expected
It should be possible to copy/paste the code example without encountering syntax problems. 

### URL

https://www.home-assistant.io/integrations/scene/

### Version

2023.2.3
