### ISSUE TITLE
The energy price example is now broken

### ISSUE THREAD

**Issue by joakimjalden** [home-assistant/home-assistant.github.io#26226]
### Feedback

The energy price example at the end is broken due to a restructuring of the webpage elen.nu. The following modification restores the same sensor functionality from the same website (different page because the original does not exist) and demonstrates the template functionality but it does not demonstrate the ":is(span)" part of the selector.

```
scrape:
  - resource: https://elen.nu/dagens-spotpris/se3-stockholm/
    sensor:
      name: Electricity price
      select: ".text-lg.font-bold"
      index: 1
      value_template: '{{ value | replace (",", ".") | float }}'
      unit_of_measurement: "öre/kWh"
```

### URL

https://www.home-assistant.io/integrations/scrape/

### Version

2023.2.3
