### ISSUE TITLE
Pool Temperature Variable Exposure

### ISSUE THREAD

**Issue by gnvdude** [home-assistant/home-assistant.github.io#26242]
### Feedback

first of all love this integration

this there a way to extract and expose the 'current pool temperature' as an element in home assistant from the climate entitiy?

I mean it shows but I can't pull it separately to display or do any automation off this element

Thanks in advance

![image](https://user-images.githubusercontent.com/9097927/218578559-6948aaf6-9b6f-4857-92b6-fc5c915816f8.png)

![image](https://user-images.githubusercontent.com/9097927/218578810-ca41d299-f619-47a9-be0a-9a276bbffd0d.png)

### URL

https://www.home-assistant.io/integrations/screenlogic/

### Version

2023.2.4

**Comment by dieselrabbit** [comment]
You can create a [template sensor](https://www.home-assistant.io/integrations/template/) to reference the `current_temperature` attribute on the climate entity.

```
template:
  - sensor:
      - name: "Pool Temperature"
        state: '{{ state_attr("climate.pentair_16_51_d0_pool_heat", "current_temperature") }}'
        unit_of_measurement: '°F'
        device_class: temperature
        state_class: measurement
  ```
