### ISSUE TITLE
This document should contain an example configuration.yaml section

### ISSUE THREAD

**Issue by ZTiKnl** [home-assistant/home-assistant.github.io#26279]
### Feedback

For people who venture onto this road, it's quite difficult finding the right piece of information, as there is a lot of outdated information online.
Also, most of the online documents for Water management in HA refer to an old style of MQTT setup in configuration.yaml, which at some point will be phased out.

Please add an example configuration.yaml section for adding Water sensors.

Below is my working example, which makes use of an MQTT connected sensor, and it integrates with Energy dashboard.
The only requirement for the user is to rename the state_topics where required, reload HA and edit the Energy dashboard to include the water consumption sensor.

```
### SmartGateways.nl Water Meter MQTT Sensoren en Firmware Switch
mqtt:
  sensor:
    - name: "Watermeter Totaal"
      state_topic: "watermeter/reading/current_value"
      device_class: water
      icon: mdi:gauge
      unit_of_measurement: L
      state_class: total_increasing
      force_update: true
      device_class: water
    - name: "Watermeter MAC Adres"
      state_topic: "watermeter/smart_gateways/mac_address"
    - name: "Watermeter Firmware versie van gateway"
      state_topic: "watermeter/smart_gateways/running_firmware_version"
    - name: "Watermeter Beschikbare firmware versie"
      state_topic: "watermeter/smart_gateways/available_firmware_version"
    - name: "Watermeter Firmware update beschikbaar"
      state_topic: "watermeter/smart_gateways/update_available"
    - name: "Watermeter WiFi Signaalsterkte (rssi)"
      state_topic: "watermeter/smart_gateways/wifi_rssi"
      unit_of_measurement: 'dB'
      device_class: "signal_strength"
    - name: "Watermeter startup time"
      state_topic: "watermeter/smart_gateways/startup_time"
  switch:
    - name: "Watermeter Install firmware update?"
      command_topic: "watermeter/smart_gateways/install_update"
      payload_on: "yes"
      payload_off: "no"
```

All in all, it took me half a day to get this setup properly, and it would have been done in less than 10 min if I had this config example readily available ;)

### URL

https://www.home-assistant.io/docs/energy/water/

### Version

2023.2.5

### Additional information

Product page for reference:
https://smartgateways.nl/product/slimme-watermeter-gateway/
