### ISSUE TITLE
Scrape sensor does not seem to accept attributes.

### ISSUE THREAD

**Issue by Troon** [home-assistant/home-assistant.github.io#26403]
### Feedback

Page includes this:
```
attributes map (optional)
Defines templates for attributes of the sensor.

  attribute: template [template](https://www.home-assistant.io/docs/configuration/templating/) REQUIRED
  The attribute and corresponding template.
```
Defining this sensor:
```yaml
scrape:
  - resource: http://example.com
    sensor:
      - name: testing
        select: html
        attributes:
          test: "{{ value }}"
```
results in this config check error:
```
Invalid config for [scrape]: [attributes] is an invalid option for [scrape]. Check: scrape->scrape->0->sensor->0->attributes. 
```

### URL

https://www.home-assistant.io/integrations/scrape/

### Version

2023.2.5
