### ISSUE TITLE
Documentation for referencing entity in snapshot and recordings is incorrect

### ISSUE THREAD

**Issue by sdwilko** [home-assistant/home-assistant.github.io#26499]
### Feedback

The provided examples for snapshots and recordings are incorrect due to a bug (https://github.com/home-assistant/core/issues/40241) which doesn't seem to gaining any traction to be fixed (since Sept 2020).
The bug is that entities cannot be referenced in template so the examples which use entity for file naming are incorrect.

For example:
```
action:
  service: camera.record
  target:
    entity_id: camera.yourcamera
  data:
    filename: '/tmp/{{ entity_id.name }}_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
```

Does not work in any current version home assistant. The only current workaround is to encapsulate the entity reference so that the template helper renders without trying to reference the entity, then the actual reference is done by the camera service as intended.

Here is a correct example utilising the workaround:

```
action:
  service: camera.record
  target:
    entity_id: camera.yourcamera
  data:
    filename: /tmp/{{ '{{ entity_id.name }}' }}_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4
```

### URL

https://www.home-assistant.io/integrations/camera/

### Version

2023.3.1
