### ISSUE TITLE
custom update intervals to enable SEMS to almso receive the inverter data

### ISSUE THREAD

**Issue by icefluffy** [home-assistant/home-assistant.github.io#26569]
### Feedback

it is unclear where following code should be pasted (which file, & location in file):
- alias: "Goodwe inverter data polling"
  trigger:
    - platform: time_pattern
      hours: "*"
      minutes: "*"
      seconds: "/30"
  action:
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.ppv

It is also unclear if the entity_id "sensor.pvv" should be replaced with the name of existing sensors that were autmoatically made by the GoodWe integration. (if this is the case, how do we add multiple sensors??)

### URL

https://www.home-assistant.io/integrations/goodwe/

### Version

2023.3.3

**Comment by icefluffy** [comment]
Hi Bot who wants to close the issue because of inactivity, this question and remark is still relevant...

**Comment by Puffo19** [comment]
Can I vote for the topic?

**Comment by Puffo19** [comment]
The topic is still open. I added follwoing trigger to the automation

```
alias: Goodwe Polling
description: ""
trigger:
  - platform: time_pattern
    hours: "*"
    minutes: "1"
    seconds: "*"
action:
  - service: homeassistant.update_entity
    target:
      device_id: 402132e21f46d001f80ab27211216023
    data: {}
```

My Goodwe Inverter GW ET15 does not support the `sensor.ppv` entity 

But there is still no data transfer to the SEMS portal.
