### ISSUE TITLE
Feedreader examples incorrect

### ISSUE THREAD

**Issue by Adam-Ant** [home-assistant/home-assistant.github.io#2687]
The feedreader docs include the line:
> *Any field under the <entry> tag in the feed can be used for example tigger.event.data.content will get the body of the feed entry.

This is incorrect, as it causes home assistant to fail the trigger, with the error `homeassistant.exceptions.TemplateError: UndefinedError: 'trigger' is undefined`. 
I can't seem to find what the correct version of this would be, as information on the feedreader platform is very difficult to come by.  The feedreader platform itself does show up under the states tab either, making this quite difficult to figure out!

**Edit**: An example of the failing config can be found on my [GitHub repo](https://github.com/Adam-Ant/home-assistant/blob/master/automation/rssalert.yaml)

**Comment by arsaboo** [comment]
I also got the same error with a similar automation. Hopefully, someone can guide us to a working example.

**Comment by rollbrettler** [comment]
Had the same issue.

Switching `data` to `data_template` fixed it.

```
- alias: RSS Alert
  trigger:
    - platform: event
      event_type: feedreader
  action:
    - service: notify.adams_android
      data_template:
        title: 'New RSS Post!'     
        message: "{{ trigger.event.data.content }}"
```

I would say its rather a consistency issue.
