### ISSUE TITLE
Missing example for using State Selector

### ISSUE THREAD

**Issue by SgtBatten** [home-assistant/home-assistant.github.io#26887]
### Feedback

I have been unable to figure out usage of the state selector. Everything I try gives an error. Most other selectors have an example and a standard format which i expected to look like this:

```
  input:
    state_filter_states_test:
      name: State Filter States TEST (Optional)
      description: 
      selector:
        state:
          entity_id: 
```

### URL

https://www.home-assistant.io/docs/blueprint/selectors/

### Version

2023.4.0

### Additional information

![image](https://user-images.githubusercontent.com/24822223/230256316-fa211053-b1b7-47a6-a108-1f3b04ad970e.png)
