### ISSUE TITLE
Google Calendar

### ISSUE THREAD

**Issue by kj4qyf** [home-assistant/home-assistant.github.io#26899]
### Feedback

It would be very useful, and I would greatly appreciate, if you could add a "Tomorrow" node to the Google Calendar.
I got used to this option from the similar nodeserver in the Universal Devices (Polisy-eisy) environment, where each calendar has a Today and a Tomorrow node.
It is probably possible to create a Tomorrow event in the HA Google Calendar Integration, but it would not allow to see the status as I can with the UD nodserver and through the UD Integration. See attached picture.
![image](https://user-images.githubusercontent.com/30532776/230499481-83a816b7-63f8-47c2-a990-976aa09e5da1.png)
In this picture, the first node for each calendar is directly from the HA Google Calendar Integration and the Tomorrow node comes from the UD Integration (and there from the Holidays Google nodeserver).

### URL

https://www.home-assistant.io/integrations/google/

### Version

2023.4.0

**Comment by allenporter** [comment]
Hi, you can record feature requests in the community forums as we use github for issues.

You can get something like this using triggers, offsets, and a template sensor. For example, here is binary sensor that turns on when trash day is tomorrow:

```
- trigger:
    - platform: calendar
      event: start
      entity_id: calendar.local_automation_schedule
      offset: "-24:00:00"
    - platform: calendar
      event: end
      entity_id: calendar.local_automation_schedule
      offset: "-24:00:00"
  binary_sensor:
    - name: Trash Pickup Tomorrow
      state: "{{ iif('Trash' in trigger.calendar_event.summary, iif(trigger.event == 'start', 'on', 'off'), states('binary_sensor.trash_pickup_tomorrow')) }}"
```
