### ISSUE TITLE
A primary of a group cannot unjoin

### ISSUE THREAD

**Issue by bvhme** [home-assistant/home-assistant.github.io#26908]
### Feedback

What I want to do: unjoin a primary from a group

Expected: another player becomes the primary and the selected player leaves the group

I often when I go to another room tranfer my music along by, in the Bluesound app, adding another player to my group and then removing the original, it seamlessly transitions my music from one room to the other.
I want to assign a button on my wall to do this.

I see the command that is sent by the app to the original primary when I do this is:

`http://[primary-ip]:11000/RemoveSlave?slave=[primary-ip]&port=11000&force=0`

If I look in the code of the integration ([line 888](https://github.com/home-assistant/core/blob/dev/homeassistant/components/bluesound/media_player.py#LL888C1-L894C52)) I see:

```python
    async def async_unjoin(self):
        """Unjoin the player from a group."""
        if self._master is None:
            return

        _LOGGER.debug("Trying to unjoin player: %s", self.id)
        await self._master.async_remove_slave(self)
```

Perhaps this return statement is interfering with the unjoining.

Alternatively, if I tell my secondary device to kick out the primary nothing happens, only if I tell the primary to kick itself out. Perhaps this is what goes wrong. I see that the unjoin functionality doesn't have the 'coordinator' functionality.

### URL

https://www.home-assistant.io/integrations/bluesound/

### Version

2023.4.1

**Comment by bvhme** [comment]
As a workaround I've made the following REST service in my `config.yml`:

```yml
rest_command:
  bluesound_primary_unjoin:
    url: http://{{ ip }}:11000/RemoveSlave?slave={{ ip }}&port={{ port | default(11000) }}
```

![image](https://user-images.githubusercontent.com/1917629/230597840-a7e7fac1-c032-4e4d-b275-e4717fa98a7a.png)

**Comment by bvhme** [comment]
With that workaround I've created the following configurable script:

```yaml
alias: Transfer Bluesound Player
fields:
  from:
    name: From what player
    required: true
    description: >-
      the name of the media player and the network device that is currently
      playing and will stop
    selector:
      entity: null
  to:
    name: To what player
    required: true
    description: >-
      the name of the media player and the network device that the playing will
      be transfered to
    selector:
      entity: null
  delay:
    name: Time to wait before removing original player from group
    default: 5
    selector:
      duration: null
  reverse:
    name: Swap players
    description: >-
      If the from player is not playing but to to player is should the inverse
      swap happen
    default: false
    selector:
      boolean: null
sequence:
  - if:
      - condition: template
        value_template: "{{ states(from) == 'playing' }}"
    then:
      - service: bluesound.join
        data:
          master: "{{from}}"
          entity_id: "{{to}}"
      - delay: "{{delay}}"
      - service: rest_command.bluesound_primary_unjoin
        data_template:
          ip: "{{ state_attr('device_tracker.' + from.split('.')[1], 'ip') }}"
    else:
      - if:
          - condition: template
            value_template: "{{ reverse == true and states(to) == 'playing' }}"
        then:
          - service: bluesound.join
            data:
              master: "{{to}}"
              entity_id: "{{from}}"
          - delay: "{{delay}}"
          - service: rest_command.bluesound_primary_unjoin
            data_template:
              ip: "{{ state_attr('device_tracker.' + to.split('.')[1], 'ip') }}"
mode: single
icon: mdi:swap-horizontal
```
