### ISSUE TITLE
Missing info about `state` var in Numeric state trigger doc

### ISSUE THREAD

**Issue by vlycop** [home-assistant/home-assistant.github.io#26930]
### Feedback

In the Numeric state trigger documentation, `value_template` usage is demonstrated but not really documented.

in those demonstration, you can see the use of a `state` variable.
```yaml
automation:
  trigger:
    - platform: numeric_state
      entity_id: climate.kitchen
      value_template: "{{ state.attributes.current_temperature - state.attributes.temperature_set_point }}"
      above: 3
```

Since this is doesn't look to be a standard thing, and don't seam to be explained in another doc, it would be good to add some doc about it.

### URL

https://www.home-assistant.io/docs/automation/trigger#numeric-state-trigger

### Version

2023.4.2
