### ISSUE TITLE
Switchbot Blindtilt template example gives error

### ISSUE THREAD

**Issue by withay** [home-assistant/home-assistant.github.io#27168]
### Feedback

When I do a simple copy/paste of the template into HA's Dev tools Template editor, I get:  **UndefinedError: 'None' has no attribute 'attributes'**

When I change the example to using my own blind tilt name, I get:  **UndefinedError: 'position' is undefined**

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2023.4.6

**Comment by dannytsang** [comment]
Are you able to provide your template and confirm you have changed
`{{ int(states.cover.example_blinds.attributes.current_tilt_position)*2 }}` to use an entity in your setup?

**Comment by withay** [comment]
Here is my template (I have seven blindtilts, this is the first one):
```

cover:
  - platform: template
    covers:
      living_room_blind_1:
        device_class: blind
        friendly_name: Living Room Blind 1
        open_cover:
          service: cover.set_cover_tilt_position
          data:
            tilt_position: 50
          target:
            entity_id: cover.living_room_blind_1
        close_cover:
          service: cover.set_cover_tilt_position
          data:
            tilt_position: 0
          target:
            entity_id: cover.living_room_blind_1
        position_template: >
          {{ int(states.cover.living_room_blind_1.attributes.current_tilt_position)*2 }}
        set_cover_position:
          service: cover.set_cover_tilt_position
          data:
            tilt_position: "{{position/2}}"
          target:
            entity_id: cover.living_room_blind_1
```

Also - this has created a new entity:  cover.living_room_blind_1_2  and I'm assuming (my apologies, I'm new at this, and this is my first attempt at templates) that is the one I use, not the original entity.
