### ISSUE TITLE
Sonos IS a supported device with Spotify

### ISSUE THREAD

**Issue by cloggedDrain** [home-assistant/home-assistant.github.io#27169]
### Feedback

Regarding the statement at the bottom of this page:
https://www.home-assistant.io/integrations/spotify/

I have successfully used Sonos and Spotify in automations within HA and Node-Red.

My automation are as follows:

First I clear the playlist: 

```
service: media_player.clear_playlist
data: 
  entity_id: media_player.game_room_play5
```

Then using the play_media service, you can specify a Spotify playlist
service: media_player.play_media
```
data:
  entity_id: media_player.game_room_play5
  media_content_id: spotify:playlist:37i9dQZF1EJCz3hr3JBapa
  media_content_type: music
```

You can also shuffle the playlist:
service: media_player.shuffle_set
```
data:
  shuffle: true
target:
  area_id:
    - gameroom
    - bar

```

### URL

https://www.home-assistant.io/integrations/spotify/

### Version

2023.4.6
