### ISSUE TITLE
multiple zone condition example causes automation to fail

### ISSUE THREAD

**Issue by kryptonitecb3** [home-assistant/home-assistant.github.io#27558]
### Feedback

In the documentation for using multiple zones in a condition it shows:
```
condition:
  condition: zone
  entity_id: device_tracker.paulus
  state:
    - zone.home
    - zone.work
```
However when used it causes the automation to fail and be disabled. The correct syntax is:
```
condition:
  condition: zone
  entity_id: device_tracker.paulus
  zone:
    - zone.home
    - zone.work
```

### URL

https://www.home-assistant.io/docs/scripts/conditions/#zone-condition

### Version

2023.5.4

### Additional information

state needs to be changed to zone
