### ISSUE TITLE
Error in documentation of Recorder?

### ISSUE THREAD

**Issue by tuxick** [home-assistant/home-assistant.github.io#27567]
### Feedback

I'm getting error "Message malformed: extra keys not allowed @ data['action'][0]['target']['entity_globs']" 
following **Example automation to remove data rows for specific entities**:
 
```
description: "Purge noise"
mode: single
trigger:
  - platform: time
    at: "01:11:00"
condition: []
action:
  - service: recorder.purge_entities
    data:
      keep_days: 28
    target:
      entity_globs: sensor.fritz*
```
Looks like the "target:" line should not be there?

### URL

https://www.home-assistant.io/integrations/recorder/

### Version

2023.5.4
