### ISSUE TITLE
The repeat syntax to determine how many times you want to clean is incorrect?

### ISSUE THREAD

**Issue by mikenhu** [home-assistant/home-assistant.github.io#27714]
### Feedback

I was making a script for cleaning separate rooms and I notice the param for repeating was not working.
Here is the current example in documentation
```
service: vacuum.send_command
data:
  command: app_segment_clean
  params:
    - segments:
        - 22
        - 23
    - repeats: 1
target:
  entity_id: vacuum.s7_roborock
```
I tried with folowing syntax and it works wonder.

```
service: vacuum.send_command
data:
  command: app_segment_clean
  params:
    - segments:
        - 22
        - 23
      repeat: 2
target:
  entity_id: vacuum.s7_roborock
```

### URL

https://www.home-assistant.io/integrations/roborock/

### Version

2023.6.0
