### ISSUE TITLE
New update issues: Command Line YAML configuration has moved

### ISSUE THREAD

**Issue by haze1986** [home-assistant/home-assistant.github.io#27747]
### Feedback

Understood the documentation to shift switch and sensors to command_line.yaml. However, what about existing switches created based on other platforms?

    - platform: broadlink
      mac: xx:xx:xx:xx:xx
      switches:
        name: MBR AC
        command_on: JgBM***************
        command_off: JgBM***************

Also

    - platform: wake_on_lan
      mac: xx:xx:xx:xx:xx

Seems like a lot of recoding required to set up the new integrated config. Any recommendations to do this?

### URL

https://www.home-assistant.io/integrations/command_line/

### Version

2023.6.1

**Comment by gjohansson-ST** [comment]
We use github to track issues but you have more like a generic question on how to type your config.

anyway if you have
```yaml
sensor:
  - platform: command_line
    commend: echo 1
```
that should now become 
```yaml
command_line:
  - sensor:
      command: echo 1
```
The rest you have below `sensor:` should probably stay as it is unless it's also changed in the release.
Will now close this.
