### ISSUE TITLE
Examples required with more than one entity definition

### ISSUE THREAD

**Issue by kaizersoje** [home-assistant/home-assistant.github.io#27771]
### Feedback

The examples listed do not show when more than one command line sensor, binary sensor etc. entities need to be defined.

I was trying to define the sensors similar to how `template` sensors are defined [here](https://www.home-assistant.io/integrations/template/#state-based-sensor-changing-the-unit-of-measurement-of-another-sensor)

```yaml
template:
  - sensor:
      - name: "Transmission Down Speed"
        unit_of_measurement: "kB/s"
        state: "{{ states('sensor.transmission_down_speed')|float * 1024 }}"
        availability: "{{ is_number(states('sensor.transmission_down_speed')) }}"

      - name: "Transmission Up Speed"
        unit_of_measurement: "kB/s"
        state: "{{ states('sensor.transmission_up_speed')|float * 1024 }}"
        availability: "{{ is_number(states('sensor.transmission_up_speed')) }}"
```

Another suggestion is to keep the definition method consistent across these core integrations.

### URL

https://www.home-assistant.io/integrations/command_line/

### Version

2023.6.1
