### ISSUE TITLE
How do I start a clean cycle?

### ISSUE THREAD

**Issue by mkanet** [home-assistant/home-assistant.github.io#27890]
### Feedback

How do I start a clean cycle?  I couldnt find it in the documentation.

I know that it is possible to do this with something like
https://github.com/natekspencer/pylitterbot
`await robot.start_cleaning()`

However, I couldn't fine the equivalent service to call for.the HA Litter-Robot Integration. 

### URL

https://www.home-assistant.io/integrations/litterrobot/

### Version

2023.6.2

**Comment by tkdrob** [comment]
Open device in the UI. Click on Litter box. There should be a play symbol. It uses `vacuum` as the service call domain to be technical. Does litter box description not show up in the documentation? You may find better support in the community forums.

**Comment by mkanet** [comment]
> Open device in the UI. Click on Litter box. There should be a play symbol. It uses `vacuum` as the service call domain to be technical. Does litter box description not show up in the documentation? You may find better support in the community forums.

Thanks.  Yes, I know how to access the play button in the UI.  However, I couldn't find an example in the documentation to create a script to start a clean cycle.  I would like to add this capability to a HA card.

**Comment by mkanet** [comment]
Below, is the closest I could get without having any examples:

```
alias: Start Litter-Robot clean cycle
sequence:
  - service: null
    data: {}
  - device_id: b3b9ef3e8a715fe547b2a57f5b30fdb2
    domain: vacuum
    entity_id: vacuum.litter_robot_litter_box
    type: clean
mode: single
```

**Comment by mkanet** [comment]
@tkdrob I was able to figure it out on my own:

This is what I used:

```yaml
alias: Start Litter-Robot clean cycle
sequence:
  - device_id: b3b9ef3e8a715fe547b2a57f5b30fdb2
    domain: vacuum
    entity_id: vacuum.litter_robot_litter_box
    type: clean
mode: single
```
