### ISSUE TITLE
HP ILO component docs example value_template not visible

### ISSUE THREAD

**Issue by Juggels** [home-assistant/home-assistant.github.io#2791]
In the _Example_ section of the [HP ILO component docs](https://github.com/home-assistant/home-assistant.github.io/blob/current/source/_components/sensor.hp_ilo.markdown), there are two examples specified with `value_template`. 

In the [end result](https://home-assistant.io/components/sensor.hp_ilo/) these example values are not visible, causing anyone to copy this example to see the entire json dump coming from the server.

**Actual:**
```yaml
sensor:
  - platform: hp_ilo
    host: IP_ADDRESS or HOSTNAME
    username: USERNAME
    password: PASSWORD
    monitored_variables:
      - name: CPU fanspeed
        sensor_type: server_health
        unit_of_measurement: '%'
        value_template: ''
      - name: Inlet temperature
        sensor_type: server_health
        unit_of_measurement: '°C'
        value_template: ''
      - name: Server Health
        sensor_type: server_health
```

**Expected result:**
```yaml
sensor:
  - platform: hp_ilo
    host: IP_ADDRESS or HOSTNAME
    username: USERNAME
    password: PASSWORD
    monitored_variables:
      - name: CPU fanspeed
        sensor_type: server_health
        unit_of_measurement: '%'
        value_template: '{{ ilo_data.fans["Fan 1"].speed[0] }}'
      - name: Inlet temperature
        sensor_type: server_health
        unit_of_measurement: '°C'
        value_template: '{{ ilo_data.temperature["01-Inlet Ambient"].currentreading[0] }}'
      - name: Server Health
        sensor_type: server_health
```
