### ISSUE TITLE
Missing functionality in counter.set_value, or Missing Documentation

### ISSUE THREAD

**Issue by ape-ck** [home-assistant/home-assistant.github.io#27946]
### Feedback

through searching on web and looking through this documentation I don't see a clear way to migrate from counter.configure to counter.set_value. I currently use it to change the step value, and fire an event.

```
alias: Add 3 steps
sequence:
  - service: counter.configure
    data:
      step: 3
    target:
      entity_id:
        - counter.counter_1
        - counter.counter_2
  - service: counter.increment
    data: {}
    target:
      entity_id:
        - counter.counter_1
        - counter.counter_2
```

All I see is a clear way to set the value of the counter. 

### URL

https://www.home-assistant.io/integrations/counter/

### Version

2023.6.2
