### ISSUE TITLE
Some sensro propierties are not working

### ISSUE THREAD

**Issue by carlos-48** [home-assistant/home-assistant.github.io#27978]
### Feedback

I have configured a Comand Line Sensor to get my water consumption. I have defined the `device_class`,  `statee_class` and  `unit_of_measurement` Propierties, but it seems only `unit_of_measurement` is working as I can see in the Developer Tools.
I'm also trying to use `json_attributes` but it also seems not to be working.

### My config
```
  - sensor:
      name: "testing Aguas de Valencia"
      command: |-
        login_data='login=XXXXXXX&pass=XXXXXXX&remember=true&suministro='; url='https://www.aguasdevalencia.es/VirtualOffice';\
        dates='start={% set lastweek =  now() - timedelta( days = 7 ) %}{{ lastweek.strftime('%d') }}%2F{{ lastweek.strftime('%m') }}%2F{{ lastweek.strftime('%Y') }}&end={{ now().strftime('%d') }}%2F{{ now().strftime('%m') }}%2F{{ now().strftime('%Y') }}'
        c=$(curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' -d $login_data -ksc - $url/action_Login -o /dev/null);\
        echo "${c}" | curl -ksb - $url/Secure/action_getDatosLecturaHorariaEntreFechas?$dates
      command_timeout: 15
      scan_interval: 14400
      unique_id: testing_aguas_de_valencia
      unit_of_measurement: "m³"
      state_class: total
      device_class: water
      value_template: "{{ value_json['table'][-1:][0].Lectura | replace (',', '.') | float + value_json['table'][-1:][0].Consumo | float /1000 }}"
      json_attributes:
        - table.[-1:][0].FechaString
```

### The curl XML Response (shortened)
```
{
    "result": true,
    "data": {
        "labels": [   
            "26/06 00:00",
            "26/06 01:00",
            "26/06 02:00",
            "26/06 03:00",
            "26/06 04:00",
            "26/06 05:00",
            "26/06 06:00",
            "26/06 07:00"
        ],
        "datasets": [
            {
                "label": "Consumo litros",
                "data": [
                    {
                        "title": "117,547",
                        "y": 0
                    },
                    {
                        "title": "117,547",
                        "y": 1
                    },
                    {
                        "title": "117,548",
                        "y": 0
                    },
                    {
                        "title": "117,548",
                        "y": 8
                    },
                    {
                        "title": "117,556",
                        "y": 0
                    },
                    {
                        "title": "117,556",
                        "y": 0
                    },
                    {
                        "title": "117,556",
                        "y": 0
                    },
                    {
                        "title": "117,556",
                        "y": 0
                    }
                ]
            },
            {
                "label": "Lectura m3",
                "data": null
            }
        ]
    },
    "table": [
        {
            "Fecha": "\/Date(1687730400000)\/",
            "FechaString": "\u003cspan style=\u0027display:none\u0027\u003e202306260000 - \u003c/span\u003e26/06/2023 0:00:00",
            "FechaDesde": null,
            "FechaHasta": null,
            "Periodo": null,
            "Consumo": "0",
            "TipoLectura": null,
            "Observacion": "26/06 00:00",
            "Lectura": "117,547"
        },
        {
            "Fecha": "\/Date(1687734000000)\/",
            "FechaString": "\u003cspan style=\u0027display:none\u0027\u003e202306260100 - \u003c/span\u003e26/06/2023 1:00:00",
            "FechaDesde": null,
            "FechaHasta": null,
            "Periodo": null,
            "Consumo": "1",
            "TipoLectura": null,
            "Observacion": "26/06 01:00",
            "Lectura": "117,547"
        },
        {
            "Fecha": "\/Date(1687737600000)\/",
            "FechaString": "\u003cspan style=\u0027display:none\u0027\u003e202306260200 - \u003c/span\u003e26/06/2023 2:00:00",
            "FechaDesde": null,
            "FechaHasta": null,
            "Periodo": null,
            "Consumo": "0",
            "TipoLectura": null,
            "Observacion": "26/06 02:00",
            "Lectura": "117,548"
        },
        {
            "Fecha": "\/Date(1687741200000)\/",
            "FechaString": "\u003cspan style=\u0027display:none\u0027\u003e202306260300 - \u003c/span\u003e26/06/2023 3:00:00",
            "FechaDesde": null,
            "FechaHasta": null,
            "Periodo": null,
            "Consumo": "8",
            "TipoLectura": null,
            "Observacion": "26/06 03:00",
            "Lectura": "117,548"
        },
        {
            "Fecha": "\/Date(1687744800000)\/",
            "FechaString": "\u003cspan style=\u0027display:none\u0027\u003e202306260400 - \u003c/span\u003e26/06/2023 4:00:00",
            "FechaDesde": null,
            "FechaHasta": null,
            "Periodo": null,
            "Consumo": "0",
            "TipoLectura": null,
            "Observacion": "26/06 04:00",
            "Lectura": "117,556"
        },
        {
            "Fecha": "\/Date(1687748400000)\/",
            "FechaString": "\u003cspan style=\u0027display:none\u0027\u003e202306260500 - \u003c/span\u003e26/06/2023 5:00:00",
            "FechaDesde": null,
            "FechaHasta": null,
            "Periodo": null,
            "Consumo": "0",
            "TipoLectura": null,
            "Observacion": "26/06 05:00",
            "Lectura": "117,556"
        },
        {
            "Fecha": "\/Date(1687752000000)\/",
            "FechaString": "\u003cspan style=\u0027display:none\u0027\u003e202306260600 - \u003c/span\u003e26/06/2023 6:00:00",
            "FechaDesde": null,
            "FechaHasta": null,
            "Periodo": null,
            "Consumo": "0",
            "TipoLectura": null,
            "Observacion": "26/06 06:00",
            "Lectura": "117,556"
        },
        {
            "Fecha": "\/Date(1687755600000)\/",
            "FechaString": "\u003cspan style=\u0027display:none\u0027\u003e202306260700 - \u003c/span\u003e26/06/2023 7:00:00",
            "FechaDesde": null,
            "FechaHasta": null,
            "Periodo": null,
            "Consumo": "10",
            "TipoLectura": null,
            "Observacion": "26/06 07:00",
            "Lectura": "117,556"
        }
    ],
    "alarmas": ""
}
```

### What I see in DevTools
![image](https://github.com/home-assistant/home-assistant.io/assets/63410909/4bdc58c1-b737-49da-993e-d75b5d900d85)

### URL

https://www.home-assistant.io/integrations/command_line/

### Version

2023.6.3
