### ISSUE TITLE
switch.[instance]_led_device could be light.[instance]_led_device

### ISSUE THREAD

**Issue by Buraqe** [home-assistant/home-assistant.github.io#28169]
### Feedback

After change in version 23.7, it is not possible to directly control brightness of ambilight. To do it, you need to turn on switch, by switch.[instance]_led_device, then turn light entity, adjust brightness and then turn off light entity. It would be great, if switch.[instance]_led_device would be light entity as well, to allow direct brightness adjustment. 

### URL

https://www.home-assistant.io/integrations/hyperion/

### Version

2023.7.1

**Comment by dermotduffy** [comment]
Perhaps I'm missing something: why can you not exclusively use the light entity? Why do you need the led switch at all?

Adding @Sab44 for context too.

**Comment by Buraqe** [comment]
> Perhaps I'm missing something: why can you not exclusively use the light entity? Why do you need the led switch at all?
> 
> Adding @Sab44 for context too.

My primary usage of hyperion is to ambilight based on USB capture device.
When I turn on light entity, leds are not turned on at all. I have to turn switch.[instance]_led_device on, to turn leds on. In this case, when I turn switch on, everything is working, because USB capture is primary source for led. Problem is, that I cannot dimm brightness. As I wrote before, to adjust brightness, I have to turn on light entity (with solid effect for example), adjust brightness, then turn off light to enable USB capture again.

In prev version, USB capture device was in effect list of light entity, in my opinion, it was better.

**Comment by Sab44** [comment]
@Buraqe I understand what you're saying. It is a valid point and once I have a working setup again I might try myself on a global brightness control that is independent of any Hyperion light source.

For now, I suggest you create 2 automations exactly as outlined in the [documentation ](https://www.home-assistant.io/integrations/hyperion/) at the very bottom to couple LED device switch to the light entity. Make sure, the priority configured in HA has a higher value than the USB priority (e.g. USB priority 120, HA priority 380). Then you should be able use the light entity to control on/off as well as brightness.

**Comment by austwhite** [comment]
Following on from @Sab44 comment. The light entity will not control on/off.  When you turn Off the light entity, it just turns Home Assistant's effect off in Hyperion.  The LED Output remains on.   This means if Hyperion has a lower priority effect running, that will resume when Home Assistant turns off it's effect.   If using USB Capture, you need at minimum to use two entities to control the LED's.    The Light entity to set brightness, the USB Capture entity to turn USB Capture on and off.   Then you have to remember to turn off the light entity to allow the usb capture entity to take over.
I got around this by writing an automation that acts as a lock out of sorts .    The automation I use turns off the USB Capture when the light entity is enabled, and turns off the light entity when the USB Capture is enabled.
I also added the LED Output entity to my dashboard to use as a definitive Off function for Hyperion LED's.  by having this LED Output enabled in Home Assistant, it also allows me to use an effect in Hyperion outside of Home Assistant, which some people do and allow a Home Assistant automation to turn off Hyperion LED Output if needed.
I don't know if it helps, but I can include my automation code and a screen capture of what I put on my dashboard.   I used the switch as x funciton to remap the LED Output as a light, just to keep it in the correct domain in Home Assistant for when I use something like turn all lights off.
I renamed the LED Output to "Ambilight"  USB Capture to "TV Capture" and the light entity to "Ambilight Effects"
![image](https://github.com/home-assistant/home-assistant.io/assets/55521360/0f6fa49b-6dff-4386-89c3-9fb24e1c00c2)

Here is the lockout automation I used that means USB Capture and the light entity can not be on at the same time:
I made it in the UI, so the YAML may be able to be simplified further, but this worked for me.  Note that I added a function when the LED Output is turned off, it will also turn off both USB Capture and the Light Entity.   I wanted to do, but it is not necessary, so you could take that part out of it.

```
alias: "Switch: Ambilight Effects or TV Capture"
description: ""
trigger:
  - platform: state
    entity_id:
      - light.livingroom_ambilight_effects
    id: Ambilight Effects On
    to: "on"
  - platform: state
    entity_id:
      - switch.livingroom_ambilight_component_usb_capture
    to: "on"
    id: TV Capture
  - platform: state
    entity_id:
      - light.livingroom_ambilight
    to: "off"
    id: Ambilight Off
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Ambilight Off
        sequence:
          - service: switch.turn_off
            data: {}
            target:
              entity_id:
                - switch.livingroom_ambilight_component_usb_capture
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.livingroom_ambilight_effects
      - conditions:
          - condition: trigger
            id:
              - TV Capture
              - Ambilight Effects On
        sequence:
          - choose:
              - conditions:
                  - condition: trigger
                    id:
                      - Ambilight Effects On
                sequence:
                  - service: switch.turn_off
                    data: {}
                    target:
                      entity_id: switch.livingroom_ambilight_component_usb_capture
              - conditions:
                  - condition: trigger
                    id:
                      - TV Capture
                sequence:
                  - service: light.turn_off
                    data: {}
                    target:
                      entity_id: light.livingroom_ambilight_effects
mode: single
```
