### ISSUE TITLE
type: call-service not mentioned?

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/home-assistant.github.io#28318]
### Feedback

Not sure if I am missing the obvious, but checking this documentation for some other [special row elements](https://www.home-assistant.io/dashboards/entities/#special-row-elements), I noticed the `type: call_service` is not mentioned?

```
        - type: call-service
          icon: mdi:power
          name: Kist
          action_name: Toggle licht
          service: light.toggle
          service_data:
            entity_id: light.kist
```

showing as:

<img width="382" alt="Scherm­afbeelding 2023-07-25 om 11 55 54" src="https://github.com/home-assistant/home-assistant.io/assets/33354141/8ac5d455-1532-4e31-954c-67949ccfbd9f">

feel this should be added to the special row elements as separate type.

### URL

https://www.home-assistant.io/dashboards/entities/

### Version

2023.7.3
