### ISSUE TITLE
Roborock documentation edit suggestion

### ISSUE THREAD

**Issue by devitus** [home-assistant/home-assistant.github.io#28830]
### Feedback

Hi,

I've noticed that the example command at the bottom of the documentation doesn't work in the suggested format:

```
service: vacuum.send_command
data:
  command: app_segment_clean
  params:
    - segments:
        - 22
        - 23
    repeat: 2
target:
  entity_id: vacuum.s7_roborock
```

After some testing and finding a [github comment](https://github.com/home-assistant/core/issues/92817#issuecomment-1538767237) elsewhere, I can confirm the `- segments:` should be removed like so:

```
service: vacuum.send_command
data:
  command: app_segment_clean
  params:
    - 22
    - 23
  repeat: 2
target:
  entity_id: vacuum.s7_roborock
```

Thanks a lot guys!

Best,

Vitaly

### URL

https://www.home-assistant.io/integrations/roborock/

### Version

2023.9.0
