### ISSUE TITLE
Multiple Power consumption sensors

### ISSUE THREAD

**Issue by wobeco** [home-assistant/home-assistant.github.io#28855]
### Feedback

How is the syntax if multiple power consumption sensors are to be obeyed?

### URL

https://www.home-assistant.io/integrations/edimax/

### Version

2023.8.4

### Additional information

It doesn‘t work with one single sensor, either 8-(

**Comment by reedy** [comment]
>It doesn‘t work with one single sensor, either 8-(

What doesn't work?

>How is the syntax if multiple power consumption sensors are to be obeyed?

```yaml
switch:
  - platform: edimax
    host: 192.168.1.32
    name: "Switch 1"
  - platform: edimax
    host: 192.168.1.33
    name: "Switch 2"
```
