### ISSUE TITLE
Updated needed on example configurations

### ISSUE THREAD

**Issue by VicL001** [home-assistant/home-assistant.github.io#28856]
### Feedback

The examples still show the old configuration format, which generates errors in current HA versions:
```yaml
mqtt:
  - sensor:
      state_topic: "home/bedroom/temperature"
```

This should be rewritten as:
```yaml
mqtt:
  sensor:
    - state_topic: "home/bedroom/temperature"
```

### URL

https://www.home-assistant.io/integrations/sensor.mqtt/

### Version

2023.9.1
