### ISSUE TITLE
Provide an example of configuring the sensor

### ISSUE THREAD

**Issue by jaspervanm** [home-assistant/home-assistant.github.io#28883]
### Feedback

For people who are not used to adding integrations via `configuration.yaml`, I think it would be helpful to provide an example to show how one can specify the configuration parameters.

For example, add:

```
# Example configuration.yaml entry, to create a sensor named "Between one and four" that generates a number between one and four
sensor:
  - platform: random
    name: Between one and four
    minimum: 1
    maximum: 4
```

### URL

https://www.home-assistant.io/integrations/random/

### Version

2023.9.1
