### ISSUE TITLE
HA generates automation yaml with undocumented elements

### ISSUE THREAD

**Issue by rvandegrift** [home-assistant/home-assistant.github.io#29010]
### Feedback

I often create automations in the visual editor and then copy the yaml for final tweaks.  Today, HA 2023.9.1 generated yaml that includes surprising elements.  Here is what HA generated:
```yaml
description: "Turn up heat in the morning"
mode: single
trigger:
  - platform: time
    at: "08:00:00"
condition:
  - condition: device
    device_id: 4f7a63a5ea9c9e3e21a45f9b7ea78bb4
    domain: climate
    entity_id: c36da393945e449ab6d080509601ac13
    type: is_hvac_mode
    hvac_mode: heat
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
action:
  - device_id: 4f7a63a5ea9c9e3e21a45f9b7ea78bb4
    domain: select
    entity_id: 751f1769cfb1822bdaa4ba1c474d5a3b
    type: select_option
    option: occupied
```

A few things here are new to me, so I tried to look them up i nthe docs.  Here are the things I couldn't find:
1. `device_id`, `domain` is not mentioned in Actions [1], Conditions [2] or Triggers [3] docs.
2. `entity_id` looks like a hash instead of something like `climate.office_thermostat`.
3. `is_hvac_mode` is not mentioned in Climate [4] docs.

Did I miss things, or were some major changes omitted from the docs?

[1] - https://www.home-assistant.io/docs/automation/action/
[2] - https://www.home-assistant.io/docs/automation/trigger/
[3] - https://www.home-assistant.io/docs/scripts/conditions/
[4] - https://www.home-assistant.io/integrations/climate/

### URL

https://www.home-assistant.io/docs/scripts/conditions/

### Version

2023.9.3
