### ISSUE TITLE
Adding more than one camera

### ISSUE THREAD

**Issue by gijzo** [home-assistant/home-assistant.github.io#29028]
### Feedback

Hi,

How do i add more than one camera without creating a duplicate error?

### URL

https://www.home-assistant.io/integrations/hikvision/

### Version

2023.9.3

**Comment by frenck** [comment]
It is a list in YAML, from the docs:

```YAML
binary_sensor:
  - platform: hikvision
    host: IP_ADDRESS
    username: user
    password: pass
```

You can add as many to the list as you like...

```YAML
binary_sensor:
  - platform: hikvision
    host: IP_ADDRESS
    username: user
    password: pass
  - platform: hikvision
    host: IP_ADDRESS
    username: user
    password: pass
```

../Frenck
