### ISSUE TITLE
Integrating your electricity grid: manual integration

### ISSUE THREAD

**Issue by pohly** [home-assistant/home-assistant.github.io#29386]
### Feedback

https://www.home-assistant.io/docs/energy/electricity-grid/#manual-integration says:
> Make sure you set and provide the device_class, state_class, and unit_of_measurement for those sensors.

But what should it be set *to*?

`unit_of_measurement` is obvious, but not `device_class` and `state_class`.

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2023.10.3

### Additional information

I am using the following in my `configuration.yaml` to read values from a Sonnenbatterie 10:
```yaml
# https://www.matusz.ch/blog/2022/07/10/sonnenbatterie-in-homeassistant/
rest:
  - resource: http://sonnenbatterie/api/v2/status
    method: GET
    headers:
      User-Agent: Home Assistant
      Content-Type: application/json
    scan_interval: 10
    timeout: 15
    sensor:
      - name: Solar Power
        value_template: '{{ value_json.Production_W }}'
        unit_of_measurement: W
        device_class: power
      - name: Battery USOC
        value_template: '{{ value_json.USOC }}'
        unit_of_measurement: '%'
        device_class: battery
      - name: Battery RSOC
        value_template: '{{ value_json.RSOC }}'
        unit_of_measurement: '%'
        device_class: battery
      - name: Battery Consumption Production Diff
        value_template: '{{ value_json.Pac_total_W }}'
        unit_of_measurement: W
        device_class: power
      - name: House Consumption
        value_template: '{{ value_json.Consumption_W }}'
        unit_of_measurement: W
        device_class: power
      - name: Battery SoC Energy
        value_template: '{{ value_json.RemainingCapacity_Wh }}'
        unit_of_measurement: Wh
        device_class: energy
```

`state_class` is missing. After some further digging, I found https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics. Further up, that page also explains valid values. Perhaps link `device_class` to https://developers.home-assistant.io/docs/core/entity/sensor/#available-device-classes and `state_class` to https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes?
