### ISSUE TITLE
Tested on Monoblock heatpump

### ISSUE THREAD

**Issue by Timieh** [home-assistant/home-assistant.github.io#29423]
### Feedback

Integration tested succesfully with Wolf CHA-07 Heat pump system. 
the Wolf CWL 400 Ventilation box is represent in Smartset portal but not in the plugin/entities. 
All translations are to German. 

Some units are not correctly displayed (not sure if this is wrong on my side, but it shows from the first time already). 
For example the flow status of the internal pump  is a attribute/text instead of a value so there is no line graph in history plot but box graph.

===Fix===
sensor.heizkreisdurchfluss
Change code to:
_parameter_id: 27002800001
value_id: 27002800001
parent: Heizung
friendly_name: Heizkreisdurchfluss
**unit_of_measurement: "L/min"
icon: "mdi:water**"_

### URL

https://www.home-assistant.io/integrations/wolflink/

### Version

2023.10.3

**Comment by naund** [comment]
Here are some more wrong assigned units:

```
homeassistant:
  customize:
    sensor.leistungsaufnahme_wp_ehz:
      state_class: measurement
      device_class: power
      unit_of_measurement: "kW"
    sensor.aktuelle_sekundarleistung:
      state_class: measurement
      device_class: power
      unit_of_measurement: "kW"
    sensor.energiemenge_hz:
      state_class: total_increasing
      device_class: energy
      unit_of_measurement: "kWh"
    sensor.heizkreisdurchfluss:
      state_class: measurement
      device_class: volume_flow_rate
      unit_of_measurement: "l/min"
    sensor.verdichterfrequenz:
      state_class: measurement
      device_class: frequency
      unit_of_measurement: "Hz"
    sensor.sollwertkorrektur:
      state_class: measurement
      device_class: temperature
      unit_of_measurement: "K"
```

**Comment by Timieh** [comment]
Thanks @naund in the meantime I use this complete list (with wolf ventilation as well). 
```

  customize:
    sensor.leistungsaufnahme_wp_ehz:
      state_class: measurement
      unit_of_measurement: "kW"
      device_class: power
    sensor.luftdurchsatz_zuluft:
      state_class: measurement
      device_class: volume_flow_rate
      unit_of_measurement: "m3/h"
    sensor.luftdurchsatz_abluft:
      state_class: measurement
      device_class: volume_flow_rate
      unit_of_measurement: "m3/h"
    sensor.verdichterfrequenz:
      state_class: measurement
      device_class: frequency
      unit_of_measurement: "Hz"
    sensor.aktuelle_sekundarleistung:
      state_class: measurement
      device_class: power
      unit_of_measurement: "kW"
    sensor.energiemenge_hz:
      state_class: total_increasing
      device_class: energy
      unit_of_measurement: "kWh"
    sensor.heizkreisdurchfluss:
      state_class: measurement
      device_class: volume_flow_rate
      unit_of_measurement: "l/min"
```
