### ISSUE TITLE
I cannot make examples in MQTT Light to work

### ISSUE THREAD

**Issue by dredkin** [home-assistant/home-assistant.github.io#29440]
### Feedback

I am trying to figure out how to configure mqtt lights.
SO I went to docs and copy-pasted the example to my configuration.yaml:

```yaml
...
mqtt:
  - light:
      name: "Office Light RGB"
      state_topic: "office/rgb1/light/status"
      command_topic: "office/rgb1/light/switch"
      brightness_state_topic: "office/rgb1/brightness/status"
      brightness_command_topic: "office/rgb1/brightness/set"
      rgb_state_topic: "office/rgb1/rgb/status"
      rgb_command_topic: "office/rgb1/rgb/set"
      state_value_template: "{{ value_json.state }}"
      brightness_value_template: "{{ value_json.brightness }}"
      rgb_value_template: "{{ value_json.rgb | join(',') }}"
      qos: 0
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false
...
```
I try to reload config and get ERROR:

Cannot quick reload all YAML configurations because the configuration is not valid: Invalid config for [mqtt]: expected dictionary for dictionary value @ data['mqtt']. Got [{'light': {'name': 'Office Light RGB', 'state_topic': 'office/rgb1/light/status', 'command_topic': 'office/rgb1/light/switch', 'brightness_state_topic': 'office/rgb1/brightness/status', 'brightness_command_topic': 'office/rgb1/brightness/set', 'rgb_state_topic': 'office/rgb1/rgb/status', 'rgb_command_topic': 'office/rgb1/rgb/set', 'state_value_template': '{{ value_json.state }}', 'brightness_value_template': '{{ value_json.brightness }}', 'rgb_value_template': "{{ value_json.rgb | join(',') .... (See /home/homeassistant/.homeassistant/configuration.yaml, line 28). 

What am I doing wrong?

### URL

https://www.home-assistant.io/integrations/light.mqtt/

### Version

2023.7.3
