### ISSUE TITLE
Add multiple stations

### ISSUE THREAD

**Issue by jakal1989** [home-assistant/home-assistant.github.io#29553]
### Feedback

I can't add multiple stations. If I add theme like in the code, only the first station will show up in home assistant. Is there a way to add more than one station?

```
sensor:
  - platform: swiss_hydrological_data
    station: 2179 # Sense
    monitored_conditions:
      - temperature
      - level
      - discharge
  - platform: swiss_hydrological_data
    station: 2215 # Saane
    monitored_conditions:
      - temperature
      - level
      - discharge
  - platform: swiss_hydrological_data
    station: 2135 # Aare
    monitored_conditions:
      - temperature
      - level
      - discharge
 ```

### URL

https://www.home-assistant.io/integrations/swiss_hydrological_data/

### Version

2023.10.5

### Additional information

Home Assistant 2023.10.5
Supervisor 2023.10.0
Operating System 11.0
Frontend 20231005.0 - latest
