### ISSUE TITLE
hddtemp for multiple hard disks

### ISSUE THREAD

**Issue by kukki** [home-assistant/home-assistant.github.io#2959]
If I have four hard disks, using `platform: hddtemp` can only get me the temperature of the first one drive. Are there any options for hddtemp to get temperatures of all hard disks? I have started the daemon of hddtemp in this way: 
```bash
hddtemp -d /dev/sda /dev/sdb /dev/sdc /dev/sdd /dev/sde
```
```bash
# curl http://localhost:7634
curl: (56) Recv failure: Connection reset by peer
|/dev/sda|Hitachi HTS545050B9SA00|37|C||/dev/sdb|TOSHIBA DT01ACA050|SLP|*||/dev/sdc|GLOWAY VAL64GS2-mSATA|32|C||/dev/sdd|Hitachi HTS545050B9SA00|32|C||/dev/sde|ST3500320SV|41|C|
#
```

**Comment by fabaff** [comment]
No, the [`hddtemp`](https://home-assistant.io/components/sensor.hddtemp/) sensor supports only one disk.

Work-around using different port for the disks and create multiple sensors.

```bash
$ hddtemp -dF -p 1234 /dev/sdb
$ hddtemp -dF -p 1235 /dev/sdc
```
and

```yaml
sensor:
  - platform: hddtemp
    name: /dev/sdb
    port: 1234
  - platform: hddtemp
    name: /dev/sdc
    port: 1235
```
