### ISSUE TITLE
Note about network settings

### ISSUE THREAD

**Issue by tuxick** [home-assistant/home-assistant.github.io#29603]
### Feedback

I found i needed to add IP of the ecowitt gateway to **trusted_proxies** like this:
```
http:
  use_x_forwarded_for: true
  trusted_proxies:
   - 127.0.0.1
   - ::1
   - 192.168.178.36

```
where nginx on localhost takes care of https proxying. Not sure if this is the ideal way but it works for me.
Not adding ip leads to error:
`aiohttp.http_exceptions.BadStatusLine: 400, message:
  Bad status line "Invalid method encountered`

### URL

https://www.home-assistant.io/integrations/ecowitt/

### Version

2023.10.5
