### ISSUE TITLE
Failed to call service remote/send_command. Service not found.

### ISSUE THREAD

**Issue by RaNo99** [home-assistant/home-assistant.github.io#29629]
### Feedback

Hi All. In my HA instance, I an unable to configure what is described in https://www.home-assistant.io/integrations/samsungtv#remote . It does provide the example:

```
service: remote.send_command
target:
  device_id: 72953f9b4c9863e28ddd52c87dcebe05
data:
  command:
    - KEY_MENU
    - KEY_RIGHT
    - KEY_UP
    - KEY_UP
    - KEY_ENTER
```

...but does not say where to put the YAML.

And wherever and however I try to leverage the `remote.send_command`, I'm getting the following error: `Failed to call service remote/send_command. Service not found.`

Any pointers on how to configure remote.send_command with the samsungtv integration end-to-end are welcome!

### URL

https://www.home-assistant.io/integrations/samsungtv/

### Version

2023.10.5
