### ISSUE TITLE
Navigate to a list

### ISSUE THREAD

**Issue by Waterbrain** [home-assistant/home-assistant.github.io#29795]
### Feedback

Hello:

I find this a very interesting add-on.

I personally have the shopping list items organized by store.

This allows me along with the zones of each store to automate this:

```
alias: Shopping list store XXX
description: ""
trigger:
  - platform: zone
    entity_id: person.jhon_doe
    zone: zone.aldi
    event: enter
condition: []
action:
  - service: notify.mobile_app_iphone_jhon_doe
    data:
      message: Here is your shopping list
      data:
        actions:
          - action: URI
            title: View shopping list
            uri: /shopping-list
mode: single
```
I wonder if in the uri you can navigate directly to the list of that store?

### URL

https://www.home-assistant.io/integrations/todo/

### Version

2023.11.2
