### ISSUE TITLE
Incorrect yaml

### ISSUE THREAD

**Issue by Ayuus** [home-assistant/home-assistant.github.io#29931]
### Feedback

Does not work:
```
service: tts.speak
target: tts.example
data:
  media_player_entity_id: media_player.kitchen
  message: "May the force be with you."

```

Does work:
```
service: tts.speak
data:
  entity_id: tts.example
  media_player_entity_id: media_player.kitchen
  message: "May the force be with you."
```

### URL

https://www.home-assistant.io/integrations/tts/

### Version

2023.11.2
