### ISSUE TITLE
Unifi AP

### ISSUE THREAD

**Issue by njaimo** [home-assistant/home-assistant.github.io#29988]
### Feedback

provide configuration.yaml example for the case of multiple APs.  Example given is for the case of only one AP in the network.  For example in my home I have two Unifi APs in the same wireless network to provide good coverage in my house.

### URL

https://www.home-assistant.io/integrations/unifi_direct/

### Version

2023.11.3

**Comment by frenck** [comment]
> provide configuration.yaml example for the case of multiple APs.

The example given is a list, which you can extend with as many as you'd like.

```yaml
# Example configuration.yaml entry
device_tracker:
  - platform: unifi_direct
    host: YOUR_AP_IP_ADDRESS
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
  - platform: unifi_direct
    host: YOUR_AP_IP_ADDRESS
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
  - platform: unifi_direct
    host: YOUR_AP_IP_ADDRESS
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
  - platform: unifi_direct
    host: YOUR_AP_IP_ADDRESS
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
```
