### ISSUE TITLE
Example Action Correct?

### ISSUE THREAD

**Issue by rwelsh09** [home-assistant/home-assistant.github.io#29991]
### Feedback

These look identical to me but one says it should be a jpg and the other a gif

### Example Action: Clip Preview thumbnail (gif) for Android or iOS
Example for cameras that support Clip Previews, but transcoded to an animated gif (Android does not render video notifications).
```
service: notify.mobile_app_android
data:
  message: Doorbell Pressed
  title: Someone pressed the doorbell
  data:
    image: >-
      /api/nest/event_media/{{ trigger.event.data.device_id }}/{{ trigger.event.data.nest_event_id }}/thumbnail
```

### Example Action: Snapshot (jpg) attachment for Android or iOS
Example for cameras that support Snapshot (jpg) on either Android or iOS.
```
service: notify.mobile_app
data:
  message: Doorbell Pressed
  title: Someone pressed the doorbell
  data:
    image: >-
      /api/nest/event_media/{{ trigger.event.data.device_id }}/{{ trigger.event.data.nest_event_id }}/thumbnail
```

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2023.11.3

**Comment by allenporter** [comment]
Yes, it depends on the camera type. See the table in the section prior about which devices support which media types.

**Comment by skewll** [comment]
My nest images show up in config/nest/event_media/{DEVICE_ID}/{EVENT_ID}-{EVENT_TYPE}.jpg

This is the only thing that would work in my case, as the filenames/directory are different then what the Nest integration page suggests, was:

```
alias: Motion in Kitchen Notify Phone
description: ""
trigger:
  - platform: device
    device_id: 11234567890abcdEFgHIjKLMnO
    domain: nest
    type: camera_motion
  - platform: device
    device_id: 11234567890abcdEFgHIjKLMnO
    domain: nest
    type: camera_person
condition: []
action:
  - service: notify.mobile_app_sm_g975u1
    data:
      title: Motion Detected Inside
      message: Motion in Kitchen
      data:
        image: >-
          /api/nest/event_media/{{ trigger.event.data.device_id }}/{{ trigger.event.data.nest_event_id }}-{{ trigger.event.data.type }}.jpg
mode: single
```
It appears the integrations is not working correctly, as I can see that I get random images attached to my notify automation. It appears that the notification is sent before the images exist sometimes. Most of the phone notifications arrive without any image.
