### ISSUE TITLE
Statistics integration - new style

### ISSUE THREAD

**Issue by prog8** [home-assistant/home-assistant.github.io#30146]
### Feedback

There is a new way of preparing configrations of sensors where platforms. How does it apply to statistics platform. Shouldn't documentation be updated here https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/statistics.markdown? For example if we go to https://www.home-assistant.io/integrations/template there is a style 

```
template:
  - sensor:
      - name: "Average temperature"
      ...
```

Shouldn't it work the same also for statistics?

### URL

https://www.home-assistant.io/integrations/statistics/
