### ISSUE TITLE
wake_on_lan not supported in new switch

### ISSUE THREAD

**Issue by Ayo91** [home-assistant/home-assistant.github.io#30210]
### Feedback

The switch entity is deprecated at top level, it must to be inside command_line. However, there is not a new support of wake_on_lan because before was inside switch

### URL

https://www.home-assistant.io/integrations/command_line/

### Version

2023.12.0

**Comment by gjohansson-ST** [comment]
Is your issue about `command_line` or `wake_on_lan` as it's two different integrations?
Maybe you can provide your YAML so we can tell?

**Comment by Ayo91** [comment]
> Is your issue about `command_line` or `wake_on_lan` as it's two different integrations? Maybe you can provide your YAML so we can tell?

Switch integration is deprecated at top level in the new HA version. I have a switch like this:

```
switch:
  - platform: wake_on_lan
    mac: XXXX
    name: name_test
    host: 192.168.1.199
    broadcast_address: 255.255.255.255
    turn_off:
      service: shell_command.turn_off_test  
```

All switches are now inside the command_line integration but in the documentation is not specified how to setup the wake_on_lan switch. Is still with the legacy behavior: https://www.home-assistant.io/integrations/wake_on_lan/
