### ISSUE TITLE
connections example incorrect

### ISSUE THREAD

**Issue by Jatoxo** [home-assistant/home-assistant.github.io#30234]
### Feedback

![image](https://github.com/home-assistant/home-assistant.io/assets/39669932/03212802-96ca-405e-96c7-22c1eedc079d)
The example entry is just a list, but connections expects a list of lists

Invalid config:
```
mqtt:
  - number:
      name: PC Volume
      device:
        "connections": ["mac", "00:00:00:00:00:00"]
```

Valid config:
```
mqtt:
  - number:
      name: PC Volume
      device:
        "connections": [["mac", "00:00:00:00:00:00"]]
```

### URL

https://www.home-assistant.io/integrations/number.mqtt/

### Version

2023.12.1
