### ISSUE TITLE
'Or' condition missing on Conditional card

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/home-assistant.github.io#30296]
### Feedback

while [documentation](https://www.home-assistant.io/dashboards/conditional/)  explicitly states

> Note: if there are multiple conditions there will be treated as an ‘and’ condition. This means that for the card to show, all conditions must be met.

this is no longer congruent with the additional option for an or condition:

![289327325-0057cd4e-afd7-4419-ab9c-d444027aa320](https://github.com/home-assistant/home-assistant.io/assets/33354141/83ef988a-26b9-465f-b4f8-6e8efe1e33ef)

see[ FR ](https://github.com/home-assistant/frontend/discussions/18991#discussioncomment-7809509)

### URL

https://www.home-assistant.io/dashboards/conditional/

### Version

2023.12.1

### Additional information

since there is neither an explanation nor an example, maybe add something like:

```
  - type: conditional
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity: binary_sensor.co_alert
            state: 'on'
          - condition: state
            entity: binary_sensor.rookmelder
            state: 'on'
    card:
```

for the yaml users to be able to copy&paste the structure required for this
