### ISSUE TITLE
Invalid configuration for mqtt switch

### ISSUE THREAD

**Issue by PaulMartinsen** [home-assistant/home-assistant.github.io#30328]
### Feedback

Copying and pasting the simple [mqtt switch example](https://www.home-assistant.io/integrations/switch.mqtt/) into my `configuration.yml` file produces the following error:
`Invalid config for [mqtt]: expected dictionary for dictionary value @ data['mqtt']. Got [{'switch': {'command_topic': 'home/bedroom/switch1/set'}}]. (See /config/configuration.yaml, line 14).`

A mqtt broker is setup using the [mqtt integration](https://www.home-assistant.io/integrations/mqtt).

Configuration file, after pasting the example is:
```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

# Example configuration.yaml entry
mqtt:
  - switch:
      command_topic: "home/bedroom/switch1/set"
      
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
```

### URL

https://www.home-assistant.io/integrations/switch.mqtt/

### Version

2023.12.2

**Comment by PaulMartinsen** [comment]
Should the example be:
```
# Example configuration.yaml entry
mqtt:
   switch:
     - command_topic: "home/bedroom/switch1/set"
```
not
```
# Example configuration.yaml entry
mqtt:
  - switch:
      command_topic: "home/bedroom/switch1/set"
```
