### ISSUE TITLE
"none" preset is not available through the Thermostat card

### ISSUE THREAD

**Issue by EndermanAPM** [home-assistant/home-assistant.github.io#30444]
### Feedback

The preset "none" is not available on the thermostat card, but it is when opening the thermostat modal.
See pic:

![image](https://github.com/home-assistant/home-assistant.io/assets/3709362/e44d3af8-c6d9-4a91-af64-990553e7721f)
![image](https://github.com/home-assistant/home-assistant.io/assets/3709362/9b49595f-53c2-4a0c-a99c-f413a03b03c9)

Not really a big issue since I control the preset with automatons, but I feel like a consistent behavior would be best. Especially for new HA users.

### URL

https://www.home-assistant.io/dashboards/thermostat/

### Version

2023.12.3

**Comment by piitaya** [comment]
What's the yaml configuration of your card?

**Comment by EndermanAPM** [comment]
Ah! I see the problem. My integration changed the way the presets work but the card didn't get updated!

Is there a way to just not declare the presets and the card to grab them all?

```
type: thermostat
entity: climate.vaillant_vsmart_07_0...
features:
  - style: icons
    preset_modes:
      - none
      - away
    type: climate-preset-modes
  - type: climate-hvac-modes
    hvac_modes:
      - auto
      - heat

```
