### ISSUE TITLE
Backup - Old service calls.

### ISSUE THREAD

**Issue by hardrockhodl** [home-assistant/home-assistant.github.io#30569]
### Feedback

Info at https://www.home-assistant.io/integrations/backup/

isnt the latest to use: `service: hassio.backup_full`

and some versions ago it was: `service: hassio.snapshot_fill`

SERVICE [BACKUP.CREATE](https://my.home-assistant.io/redirect/developer_call_service?service=backup.create)
The [backup.create](https://my.home-assistant.io/redirect/developer_call_service?service=backup.create) service can be used to create a backup for your Home Assistant instance.

The service has no additional options or parameters.

Example service call:

`service: backup.create`

Example: Backing up every night at 3:00 AM
This is a YAML example for an automation that initiate a backup every night at 3 AM:

```
automation:
  - alias: "Backup Home Assistant every night at 3 AM"
    trigger:
      platform: time
      at: "03:00:00"
    action:
      alias: "Create backup now"
      service: backup.create
```

### URL

https://www.home-assistant.io/integrations/backup/

### Version

2023.12.4

### Additional information

would be could to write out last working versions.
and the different ways to do it depending on version.
