### ISSUE TITLE
Correction to "Sending messages to Signal to trigger events"

### ISSUE THREAD

**Issue by morikplay** [home-assistant/home-assistant.github.io#30585]
### Feedback

The current example for this section is misleading for 2 reasons:

```
- resource: "http://127.0.0.1:8080/v1/receive/<number>"
  headers:
    Content-Type: application/json
  sensor:
    - name: "Signal message received"
      value_template: "" #this will fetch the message
      json_attributes_path: $[0].envelope
      json_attributes:
        - source #using attributes you can get additional information, in this case, the phone number.
```

1. `value_template` needs a value for json_attributes to work. It can be found on the authors' [original page](https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/signal_messenger.markdown). 
2. Per [Swagger API](https://bbernhard.github.io/signal-cli-rest-api/) definitions, providing `payload` is mandatory for this to work. It is missing in the authors' [original page](https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/signal_messenger.markdown) example as well 

Here's a working example from my testing:

```
  - resource: "http://homeassistant.esco.ghaar:8080/v1/receive/<number>"
    method: GET
    headers:
      Content-Type: application/json
    payload: '{"number": "<number>"}'
    sensor:
      - name: "signal chatbot"
        unique_id: <unique_id>
        value_template: "{{ value_json[0].envelope.dataMessage.message }}"         # this will fetch the msg
        json_attributes_path: $[0].envelope
        json_attributes:
          - source # this is senders' phone number, not the recipient (which is what the chat bot uses)
          - dataMessage #this contains the actual message and other useful information e.g. recipient (esp if group)
```

### URL

https://www.home-assistant.io/integrations/signal_messenger/

### Version

2023.12.4
