### ISSUE TITLE
Templated entities in conditions

### ISSUE THREAD

**Issue by te-hb-whatever** [home-assistant/home-assistant.github.io#30676]
### Feedback

As far as I can see there is nowhere mentioned that the use of templates is somewhat arbitrarily (at least for the user)  restricted. This causes some confusion, i.e.

https://community.home-assistant.io/t/script-variables-to-entity-id-in-conditions/603916

It does not help that the error message is generic and does not provide any hint of what's actually going wrong.

### URL

https://www.home-assistant.io/docs/scripts/conditions/

### Version

2024.1.1

**Comment by frenck** [comment]
I'm not sure what your suggestion is for the documentation improvement.

Could you clarify?

../Frenck

**Comment by te-hb-whatever** [comment]
Example (stripped for brevity):

```
alias: Template Demo
fields:
  AC_Device:
    description: The AC Device ID
  Temperature:
    description: Target Temperature
sequence:
  - if:
      - condition: numeric_state
        entity_id: "{{ Temperature }}"
        above: 25
    then:
      - service: climate.turn_on
        data: {}
        target:
          device_id: "{{ AC_Device }}"
```

produces the error upon save:

(**_Template_** is an entity of type _**input_number**_)

`Message malformed: Entity {{ Temperature }} is neither a valid entity ID nor a valid UUID for dictionary value @ data['sequence'][0]['if'][0]['entity_id']`

So templating works in the **_service_** part but not in the **_if_** part. The error message only gives a vague indication of what went wrong and for the user it is surprising to say the least, that you cannot use template interpolation in the if clause.

I know about the **_template condition_**. This is not the issue. The issue here is that the most straightforward approach fails without a helpful error message. Also this behavior is not documented, at least not to my knowledge.
