### ISSUE TITLE
Entites Card conditional row conditions not the same as Conditional Card conditions

### ISSUE THREAD

**Issue by phipolis** [home-assistant/home-assistant.github.io#30672]
### Feedback

I wanted to toggle a row in a conditional card based on a user condition, which the docs suggest is possible, but that does not appear to be true.

A forum [answer](https://community.home-assistant.io/t/conditional-inside-entities-card/208819/6?u=persimmon) to a similar question says "[conditional entites card row] is not the same as the conditional card", with a screenshot to docs stating it only accepts "a list of entity IDs and matching states". 

The docs changed in #29506, and now the Entities Card documentation for [a conditional row's](https://www.home-assistant.io/dashboards/entities/#conditional) `conditions` key links to the [conditional card](https://www.home-assistant.io/dashboards/conditional/#card-conditions) documentation as reference. However a conditional entities card row appears to still only allow entity IDs. It otherwise throws the error `Required key 'entities.0.conditions.0.entity' is missing`

### URL

https://www.home-assistant.io/dashboards/entities/

### Version

2024.1.1

### Additional information

As a basic example, this works:

```
type: entities
entities:
  - type: conditional
    conditions:
      - entity: light.bookcase
        state: 'on'
    row:
      type: buttons
      entities:
        - entity: light.bookcase
```

However this does not:

```
type: entities
entities:
  - type: conditional
    conditions:
      - condition: "user"
        users:
          - 581fca7fdc014b8b894519cc531f9a04
    row:
      type: buttons
      entities:
        - entity: light.bookcase
```
