### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by CristianSto** [home-assistant/home-assistant.github.io#30745]
### Feedback

for automation:
```yaml
  - alias: "MeteoAlarm Bucuresti"
    trigger:
      platform: state
      entity_id: binary_sensor.meteoalarm
      from: ‘off’
    action:
      - service: notify.notify
        data:
          title: "{{state_attr('binary_sensor.meteoalarm', 'headline')}}"
          message: "{{state_attr('binary_sensor.meteoalarm', 'description')}} is effective on {{state_attr('binary_sensor.meteoalarm', 'effective')}}"
```

i received error
Message malformed: extra keys not allowed @ data['automation']

### URL

https://www.home-assistant.io/integrations/meteoalarm/

### Version

2024.1.2
