### ISSUE TITLE
Trend Sensor documentation issue

### ISSUE THREAD

**Issue by Adesfire** [home-assistant/home-assistant.github.io#30761]
### Feedback

Hi,
trying to setup a trend sensor using the example provided in the documentation :
```
binary_sensor:
  - platform: trend
    sensors:
      temp_falling:
        entity_id: sensor.outside_temperature
        sample_duration: 7200
        max_samples: 120
        min_samples: 20
        min_gradient: -0.0008
        device_class: cold

      temp_rising:
        entity_id: sensor.outside_temperature
        sample_duration: 7200
        max_samples: 120
        min_samples: 20
        min_gradient: 0.0008
        device_class: heat

```
Doing so, I got the following error when reloading my configuration:
`
Invalid config for 'binary_sensor.trend' at configuration.yaml, line 117: **'min_samples**' is an invalid option for 'binary_sensor.trend', check: sensors->temp_falling->min_samples, please check the docs at https://www.home-assistant.io/integrations/trend Invalid config for 'binary_sensor.trend' at configuration.yaml, line 125: 'min_samples' is an invalid option for 'binary_sensor.trend', check: sensors->temp_rising->min_samples, please check the docs at https://www.home-assistant.io/integrations/trend`

I seems min_samples is no longer correct, thus the documentation might be updated?

Thank you.

### URL

https://www.home-assistant.io/integrations/trend

### Version

2023.12
