### ISSUE TITLE
Missing service_data tag for call-service, and plausible examples

### ISSUE THREAD

**Issue by ggonmar** [home-assistant/home-assistant.github.io#30778]
### Feedback

This page is not providing much insight into how to use the tap-action (or any of the others) when the `action` is set to call-service needing a target (`service_data` is not mentioned as an optional parameter when it should).

This could be a reasonable example to include:
```
      tap_action:
        action: call-service
        service: switch.toggle
        service_data:
          entity_id: switch.plug1
```

### URL

https://www.home-assistant.io/dashboards/actions/

### Version

2024.1.2
