### ISSUE TITLE
can't create a custom polling interval for enphase_envoy

### ISSUE THREAD

**Issue by wptracy** [home-assistant/home-assistant.github.io#30809]
### Feedback

This home-assistant core integration (enphase_envoy) says the polling interval is every 60 seconds, but that's not true.  It's every 3 minutes.  I want to change it to poll every 15 seconds.  

The home-assistant Enphase Envoy integration page says I can customize the polling interval by defining a custom polling interval by disabling the polling interval on the integration entity page and creating a new automation for it.

I did that and it doesn't work.

Here is my yaml for the new automation.
 ```
alias: update envoy every 15 seconds
description: ""
trigger:
  - platform: time_pattern
    seconds: /15
condition: []
action:
  - service: homeassistant.update_entity
    target:
      entity_id: sensor.envoy_202321168106_current_power_production
    data: {}
mode: single
```
I see that @foggy-stakes opened this same issue last November 2023.
https://github.com/home-assistant/home-assistant.io/issues/29703#issue-1977699750

The issue was assigned to @bdraco, @cgarwood, @dgomes, @joostlek, but got no response.

Can someone help me please.

### URL

https://www.home-assistant.io/integrations/enphase_envoy/

### Version

2024.1.2
