### ISSUE TITLE
Alerts: please add info and examples on how to acknowledge alerts in Lovelace and via mobile app notifications 

### ISSUE THREAD

**Issue by sneakinhysteria** [home-assistant/home-assistant.github.io#30859]
### Feedback

The reason alerts are so poorly adopted is mainly because there is absolutely no info on how acknowledgements work. I did a writeup on Reddit, maybe this can be added:

https://www.reddit.com/r/homeassistant/s/WdFNJqf49V

### URL

https://www.home-assistant.io/integrations/alert/

### Version

2024.1.3

**Comment by sneakinhysteria** [comment]
Still required. On 16 Mar 2024, at 00:03, github-actions[bot] ***@***.***> wrote:﻿
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved.
If this issue is still relevant, please let us know by leaving a comment 👍
This issue has now has been marked as stale and will be closed if no further activity occurs. Thank you for your contributions.

**Comment by rmnp30** [comment]
I can verify that:
1) There is nothing within the current Alert documentation describing how to acknowledge an alert.

2) Actionable notifications with Alerts do not work, at least not when sent to a Samsung Galaxy device. I do not own an Apple device to test.

I am currently running Home Assistant HAOS: 13.1 Supervisor: 2024.08.0 & Core: 2024.8.2. I created an alert & an automation, following sneakinhysteria write up on Reddit: https://www.reddit.com/r/homeassistant/s/WdFNJqf49V. This does not work, at least with the latest HA software, because the mobile_app_notification_action event is never generated. This was determined by listening for it within Developer Tools > Events during an alert condition that successfully sent a notification to my phone. 

I believe the mobile_app_notification_action event only occurs when a button, on the actionable notification, is clicked. With the received alert actionable notification, there were NOT any actionable buttons visible, thus no way to generate the mobile_app_notification_action event.

Actionable Notifications sent via an automation was tested and buttons are seen on the notification and perform as expected on this same Samsung device. As a result I feel confident the Alert issue is not due to some configuration related issue on the Samsung phone.

Here is the alert I tested with:
```
download_speeds_too_low:
  name: "Download internet speeds have dropped to {{ states.sensor.speedtest_download.state }}"
  done_message: clear_notification
  entity_id: binary_sensor.speedtest_download_slow
  state: 'on'
  repeat:
    - 60
  can_acknowledge: true
  skip_first: false
  notifiers:
    - mobile_app_sm_s901u1
  data:
    tag: speed-test
    actions:
      - action: "okalertdstl"
        title: "Ack Alert"
```
