### ISSUE TITLE
apiai example config contains errors

### ISSUE THREAD

**Issue by pschmitt** [home-assistant/home-assistant.github.io#3098]
The docs regarding the [apiai](https://home-assistant.io/components/apiai/) component are missing the `text` node.

Current (bogus - not passing the config validator):
```
intent_script:
  Temperature:
    speech: The temperature at home is {{ states('sensor.home_temp') }} degrees
```

That should be:
```
intent_script:
  Temperature:
    speech: 
      text: The temperature at home is {{ states('sensor.home_temp') }} degrees
```
