### ISSUE TITLE
Wrong type of mapping in climate documentation

### ISSUE THREAD

**Issue by CyberLine** [home-assistant/home-assistant.github.io#30984]
### Feedback

Wrong type of availability in Documentation

### URL

https://www.home-assistant.io/integrations/climate.mqtt/#availability

### Additional information

While `availability` is a list in documentation, it has to be a map in configuration.

**Comment by jbouwh** [comment]
https://github.com/home-assistant/core/blob/988d72b8b61c49250c81a3067b7904e4d55ecb94/homeassistant/components/mqtt/mixins.py#L159-L170

List is the correct type. In fact it is a list of mappings. The schema will ensure a list in case a mapping is provided.

**Comment by CyberLine** [comment]
It's very confusing then because i have to provide:
```
availability:
    topic: "aircondition/connected"
    payload_available: "1"
    payload_not_available: "0"
```
instead of
```
availability:
    - topic: "aircondition/connected"
    - payload_available: "1"
    - payload_not_available: "0"
 ```

**Comment by jbouwh** [comment]
```yaml
availability:
  - topic: "aircondition/connected1"
    payload_available: "1"
    payload_not_available: "0"
  - topic: "aircondition/connected2"
    payload_available: "1"
    payload_not_available: "0"
```
