### ISSUE TITLE
None of the examples given for Apple TV Deep Links work

### ISSUE THREAD

**Issue by codyc1515** [home-assistant/home-assistant.github.io#31108]
### Feedback

I have tried each of the Deep Links supplied. While the service call appears to be succesful in HA, each time I do this the ATV brings up a media player-esque screen, with a little crossed-out cirle in the bottom left - the content does not play.

```
service: media_player.play_media
data:
  media_content_type: video
  media_content_id: https://www.netflix.com/title/81338328
target:
  entity_id: media_player.lounge_apple_tv
```

I have also tried media_content_type = tv show, tv_show, tvshow, episode and channel. None worked. Even YouTube doesn't work.

### URL

https://www.home-assistant.io/integrations/apple_tv/

### Version

2024.1.5

### Additional information

I am using Apple TV 4K (2nd generation).
