### ISSUE TITLE
Document Update

### ISSUE THREAD

**Issue by jeffh2os** [home-assistant/home-assistant.github.io#31176]
### Feedback

I have been trying to get this working with both my dl380's and finally got it sorted out tonight. If you want to add some more examples I think it may help others out.
Of course naming is up to the user I left mine in as an example.
Thanks for putting this code into Home Assistant!

```
sensor:
  - platform: hp_ilo
    host: 
    username: 
    password: 
    monitored_variables:
      - name: DL380 Vmware Model
        sensor_type: server_name
      - name: DL380 Vmware Inlet temperature
        sensor_type: server_health
        unit_of_measurement: "°C"
        value_template: '{{ ilo_data.temperature["01-Inlet Ambient"].currentreading[0] }}'
      - name: DL380 Vmware Storage Status
        sensor_type: server_health
        value_template: '{{ ilo_data.health_at_a_glance["storage"].status }}'
      - name: DL380 VMware Server Power Health
        sensor_type: server_health
        value_template: '{{ ilo_data.health_at_a_glance["power_supplies"].status }}'
  - platform: hp_ilo
    host: 
    username: 
    password: 
    monitored_variables:
      - name: DL380 ESOS Server
        sensor_type: server_name
      - name: DL380 ESOS Inlet temperature
        sensor_type: server_health
        unit_of_measurement: "°C"
        value_template: '{{ ilo_data.temperature["01-Inlet Ambient"].currentreading[0] }}'
      - name: DL380 ESOS Storage Status
        sensor_type: server_health
        value_template: '{{ ilo_data.health_at_a_glance["storage"].status }}'
      - name: DL380 ESOS Server Power Health
        sensor_type: server_health
        value_template: '{{ ilo_data.health_at_a_glance["power_supplies"].status }}'
```

### URL

https://www.home-assistant.io/integrations/hp_ilo/

### Version

2024.1.6
