### ISSUE TITLE
Sensors not available in virtualized environment

### ISSUE THREAD

**Issue by mikeg-de** [home-assistant/home-assistant.github.io#31198]
### Feedback

Sensors were available before via:

```
# Internal Raspi Sensors
# https://www.home-assistant.io/integrations/sensor.command_line
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: disk_use
      - type: disk_free
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: swap_use_percent
      - type: swap_use
      - type: swap_free
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: throughput_network_in
        arg: eth0
      - type: throughput_network_out
        arg: eth0
      - type: packets_in
        arg: eth0
      - type: packets_out
        arg: eth0
      - type: ipv4_address
        arg: eth0
      - type: ipv6_address
        arg: eth0
      - type: processor_use
      - type: processor_temperature
      - type: last_boot
```

But seems to not get exposed to the integration:
<img width="721" alt="image" src="https://github.com/home-assistant/home-assistant.io/assets/604842/2ee8db15-d63d-4e79-ba40-1cc12205ab5b">

Is it possible to add  support?

### URL

https://www.home-assistant.io/integrations/systemmonitor/

### Version

2024.1.6
