### ISSUE TITLE
Phillips Hue Documentation - Multiple Hubs

### ISSUE THREAD

**Issue by itchaboy** [home-assistant/home-assistant.github.io#3159]
Recently got a new Hue Hub and trying to add it to HA was very frustrating due to the lack of documentation. Luckily I found help while browsing someone else configuration file. 

Turns out you need to do this....

```
light:
  - platform: hue
    host: 192.168.10.75
    filename: phue.conf
    allow_unreachable: true
    allow_in_emulated_hue: false
    allow_hue_groups: false

light 2:
  - platform: hue
    host: 192.168.10.76
    filename: phue2.conf
    allow_unreachable: true
    allow_in_emulated_hue: false
    allow_hue_groups: false
```

And of course this worked out just fine. The hubs battle over the one phue.conf file so a second one is needed. I recommend this be added.
