### ISSUE TITLE
Question about proxy view usage

### ISSUE THREAD

**Issue by kdknigga** [home-assistant/home-assistant.github.io#31752]
### Feedback

I have a question about proxy views.  The docs say:

> These URLs work great when trying to send notifications. Home Assistant will automatically sign the URLs and make them safe for external consumption if used in an automation
or [notify service](https://www.home-assistant.io/integrations/notify/).

I've tried this, and I'm not sure what I'm doing wrong.

I have a script set up like this:

```
alias: Alert Phone about Person detected by Unifi Protect
variables:
  entity_id: trigger.entity_id
  event_id: "{{ trigger.entity_id }}"
  nvr_id: "{{ config_entry_id(entity_id) }}"
  notification_image: "/api/unifiprotect/thumbnail/{{ nvr_id }}/{{ event_id }}"
sequence:
  - service: notify.phone_twilio_sms
    data:
      message: Person Detected
      data:
        media_url:
          - https://externally.available.domain.org{{ notification_image }}
mode: single
```

However, when this gets triggered, I get the following the in logs:

```
Logger: homeassistant.components.http.ban
Source: components/http/ban.py:129
Integration: HTTP (documentation, issues)
First occurred: 4:54:05 PM (1 occurrences)
Last logged: 4:54:05 PM

Login attempt or request with invalid authentication from some_twilio_server (1.2.3.4). Requested URL: '/api/unifiprotect/thumbnail/c86840009a60927c58ade5bd8ed27493/64ba8fa702100403e4001245'. (TwilioProxy/1.1)
```

I can't even access the URL locally in my browser without getting the same error.

Is there something I'm missing?

### URL

https://www.home-assistant.io/integrations/unifiprotect/

### Version

2024.2.5

### Additional information

[config_entry-unifiprotect-c86840009a60927c58ade5bd8ed27493.json](https://github.com/home-assistant/home-assistant.io/files/14502386/config_entry-unifiprotect-c86840009a60927c58ade5bd8ed27493.json)
