### ISSUE TITLE
Quite cumbersome explanation

### ISSUE THREAD

**Issue by darucaile** [home-assistant/home-assistant.github.io#31986]
### Feedback

 `seconds: "/30"` means...? 1/2 minute - 30s? Or 1/30s?? Or..???  
B/c `seconds: "/3"` means what then...???  And `seconds: "30"` ?

### URL

https://www.home-assistant.io/integrations/goodwe/

### Version

2024.3.1

### Additional information

More than confusing, when text above doesn't mention connected example. eg: 
For 1/30s use: ... 
Not even obvious, when phrasing like: "..receive fresh inverter data less (or more) frequently.."

**Comment by cflurin** [comment]
I'm new to Home Assistant and Goodwe but here is my automation for the "goodwe inverter data polling:

```
alias: Goodwe inverter data polling
description: ""
triggers:
  - trigger: time_pattern
    hours: "*"
    minutes: "*"
    seconds: /30
conditions: []
actions:
  - action: homeassistant.update_entity
    data:
      entity_id:
        - automation.pv_power
        - sensor.house_consumption
        - sensor.meter_active_power_total
        - sensor.today_load
        - sensor.total_pv_generation
        - sensor.meter_total_energy_export
        - sensor.meter_total_energy_import
mode: single
```

- Polling interval: 30 seconds
 have a look at: [time-pattern-trigger](https://www.home-assistant.io/docs/automation/trigger/#time-pattern-trigger)
- you can edit (add, remove) the entity_ids as needed.
