### ISSUE TITLE
Entering Non-Integer (Digital) Channels

### ISSUE THREAD

**Issue by rpruden** [home-assistant/home-assistant.github.io#31993]
### Feedback

I am having a hard time finding out how to tune digital channels. If I want to change the channel I can use the channel content type and enter a channel number. But what if I need to enter a digital channel number? 13.1 will be selected if I enter 13, but what if I want to go to 13.2 or 13.4?

data:
  media_content_id: 13
  media_content_type: channel

I have tried this using decimal numbers and quotes but it does not work. I have also tried using the remote commands but I can not find a way to enter the . or - that the physical remote would use.

data:
  media_content_id: 13.2
  media_content_type: channel
##This does not work

Do you have any guidance for this process?

### URL

https://www.home-assistant.io/integrations/androidtv_remote/

### Version

2024.3.1

**Comment by tronikos** [comment]
Does `MINUS` from  https://github.com/tronikos/androidtvremote2/blob/e54e33772e61e4ccb24b0c5ba6e0f2ad3efb2547/src/androidtvremote2/remotemessage.proto#L249C11-L249C16 work? Something like:

```yaml
service: remote.send_command
data:
  command:
    - 1
    - 3
    - MINUS
    - 2
target:
  entity_id: remote.living_room_tv
```

You might need to set the `delay_secs` parameter in the service call.
