### ISSUE TITLE
? error in YAML config example

### ISSUE THREAD

**Issue by chris-hunter** [home-assistant/home-assistant.github.io#32041]
### Feedback

When I tried to add this to my config it didn't work - I needed to add a das to my YAML as below:

```
sensor:
  - platform: worxlandroid
    host: 10.31.10.13
    pin: !secret worx_pin
```

### URL

https://www.home-assistant.io/integrations/worxlandroid/

### Version

2024.3.3
