### ISSUE TITLE
Bug in mqtt switch configuration documentation

### ISSUE THREAD

**Issue by IMozgg** [home-assistant/home-assistant.github.io#32177]
### Feedback

Good afternoon, I found probably a bug in the documentation.

You have the following switch configuration code for mqtt, but it is not correct. Or I'm wrong. In any case it didn't work for me.

The correct solution is similar for sensors. Your solution:
```yaml
# Example configuration.yaml entry
mqtt:
  - switch:
      name: bathroom
      state_topic: "home/bathroom/gpio/13"
      command_topic: "home/bathroom/gpio/13"
      payload_on: "1"
      payload_off: "0"
```

Checking the configuration shows errors
```
Invalid config for 'mqtt' at configuration.yaml, line 29: 'name' is an invalid option for 'mqtt', check: mqtt->0->name
Invalid config for 'mqtt' at configuration.yaml, line 30: 'command_topic' is an invalid option for 'mqtt', check: mqtt->0->command_topic
Invalid config for 'mqtt' at configuration.yaml, line 31: 'state_topic' is an invalid option for 'mqtt', check: mqtt->0->state_topic
Invalid config for 'mqtt' at configuration.yaml, line 34: 'payload_on' is an invalid option for 'mqtt', check: mqtt->0->payload_on
Invalid config for 'mqtt' at configuration.yaml, line 35: 'payload_off' is an invalid option for 'mqtt', check: mqtt->0->payload_off
Invalid config for 'mqtt' at configuration.yaml, line 36: 'state_on' is an invalid option for 'mqtt', check: mqtt->0->state_on
Invalid config for 'mqtt' at configuration.yaml, line 37: 'state_off' is an invalid option for 'mqtt', check: mqtt->0->state_off
Invalid config for 'mqtt' at configuration.yaml, line 38: 'optimistic' is an invalid option for 'mqtt', check: mqtt->0->optimistic
Invalid config for 'mqtt' at configuration.yaml, line 39: 'qos' is an invalid option for 'mqtt', check: mqtt->0->qos
Invalid config for 'mqtt' at configuration.yaml, line 40: 'retain' is an invalid option for 'mqtt', check: mqtt->0->retain
```

Correct configuration like this:
```yaml
mqtt:
  switch:
    - name: some_switch
      state_topic: "home/bathroom/gpio/13"
      command_topic: "home/bathroom/gpio/13"
      payload_on: "1"
      payload_off: "0"
#...
```

### URL

https://www.home-assistant.io/integrations/switch.mqtt/

### Version

2024.4.1

**Comment by jbouwh** [comment]
That is weird. Do you run the latest version of Home Assistant?
If you set up more than one manual mqtt entry theey should be all the same.

I tested the example, and it works for me, apart from the fact that it is not very useful to have a state topic equal to the command topic.

**Comment by jbouwh** [comment]
The error messages assume you omitted to supply the platform key. Is that correct?

**Comment by IMozgg** [comment]
> That is weird. Do you run the latest version of Home Assistant? If you set up more than one manual mqtt entry theey should be all the same.
> ...

No, not the latest version HA. 

```
Core 2024.3.3
Supervisor 2024.03.1
```

> I tested the example, and it works for me, apart from the fact that it is not very useful to have a state topic equal to the command topic

yes, it is only example yaml config. I don't have equals a state topic and command etc...

> The error messages assume you omitted to supply the platform key. Is that correct?

What do you mean? Old configuration through setting platform key like this? 
# Example configuration.yml entry
```yaml
switch:
  - platform: mqtt
    name: "Bedroom Switch"
    state_topic: "home/bedroom/switch1"
    command_topic: "home/bedroom/switch1/set"
    availability_topic: "home/bedroom/switch1/available"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
```

This configuration successfully passes validation, but after restarting, this is the error in the notifications
![image](https://github.com/home-assistant/home-assistant.io/assets/33234666/159b89c1-7ecc-40d8-8447-1270bd41b40a)


At now my configuration like that
```yaml
mqtt:
  sensor: !include sensors/esp8266_custom.yaml
  switch: !include switches/esp8266_custom.yaml
```
switches/esp8266_custom.yaml
```yaml
- name: "esp_light"
  command_topic: "office/light1/switch"
  state_topic: "office/light1/status"
  # availability:
  #   - topic: "home/bedroom/switch1/available"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
```
And this configuration passes the test successfully and the switch is detected successfully
