### ISSUE TITLE
集成event.mqtt页面的configuration.yaml示例写法有误，格式不对

### ISSUE THREAD

**Issue by winteris** [home-assistant/home-assistant.github.io#32398]
### Feedback

hass的集成event.mqtt页面，也就是下面这个链接
[https://www.home-assistant.io/integrations/event.mqtt](url)
这里所有的示例code有误
举个例子：
  ```
mqtt:
  - event:
      name: "Desk button"
      state_topic: "desk/button/state"
      event_types:
        - single
        - double
      device_class: "button"
      value_template: |
        { {% for key in value_json %}
        {% if value_json[key].get("Action") %}
        "button": "{{ key }}",
        "event_type": "{{ value_json[key].Action | lower }}"
        {% endif %}
        {% endfor %} }
````
实测是跑不通的，正确应该是下面这样的
````
mqtt:
  event:
    - name: "Desk button"
      state_topic: "desk/button/state"
      event_types:
        - single
        - double
      device_class: "button"
      value_template: |
        { {% for key in value_json %}
        {% if value_json[key].get("Action") %}
        "button": "{{ key }}",
        "event_type": "{{ value_json[key].Action | lower }}"
        {% endif %}
        {% endfor %} }
````

### URL

https://www.home-assistant.io/integrations/event.mqtt
