### ISSUE TITLE
Message malformed: extra keys not allowed @ data['0']

### ISSUE THREAD

**Issue by hensjl** [home-assistant/home-assistant.github.io#32491]
### Feedback

Always have the same error message:
`Message malformed: extra keys not allowed @ data['0']`
The code I use as model is the last: # Example automation using snapshot
I get the same error with the sample code itself.
```
# Example automation using snapshot
- alias: "Window opened"
  trigger:
  - platform: state
    entity_id: binary_sensor.window
    from: "off"
    to: "on"
  condition: []
  action:
  - service: scene.create
    data:
      scene_id: before
      snapshot_entities:
      - climate.ecobee
      - light.ceiling_lights
  - service: light.turn_off
    target:
      entity_id: light.ceiling_lights
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.ecobee
    data:
      hvac_mode: "off"
- alias: "Window closed"
  trigger:
  - platform: state
    entity_id: binary_sensor.window
    from: "on"
    to: "off"
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.before
```

### URL

https://www.home-assistant.io/integrations/scene/

### Version

2024.4.4

**Comment by hensjl** [comment]
Same problem as #26218, but no solution since Feb 2023.

**Comment by Hindelaufen** [comment]
I have this issue too.
Whenever I try to save any script (be it in Automations or in Scripts) I get the same error:

Message malformed: extra keys not allowed @ data['0']

I tried scripts (1 to 1 copy, no modifications) other users enabled succesfully.

See example attached, but again: this happens to all scripts created in YAML when I try to save.

[Vacation_timer_ORG.txt](https://github.com/user-attachments/files/16319318/Vacation_timer_ORG.txt)

**Comment by DocSalvager** [comment]
Having same problem. Seems to be failing on...

```
action:
  - alias: Enable Kitchen Light Motion
    device_id: cf682cfa869411186c9449644db0636f
    domain: zwave_js
    type: set_config_parameter
    endpoint: 0
    parameter: 6
    bitmask: null
    subtype: 6 (Motion Sensor) on endpoint 0
    value: 1

```
