### ISSUE TITLE
WebOS TV documentation: Mention how to open input selector

### ISSUE THREAD

**Issue by dwillbarron** [home-assistant/home-assistant.github.io#32735]
### Feedback

Hi! I'm here to pitch in some obscure info that might save a few people some pain:

https://www.home-assistant.io/integrations/webostv/

If you read the docs, you'll notice there's no equivalent of an input/source button listed for the `webostv.button` service. That's not a mistake--after a fair amount of digging, it looks like there's no "INPUT" button (I tried many variants of input, source, picker...).

For people that _really_ want that button, it turns out there's an endpoint that directly opens the same menu. You can open the input sidebar menu with the following command:

```yaml
# Tested on WebOS 05.50.15
service: webostv.command
  target:
    entity_id: media_player.living_room_tv
  data:
    command: com.webos.surfacemanager/showInputPicker
```

This info was really hard to find, which is why I figured I'd share it in the hope that someone can find a home for it within the docs here. I only found it after many failed searches because of a passing mention in a 2015 Github issue on a completely different project: https://github.com/ConnectSDK/Connect-SDK-iOS/issues/131

P.S.
I'm aware that it's possible to change inputs directly via home assistant, skipping the TV's menu entirely--but I'm far too stubborn to accept defeat when there's a button missing from a thing.

### URL

https://www.home-assistant.io/integrations/webostv/

### Version

2024.5.3
