### ISSUE TITLE
Since PR  #115108 is IMAP documentation up-to-date?

### ISSUE THREAD

**Issue by kds69** [home-assistant/home-assistant.github.io#32732]
### Feedback

Documentation still refers to text and headers whereas this PR  #115108 is aiming at removing text and headers from data event for the sake of size.
Do I get this right and below example taken from "**Using events**" section of the IMAP documentation is still pulling event text and headers data?
(https://www.home-assistant.io/integrations/imap)

```
template:
  - trigger:
      - platform: event
        event_type: "imap_content"
        id: "custom_event"
    sensor:
      - name: imap_content
        state: "{{ trigger.event.data['subject'] }}"
        attributes:
          Entry: "{{ trigger.event.data['entry_id'] }}"
          UID: "{{ trigger.event.data['uid'] }}"
          Message: "{{ trigger.event.data['text'] }}"
          ...
          To: "{{ trigger.event.data['headers'].get('Delivered-To', ['n/a'])[0] }}"
          Return-Path: "{{ trigger.event.data['headers'].get('Return-Path',['n/a'])[0] }}"
          Received-first: "{{ trigger.event.data['headers'].get('Received',['n/a'])[0] }}"
          Received-last: "{{ trigger.event.data['headers'].get('Received',['n/a'])[-1] }}"
```

### URL

https://www.home-assistant.io/integrations/imap/

### Version

2024.5.3
