### ISSUE TITLE
Please add examples for outputting simple variables (States,If,Then,Else,random).

### ISSUE THREAD

**Issue by Watchkido** [home-assistant/home-assistant.github.io#32855]
### Feedback

Examples for the output of normal variables.

```
service: media_player.play_media
target:
  entity_id: media_player.vlc_telnet
data:
  media_content_id: >-
        media-source://tts/tts.piper_2?message=WARNUNG+SONNENSTURM+{{states('sensor.ham_radio_propagation_solar_xray')}}&language=de_DE&voice=de_DE-ramona-low
  media_content_type: provider
metadata:
  title: WARNUNG SONNENSTURM  {states('sensor.ham_radio_propagation_solar_xray') }
  thumbnail: https://brands.home-assistant.io/_/tts/logo.png
  media_class: app
  children_media_class: null
  navigateIds:
    - {}
    - media_content_type: app
      media_content_id: media-source://tts
    - media_content_type: provider
      media_content_id: >-
        media-source://tts/tts.piper_2?message=WARNUNG+SONNENSTURM+{{states('sensor.ham_radio_propagation_solar_xray')}}&language=de_DE&voice=de_DE-ramona-low 
```

(Incorrect) example for the output of random variables:

```
service: media_player.play_media
target:
  entity_id: media_player.vlc_telnet
data:
  media_content_id: >-
        media-source://tts/tts.piper_2?message=WARNUNG+SONNENSTURM+{{states('sensor.ham_radio_propagation_solar_xray')}}&language=de_DE&voice=de_DE-ramona-low
  media_content_type: provider
metadata:
  title: WARNUNG SONNENSTURM  {states('sensor.ham_radio_propagation_solar_xray') }
  thumbnail: https://brands.home-assistant.io/_/tts/logo.png
  media_class: app
  children_media_class: null
  navigateIds:
    - {}
    - media_content_type: app
      media_content_id: media-source://tts
    - media_content_type: provider
      media_content_id: {% set kalorien ="Nur" ~
    (states('sensor.f_basal_metabolism'))|float| round (0) ~
    "Kalorien essen !" %}    {% set sollgewicht =
    states('sensor.sollgewicht_avi') |float|round(1) ~ "Sollgewicht"%} {% set
    uebergewicht = states('sensor.uebergewicht_avi')|float| round (0) ~ "kilo
    sind zuviel" %}  {% set innentemperatur =
    "Temperatur innen" ~
    states('sensor.esp360_default_1_living_room_temperature') |float|round(1) ~
    "Grad" %}{% set aussentemperatur = "Temperatur aussen" ~
    states('sensor.aussentemperatur') |float|round(1) ~ "Grad" %}

    {% if states.sensor.mi_waage_weight_frank is defined %} {% set gewicht =
    "Aktuelles Gewicht " ~ states('sensor.mi_waage_weight_frank')
    |float|round(1)%} {% else %} {% set gewicht = "Jetzt Wiegen!"%} {% endif %}

    {% set ZufallsAnsage =  [ kalorien, "Schutzkugel jetzt","Ziel 83 Kilogramm
    wohlfühlgewicht", "Übergewicht verringern",  uebergewicht, gewicht,
    Maximalgewicht, sollgewicht, "Rückstrahler an", innentemperatur, Sport
    ,kalorien, "Kugel","Waschbrettbauch Wettkampf mit  Nic"]|random %}

    {# Ausgabe hier -#} 
enabled: true
        media-source://tts/tts.piper_2?message={{ZufallsAnsage}}&language=de_DE&voice=de_DE-ramona-low
```

### URL

https://www.home-assistant.io/voice_control/using_tts_in_automation/

### Version

2024.5.4
