### ISSUE TITLE
Spot clean up

### ISSUE THREAD

**Issue by Adaaks** [home-assistant/home-assistant.github.io#32952]
### Feedback

The old deebot 4 home assistant used to specify a list of commands, such as spot clean ups, but now im not sure how to setup a spot clean up with the integration.

This used to be my old call service, but it does not work anymore with the new integration.
![image](https://github.com/home-assistant/home-assistant.io/assets/62220165/db9ced76-4019-4d8d-a853-9b1beaafb8ea)

### URL

https://www.home-assistant.io/integrations/ecovacs/

### Version

2024.5.5

**Comment by edenhaus** [comment]
You can use the same commands as in the Deebot 4 Home Assistant custom command. Only deprecated commands were not ported to core.

```yaml
alias: Send cleaning job to vacuum
service: vacuum.send_command
data:
  entity_id: '{{ vacuum_bot }}'
  command: spot_area
  params:
    rooms: '{{ rooms }}'
    cleanings: 1
```

I can confirm that this command is working
