### ISSUE TITLE
Pet names unclear, error message not helpful

### ISSUE THREAD

**Issue by tfischer4765** [home-assistant/home-assistant.github.io#33469]
### Feedback

I'm getting the error `value must be one of ['999.202111200094', 'Canossa ', 'Kitty '] for dictionary value @ data['pet_name']. Got None`

for the following integration:

```
if:
  - condition: state
    entity_id: input_boolean.kitty_indoor
    state: "on"
then:
  - service: surepetcare.set_pet_location
    data:
      pet_name: Kitty
      location: Inside
  - service: tts.cloud_say
    metadata: {}
    data:
      cache: false
      entity_id: media_player.arbeitszimmer
      message: kitty coming in
else:
  - service: surepetcare.set_pet_location
    data:
      pet_name: Kitty
      location: Outside
  - service: tts.cloud_say
    metadata: {}
    data:
      cache: false
      message: kitty going out
      entity_id: media_player.arbeitszimmer
```

which is created using the online editor. 

Please make it clear in the documentation in what format the pet name must be supplied. or alternatively, allow for the unique pet-id to be used.

### URL

https://www.home-assistant.io/integrations/surepetcare/

### Version

2024.6.4
