### ISSUE TITLE
MQTT sensor timestamp extraction

### ISSUE THREAD

**Issue by ievren** [home-assistant/home-assistant.github.io#33742]
### Title: Clarification Needed on Extracting Timestamps from MQTT Sensors

**Description:**

I don't understand how to extract the timestamp from a sensor, and it's not very clear to me based on the current documentation.

There is an example explaining processing timestamps, but I am not 100% sure if my approach is correct:
- [MQTT Sensor - Processing Unix Epoch Timestamps](https://www.home-assistant.io/integrations/sensor.mqtt/#processing-unix-epoch-timestamps)

I would appreciate it if there were a clear example of how to handle a scenario where a sensor wakes up and sends multiple time points. Is this not a common approach (for battery saving)?

Here's my specific case:
1. Topic: `enviro/enviro-urban`
2. Message payload:
    ```json
    {
      "readings": {
        "pressure": 964.46,
        "pm1": 7,
        "pm2_5": 9,
        "noise": 0.036,
        "humidity": 31.65,
        "temperature": 31.53,
        "pm10": 10
      },
      "nickname": "enviro-urban",
      "model": "urban",
      "uid": "e66164084356202d",
      "timestamp": "2024-07-13T21:44:07Z"
    }
    ```

To handle this, I manually added the following section to `configuration.yaml` using the file editor:

```yaml
mqtt:
  sensor:
    - name: "Enviro Urban Temperature"
      state_topic: "enviro/enviro-urban"
      unit_of_measurement: "°C"
      value_template: "{{ value_json.readings.temperature }}"
      json_attributes_topic: "enviro/enviro-urban"
      json_attributes_template: "{{ {'timestamp': value_json.timestamp} | tojson }}"
      expire_after: 3600
      force_update: true
    
    - name: "Enviro Urban Humidity"
      state_topic: "enviro/enviro-urban"
      unit_of_measurement: "%"
      value_template: "{{ value_json.readings.humidity }}"
      json_attributes_topic: "enviro/enviro-urban"
      json_attributes_template: "{{ {'timestamp': value_json.timestamp} | tojson }}"
      expire_after: 3600
      force_update: true

    - name: "Enviro Urban Pressure"
      state_topic: "enviro/enviro-urban"
      unit_of_measurement: "hPa"
      value_template: "{{ value_json.readings.pressure }}"
      json_attributes_topic: "enviro/enviro-urban"
      json_attributes_template: "{{ {'timestamp': value_json.timestamp} | tojson }}"
      expire_after: 3600
      force_update: true
    
    - name: "Enviro Urban Noise"
      state_topic: "enviro/enviro-urban"
      unit_of_measurement: "V"
      value_template: "{{ value_json.readings.noise }}"
      json_attributes_topic: "enviro/enviro-urban"
      json_attributes_template: "{{ {'timestamp': value_json.timestamp} | tojson }}"
      expire_after: 3600
      force_update: true
    
    - name: "Enviro Urban PM1"
      state_topic: "enviro/enviro-urban"
      unit_of_measurement: "µg/m³"
      value_template: "{{ value_json.readings.pm1 }}"
      json_attributes_topic: "enviro/enviro-urban"
      json_attributes_template: "{{ {'timestamp': value_json.timestamp} | tojson }}"
      expire_after: 3600
      force_update: true

    - name: "Enviro Urban PM2.5"
      state_topic: "enviro/enviro-urban"
      unit_of_measurement: "µg/m³"
      value_template: "{{ value_json.readings.pm2_5 }}"
      json_attributes_topic: "enviro/enviro-urban"
      json_attributes_template: "{{ {'timestamp': value_json.timestamp} | tojson }}"
      expire_after: 3600
      force_update: true
    
    - name: "Enviro Urban PM10"
      state_topic: "enviro/enviro-urban"
      unit_of_measurement: "µg/m³"
      value_template: "{{ value_json.readings.pm10 }}"
      json_attributes_topic: "enviro/enviro-urban"
      json_attributes_template: "{{ {'timestamp': value_json.timestamp} | tojson }}"
      expire_after: 3600
      force_update: true
    
    - name: "Enviro Urban Voltage"
      state_topic: "enviro/enviro-urban"
      unit_of_measurement: "V"
      value_template: "{{ value_json.readings.voltage }}"
      json_attributes_topic: "enviro/enviro-urban"
      json_attributes_template: "{{ {'timestamp': value_json.timestamp} | tojson }}"
      expire_after: 3600
      force_update: true
```

It may be related to this discussion:
- [Home Assistant Community - Sensor Transmits Multiple Time Points](https://community.home-assistant.io/t/sensor-transmits-multiple-time-points-how-to-ingest-into-ha/527887)
- [GitHub - Pimoroni/enviro Issues #227](https://github.com/pimoroni/enviro/issues/227)

**Would it be possible to get a clear example or further guidance on this?**

### URL

https://www.home-assistant.io/integrations/sensor.mqtt/

### Version

2024.7.2
