### ISSUE TITLE
Presence detection (opnsense) does not work for me

### ISSUE THREAD

**Issue by alexg-k** [home-assistant/home-assistant.github.io#34059]
### Feedback

My problem is that all device-trackers are being shown always as at `Home` and never as `Away`. It does not depend on the connection status of the device in the network as it should.

Homeassistant seems to connect to Opnsense. It showed a SSL connection error at first, but that was fixed by adding my custom CA. I get no error in the logs now. 

Here is my Homeassistant configuration: 
```
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5

additional_ca:
  my_private_ca: lan.crt

opnsense:
  url: https://router.lan/api
  api_secret: U+sfLniJujz94...
  api_key: JdjDxeaxhOs3cL...
  verify_ssl: True
  tracker_interfaces:
    - Trusted

group:
  smartphones:
    name: "Our Smartphones"
    entities:
      - device_tracker.phone_alice
      - device_tracker.phone_bob
```
The interface `Trusted` is the name of the opnsense interface where both devices are in.

Here is my Opnsense user configuration: ![Screenshot from 2024-08-01 07-11-37](https://github.com/user-attachments/assets/74c66f06-ef0e-4c24-9ef6-30b0f001f784)

The devices show up in homeassistant: ![Screenshot from 2024-08-01 07-41-35](https://github.com/user-attachments/assets/11f76803-97e2-437f-ab3d-e11e87f641cf)

When I open a device tracker in homeassistant I get this warning, but this might be normal: ![Screenshot from 2024-08-01 07-47-19](https://github.com/user-attachments/assets/d2062383-1e58-4b19-aac3-197dbf7ece97)

### URL

https://www.home-assistant.io/integrations/opnsense/

### Version

2024.7.4
