### ISSUE TITLE
Get prices today/tomorrow

### ISSUE THREAD

**Issue by martijnz43** [home-assistant/home-assistant.github.io#34195]
### Feedback

Very nice intergration but on the documentation side it would be very nice if there is more info on how to request the prices for the day and for tomorrow and save them in homeassistant

### URL

https://www.home-assistant.io/integrations/tibber/

### Version

2024.8.0

**Comment by forTT78** [comment]
I have a similar issue:
```
action: tibber.get_prices
data:
  start: "2024-10-12 00:00:00"
  end: "2024-10-13 00:00:00"
```

gives me:
`Die Aktion tibber.get_prices konnte nicht ausgeführt werden. Unknown error`

Notify action works, so user credentials are present.

Any hint?
