### ISSUE TITLE
Button action config example not correct on Android TV Remote integration documentation

### ISSUE THREAD

**Issue by adorobis** [home-assistant/home-assistant.github.io#34201]
### Feedback

The card example provided on Android TV Remote integration documentation is not correct, it now has some duplicate `action:` keys. Not sure if the frontend is now fully aligned to the rename of "service" into "action", I believe in case of button actions we have a bit of confusion now. I guess too much search&replace has happened here :)
Example of wrong code in the document:
```
      - type: button
        icon: mdi:arrow-up-bold
        tap_action:
          action: call-service
          action: remote.send_command
          data:
            command: DPAD_UP
          target:
            entity_id: remote.living_room_tv
```
a correctly working example:
```
      - type: button
        icon: mdi:arrow-up-bold
        tap_action:
          action: call-service
          service: remote.send_command
          data:
            command: DPAD_UP
          target:
            entity_id: remote.googletv
```

### URL

https://www.home-assistant.io/integrations/androidtv_remote/

### Version

2024.8.0
