### ISSUE TITLE
typo in Notify groups?

### ISSUE THREAD

**Issue by RedNo7** [home-assistant/home-assistant.github.io#34223]
### Feedback

Hi,

I think that 
```yaml
notify:
  - platform: group
    name: "My notification group"
    services:
      - action: html5
        data:
          target: "macbook"
      - action: html5_nexus
```

should be:
```yaml
notify:
  - platform: group
    name: "My notification group"
    services:
      - service: html5
        ^^^^^
        data:
          target: "macbook"
      - service: html5_nexus
        ^^^^^^
```

per the config section below it.

At least, when I try with 2024.8.0 (i.e. post the `service:` ➜ `action:` change, I get errors when I check my config.

### URL

https://www.home-assistant.io/integrations/group/

### Version

2024.8.0
