### ISSUE TITLE
Folder watcher example doesn't work

### ISSUE THREAD

**Issue by smokethis** [home-assistant/home-assistant.github.io#34230]
### Feedback

I assume the currently published notification example on the Folder watcher page [https://www.home-assistant.io/integrations/folder_watcher](url) is from an earlier release, however the code example is wildly incompatible with HA as-is. Have just spent ages trawling forums and pages and can suggest an alternative that is functional:

```
alias: New file alert
trigger:
  - platform: event
    event_type: folder_watcher
    event_data:
      event_type: created
action:
  - action: notify.persistent_notification
    data:
      title: New file alert
      message: Check out new file {{ trigger.event.data.path }}
```

Is close to the existing example and works properly with the event framework.

### URL

https://www.home-assistant.io/integrations/folder_watcher/

### Version

2024.8.0
