### ISSUE TITLE
Folder Watcher installation docs are completely wrong

### ISSUE THREAD

**Issue by glennlawyer** [home-assistant/home-assistant.github.io#34295]
### Feedback

Trying to install Folder Watcher. The instructions offer two options, neither of which work. The correct solution is not in the instructions.

## the two wrong options

```
Configuration
To add the Folder watcher integration to your Home Assistant instance, 
use this My button:
```
```
If the above My button doesn’t work, you can also perform the following steps manually:

    Browse to your Home Assistant instance.

    Go to[ Settings > Devices & Services](https://my.home-assistant.io/redirect/integrations).

    In the bottom right corner, select the[ Add Integration](https://my.home-assistant.io/redirect/config_flow_start?domain=folder_watcher) button.

    From the list, select Folder watcher.

    Follow the instructions on screen to complete the setup.
```

Using either of these gives a dialog telling me that 
```
The device cannot be added from the UI
You can add this device by adding it to your 'configuration.yaml'. See the documentation for more information.
```

**The linked documentation does not say how to add Folder Watcher to configuration.yaml, it only offers the two approaches mentioned above!!**

##  How to install it

This is guesswork; I'm actually counting on you to give proper instructions. I'm writing this as proof that I've tried to solve the problem on my own and am not just whining.

The correct approach seems to be to edit `configuration.yaml`, adding a section under the `homeassistant` setting, as follows:
```
homeassistant:
  name: Home
  ... 
  allowlist_external_dirs:
    - "/usr/var/dumping-ground"
    - "/tmp"
```

where `"/usr/var/dumping-ground" and "/tmp" are the folders you want to watch

[example taken from docs here](https://www.home-assistant.io/integrations/homeassistant/#allowlist_external_dirs)

However, [a different post](https://community.home-assistant.io/t/problem-with-folder-watcher/50954/26) suggests that I should directly add a `folder watcher` section to the yaml, and should whitelist the external dirs (note that this has `whitelist` while the other approach has `allowlist`; I'm guessing the `allowlist` form is more current).

```
homeassistant:
  whitelist_external_dirs:
    - /config
    - /share
    - /backup

folder_watcher:
  - folder: /config
  - folder: /share
  - folder: /backup
  ```

Some other posts suggest that it is then necessary to restart HA to have this take effect.

I would actually love to contribute the correct solution to the docs, but am unsure 

1 what the solution is
2 how best to do so.

### URL

https://www.home-assistant.io/integrations/folder_watcher/

### Version

2024.8.1
