### ISSUE TITLE
Amcrest example broken with PR #34023

### ISSUE THREAD

**Issue by urdaalex** [home-assistant/home-assistant.github.io#34337]
### Feedback

#34023 bulk renamed some docs and now the 'action' key shows up twice for the Amcrest integration. The example below will not run when tested on my 2024.5.5

Example: https://www.home-assistant.io/integrations/amcrest/#example-card-with-controls

``` yaml
elements:
  - type: icon
    icon: "mdi:arrow-up"
    style:
      background: "rgba(255, 255, 255, 0.25)"
      right: 25px
      bottom: 50px
    tap_action:
      action: call-service   ## <----- used to be a 'service' key
      action: amcrest.ptz_control  ## <----- duplicate 'action' key
      service_data:
        entity_id: camera.lakehouse
        movement: up
```

### URL

https://www.home-assistant.io/integrations/amcrest/

### Version

2024.8.2
