### ISSUE TITLE
SONOS Microphone binary sensor not turning off

### ISSUE THREAD

**Issue by BoKKeR** [home-assistant/home-assistant.github.io#34367]
### Feedback

SONOS Microphone binary sensor not turning off when manually turning off the microphone on the Sonos speakers. I have tried it on 3 devices, two SL One-s and a beam. They all fail to update from On to Off within HA.

### URL

https://www.home-assistant.io/integrations/sonos/

### Version

2024.8.2

### Additional information

I have also tried this on an older HA 2023.11 and the problem was the same. It could be on the side of sonos.

**Comment by PeteRager** [comment]
Are you talking about the physical switch on the speaker that disconnects the microphone? Or turning the microphone on and off from the Sonos App?

**Comment by BoKKeR** [comment]
I am talking about the physical switch on the device

**Comment by PeteRager** [comment]
Try the following

- turn the physical switch off / restart HA what does the binary sensor report? This will tell us if the state is fetched on startup


Next step is to enable debug logging,
- enable debug logging for the integration
- turn the switch on
- restart HA
- get the integration diagnostic logs
- Turn the switch off and record the approximate local time
- Get the integration diagnostic logs

post the two diagnostic logs, the home assistant log and the time you turned the switch off.

**Comment by BoKKeR** [comment]
All done on entity: 

media_player.living_room
binary_sensor.living_room_microphone

Log1
14:57 turned switch on
14:59 restarted HA
15:00 already seen as microphone ON in dashboard
[home-assistant_sonos_2024-08-19T13-00-43.637Z.log](https://github.com/user-attachments/files/16660515/home-assistant_sonos_2024-08-19T13-00-43.637Z.log)

Log2
15:02 disabled microphone
15:04 no status change
[home-assistant_sonos_2024-08-19T13-04-14.396Z.log](https://github.com/user-attachments/files/16660538/home-assistant_sonos_2024-08-19T13-04-14.396Z.log)

The good news is that the binary sensor updates when I restart home assistant!

**Comment by PeteRager** [comment]
Thanks.  Can see this is the log

```
quot; MicEnabled=&quot;0&quot;
``` 

At 15:03:28.529

so the good news it is seems to be being sent, need to figure out why it doesn't process.

**Comment by PeteRager** [comment]
Do you have voice services configured for Sonos?

It also looks like your system is using polling mode vs subscriptions. Is HA running on a separate network?

**Comment by BoKKeR** [comment]
Yes, I am running it within kubernetes. I have found the documentation mentioning the subscription problem with kubernets, I will try to solve this since that should solve the events not arriving back to HA. Thanks for helping finding the potential solution. No fault on the addons side.

**Comment by PeteRager** [comment]
the path within the integration is different when in polling vs subscription mode, and the test coverage for polling is fairly limited so i do think you have found a bug.

**Comment by BoKKeR** [comment]
I fixed the routing and advertised ip and now the subscription works. The microphone events work also. 

Posting below the config in case someone else runs into the same problem using metallb

```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: home-automation
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      hostNetwork: false
      containers:
      - name: home-assistant
        image: homeassistant/home-assistant:2024.8.2
        ports:
        - containerPort: 8123
        - containerPort: 1400
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  selector:
    app: home-assistant
  type: ClusterIP
  ports:
  - name: webui
    protocol: TCP
    port: 8123
    targetPort: 8123
  - name: sonos
    protocol: TCP
    port: 1400
    targetPort: 1400
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-sonos-metallb
  namespace: home-automation
  annotations:
    metallb.universe.tf/allow-shared-ip: local
spec:
  selector:
    app: home-assistant
  ports:
    - port: 1400
      targetPort: 1400
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 10.0.0.20
```

and in my configuration.yaml

```
sonos:
  media_player:
    hosts:
      - 10.0.0.210
      - 10.0.0.211
    advertise_addr: 10.0.0.20
```
