### ISSUE TITLE
Examples please!

### ISSUE THREAD

**Issue by nzrutman** [home-assistant/home-assistant.github.io#34426]
### Feedback

I could really use an example for how to use an Abode camera in Home Assistant. E.g. CUE package detection event triggers Home Assistant to capture_image and a picture_entity card that displays it. I can't seem to find any examples on the Google.

### URL

https://www.home-assistant.io/integrations/abode/

### Version

2024.8.2

**Comment by nzrutman** [comment]
Picture-entity card that captures an image on tap:
```
show_state: true
show_name: true
camera_view: auto
type: picture-entity
entity: camera.porch_2
tap_action:
  action: perform-action
  perform_action: abode.capture_image
  data:
    entity_id: camera.porch_2
```

Automation triggered by Abode capture
```
alias: abode simple
trigger:
  - platform: event
    event_type: abode_capture
    event_data:
      event_type: Video Capture
condition: []
action:
  - data:
      title: "Debug: Abode Automation"
      message: >
        Title: {{ trigger.event.data.event_name }} {{'<br>'}} 
        Camera: {{ trigger.event.data.device_name.lower() }} {{'<br>'}} 
        Time: {{ trigger.event.data.event_utc | as_datetime | as_local }}
    action: notify.persistent_notification
```

(but how do I get an image from that event??)
