### ISSUE TITLE
Cannot find the available Piper-Message-Options

### ISSUE THREAD

**Issue by tackin** [home-assistant/home-assistant.github.io#34616]
### Feedback

```
action: tts.speak
data:
  message: some random text.
  media_player_entity_id: media_player.my_player
  options:
    voice: de_DE-thorsten-medium
    ....
target:
  entity_id:
    - tts.piper

```
### URL

https://www.home-assistant.io/voice_control/voice_remote_local_assistant/

### Version

2024.9.0

### Additional information

Which other options are available in an action-yml?

In the piper docker-compose-container I can configure a default like:
- PIPER_VOICE=de_DE-thorsten-medium #
- PIPER_LENGTH=1.0     #optional. Voice speaking rate, 1.0 is default with < 1.0 being faster and > 1.0 being slower.
- PIPER_NOISE=0.667 #optional
- PIPER_NOISEW=0.333 # optional. Controls the variability of speaking cadence. Values above 1 produce extreme stutters and pauses.
- PIPER_SPEAKER=0 #optional. Controls the variability of the voice by adding noise. Values above 1 will start to degrade audio.
- PIPER_PROCS=1 #optional. Number of Piper processes to run simultaneously.

The only one I could figure out is working in the homeassistant-yml is the option "voice" (see above).
I would expect to find all options in the homeassistant-docs somewhere.
