### ISSUE TITLE
Add simpler notification grouping example to group documentation.

### ISSUE THREAD

**Issue by lacrimal** [home-assistant/home-assistant.github.io#34633]
### Feedback

Please consider adding simple notification grouping example.
Since bunch of people move logic to node-red they often not using full blown notification grouping and what they want is group for example mobile apps:
```
notify:
  - name: all_phones
    platform: group
    services:
      - service: mobile_app_sm_g9730
      - service: mobile_app_sm_s901b
```
It is also important to have additional example since UI does not support it yet.

Thanks

### URL

https://www.home-assistant.io/integrations/group/

### Version

2024.9.1
