### ISSUE TITLE
Outdated YAML formatting in MQTT Siren integration examples

### ISSUE THREAD

**Issue by milkywade** [home-assistant/home-assistant.github.io#34648]
### Feedback

Outdated YAML formatting in MQTT Siren integration examples: https://www.home-assistant.io/integrations/siren.mqtt/

Somewhere over the last 12 months the YAML notation changed to this instead:

```
mqtt:
  siren:
    - unique_id: custom_siren
      name: "Intrusion siren"
      ...
```

### URL

https://www.home-assistant.io/integrations/siren.mqtt/

### Version

2024.9.1
