### ISSUE TITLE
Possible error in cover template integration documentation 

### ISSUE THREAD

**Issue by noosander** [home-assistant/home-assistant.github.io#34788]
### Feedback

The documentation for the cover template indicates the following configuration variables along with their valid outputs:
`value_template:` —> `open` , `opening` , `closed` , `closing`
`position_template:` —> numbers between `0` and `100`

The examples however seem to indicate the opposite.

Here the `value_template` define as `float`:
```
cover:
  - platform: template
    covers:
      garage_door:
        device_class: garage
        friendly_name: "Garage Door"
        value_template: "{{ states('sensor.garage_door')|float > 0 }}"
        open_cover:
          action: script.open_garage_door
        close_cover:
          action: script.close_garage_door
        stop_cover:
          action: script.stop_garage_door
```

And `position_template` with states `on` and `off`:

```
cover:
  - platform: template
    covers:
      garage_door:
        device_class: garage
        friendly_name: "Garage Door"
        position_template: "{{ states('sensor.garage_door') }}"
        open_cover:
          - condition: state
            entity_id: sensor.garage_door
            state: "off"
          - action: switch.turn_on
            target:
              entity_id: switch.garage_door
        close_cover:
          - condition: state
            entity_id: sensor.garage_door
            state: "on"
          - action: switch.turn_off
            target:
              entity_id: switch.garage_door
        stop_cover:
          action: switch.turn_on
          target:
            entity_id: switch.garage_door
        icon_template: >-
          {% if states('sensor.garage_door')|float > 0 %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}
```

### URL

https://www.home-assistant.io/integrations/cover.template/

### Version

2024.9.2
