### ISSUE TITLE
Example incorrect

### ISSUE THREAD

**Issue by 1iverea9er** [home-assistant/home-assistant.github.io#35032]
### Feedback

```
type: heading
heading: Living room
icon: mdi:sofa
badges:
  - type: entity
    entity_id: sensor.living_room_sensor_temperature
    color: red
  - type: entity
    entity_id: sensor.living_room_sensor_humidity
    color: deep-purple
```

### URL

https://www.home-assistant.io/dashboards/heading/

### Version

2024.10.0

### Additional information

Must be

```
type: heading
heading: Living room
icon: mdi:sofa
badges:
  - type: entity
    entity: sensor.living_room_sensor_temperature
    color: red
  - type: entity
    entity: sensor.living_room_sensor_humidity
    color: deep-purple
```
