### ISSUE TITLE
Suggested change to the example config

### ISSUE THREAD

**Issue by philshacks** [home-assistant/home-assistant.github.io#35278]
### Feedback

From some trial and error, I think it is necessary to include the port for the connection to the ebus adapter.
Adding the 'port' line as below worked for me. If this is needed in most cases it could be useful to add to example, and also include in the documentation that it is a valid parameter to pass.
```
# Example configuration.yaml entry
ebusd:
  host: 127.0.0.1
  port: 9999
  circuit: "700"
```
This is captured in the thread <a href="https://community.home-assistant.io/t/anyone-help-me-getting-ebusd-to-work-please/492805/9">here</a>.
Thanks :)

### URL

https://www.home-assistant.io/integrations/ebusd/

### Version

2024.10.2
