### ISSUE TITLE
Mix of sensorss names?

### ISSUE THREAD

**Issue by WallyDW** [home-assistant/home-assistant.github.io#35345]
### Feedback

Should the sensors not be either named "my" or" mqtt" everywhere in the example?

### URL

https://www.home-assistant.io/integrations/plant/

### Version

2024.10.3

**Comment by frenck** [comment]
> Should the sensors not be either named "my" or" mqtt" everywhere in the example?

I've been looking through the page, I didn't spot the inconsistency or error. I might be misunderstanding your feedback here. Could you add a little more details to your feedback that might help me understand your concern in this case?

Thanks! 👍 

../Frenck

**Comment by WallyDW** [comment]
It is the example I am looking at.
It looks like the MQTT sensors are named my_plant_.... and I guess those are supposed to be the ones used in the simulated_plant sensor, which are named  mqtt_plant_....

```
# Example configuration.yaml entry
plant:
  simulated_plant:
    sensors:
      moisture: sensor.mqtt_plant_moisture
      battery: sensor.mqtt_plant_battery
      temperature: sensor.mqtt_plant_temperature
      conductivity: sensor.mqtt_plant_conductivity
      brightness: sensor.mqtt_plant_brightness
    min_moisture: 20
    max_moisture: 60
    min_battery: 17
    min_conductivity: 500
    min_temperature: 15

sensor:
  - platform: mqtt
    name: my_plant_moisture
    state_topic: my_plant_topic
    value_template: "{{ value_json.moisture | int }}"
    unit_of_measurement: "%"
  - platform: mqtt
    name: my_plant_battery
    state_topic: my_plant_topic
    value_template: "{{ value_json.battery | int }}"
    unit_of_measurement: "%"
  - platform: mqtt
    name: my_plant_temperature
    state_topic: my_plant_topic
    value_template: "{{ value_json.temperature | float }}"
    unit_of_measurement: "°C"
  - platform: mqtt
    name: my_plant_conductivity
    state_topic: my_plant_topic
    value_template: "{{ value_json.conductivity | int }}"
    unit_of_measurement: "µS/cm"
  - platform: mqtt
    name: my_plant_brightness
    state_topic: my_plant_topic
    value_template: "{{ value_json.brightness | int }}"
    unit_of_measurement: "Lux"

```
