### ISSUE TITLE
Inconsistent use of trigger

### ISSUE THREAD

**Issue by basslet** [home-assistant/home-assistant.github.io#35364]
### Feedback

Your use of trigger in Template is inconsistent to automation triggers: 

The template docs state: https://www.home-assistant.io/integrations/template/#trigger-based-template-binary-sensors-buttons-numbers-selects-and-sensors

```
template:
  - trigger:
      - trigger: time_pattern
        hours: 0
        minutes: 0

```

In automations, you now use:
```
triggers: (with an s)
- trigger:
- trigger

```

Why the inconsistency?

### URL

https://www.home-assistant.io/integrations/template/

### Version

2024.10.3
