### ISSUE TITLE
Add a usefull automation example alerting potential new peaks?

### ISSUE THREAD

**Issue by ikke44** [home-assistant/home-assistant.github.io#35528]
### Feedback

I spend some time figuring out how to get a notification based on the DSMR integration data in HA, a lot of information I found is outdated and doesn't use the sensors the DSMR integration is providing out of the box.

Finally I've realized it can be as simple as this:
```
alias: kwartierpiek alarm (DSMR)
description: Notificatie voor dreigende nieuwe kwartierpieken op basis van DSMR integratie
triggers:
  - trigger: template
    value_template: >-
      {{ states("sensor.electricity_meter_current_average_demand") | float(0) >
      states("sensor.electricity_meter_maximum_demand_current_month") | float(0)*0.9 }}
conditions: []
actions:
  - variables:
      maandkwartierpiek: "{{ states(\"sensor.electricity_meter_maximum_demand_current_month\") }}"
      huidigkwartier: "{{ states(\"sensor.electricity_meter_current_average_demand\") }}"
  - action: notify.mobile_app_pixel_7a
    metadata: {}
    data:
      message: >-
        Nieuwe kwartierpiek dreigt... Momenteel {{ huidigkwartier|round(2) }}kW
        vs. maand {{ maandkwartierpiek|round(2) }}kW
      data: {}
mode: single
```
Hence I suggest adding an 'example' section to your documentation.

### URL

https://www.home-assistant.io/integrations/dsmr/

### Version

2024.10.4

### Additional information

The above provided example uses "dsmr_version": "5B" and "dsmr-parser==1.4.2" (as I've noticed that the names of the sensors the DSMR integration provides, depend on the DSMR version) and I am using the latest stable version (Core v2024.10.4).
