### ISSUE TITLE
Spelling error?

### ISSUE THREAD

**Issue by WallyDW** [home-assistant/home-assistant.github.io#35765]
### Feedback

In the second example on the page https://www.home-assistant.io/integrations/template/ the text starts like this:

```
# Example configuration entry
template:
  - trigger:
      - trigger: time_pattern
```

Should the first trigger line not be triggers instead?

### URL

https://www.home-assistant.io/integrations/template/

### Version

2024.11.1
