### ISSUE TITLE
Script (Conditions) have different format than the conditional card

### ISSUE THREAD

**Issue by YogoGit** [home-assistant/home-assistant.github.io#35778]
### Feedback

In the conditional card, the example for determining if a condition is valid is the following for an entity:
https://www.home-assistant.io/dashboards/conditional/#examples
```
type: conditional
conditions:
  - condition: state
    entity: light.bed_light
    state: "on"
  - condition: state
    entity: light.bed_light
    state_not: "off"
```

Note, it's ***entity***

However, for all other automations (triggers, conditions, etc...), as documented here

https://www.home-assistant.io/docs/scripts/conditions/#state-condition
```
conditions:
  - condition: state
    entity_id:
      - light.kitchen
      - light.living_room
    state: "on"
```

Note, it's using ***entity_id*** for the state condition, not ***entity***.

### URL

https://www.home-assistant.io/dashboards/conditional/

### Version

2024.11.1

### Additional information

It would be nice to have consistent syntax.
