### ISSUE TITLE
Unclear description boolean selector

### ISSUE THREAD

**Issue by gorgorgonzales** [home-assistant/home-assistant.github.io#35972]
### Feedback

In the documentation for the boolean selector is says:

> The output of this selector is true when the toggle is on, false otherwise.

But it seems that the selector only reports `false` when the the code also contains a `default: false`.

The Blueprint dose not work if the code is:
```
  test_boolean:
      name: Test
      selector:
        boolean: {}
```

But works just fine if the code is:
```
  test_boolean:
      name: Test
      default: false
      selector:
        boolean: {}
```

It would be great if this could be mentioned in the documentation, since it would make things a lot clearer.

Keep up the good work, Gregor

### URL

https://www.home-assistant.io/docs/blueprint/selectors/

### Version

2024.11.3
