### ISSUE TITLE
attachment

### ISSUE THREAD

**Issue by LouisPapy** [home-assistant/home-assistant.github.io#36227]
### Feedback

I use gmail integration but I am not succeding in attaching a photo to the mail. I have tried a lot of different code like 

```
action: notify.XXX_gmail_com
      data:
        title: photo
        message: passé devant la caméra
        target: XXX@orange.fr
        data: 
          images:
            - /config/www/snapshots/frontyard.jpg
```

with in the configuration.yaml :
```
homeassistant:
  allowlist_external_dirs:
    - /config/www/snapshots/
```
 
How to achieve this?

### URL

https://www.home-assistant.io/integrations/smtp/
