### ISSUE TITLE
External IP address

### ISSUE THREAD

**Issue by AndreMarschalek** [home-assistant/home-assistant.github.io#36368]
### Feedback

doc recommend using http://ip.jsontest.com/ but since few days the url results in 404 "Error: Page not found
The requested URL was not found on this server."

may be switch to https://api.ipify.org/?format=json

### URL

https://www.home-assistant.io/integrations/sensor.rest/

### Version

2024.12.3

**Comment by frenck** [comment]
Thanks, @AndreMarschalek 👍 

I've opened up a pull request to address the issue.

../Frenck

**Comment by cipnt** [comment]
I've just made the switch myself to `api.ipify.org/?format=json` but would also recommend that the documentation also adds the `unique_id` and `scan_interval` for this sensor.

```
sensor:
  - platform: rest
    name: External IP
    scan_interval: 3600
    unique_id: external_ip
    resource: https://api.ipify.org?format=json
    value_template: "{{ value_json.ip }}"
```
instead of just
```
sensor:
  - platform: rest
    resource: http://ip.jsontest.com
    name: External IP
    value_template: "{{ value_json.ip }}"
```
