### ISSUE TITLE
Intent Script configuration missing input parameters

### ISSUE THREAD

**Issue by fortuna** [home-assistant/home-assistant.github.io#36370]
### Feedback

The page says "If you are using intent script with LLMs and have parameters, make sure to mention the parameters and their types in the description.", but it doesn't explain how to declare the parameters in the intent config. There's also no explanation on how to refer to the parameters in the action.

### URL

https://www.home-assistant.io/integrations/intent_script/

### Version

2024.12.3

### Additional information

I'm trying to create an action to pause for X seconds, so I can make the assistant do actions that need timing, like blinking a light a few times.

I was writing something like this:
```yaml
intent_script:
  WaitForDuration:
    description: Pauses execution and waits for a duration of time given in the input
    # Where do I declare the input duration in seconds?
    mode: parallel
    action:
      delay:
        seconds:  ??? # How do I refer to the input duration here?
```
