### ISSUE TITLE
Pushover integration examples are unclear, data structure is outdated.

### ISSUE THREAD

**Issue by skywaymsn** [home-assistant/home-assistant.github.io#36584]
### Feedback

The integration YAML examples use both notify.entity_id and notify.notify to describe the action.

I recommend clarifying the integration by default is notify.pushover

Also, in the YAML the data section uses the following structure:

```
  - action: notify.pushover
    data:
      data:
        sound: siren
        priority: 2
      message: Message Body
      title: Message Title
```

### URL

https://www.home-assistant.io/integrations/pushover/

### Version

2024.12.5
