### ISSUE TITLE
Change documentation for Foscam - Example card with controls

### ISSUE THREAD

**Issue by LaZyCraZy71** [home-assistant/home-assistant.github.io#36594]
### Feedback

Due to the updates of HA, here is a working YAML code for the "Example card with controls" section.

Enjoy ! 😊

``` yaml
type: picture-elements
image: camera.interieur
camera_image: camera.interieur
camera_view: live
elements:
  - type: icon
    icon: mdi:arrow-up
    style:
      background: rgba(255, 255, 255, 0.5)
      right: 25px
      bottom: 50px
    tap_action:
      action: perform-action
      perform_action: foscam.ptz
      target:
        entity_id: camera.interieur
      data:
        movement: up
  - type: icon
    icon: mdi:arrow-down
    style:
      background: rgba(255, 255, 255, 0.5)
      right: 25px
      bottom: 0px
    tap_action:
      action: perform-action
      perform_action: foscam.ptz
      target:
        entity_id: camera.interieur
      data:
        movement: down
  - type: icon
    icon: mdi:arrow-left
    style:
      background: rgba(255, 255, 255, 0.5)
      right: 50px
      bottom: 25px
    tap_action:
      action: perform-action
      perform_action: foscam.ptz
      target:
        entity_id: camera.interieur
      data:
        movement: left
  - type: icon
    icon: mdi:arrow-right
    style:
      background: rgba(255, 255, 255, 0.5)
      right: 0px
      bottom: 25px
    tap_action:
      action: perform-action
      perform_action: foscam.ptz
      target:
        entity_id: camera.interieur
      data:
        movement: right
  - type: icon
    icon: mdi:arrow-top-left
    style:
      background: rgba(255, 255, 255, 0.5)
      right: 50px
      bottom: 50px
    tap_action:
      action: perform-action
      perform_action: foscam.ptz
      target:
        entity_id: camera.interieur
      data:
        movement: top_left
  - type: icon
    icon: mdi:arrow-top-right
    style:
      background: rgba(255, 255, 255, 0.5)
      right: 0px
      bottom: 50px
    tap_action:
      action: perform-action
      perform_action: foscam.ptz
      target:
        entity_id: camera.interieur
      data:
        movement: top_right
  - type: icon
    icon: mdi:arrow-bottom-left
    style:
      background: rgba(255, 255, 255, 0.5)
      right: 50px
      bottom: 0px
    tap_action:
      action: perform-action
      perform_action: foscam.ptz
      target:
        entity_id: camera.interieur
      data:
        movement: bottom_left
  - type: icon
    icon: mdi:arrow-bottom-right
    style:
      background: rgba(255, 255, 255, 0.5)
      right: 0px
      bottom: 0px
    tap_action:
      action: perform-action
      perform_action: foscam.ptz
      target:
        entity_id: camera.interieur
      data:
        movement: bottom_right
```

### URL

https://www.home-assistant.io/integrations/foscam/

### Version

2024.12.5
