### ISSUE TITLE
Improving Sensibo documentation: Case Sensitivity and Examples Needed

### ISSUE THREAD

**Issue by fx-host-assistant** [home-assistant/home-assistant.github.io#36637]
### Feedback

Hi everyone,

I’m trying to use the sensibo.full_state service to control my Sensibo devices, but the lack of detailed documentation is making it challenging.

The GitHub issue https://github.com/home-assistant/core/issues/94661 and documentation mention parameters are case-sensitive, but the documentation doesn’t explain this or how to align it with Home Assistant’s lowercase attributes (e.g.,  swing modes).
    Examples: There are no examples or links to Sensibo’s API documentation to clarify parameter formats or usage.
    Templates: It’s unclear if templates are supported and how to use them effectively.

I’m trying to replace a script that sends individual commands with one using sensibo.full_state, but I keep getting errors. Clearer documentation with examples would help greatly.

Can anyone share insights or examples?

Here is my original script
```
script:
  controlla_climatizzatore_camera_martinetto_caldo:
    alias: Controllo climatizzatore camera martinetto caldo
    mode: single
    sequence:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: climate.camera_martinetto
                attribute: temperature
                above: input_number.temperatura_massima_camera_martinetto
            sequence:
            -  service: climate.set_temperature
               target:
                 entity_id: climate.camera_martinetto
               data:
                 temperature: "{{ states('input_number.temperatura_massima_camera_martinetto') | float }}"
      - choose:
          - conditions:
              - condition: state
                entity_id: climate.camera_martinetto
                attribute: fan_mode
                state:
                  - "medium"
                  - "high"
            sequence:
              - service: climate.set_fan_mode
                target:
                  entity_id: climate.camera_martinetto
                data:
                  fan_mode: "auto"
      - choose:
        - conditions:
          - condition: state
            entity_id: climate.camera_martinetto
            attribute: swing_mode
            state:
            - 'fixedtop'
            - 'fixedmiddletop'
            - 'fixedmiddle'
          sequence:
          - service: climate.set_swing_mode
            target:
              entity_id: climate.camera_martinetto
            data:
              swing_mode: "fixedbottom"
```

and the full_state version that doesn't work
```
sequence:
  - action: sensibo.full_state
    data:
      mode: "{{ states('sensor.modo_climatizzatori_martinetto') }}"
      target_temperature: >
        {% if state_attr('climate.camera_martinetto', 'temperature') | float > states('input_number.temperatura_massima_camera_martinetto') | float %}
          {{ states('input_number.temperatura_massima_camera_martinetto') | float }}
        {% else %}
          {{ state_attr('climate.camera_martinetto', 'temperature') | float }}
        {% endif %}
      fan_mode: >
        {% if is_state_attr('climate.camera_martinetto', 'fan_mode', 'medium') or
              is_state_attr('climate.camera_martinetto', 'fan_mode', 'high') %}
          auto
        {% else %}
          {{ state_attr('climate.camera_martinetto', 'fan_mode') }}
        {% endif %}
      swing_mode: >
        {% if is_state_attr('climate.camera_martinetto', 'swing_mode', 'fixedtop') or
              is_state_attr('climate.camera_martinetto', 'swing_mode', 'fixedmiddletop') or
              is_state_attr('climate.camera_martinetto', 'swing_mode', 'fixedmiddle') %}
          fixedbottom
        {% else %}
          {{ state_attr('climate.camera_martinetto', 'swing_mode') }}
        {% endif %}
    target:
      entity_id: climate.camera_martinetto
description: ""

```

### URL

https://www.home-assistant.io/integrations/sensibo/
