### ISSUE TITLE
Back up integration in Home Assistant Container

### ISSUE THREAD

**Issue by Ren656** [home-assistant/home-assistant.github.io#36662]
### Feedback

I’m trying to create a backup automation. But using the example automations YAML of the Backup page of Home Assistant results in:

Error loading /config/configuration.yaml: mapping values are not allowed here
  in "/config/automations.yaml", line 36, column 13. 

The text I added to the automation.yaml was:

```
  - alias: "Backup Home Assistant every night at 3 AM"
    triggers:
      - trigger: time
        at: "03:00:00"
    actions:
      - alias: "Create backup now"
        action: backup.create
```

Please advice, what went wrong. I’m using core version 2024.12.1

Besides, from the documention I understand the backup will be stored in a file (“backups”) in the config directory of Home Assistant. Is there no way of using other locations like Google Drive?

### URL

https://www.home-assistant.io/integrations/backup/

### Version

2024.12.5
