### ISSUE TITLE
Apprise Integration Documentation

### ISSUE THREAD

**Issue by drshajul** [home-assistant/home-assistant.github.io#36788]
### Feedback

Some examples for the configuration would be useful.. 

**Example URL:**
```
  url: 
    - "hassio://user@hostname/accesstoken"
    - "mailtos://user:password@gmail.com?to=myemailaddress@gmail.com&format=text"
```
**Example Config File:**
```
  config: /config/apprise.yaml
```

Also, clarity on the configuration file location, where on the filesystem in core installation

### URL

https://www.home-assistant.io/integrations/apprise

### Version

2025.1

### Additional information

I am willing to fork the documentation and propose the changes.

**Comment by caronc** [comment]
A source i can additional share with you is a [very old blog entry which is on point](https://nuxref.com/2020/12/15/setup-apprise-notifications-on-home-assistant/).

Another thing that may be useful is some [old doc changes](https://github.com/home-assistant/home-assistant.io/pull/11461/files) I made. If you do the pr yourself, you could reuse some of this.

**Comment by LeeThompson** [comment]
As far as I can tell, sending notifications from HA to Apprise doesn't actually work as of Core 2025.7.3 (20250702.3).  

The original poster, those configuration urls are for Apprise, not HA.   There is confusion because you can have Apprise pull configuration from alternate URLs as well (and include that URL with the API call).

The way it's supposed to work.   I'm still doing tests before I make a bug report.   

## APPRISE

```
my_desktop=growl://desktop.local/?sticky=no
my_htpc=kodi://user:pass@htpc.local
my_rocketchat=rocket://(token)@rocketchat.local:3000/#notifications
my_homeassistant=hassio://homeassistant.local:8123/
```

## CURL 

`curl. -X POST  -F "body=Test Message" -F "type=info" -F "tags=my_desktop,my_htpc" http://apprise.server.local/notify/apprise`
(This would send to growl & KODI)

`curl -X POST  -F "body=Test Message" -F "type=info" -F "tags=my_homeassistant" http://apprise.server.local/notify/apprise`
(This would only send to HA)


`curl -X POST  -F "body=Test Message" -F "type=info" -F "tags=all" http://apprise.server.local/notify/apprise`
(This would send to everything listed in Apprise's configuration).

## Issues

In Home Assistant, you are supposed to be able to define the tags under "target" but Home Assistant just seems to ignore it.

**Comment by LeeThompson** [comment]
HA using Apprise to send notifications is completely broken.

**Comment by caronc** [comment]
I disagree; it's working fine for me, can you share your configuration and maybe we can spot what is going on; here is an example of what I have as an automation:
```yaml
#
# Automation Example with Apprise
#
- alias: "Just an action"
  trigger:
    <my triggers>

  condition:
  <my conditions>

  action:
  - service: notify.apprise
    data_template:
      target: my-family
      title: Alarm System Activated (Stay Mode)
      message: >-
        Nightly Stay Alarm activated at {{ now().strftime('%Y-%m-%d %H:%M:%S') }}.
```

the above would trigger by mapping `target` to a tag i defined in Apprise (assuming i just had defined local configuration.  Now in your case, you're not using Apprise directly (or defining your configuration locally), but through the (Apprise) API instead.  I this case, you're going to need to notify the Apprise API and trigger your defined URL by the `key` you identified.  Based on your example, your key is `apprise`.  What you need to do is let the Apprise Instance of Home Assistant known where it can find your Apprise API. 

There are several ways to solve your problem....

Create a `/config/apprise.conf` file in our HA configuration (put exactly what you put above in your example there) and somewhere define:
   ```yaml
   notify:
     name: apprise
     platform: apprise
     config: /config/apprise.conf
   ```
1. Leave your configuration centrally (one location - on your API).  I mean that's the beautify of Apprise, you can just define your configuration once and everyone else can use it).   BUT you still need to let Home Assistant know where this configuration is.   You can do the same as what I shared above, but instead, make sure your `/config/apprise.conf` has the following in it:
   ```
   include http://your.apprise.server/get/apprise
   ```
   This causes the local Apprise instance associated with Home Assistant to fetch it's configuration from the path you specify (which you already shared) and load it's configuration from there (remotely).   See [here for details](https://github.com/caronc/apprise/wiki/config_text#expanding-configuration-sources). Then you can go ahead and use the `target:` in HA Automations as you would expect.  IF however you're setting your Apprise API with the global variable `APPRISE_CONFIG_LOCK` to `yes` ([see here](https://github.com/caronc/apprise-api?tab=readme-ov-file#environment-variables)), then this approach won't work.  You can however still leverage the API (and keep your notifications centralized); but you need to create a different `/config/apprise.conf` file instead.
1. This is the option you would fall back to if `APPRISE_CONFIG_LOCK`  is set to `yes`.  Now you need to tell Home Assistance's instance of Apprise how it can still trigger the tags you set up.  You're already familiar with the `curl` calls which is perfect.  this is how you'll also define the configuration (below is an example of what a `/config/apprise.conf` may look like:
   ```
   # What you'll see is the re-use of the tags you're already aware of, and a relay of their use
   # To your upstream Apprise API server.
   my_desktop=apprise://apprise.server.local/apprise?tags=my_desktop
   my_htpc=apprise://apprise.server.local/apprise?tags=my_htpc
   my_rocketchat=apprise://apprise.server.local/apprise?tags=my_rocketchat
   my_homeassistant=apprise://apprise.server.local/apprise?tags=my_homeassistant
   ```


Again... ALL of the above assumes your Home Assistant Configuration defines an Apprise configuration. Remember, the Home Asisstant Apprise Library does not know about your Apprise API hosted instance unless you tell it (defined above).
```yaml
notify:
  name: apprise
  platform: apprise
  config: /config/apprise.conf
```

How you define the configuration purely comes down to how locked up your Apprise setup is.

**Comment by LeeThompson** [comment]
Your syntax doesn't seem to match HA, did you mean something else?

Most of the information you're giving is for **Apprise**, not HA.  My Apprise instance works **outside** of _Home Assistant_ just fine.

My issue is HA's notification *to* Apprise is not working, at all. 

This is my HA config for apprise:

```
notify:
  - platform: apprise
    name: apprise
    url: http://notify.local/notify/apprise
```

(NOTE: I have replaced my actual intranet domain with `.local` here for privacy/security reasons.)


Also your HA notification action is not like mine:

```
sequence:
  - action: notify.apprise
    metadata: {}
    data:
      message: This is a test.
      target: my_desktop
alias: Apprise Test 1
description: ""
```

My Apprise not using `APPRISE_CONFIG_LOCK`.

**Comment by caronc** [comment]
Try changing your `url` defnition to `http://notify.local/get/apprise`  (note the `/get`)

**Comment by LeeThompson** [comment]
> Try changing your `url` defnition to `http://notify.local/get/apprise` (note the `/get`)

That causes the integration to fail to load.

Trying again with the `config:` url removed.

UPDATE:

Yeah this configuration causes Apprise integration not to load at all:

```
notify:
  - platform: apprise
    name: apprise
    url: http://notify.local/get/apprise
```

**Comment by LeeThompson** [comment]
@caronc I'm back to this in my HA configuration.yaml:



```
notify:
  - platform: apprise
    name: apprise
    url: http://notify.local/notify/apprise
    config: http://notify.local/get/apprise
```

Changing `url` to `http://notify.local/get/apprise` causes the HA Apprise integration not to load.  Not sure why.

**Comment by LeeThompson** [comment]
This is still broken.   I cannot get HomeAssistant to send a notification using Apprise no matter what.

**Comment by caronc** [comment]
Try setting your home assistant config to:
```yaml
notify:
  - platform: apprise
    name: apprise
    config: http://notify.local/get/apprise
```

Also make sure Apprise is accessible from your home assistant container:

```bash
# Maybe try something like:
docker exec -it homeassistant /bin/sh
curl -v http://notify.local/get/apprise
```

It could be a DNS issue from within the hassio container. You could always try by the IP to rule that out.

The `url` and `target` entries pair with the automation itself. See examples above I shared.

I presume your not forgetting the Apprise API port? Out of the box, it might be on port 8000. Try: 

```bash
# possibly..
docker exec -it homeassistant /bin/sh
curl -v http://notify.local:8000/get/apprise

# or swap the below with the actual IP of your Apprise server
curl -v http://ip.add.re.ssl:8000/get/apprise

```

Get the curl working from your Home Assistant server, then swap the value into the `config`.

**Comment by LeeThompson** [comment]
I've already done all that.   I can use curl on a bash terminal in the Home Assistant container and have it work successfully.   From within Home Assistant it does not work.    

(I use a tag setup with Apprise.) 

NOTES:

* I've changed the url to `http://notify.[redacted]/notify/apprise` so my domain doesn't show up in public.
* The port 8000 isn't necessary since "`notify.[redacted]`" points to Traefik which handles the port redirection.   Before you ask I've tried setting it up in Home Assistant to be direct using the IP address and port number and there is no difference.


From HomeAssistant's container (docker on a Synology NAS):
```
HomeAssistant:/# curl -X POST -F "body=This is a test" -F "type=info" -F "tags=desktop" -F "title=Test" http://notify.[redacted]/notify/apprise
2025-12-04 23:23:34,833 [INFO] apprise: Loaded 11 entries from memory://                                   
2025-12-04 23:23:34,850 [INFO] apprise: Sent Growl notification
```

(The notification then appears in Growl on my Windows desktop).



From HomeAssistant's container:
```
HomeAssistant:/# curl -v http://notify.[redacted]/get/apprise                                            
* Host notify.[redacted]:80 was resolved.                                                                
* IPv6: (none)                                                                                             
* IPv4: 192.168.0.195                                                                                      
*   Trying 192.168.0.195:80...                                                                             
* Connected to notify.[redacted] (192.168.0.195) port 80                                                 
* using HTTP/1.x                                                                                           
> GET /get/apprise HTTP/1.1                                                                                
> Host: notify.[redacted]                                                                                
> User-Agent: curl/8.14.1                                                                                  
> Accept: */*                                                                                              
>                                                                                                          
* Request completely sent off                                                                              
< HTTP/1.1 405 Method Not Allowed                                                                          
< Allow: POST, OPTIONS                                                                                     
< Cache-Control: max-age=0, no-cache, no-store, must-revalidate, private                                   
< Content-Length: 0                                                                                        
< Content-Type: text/html; charset=utf-8                                                                   
< Date: Fri, 05 Dec 2025 05:28:24 GMT                                                                      
< Expires: Fri, 05 Dec 2025 05:28:24 GMT                                                                   
<

```

**Comment by caronc** [comment]
Error 405 sounds like your Apprise configuration has the environment variable `APPRISE_CONFIG_LOCK` set, see [here](https://github.com/caronc/apprise-api?tab=readme-ov-file#environment-variables).

**Comment by LeeThompson** [comment]
> Error 405 sounds like your Apprise configuration has the environment variable `APPRISE_CONFIG_LOCK` set, see [here](https://github.com/caronc/apprise-api?tab=readme-ov-file#environment-variables).

`APPRISE_CONFIG_LOCK` is not set.

Env for the container are as follows;
`PATH`
`LANG`
`GPG_KEY`
`PYTHON_VERSION`
`PYTHON_SHA256`
`PYTHONDONTWRITEBYTECODE`
`PYTHONUNBUFFERED`
`APPRISE_CONFIG_DIR`
`APPRISE_ATTACH_DIR`
`APPRISE_PLUGIN_PATHS`
`TZ` (not sure if this does anything with Apprise; I usually set it out of habit)

**Comment by caronc** [comment]
Ah, I spotted the error: try the following from inside your home assistant server:
```bash
:/# curl -X POST -v http://notify.[redacted]/get/apprise
```

This will likely work judging by the 405 you already got.

 Double check your configuration line. You were using `url` before. You need to use `config`:
```yaml
notify:
  name: apprise
  platform: apprise
  config: http://notify.[redacted]/get/apprise
```


That's all you should need. The Apprise library under the hood knows to load that URL by posting to it. Then create an action like: 
```yaml
#
# Automation Example with Apprise
#
- alias: "Just an action"
  trigger:
    <my triggers>

  condition:
  <my conditions>

  action:
  - service: notify.apprise
    data_template:
      target: desktop
      title: Desktop Notification 
      message: >-
        Message to desktop activated at {{ now().strftime('%Y-%m-%d %H:%M:%S') }}.
```

I can't reproduce your issue, so there is something unique still to your HA environment if this doesn't work. What version of HA are you using?

Can you share your HA logs surrounding the initialization of Apprise (on startup)?
