### ISSUE TITLE
Can't get Microsoft TTS integration to work

### ISSUE THREAD

**Issue by ddppddpp** [home-assistant/home-assistant.github.io#36849]
### Feedback

Following the provided instructions doesn't lead to a working Microsoft TTS integration. There are no error messages logged. There are no entities created.

### URL

https://www.home-assistant.io/integrations/microsoft/

### Version

2025.1.1

### Additional information

Configuration:
```
tts:
  platform: microsoft
  api_key: ***
  language: 'bg-bg'
  gender: 'Male'
  type: 'BorislavNeural'
  rate: 20
  volume: -50
  pitch: high
  contour: (0, 0) (100, 100)
  region: westeurope
```
