### ISSUE TITLE
Calendar trigger and conditions through the UI example documenation

### ISSUE THREAD

**Issue by Floriszz** [home-assistant/home-assistant.github.io#37230]
### Feedback

I had a hard time using the documentation(https://www.home-assistant.io/integrations/calendar/) for calendar trigger and conditions when using the Homeassistant UI, while this needs to be added in 'Edit yaml' mode, while the documentation is for when you edit the yaml directly in a yaml configuration file.
Would be nice for others to add my example when trying to use the calendar for trigger and condition through the Homeassistant UI.

In this example I have a Google Calender with the name: automations.

**Example trigger**
```
trigger: calendar
entity_id: calendar.automations
event: start
alias: Calendar automations
```

**Example conditions**
Example with a single condition:
```
condition: template
value_template: "{{ 'Front Lights' in trigger.calendar_event.summary }}"
alias: Front Lights on-off
```

Example with 2 different events in the calendar:
```
condition: or
conditions:
  - condition: template
    value_template: "{{ 'Front Lights' in trigger.calendar_event.summary }}"
    alias: Front Lights on-off
  - condition: template
    value_template: "{{ 'Back Lights' in trigger.calendar_event.summary }}"
    alias: Back Lights on-off
```

### URL

https://www.home-assistant.io/integrations/calendar/

### Version

2025.1.4

### Additional information

As you can see there is a slight different in format between editing the yaml in a yaml configurationn file or when editing the yaml through the UI. For example the '-' in front of trigger must not be added.
