### ISSUE TITLE
Documentation for the Google Sheets integration is missing a couple of key insights

### ISSUE THREAD

**Issue by ajfhodgson** [home-assistant/home-assistant.github.io#37245]
### Feedback

Thanks for this integration. 

I was trying to use this in a Blueprint, and therefore writing YAML rather than using the UI to create an automation. I struggled for an hour before stumbling across https://github.com/home-assistant/core/issues/79731#issuecomment-1276534254

Two key points that would have helped me if they had been in your written documentation:
- the `config_entry`: is **NOT** the google doc id as you might expect, (but is supplied automatically and silently in the UI automation creation process). Please mention this in the Create event action details box.
- for the content of the `data` dictionary, they `key` is the column header under which to write the data (created if does not exist), the `value` is what is written under that column. Obvious in hindsight but not at all from the words.

"**_Dictionary of_** data to be appended to the worksheet. This puts the data on new rows, one value per column **_in columns headed by the keys, column headers being created if they do not already exist_**.

For people who like to read rather than watch videos: It would be REALLY helpful to show a screenshot of the spreadsheet resulting from your example:
```
# Example action
action: google_sheets.append_sheet
data:
  config_entry: 1b4a46c6cba0677bbfb5a8c53e8618b0
  worksheet: "Car Charging"
  data:
    Date: "{{ now().strftime('%-d-%b-%y') }}"
    KWh: "{{ states('input_number.car_charging_kwh')|float(0) }}"
    Cost: "{{ states('input_number.car_charging_cost')|float(0) }}"

# Example action with multiple rows
action: google_sheets.append_sheet
data:
  config_entry: 1b4a46c6cba0677bbfb5a8c53e8618b0
  worksheet: "Car Charging"
  data:
    - Item: "Car 1 cost"
      Cost: "{{ states('input_number.car_1_charging_cost')|float(0) }}"
    - Item: "Car 2 cost"
      Cost: "{{ states('input_number.car_2_charging_cost')|float(0) }}"

```

This would clearly show the utilisation of the dictionary keys to create columns:

```
created        Date        KWh   Cost    Item
.......     12-12-2023    12.3  34.00
.......                         68.22    Car 1 cost
.......                         86.23    Car 2 cost

```
This would have got across very clearly the creation of columns when needed, and saved me a LOT of time and puzzlement.

### URL

https://www.home-assistant.io/integrations/google_sheets/

### Version

2025.1.4
