### ISSUE TITLE
Add some example on how to use piper with tts.speak for a given language and voice.

### ISSUE THREAD

**Issue by FabienD74** [home-assistant/home-assistant.github.io#37275]
### Feedback

Hi, It would be nice to include in the documentation a small example of tts.speak using a given languange AND voice
Otherwise it falls back to the defaults setting in piper. ... :-( :-(
PS: I think it's still mandatory to change the settings in piper to FORCE IT to download the new voice. not sure.
My 2 cents: please note the "options:" below:
```
  - action: tts.speak
    target:
      entity_id: tts.piper
    data:
      cache: false
      media_player_entity_id: media_player.esp32_s3_media_player
      message: Ceci et un test
      language: fr_FR
      options:
        voice: fr_FR-siwis-medium
```

### URL

https://www.home-assistant.io/integrations/piper/

### Version

2025.1.4
