### ISSUE TITLE
Muliple routers

### ISSUE THREAD

**Issue by tamas-unter** [home-assistant/home-assistant.github.io#37350]
### Feedback

How can I configure multiple instances? I have 4 DD-WRT routers here and would like to collect wireless information from each.

### URL

https://www.home-assistant.io/integrations/ddwrt/

### Version

2025.2.0

### Additional information

I have tried using "name" and "unique_name" for identification but those are unknown keywords in the yaml according to the log.

**Comment by frenck** [comment]
Hi there @tamas-unter 👋 

Thank you for reaching out. We use GitHub for tracking documentation feedback, not for providing support. However, I can answer your question quickly I think.

This is the example from the docs:

```yaml
# Example configuration.yaml entry
device_tracker:
  - platform: ddwrt
    host: ROUTER_IP_ADDRESS
    username: YOUR_ADMIN_USERNAME
    password: YOUR_ADMIN_PASSWORD
```

In YAML the `-` (dash) there indicates it is a list. Once can extend that list with as many items as you'd like. For example:

```yaml
# Example configuration.yaml entry
device_tracker:
  - platform: ddwrt
    host: ROUTER_IP_ADDRESS
    username: YOUR_ADMIN_USERNAME
    password: YOUR_ADMIN_PASSWORD
  - platform: ddwrt
    host: SECOND_ROUTER_IP_ADDRESS
    username: YOUR_ADMIN_USERNAME
    password: YOUR_ADMIN_PASSWORD
```

Anyway,  if you are in need for more support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍 

../Frenck
