### ISSUE TITLE
Cannot create Webhook using the yaml code in the documentation

### ISSUE THREAD

**Issue by daniel-finger** [home-assistant/home-assistant.github.io#37443]
### Feedback

When trying to use the code in
```
template:
  - trigger:
      - trigger: webhook
        webhook_id: my-super-secret-webhook-id
    sensor:
      - name: "Webhook Temperature"
        state: "{{ trigger.json.temperature }}"
        unit_of_measurement: °C

      - name: "Webhook Humidity"
        state: "{{ trigger.json.humidity }}"
        unit_of_measurement: %

    binary_sensor:
      - name: "Motion"
        state: "{{ trigger.json.motion }}"
        device_class: motion
```
it cannot be parsed:
```
bad indentation of a mapping entry (37:30)

 34 | 
 35 |       - name: "Webhook Humidity"
 36 |         state: "{{ trigger.json.humidity }}"
 37 |         unit_of_measurement: %
-----------------------------------^
```
I am new to homeassistant, but it seems via GUI I can only set specific helper templates via webhook and not a generic sensor?

### URL

https://www.home-assistant.io/integrations/template/

### Version

2025.2.3
