### ISSUE TITLE
Automation for nearby Earthquake detection

### ISSUE THREAD

**Issue by claudy-us** [home-assistant/home-assistant.github.io#37778]
### Feedback

I'm struggling to create an automation that triggers when an earthquake is detected nearby. The problem is that a dynamic entity is generated when this event occurs. I'm trying to catch this event. but it is not as simple as a direct attribute automation.
I tried getting the attributes first, but as it is a new entity, I wouldn't be able to catch it.
Now I'm trying to get an event, but I think the way it is is somewhat inneficient (1st Code)

Maybe this way is a little better, but I have to wait for an earthquake to see if it works... (2nd Code)
 
I will be glad if someone could point me in the right direction.

### URL

https://www.home-assistant.io/integrations/usgs_earthquakes_feed/

### Version

2025.2.5

### Additional information

1st Automation:
```
alias: Earthquake Notification
description:
Notify via TTS when a significant earthquake occurs.
triggers:
  - trigger: event
    event_type: state_changed
condition:
  - condition: template
    value_template: >
      {{ 'geo_location' in trigger.event.data.entity_id }}
  - condition: template
    value_template: >
      {{ trigger.event.data.new_state.attributes.magnitude | float > 4.0 }}
  - condition: template
    value_template: >
      {{ trigger.event.data.new_state.state | float < 50 }} 
```
Second Automation:
```
alias: Earthquake Notification - Optimized
description: Notify via TTS when significant earthquakes occur dynamically and efficiently.
trigger:
  - platform: template
    value_template: >
      {{ trigger.event.data.new_state and
         trigger.event.data.new_state.domain == 'geo_location' and
         'usgs_earthquakes_feed' in trigger.event.data.new_state.attributes.source and
         trigger.event.data.new_state.attributes.magnitude | float > 4.0 and
         trigger.event.data.new_state.state | float < 50 }}
```
