### ISSUE TITLE
Spotify doesnt keep Cast devices in the Device list

### ISSUE THREAD

**Issue by Narimm** [home-assistant/home-assistant.github.io#38095]
### Feedback

I had been using spotify to play a morning alarm playlist 
For the past 3 mths it simply no longer works.

From what I can see spotify is much more aggressive at removing old cast devices from the permanent device list. Thus the spotify integration gets a very short device list

On this [page ](https://www.home-assistant.io/integrations/spotify/#selecting-output-source )it talks about using 
```
data: 
  source: "SourceName"
```

I use  Google Cast Speaker(Nest) called "House" but its not in the list that being sent - if I set spotify to playing and then review the attributes I can see
```
source_list:
  - Web Player (Chrome)
  - Web Player (Chrome)
  - Chromecast HD
  - Web Player (Chrome)
friendly_name: Spotify Ben Charlton
supported_features: 444983
volume_level: 0.08
media_content_id: spotify:track:3LI4MmibTkXH5cGpCGZgyw
media_content_type: music
media_duration: 242
media_position: 16
media_position_updated_at: "2025-03-20T10:04:22.384799+00:00"
media_title: Teenage Dirtbag
media_artist: Wheatus
media_album_name: Songs From Dawson's Creek, Vol. II
media_track: 10
media_playlist: Poker for Oc
source: House
shuffle: true
repeat: all
entity_picture: >-
  /api/media_player_proxy/media_player.spotify_xxxxxxxx?token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
```
You can see the device works fine via Spotify - however if I use the following action:->
```
action: media_player.play_media
metadata: {}
data:
  media_content_id: https://open.spotify.com/playlist/6cdwqGZuL9uA6wQaOlC5Hw
  media_content_type: playlist
  source: "House"
target:
  entity_id: media_player.spotify
```
I get the error 
```
Error running action
extra keys not allowed @ data['source']. Got None
```

### URL

https://www.home-assistant.io/integrations/spotify/

### Version

2025.3.3
