### ISSUE TITLE
For Automations, how to only "start" the laundry with settings done locally on the machine

### ISSUE THREAD

**Issue by Stefan-Linux** [home-assistant/home-assistant.github.io#38330]
### Feedback

Hi,
I try to start a Siemens Laundry machine with **HomeConnect** integration. I managed to start the cotton program. But I would like to simply start _whatever_ was setup locally on the machine. (This is for better usage of Solar Power)
Note: I have a similar issue on my dishwasher. But as I use only a single program, it's not that problematic there. 

The action I use so far:
```
data:
  device_id: 14c5e38aed7ab23cff734ad6a8ca5deb
  affects_to: active_program
  program: laundry_care_washer_program_cotton
action: home_connect.set_program_and_options
```

What I would like to use to start the current program (but the function call returns empty) - I tried to read back the selected program:
```
data:
  device_id: 14c5e38aed7ab23cff734ad6a8ca5deb
  affects_to: active_program
  program: {{ states('select.wm_or10_0_ausgewahltes_programm') }}
action: home_connect.set_program_and_options
```

I did lots of testing and experimenting, but did not find a solution for this.
In the HomeConnect App itself, there is a "play" button... that's what I'm missing inside homeassistant/homeconnect.

Note:
This would also be a great improvement for the documentation. To tell how to simply "start" the already configured program.

Thanks
 Stefan

### URL

https://www.home-assistant.io/integrations/home_connect

### Version

2025.3.4
