### ISSUE TITLE
Update documentation with instructions for custom attributes

### ISSUE THREAD

**Issue by jrb80** [home-assistant/home-assistant.github.io#38404]
### Feedback

I didn't realise this integration supports custom attributes until I stumbled upon it under the "configure" menu. I believe a section in the documentation should be created for this feature as it's so useful. I've included a snip of my configuration for reference.

![Image](https://github.com/user-attachments/assets/1a0927dd-9016-4e40-8207-2d98193cf548)

It may be also useful to show a template example to create a sensor from the custom attribute, for example;

Ignition
```
 binary_sensor:
  - name: "Traccar Mercedes Ignition"
    unique_id: traccar_mercedes_ignition
    icon: mdi:car-key
    state: "{{ state_attr('device_tracker.traccar_mercedes', 'ignition') }}"
```

Mileage
```
sensor:
  - name: "Traccar Mercedes Odometer"
    unique_id: traccar_mercedes_odometer
    icon: mdi:counter
    state: "{{ state_attr('device_tracker.traccar_mercedes', 'odometer') }}"
```

### URL

https://www.home-assistant.io/integrations/traccar_server/

### Version

2025.4.1
