### ISSUE TITLE
Templates not showing up in Google Generative AI sample script

### ISSUE THREAD

**Issue by sashabu** [home-assistant/home-assistant.github.io#38480]
### Feedback

The script that was added in https://github.com/home-assistant/home-assistant.io/pull/38391 (/cc @tronikos ) is not rendering correctly. Specifically, the `sequence` part is showing up as:

```
sequence:
  - action: conversation.process
    metadata: {}
    data:
      agent_id: conversation.google_generative_ai_2
      text: ""
    response_variable: result
  - variables:
      result:
        response: ""
  - stop: ""
    response_variable: result
```

Note that both the `text` and `response` are empty strings, whereas the PR that added them has templates in double curlies.

### URL

https://www.home-assistant.io/integrations/google_generative_ai_conversation/

### Additional information

Copy-pasting the script as is causes hard to diagnose issues: it still parses correctly, but since no text is passed to the search-enabled LLM or returned to the caller, the user sees the same behaviour as without the script (the calling LLM calls the script, doesn't get anything back, and falls back to its built-in knowledge).
