### ISSUE TITLE
Nanoleaf documentation lacking details on how to handle swipe events

### ISSUE THREAD

**Issue by varenc** [home-assistant/home-assistant.github.io#38562]
### Feedback

A recent-ish update to Home Assistant has created this warning:

<img width="491" alt="Image" src="https://github.com/user-attachments/assets/ab94aae6-c4c6-4efc-b8d8-e2717fb49ffb" />

Essentially I believe it means that the easy automation triggers like this, as Home Assistant suggests when creating an automation from the device page, no longer work:
```
domain: nanoleaf
device_id: 95ab7099a3b8bdd3b40cd0ee82379b66
type: swipe_down
trigger: device
enabled: false
alias: Nanoleaf Canvas swipe down (deprecated)

```

Instead I believe the new solution is something like this:
```
trigger: event
event_type: nanoleaf_event
event_data:
  device_id: 95ab7099a3b8bdd3b40cd0ee82379b66
  type: swipe_down
```

However, creating that manual event is impossible from the HA automation GUI only and requires editing YAML. That's fine, but there's no documentation on this on the HA website: https://www.home-assistant.io/integrations/nanoleaf/

Alternatively, I believe a trigger like this could work:
```
trigger: state
entity_id:
  - event.nanoleaf_canvas_touch_gesture
attribute: event_type
to: swipe_down
```

But the trouble with that is that it only triggers on state changes, so successive triggers of "swipe down" don't trigger it. This can be changed so that it triggers on any update, but then you need to use additional logic to determine the event_type. Hence why it seems like the `trigger: event` above is the better approach?

Though I'm not really sure what the correct approach is since there's no documentation [on it here](https://www.home-assistant.io/integrations/nanoleaf/) 😇.

tl;dr; the nanoleaf integration documentation page should document how to use gesture event triggers

### URL

https://www.home-assistant.io/integrations/nanoleaf/

### Version

2025.4.2

### Additional information

Also worth mentioning is that the repair warning says the old device based trigger will be removed in 2025.1.0, but as of 2025.4.2 it still appears to be working for me. Perhaps it's not being deprecated? And either way, the built in tooling to create an automation on the Nanoleaf Canvas device page shouldn't be suggesting the use of the device based trigger if this is going to be deprecated.

**Comment by milanmeu** [comment]
It is still possible to create the trigger in the user interface, but it has become more difficult.

The documentation is not on the Nanoleaf integration page, but on the general event integration page, as these apply to all event entities: https://www.home-assistant.io/integrations/event/.

> But the trouble with that is that it only triggers on state changes, so successive triggers of "swipe down" don't trigger it

The state of an "event" entity is the timestamp of the event, so it will trigger for every touch. You can add a condition to filter for specific event types.

Here is an example created from the UI:

![Image](https://github.com/user-attachments/assets/858e6f91-3568-427f-b347-7d11b2494e4d)

```yaml
alias: Nanoleaf swipe up to turn on/off
triggers:
  - trigger: state
    entity_id:
      - event.canvas_adf9_touch_gesture
conditions:
  - condition: state
    entity_id: event.canvas_adf9_touch_gesture
    attribute: event_type
    state: swipe_up
actions:
  - type: toggle
    device_id: 7bf4da65e8a65079bb3483ccf3292ce0
    entity_id: aeff57bcc929ed63328f9552ff4930ae
    domain: light
mode: single

```
