### ISSUE TITLE
Verbindungsverlust

### ISSUE THREAD

**Issue by itsajokeor** [home-assistant/home-assistant.github.io#38697]
### Feedback

Hi ich habe jeden Tag das Problem das die Verbindungen gegen Abend nichts mehr anzeigen, heisst wie Serververbindung die plötzlich fehlt, habe ich bei keiner anderen Integration. Was kann das sein? Am nächsten Morgen läuft sie dann wieder!

### URL

https://www.home-assistant.io/integrations/swiss_public_transport/

### Version

2025.4.3

**Comment by itsajokeor** [comment]
Ich lasse mal das Debug Protokoll laufen um zu sehen was passiert.

**Comment by miaucl** [comment]
Hallo, du wirst wahrscheinlich mehr als eine Verbindung konfiguriert haben? Dann läufst du nämlich in das rate limit der API (siehe ersten Abschnitt der Integration Docs).

<img width="878" alt="Image" src="https://github.com/user-attachments/assets/47229be9-bc63-4882-8a5e-82cf005aaba1" />

In dem Fall musst du "Custom polling" verwenden und zum Beispiel in der Nacht die Updates pausieren oder die Frequenz runterschrauben.
https://www.home-assistant.io/integrations/swiss_public_transport/#defining-a-custom-polling-interval

Ich habe 4 Verbindungen aktiv die zwischen 00h00 und 06h00 nicht aktiv sind und tagsüber alle 3 minuten aktualisieren. Damit komme ich knapp unter 1000 requests durch pro Tag. 

Da ist leider ein bisschen Kreativität gefragt seitens Nutzer :)

Ich hoffe ich konnte helfen.

**Comment by miaucl** [comment]
PS: Für Abfahrstabellen kann auch folgendes Tool verwendet werden
https://www.oevplus.ch/departures/

**Comment by itsajokeor** [comment]
Vielen Dank für deine Antwort, ich bin blutiger Anfänger sorry🙈 Evtl. kannst du mir ein wenig helfen? Muss ich eine Automation erstellen? Für dieses custom Polling?Für ÖVplus gibt es da eine integration? Oder via API?Beste GrüsseSerge GuggerAm 23.04.2025 um 22:18 schrieb Cyrill Raccaud ***@***.***>:﻿
miaucl left a comment (home-assistant/home-assistant.io#38697)
PS: Für Abfahrstabellen kann auch folgendes Tool verwendet werden
https://www.oevplus.ch/departures/

**Comment by miaucl** [comment]
öVplus kannst du einfach als iframe einbinden in den dashboards (wie eine x-beliebige website), aber nicht für automationen verwenden. Wenn du dazu fragen hast, gibt es in der HA community genug anleitungen und sonst auf discord fragen :)

Custom polling sollte eigentlich hier gut beschrieben sein: https://www.home-assistant.io/integrations/swiss_public_transport/#defining-a-custom-polling-interval

1. Default polling für alle Verbindungen abschalten (System Options)

<img width="785" alt="Image" src="https://github.com/user-attachments/assets/22700075-f153-4441-8345-06f7eb541bc4" />

2. Eine Automation schreiben, die jede Verbindung dann aktualisiert wenn du es willst. Hier meine zwei Beispiele für Metro und Zug

```
alias: SPT Automation All Day Frequency (Train)
description: ""
triggers:
  - minutes: /5
    trigger: time_pattern
conditions:
  - condition: time
    after: "05:00:00"
    before: "08:00:00"
    weekday:
      - fri
      - thu
      - wed
      - tue
      - mon
      - sat
      - sun
actions:
  - action: homeassistant.update_entity
    metadata: {}
    data:
      entity_id:
        - sensor.lausanne_nyon_at_07_10_00_departure
        - sensor.lausanne_zurich_at_07_15_00_departure
    alias: Update entities
mode: single
```

```
alias: SPT Automation All Day Frequency (Metro)
description: ""
triggers:
  - minutes: /5
    trigger: time_pattern
conditions:
  - condition: time
    after: "06:30:00"
    before: "23:00:00"
    weekday:
      - fri
      - thu
      - wed
      - tue
      - mon
      - sat
      - sun
actions:
  - action: homeassistant.update_entity
    metadata: {}
    data:
      entity_id:
        - sensor.fourmi_croisettes_in_00_05_00_departure
        - sensor.fourmi_ouchy_in_00_05_00_departure
    alias: Update entities
mode: single
```

<img width="524" alt="Image" src="https://github.com/user-attachments/assets/e0501815-068c-43ed-9e67-bc57177b6728" />

Ich hoffe ich konnte dir helfen.

Github ist eigentlich keine Support Platform, daher empfehle ich dir weitere Fragen auf dem Discord zu stellen. Ich werde dieses Issue hiermit schliessen.
