### ISSUE TITLE
Bad YAML in example

### ISSUE THREAD

**Issue by mmanski-cv** [home-assistant/home-assistant.github.io#39199]
### Feedback

All examples with trigger have incorrect indentation of entity definition. 
```YAML
template:
  - triggers:
      - trigger: webhook
        webhook_id: my-super-secret-webhook-id
    sensor:
``` 
correct is:
```YAML
template:
  - triggers:
      - trigger: webhook
        webhook_id: my-super-secret-webhook-id
        sensor:
``` 

### URL

https://www.home-assistant.io/integrations/template/

### Version

2025.5.3
