### ISSUE TITLE
example yaml code throws error

### ISSUE THREAD

**Issue by IceBlackz** [home-assistant/home-assistant.github.io#39204]
### Feedback

When trying to copy paste the example code and saving it, it throws the following error: 

Message malformed: extra keys not allowed @ data['0'] 

As inexperienced using automations I would not know how to solve this, as I do not know the basic/correct structure. The error code is also very vague as it doesn't point where the error actually is (line number etc.) 

### URL

https://www.home-assistant.io/integrations/google_travel_time/

### Version

2025.5.3

**Comment by IceBlackz** [comment]
Turns out I used the wrong sensor name. Could be useful to note where to find it! I also think the dash in front of alias is incorrect, but didn't test that

**Comment by nowthatsorignal** [comment]
I am also having the same issue but I do have the sensor name correct were you able to figure it out?

**Comment by IceBlackz** [comment]
Hi @nowthatsorignal , yes I made it work (and expanded it a little) with the following:

```
alias: Update reistijd 's ochtends
description: >-
  Om de API polling rate niet te overschrijden, alleen de reistijd 's ochtends
  updaten met een interval elke minuut, als of <owner 1>, of <owner 2> thuis is.
triggers:
  - trigger: time_pattern
    minutes: /1
conditions:
  - condition: time
    after: "06:30:00"
    before: "11:00:00"
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: or
    conditions:
      - condition: device
        device_id: <mobile device 1, entered through GUI editor>
        domain: device_tracker
        entity_id: <mobile device 1, entered through GUI editor>
        type: is_home
      - condition: device
        device_id: <mobile device 2, entered through GUI editor>
        domain: device_tracker
        entity_id: <mobile device 2, entered through GUI editor>
        type: is_home
actions:
  - action: homeassistant.update_entity
    data:
      entity_id:
        - sensor.<name>
initial_state: "on"

```

Where < name > could be found here:

Settings -> Devices -> Entities -> Open your entity to show graph -> cogwheel top right corner -> entity_id shown in 5th row
