### ISSUE TITLE
Integrations/Template Documentation is out of date

### ISSUE THREAD

**Issue by benkrejci** [home-assistant/home-assistant.github.io#39328]
### Feedback

Many of the examples on this page appear to all use a "legacy" syntax according to the schema warnings in the VS Code add-on. For example, the second example prescribes this trigger sensor:
```
# Example configuration entry
template:
  - triggers:
      - trigger: time_pattern
        # This will update every night
        hours: 0
        minutes: 0
    sensor:
      ...
```
Which is wrong, and I gather based on random forum posts and hunting and pecking should start out something like this:
```
template:
  - trigger:
    - trigger:
        hours: 0
        minutes: 0
    sensor:
      ...
```
Is the current syntax documented anywhere?

### URL

https://www.home-assistant.io/integrations/template/

### Version

2025.5.3

**Comment by Petro31** [comment]
Both

```
# Example configuration entry
template:
  - triggers:
      - trigger: time_pattern
        # This will update every night
        hours: 0
        minutes: 0
    sensor:
      ...
```

and

```
# Example configuration entry
template:
  - trigger:
      - trigger: time_pattern
        # This will update every night
        hours: 0
        minutes: 0
    sensor:
      ...
```

are valid.  `triggers`, `actions`, `conditions` are correct and actually the new style.  The VSCode addon is actually wrong.
