### ISSUE TITLE
Removing light and readding as switch in alexa app wont work

### ISSUE THREAD

**Issue by vancrize** [home-assistant/home-assistant.github.io#39401]
### Feedback

> were automatically added as lights in discovery. Remove each device in the Alexa app. Turn on all the switches in Home Assistant. In the Alexa app go to “Add New Device” select “Switch” and then “other” to add them correctly.

Whatever i try, Alexa adds my input_boolean as a light. I cant use it as a light, because i have to build a skill in the alexa app that reacts to changes in my boolean input.

If i try do discover switches it says it found a light and adds it as light, with no option to change it.

### URL

https://www.home-assistant.io/integrations/emulated_hue/

### Version

2025.5.3

### Additional information

This is my current setup:
```
input_boolean:
  esp32_doorbell_bottom:
    name: ESP32 Doorbell Street
    initial: false

emulated_hue:
  host_ip: 192.168.178.113
  listen_port: 80
  expose_by_default: false
  exposed_domains:
    - input_boolean

  entities:
    input_boolean.esp32_doorbell_bottom:
      name: Klingel Unten
      hidden: false
```
