### ISSUE TITLE
Better example desired

### ISSUE THREAD

**Issue by Pim-Veld** [home-assistant/home-assistant.github.io#39670]
### Feedback

On this page: https://www.home-assistant.io/integrations/button/ an example is given under "Because the state of a button entity in Home Assistant is a timestamp, it means we can use it in our automations." But this example doesn't use a timestamp! I am not the first one complaining about this (see #26866), but in spite of the long discussion over there nothing is done about it.

### URL

https://www.home-assistant.io/integrations/button/

### Version

2025.6.1

**Comment by ecspiegel** [comment]
Would this be a better example? 

```yaml
triggers:
  - trigger: state
    entity_id: button.my_button
    from: 09:00:00
    to: 17:00:00
    # Automation only triggers between 0900 and 1700. 
actions:
  - action: notify.frenck
    data:
      message: "My button has been pressed!"
```

**Comment by frenck** [comment]
No, that example would not work.

**Comment by ecspiegel** [comment]
What would then? Specifically, an example that uses a timestamp, since the lead up text emphasizes that.

**Comment by frenck** [comment]
The fact it is a timestmap, means the state changes as soon as the button is pressed, thus:

```yaml
triggers:
  - trigger: state
    entity_id: button.my_button
actions:
  - action: notify.frenck
    data:
      message: "My button has been pressed!"
```
