### ISSUE TITLE
Undesired Group Displayed

### ISSUE THREAD

**Issue by RonJ103** [home-assistant/home-assistant.github.io#4166]
I think this is a bug.  This test case shows the behavior clearly.

I have defined 3 tabs on the frontend:

```
  test_view1:
    view: yes
    name: "Test 1"
    entities:
      - group.scheduled_items
      
  test_view2:
    view: yes
    name: "Test 2"
    entities:
      - group.outdoor_lights
      
  test_view3:
    view: yes
    name: "Test 3"
    entities:
      - group.scheduled_items
      - group.outdoor_lights
```

The two groups used in the test case are defined as follows:
```
  scheduled_items:
    name: "Scheduled Items"
    entities:
      - light.front_porch_light
      - light.sconce_lights
      - switch.living_room_lamp
      - group.driveway_lights
      - switch.tree

  outdoor_lights:
    name: "Outdoor Lights"
    entities:
      - switch.backyard_light
      - switch.deck_light
      - switch.flood_light
      - light.front_porch_light
      - switch.garage_door_light
      - switch.driveway_light
```

This is what is displayed.  Note that test_view1 and test_view2 work correctly (only display defined gropus) and test_view3 adds an additional group display.

I don't see an option to upload pictures.  The screen shots can be viewed on this thread:
https://community.home-assistant.io/t/groups-displaying-that-i-did-not-specify/35036/6
