### ISSUE TITLE
Drop use of 'delay' in favour of 'wait_template'

### ISSUE THREAD

**Issue by nickfennell** [home-assistant/home-assistant.github.io#4396]
Hi.

Assuming your use of 'delay' is to allow the TTS to complete before SONOS drops back in with your banging tunes. I hit a few snags with latency and such resulting in incomplete messages and premature resumption of the party.

See example below in context:

```
'sonos_say':
    alias: "Sonos TTS script"
    sequence:
     - service: media_player.sonos_snapshot
       data_template:
         entity_id: "{{ sonos_entity }}"
     - service: media_player.sonos_unjoin
       data_template:
         entity_id: "{{ sonos_entity }}"
     - service: media_player.volume_set
       data_template:
         entity_id: "{{ sonos_entity }}"
         volume_level: "{{ volume }}"
     - service: tts.google_say
       data_template:
         entity_id: "{{ sonos_entity }}"
         message: "{{ message }}"
     - wait_template: "{{ states.media_player.sonos.state == 'paused' }}"
     - service: media_player.sonos_restore
       data_template:
         entity_id: "{{ sonos_entity }}"
```

The statement wait_template does not continue until the media_player,sonos,state == Paused which it dose after TTS has finished. This option can be appended with a 'timeout: 00:00:05' to abort of the state is not met.
