### ISSUE TITLE
Gramatical errors with Templates examples, in components web.

### ISSUE THREAD

**Issue by Rapejim** [home-assistant/home-assistant.github.io#4640]
The follow webs:
https://home-assistant.io/components/binary_sensor.template/
https://home-assistant.io/components/cover.template/
https://home-assistant.io/components/light.template/
https://home-assistant.io/components/sensor.template/
https://home-assistant.io/components/switch.template/

The examples have double quotation marks, and it's an error, they must have single quotes.

_Bad example of Template Sensor:_
```
# Example configuration.yaml entry
sensor:
  - platform: template
    sensors:
      solar_angle:
        friendly_name: "Sun angle"
        unit_of_measurement: 'degrees'
        value_template: "{{ states.sun.sun.attributes.elevation }}"

      sunrise:
        value_template: "{{ states.sun.sun.attributes.next_rising }}"
```

**Good example of Template Sensor (the same, but corrected):**
```
# Example configuration.yaml entry
sensor:
  - platform: template
    sensors:
      solar_angle:
        friendly_name: 'Sun angle'
        unit_of_measurement: 'degrees'
        value_template: '{{ states.sun.sun.attributes.elevation }}'

      sunrise:
        value_template: '{{ states.sun.sun.attributes.next_rising }}'
```

And the same error happens in "Template binary sensor", "Template cover", "Template light", "Template switch",...
