### ISSUE TITLE
input datetime "has_date:" not optional

### ISSUE THREAD

**Issue by Supermillhouse** [home-assistant/home-assistant.github.io#4738]
I was unable to remove the "has_date: false" to only have time.
Documentation states it is optional and will default to false if not defined as long as "has_time: true" is defined but doing so always flag a configuration.yaml error when I try this. am I doing something wrong.

```
input_datetime:
  only_time:
    name: Input with only time
    has_time: true
```

should this work?
