### ISSUE TITLE
HomeKit Plugin Hide Devices

### ISSUE THREAD

**Issue by erfind** [home-assistant/home-assistant.github.io#4874]
I think the new native HomeKit Integration is awesome!

Is there any way to exclude or just show specific device types? Or a way to hide specific devices individually?

**Comment by MartinHjelmare** [comment]
If you need help please use our help channels:
https://home-assistant.io/help/#communication-channels

Thanks!

**Comment by VdkaShaker** [comment]
@erfind I know this is old (and possibly not the right forum), but I'm working on updates to the documentation to clarify this:

```
# Example filter to include specified domains and exclude specified entities
homekit:
  filter:
    include_domains:
      - alarm_control_panel
      - light
    exclude_entities:
      - light.kitchen_light
```

Filters are applied as follows:

- No includes or excludes - pass all entities
- Includes, no excludes - only include specified entities
- Excludes, no includes - only exclude specified entities
- Both includes and excludes:
   - Include domain specified
      - if domain is included, and entity not excluded, pass
      - if domain is not included, and entity not included, fail
   - Exclude domain specified
      - if domain is excluded, and entity not included, fail
      - if domain is not excluded, and entity not excluded, pass
      - if both include and exclude domains specified, the exclude domains are ignored
   - Neither include or exclude domain specified
      - if entity is included, pass (as #2 above)
      - if entity include and exclude, the entity exclude is ignored
