### ISSUE TITLE
How to use DoorBird doorbell_events?

### ISSUE THREAD

**Issue by northhacks** [home-assistant/home-assistant.github.io#4932]
I am able to see that the callback URL is registered in the DoorBird App. When I try this URL with my Browser I got a OK back. But how could I use that the events published to the event bus. Is there a way to use it in Automations oder as a Sensor?

Thanks

**Comment by arsaboo** [comment]
Please ask configuration questions in the [forums](https://community.home-assistant.io/). Here's one example of how you can use events in an automation. I guess, the docs need to improved, feel free to open a PR. 
```
- alias: Doorbell
  trigger:
  - platform: event
    event_type: doorbird_doorbell
  action:
  - service: logbook.log
    data:
      name: Doorbell
      message: rang
```
