### ISSUE TITLE
Problem with Samsung Tv component

### ISSUE THREAD

**Issue by NikosVlagoidis** [home-assistant/home-assistant.github.io#5033]
Autodiscover finds my Samsung tv. But then I cannot do anything.

Updating samsungtv media_player took longer than the scheduled update interval 0:00:10 9:21 PM helpers/entity_component.py (WARNING)

I then tried to put on configuration  and also install websocket-client but nothing seems to be working. Any ideas?:

```yaml
media_player:
  - platform: samsungtv
    host: 192.168.0.10
    port: 8001
```
I see 2 TVs now but it is not working either.
