### ISSUE TITLE
dialogflow require speech: or hangs

### ISSUE THREAD

**Issue by antoniosap** [home-assistant/home-assistant.github.io#5107]
i have a configuraton as...

...
```
intent_script:
  blinds-down-intent:
    action:
      service: cover.close_cover
    speech:
      text: the cover is closing
```
...

if speech tag is not present, the dialogflow answer my json answer and hangs up [app test]
if speech tag is present text: override my default answer on cloud and return DialogFlowResponse
