### ISSUE TITLE
documentation example for recorder component incorrect for sqlite database file path

### ISSUE THREAD

**Issue by lmamakos** [home-assistant/home-assistant.github.io#5276]
In `source/_components/recorder.markdown` the example for an sqlite database is cited as:

```yaml
# Example configuration.yaml entry with exclude
recorder:
  purge_keep_days: 5
  db_url: sqlite:///home/user/.homeassistant/test
```

when the path probably ought to be something like:

```yaml
  db_url: sqlite:////home/user/.homeassistant/test
```
instead.  Note there should be 4 `/` characters for an absolute path after the `sqlite:`, not 3.  

In my configuration, a path like `sqlite:////Users/louie/hass/db/home-assistant_v2.db` works, while `sqlite:///Users/louie/hass/db/home-assistant_v2.db` did not work.  This on macOS.
