### ISSUE TITLE
Issue with Lovelace weblink and divider

### ISSUE THREAD

**Issue by edoardop13** [home-assistant/home-assistant.github.io#5872]
I followed this guide: https://home-assistant-lovelace-gallery.netlify.com/#demo-hui-entities-card, but when I add this:
```
- type: entities
        entities:
          - type: weblink
            name: Router
            url: http://192.168.1.1/
            icon: mdi:router-wireless
```

I got the following errors: "entity object at position 0 is missing entity field"

**Comment by tjorim** [comment]
As far as I know that's not the official documentation. That can be found [here](https://www.home-assistant.io/lovelace/).
Regarding the [Entities Card](https://www.home-assistant.io/lovelace/entities/), it simply needs an `entity`, which you don't provide.


If you had an existing weblink entity...
```yaml
# example configuration.yaml
weblink:
  entities:
    - name: Router
      icon: mdi:router-wireless
      url: http://192.168.1.1/
```
I would think adding it like this might work:
```yaml
# example ui-lovelace.yaml
- type: entities
  entities:
    - weblink.router
```
However that gives a not clickable link as I just tested.


A better solution (as far as I know) is a [Markdown Card](https://www.home-assistant.io/lovelace/markdown/). Here is an example that could work for you:
```yaml
# example ui-lovelace.yaml
- type: markdown
  title: Weblinks
  content: >
    ![Router](https://materialdesignicons.com/api/download/icon/png/3244EAC8-8349-4CFB-BE35-A0812368CEDA)
    [Router](http://192.168.1.1/)
```

This is the result I get for both options:
![image](https://user-images.githubusercontent.com/1294876/43142159-087f4fc0-8f58-11e8-9742-7b7bdc8589fc.png)

Note: I hotlinked to an image, you shouldn't do that. [Save the image file on your installation instead.](https://www.home-assistant.io/components/http/#hosting-files)
