### ISSUE TITLE
Switch docu possibly wrong?

### ISSUE THREAD

**Issue by NicoHood** [home-assistant/home-assistant.github.io#6299]
https://github.com/home-assistant/home-assistant.io/blob/current/source/_components/switch.template.markdown#-linkable_title-sensor-and-two-switches-

I cannot see any 2nd switch there. I might missunderstand. I expected an example where 1 sensor controls 2 other switches at the same time. For example to control 2 led strips.

**Comment by point-4ward** [comment]
Does this not work? 

```
switch:
  - platform: template
    switches:
      skylight:
        friendly_name: "Skylight and curtains"
        value_template: "{{ is_state('sensor.skylight', 'on') and is_state ('sensor.curtains', 'on') }}"
        turn_on:
          service: switch.turn_on
          entity_id:
            - switch.skylight_open
            - switch.curtains_open
        turn_off:
          service: switch.turn_on
          entity_id:
            - switch.skylight_close
            - switch.curtains_close
```

Presuming it does, and I think it should, this is explained in the various getting started pages, such as https://www.home-assistant.io/docs/configuration/yaml/. Putting every eventuality in to each example makes them too complicated, but by all means you could add a PR with an additional example, or I'll do the PR for you if you paste me a working real world example from your setup?

**Comment by NicoHood** [comment]
Hi,
I did not test that yet, but that is an example I would expect. Look at the link above. I've linked to a specific headline/section. I guess your example is what should have been placed there. Otherwise the descriptional text above the example seems wrong.

**Comment by fabaff** [comment]
Well, `switch.skylight_open` and `switch.skylight_close` are two switches. The example by @mf-social covers four switches.

**Comment by nwesterhausen** [comment]
I have a set a Z-Wave switches controlling the lights in one of my room. To be able to switch them all at once, I put them into a group. I then can turn the group on and off, and when I put the group on an entity card it gives me a toggle. @NicoHood if your LED strips just need turned on and off using a group would be better.

For example, I have two dimmers (which show up in the light domain) and two switches:

```
group:
  recroom_lights:
    icon: mdi:lamp
    entities:
      - switch.recroom_ceiling
      - switch.recroom_corner
      - light.recroom_table
      - light.recroom_wall
```

Then in lovelace I simply have that entity in an entity card and I have a nice toggle to turn them all on or off.

```
      - type: entities
        title: Rec Room
        id: recroomcontrol
        show_header_toggle: false
        entities:
          - entity: group.recroom_lights
            name: All Recroom Lights
```

If you wanted to control that group from any automations, you can use the `homeassistant.turn_on` and `homeassistant.turn_off` service calls.

As far as documentation goes, I used the searchbox on the documentation site and it was not very useful. But I did find the [group component page](https://www.home-assistant.io/components/group/) which discusses a very similar use case:

> If all entities in a group are switches or lights then Home Assistant adds a switch at the top of the card that turns them all on/off at once.

However, the main focus of that component page is using groups for views and cards with the frontend. When we move to lovelace as the default, we will need to modify that page.
