### ISSUE TITLE
Automation condition possibly wrong?

### ISSUE THREAD

**Issue by NicoHood** [home-assistant/home-assistant.github.io#6345]
https://github.com/home-assistant/home-assistant.io/blob/current/source/_docs/automation/condition.markdown
```yaml
automation:
- alias: 'Enciende Despacho'
  trigger:
    platform: state
    entity_id: sensor.mini_despacho
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: '{% raw %}{{ states.sun.sun.attributes.elevation < 4 }}{% endraw %}'
      - condition: template
        value_template: '{% raw %}{{ states.sensor.sensorluz_7_0.state < 10 }}{% endraw %}'
  action:
    - service: scene.turn_on
      entity_id: scene.DespiertaDespacho
```

It says `condition: or conditions`. But for me only `condition` worked. Could you please verify and cross that line out, if correct?

**Comment by point-4ward** [comment]
The code there is correct.

When you use an OR or AND condition, you then specify which conditions to compare under the `conditions:` key in a list.

**Comment by NicoHood** [comment]
And if you have a single condition? I had to put it under `condition`. I expected to use `conditions`, so If i add another condition its already in the same list. Thats is quite confusing. But is this by design?

My example:
```yaml
  - alias: "Get TallonIV System Volume"
    trigger:
      - platform: state
        entity_id: sensor.talloniv_system_volume
      - platform: homeassistant
        event: start
    condition:
      - condition: template
        value_template: "{{ states.input_number.talloniv_system_volume.state != states.sensor.talloniv_system_volume.state }}"
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.talloniv_system_volume
          value: "{{ states.sensor.talloniv_system_volume.state }}"
```
