### ISSUE TITLE
Basic authentication reverse proxy (NGINX) and login mechanism (HA) overwrite the same authorisation header

### ISSUE THREAD

**Issue by vincentcox** [home-assistant/home-assistant.github.io#6350]
When you use NGINX to (reverse) proxy the Home Assistant, but want to use basic authentication to password protect it (for let's say the outside world) it won't work.

![image](https://user-images.githubusercontent.com/9286611/45951259-16843c80-c003-11e8-8672-9d032f322a2a.png)

With the NGINX basic authentication you use the authorization-header. However, home assistant also uses the authorization-header (and overwrites this header). This way, if you log into hom-assistant, you are not authorized anymore by the NGINX reverse proxy. When you reload your page, it asks to log in again on reverse proxy.

Related documentation:
https://github.com/home-assistant/home-assistant.io/blob/current/source/_docs/ecosystem/nginx_subdomain.markdown

My partial nginx config:

```
geo $authentication {
                default "Authentication required";
                127.0.0.1 "off";
                192.168.1.1/24 "off";
        }
location / {
                auth_basic $authentication;
                auth_basic_user_file /etc/nginx/.htpasswd;
		proxy_pass http://<ip-home-assistant>:8123/;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Scheme $scheme;
                proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";					
        }
```

**Comment by vincentcox** [comment]
A solution can be "trusted networks", but it will be taken out in the future?

https://github.com/home-assistant/home-assistant.io/blob/current/source/_docs/authentication/providers.markdown#-linkable_title-trusted-networks-


**linkable_title Trusted Networks**

With the trusted networks auth provider you can whitelist an IP range for which no authentication will be required. The user will be prompted to pick a user to log in as.

<p class='note info'>
The [multi-factor autentication module](../multi-factor-auth) will not participate in login process by using this auth provider.
</p>

```yaml
homeassistant:
  auth_providers:
   - type: trusted_networks

# Temporary, this will be moved to be part of auth provider config
# https://github.com/home-assistant/home-assistant/issues/16149
http:
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.0.0/24
    - fd00::/8
```
