### ISSUE TITLE
Use the new style for configuration variables description

### ISSUE THREAD

**Issue by fabaff** [home-assistant/home-assistant.github.io#6385]
A while back an [advance way to describe the configuration variables](https://developers.home-assistant.io/docs/en/documentation_create_page.html#configuration) was introduced. 

```yaml
{% configuration %}
api_key:
  description: The API key to access the service.
  required: true
  type: string
name:
  description: Name to use in the frontend.
  required: false
  default: The default name to use in the frontend.
  type: string
{% endconfiguration %}
```

At the moment not all platform and component documentation is ported to the new style.

This the tracking issue. Please don't close but add as a reference to your Pull request.
