### ISSUE TITLE
Appdaemon configuration page appears to be out of date

### ISSUE THREAD

**Issue by borpin** [home-assistant/home-assistant.github.io#6549]
The Appdaemon configuration page appears to be out of date.

https://github.com/home-assistant/home-assistant.io/blob/current/source/_docs/ecosystem/appdaemon/configuration.markdown

My default appdaemon.yaml is like this
```
secrets: /config/secrets.yaml
log:
  logfile: STDOUT
  errorfile: STDERR
appdaemon:
  threads: 10
  app_dir: /config/appdaemon/apps
  plugins:
    HASS:
      type: hass
      ha_url: http://hassio/homeassistant
      ha_key: xxxxxxxxxxxxxxxxxxxxxxxx
hadashboard:
  dash_url: http://127.0.0.1:5050
  dash_dir: /config/appdaemon/dashboards
```
