### ISSUE TITLE
Edit HA documention

### ISSUE THREAD

**Issue by sirs2k** [home-assistant/home-assistant.github.io#6550]
Thanks for the great component guys, 

I don't know why there's no mention of this ability anywhere I looked but it's indeed very useful and should be reflected in the documentation.

It's possible to include templates in the notification that goes out to the devices by including the template in the "name" variable of the Alert.

For example
```
alert:
  garage_door:
    name: Garage has been open for {{ relative_time(states.binary_sensor.garage.last_changed) }}
    done_message: Garage is closed
    entity_id: binary_sensor.garage
    state: 'on'
    repeat:
      - 30
      - 60
      - 120
    can_acknowledge: True
    skip_first: True
    notifiers:
      - my_phone_join
```

Apart from that, I only wish that it was possible to send out Actionable notifications like the HTML5 or the new HANotify based on FCM. That along with templates would make this component almost perfect...
