### ISSUE TITLE
New lovelace thermostat card doesn't show in the card

### ISSUE THREAD

**Issue by novikovav69** [home-assistant/home-assistant.github.io#7196]
I placed this code in my ui-lovelace.yaml and configuration.yaml
```yaml
ui-lovelace.yaml:
    cards:
      - id: 3d34127671ae4cfe8b9ac6e021612ac3  # Automatically created id
        type: thermostat
        entity: climate.Study
configuration.yaml:
climate:
  - platform: generic_thermostat
    name: Study
    heater: switch.torsher
    target_sensor: sensor.temperature_158d0002270b28
    min_temp: 5
    max_temp: 35
```

But the thermostat card did not appear on the screen.
what did i do wrong?
