### ISSUE TITLE
template sensor change #17276 doesn't work as described in #7159

### ISSUE THREAD

**Issue by tedstriker** [home-assistant/home-assistant.github.io#7398]
Using HA 0.81.6

In PR #17276 the template sensors update behaviour has been changed.
Despite using `entity_ids` the sensor is not updated automatically.
It seems like device_tracker.my_phone is not recognised anymore as described in pull request #7159.
Behaviour was fine in 0.80.x and before.

here's the sensors code:
```
people_counter:
  value_template: >
    {{ (dict(states.device_tracker|groupby('state'))['home']|length) }}
  entity_id: device_tracker.my_phone
```

the device trackers type is `mqtt_json`
