### ISSUE TITLE
Rainmachine configuration documentation is incorrect.

### ISSUE THREAD

**Issue by leoruiz** [home-assistant/home-assistant.github.io#7828]
As of commit https://github.com/home-assistant/home-assistant/commit/08702548f3b74b07923fc49d37533303e7196524
in 0.84.1 the documentation for rain machine is incorrect.
```
rainmachine:
  ip_address: 192.168.1.100
  password: YOUR_PASSWORD
  binary_sensors:
    # binary sensor configuration options...
  sensors:
    # sensor configuration options...
  switches:
    # switch configuration options...
```

shoud probably be:

```
rainmachine:
  controllers:
    - ip_address: 192.168.1.100
      password: YOUR_PASSWORD
      binary_sensors:
        # binary sensor configuration options...
      sensors:
        # sensor configuration options...
      switches:
        # switch configuration options...
```
