### ISSUE TITLE
Aqara Air Conditioning Companion (lumi.acpartner.v3) is not appeared in the homeassistant

### ISSUE THREAD

**Issue by carlyang1986** [home-assistant/home-assistant.github.io#7871]
I want to use Aqara Air Conditioning Companion (lumi.acpartner.v3) as the gateway access to homeassistant. During hass start wo noticed the xiaomi_aqara gateway is detect by homeassitant and found 2 devices. But I can't see any devices(the weather and humidity sensor of lumi.sensor which has accessed in this air conditioner) or the gateway in the website. The homassistant has been upgrade to newest 0.84.2 version. The code in configuration.yaml is:
```yaml
# aqara gateway
xiaomi_aqara:
  discovery_retry: 10
  interface: '192.168.2.124'
  gateways:
   - mac: 7c49eb7fd832
     key: 8ks9nc3xencmcxdu
     host: 192.168.2.64
```

The discription during hass start is:
```
Discovering Xiaomi Gateways (Try 1)
2018-12-16 07:45:21 INFO (SyncWorker_6) [xiaomi_gateway] Xiaomi Gateway 7c49eb7fd832 configured at IP 192.168.2.64:9898
2018-12-16 07:45:21 INFO (SyncWorker_6) [xiaomi_gateway] Discovering Xiaomi Devices
2018-12-16 07:45:21 INFO (SyncWorker_6) [xiaomi_gateway] Found 2 devices
```

I had open multicast function of my router.
![image](https://user-images.githubusercontent.com/30430231/50048720-a02d3d00-010e-11e9-9e1a-a57a28f404aa.png)
![image](https://user-images.githubusercontent.com/30430231/50048731-d10d7200-010e-11e9-8e8a-04d4d6f260f5.png)
![image](https://user-images.githubusercontent.com/30430231/50048733-dcf93400-010e-11e9-8c90-6d6c91d32d5a.png)
