### ISSUE TITLE
Documentation issue on !include_dir_merge_named

### ISSUE THREAD

**Issue by dagobert** [home-assistant/home-assistant.github.io#7882]
https://github.com/home-assistant/home-assistant.io/blob/current/source/_docs/configuration/splitting_configuration.markdown

I have just read about splitting the configuration file. In your last explanation about `!include_dir_merge_named` I stumbled on a possible mistake.
As I understand it the ...`named`... part in this "command" means that the filename in a directory will be used as a YAML identifier when merging. It is described like this in the section `!include_dir_named`. Therefore the pre-split example for `!include_dir_merge_named` should be like the following?

```
group:
  interior:
    bedroom:
      name: Bedroom
      entities:
        - light.bedroom_lamp
        - light.bedroom_overhead
    hallway:
      name: Hallway
      entities:
        - light.hallway
        - thermostat.home
  exterior:  
    front_yard:
      name: Front Yard
      entities:
        - light.front_porch
        - light.security
        - light.pathway
        - sensor.mailbox
        - camera.front_porch
```

Notice the missing identifier `interior` and `exterior`.

**Comment by nwesterhausen** [comment]
No it wouldn't have those identifiers when using `!include_dir_merge_named`. The `merge_named` is for importing named items to be part of a dictionary (in this case, groups), and the files get merged and put as children where the include is.

To get what you describe with the interior and exterior you actually would use `!include_dir_named`.

The `merged` includes just combine what files are being included and put them in place where you include them. I don't know if I made much sense, please ask for clarification if you need it.

**Comment by dagobert** [comment]
Thank you for your answer.
I am sorry that I misread the whole thing. I am relatively new. Probably because of the way the examples were chosen, I was under the impression, that the directory name was also taken into account such as:

```
groups:
  interior:
    bedroom:
      ....
```

 This could also be split into

```
groups:
```

and file `groups/interior/bedroom.yaml`

```
bedroom:
```

I was probably thinking to complicated.

If I understand correctly `..._list_...` and `..._named_...` refer to the YAML concept of lists ans names. For someone who is not perfectly familiar of YAML this was not obvious. Shame on me not to think about this first.

Now that I know this, one thin I did not read about was when or why should I use `..._merged_...` compared to not merged.
