### ISSUE TITLE
Document snapshots (and services)

### ISSUE THREAD

**Issue by tjorim** [home-assistant/home-assistant.github.io#7968]
Currently there is no documentation on snapshots yet (AFAIK).
This should be considered to add (as well as the service calls).

- hassio.snapshot_full
- hassio.snapshot_partial
  - addons
  - folders

This is just an issue to remind me to create those docs,
if someone else can do it or it already exists that's fine.

Should probably go somewhere here: https://www.home-assistant.io/hassio/

**Comment by klaasnicolaas** [comment]
I want to help where necessary 😉 
I also learned last week that these services existed.

**Comment by Bennekom** [comment]
Yes, want to help. Was already surprised had no documentation in the dev.tools.

With a little bit of trail and error was i able to this syntax.

{ 
  "name":"test",
  "password":"testing123"
}

**Comment by klaasnicolaas** [comment]
Would like to start with some text and example script, etc. Only I have no idea how to add images or add the page to the menu.

**Comment by tjorim** [comment]
If adding to the place I suggested these would be the steps I think:
(**disclaimer:** just tried to figure it out myself, I know almost nothing about Jekyll)

1. Create a new file [here (/source/hassio)](https://github.com/home-assistant/home-assistant.io/tree/current/source/hassio), e.g. `snapshots.markdown` (base it on commandline.yaml or similar). What it is (basically simply a good backup), the services...
1. Edit the 'include hassio navbar-file' to add a link to the page in the sidebar nav [here (/source/_includes/asides)](https://github.com/home-assistant/home-assistant.io/blob/current/source/_includes/asides/hassio_navigation.html). Something like `<li>{% active_link /hassio/snapshots/ Snapshots %}</li>`.
1. Screenshots an other images would go in [here (/source/images/hassio)](https://github.com/home-assistant/home-assistant.io/tree/current/source/images/hassio), and embedded in the page created in step 1 like
    ```
    <p class='img'>
    <img src='/images/hassio/example.png'>
    A nice description of the image that would be placed below it
    </p>
    ```
<br>

@klaasnicolaas Do you plan on doing it ~~later tonight~~ ~~today~~ in the coming hours (ugh, timezones)? Otherwise I might take a shot.
<br>

_Extra things I would consider:_

- Currently the general docs mentions 3 types of backup in the sidebar as seen on the following page: https://www.home-assistant.io/docs/
- Add a link to the snapshots page as well (clearly name it Hass.io snapshots to avoid confusion)
- Maybe make the 'Backup' parent itself a link as well, with a new short page that describes the 3 (4 with the snapshots) options. Mainly to tell users the first 3 options (that already are there) is actually to use on a non-Hass.io-system (theoretically it could work on Hass.io I think) and that the snapshots feature is only available on Hass.io installations.

_Slightly off-topic:_

- I actually think that all those different pages (with sometimes seperate sidenavs and/or url paths) should be cleaned up but that's an issue for another time.

**Comment by klaasnicolaas** [comment]
Unfortunately, I did not have the time yet, I took a quick look at your PR and posted a comment with a link to a part of my config which you could use as an example script.

**Comment by Jpsy** [comment]
This is what I found out about the available services.  
They are shown in form of complete automations (nearly) ready to use.

### Full Backup:

```yaml
automation:
  - alias: Weekly Full Backup, Friday 03:00
    initial_state: 'on'
    trigger:
      platform: time
      at: '03:00:00'
    condition:
    - condition: time
      weekday:
        - fri
    action:
    - service: hassio.snapshot_full
      data_template:
      name: Automatic Full Backup {{ now().strftime('%Y-%m-%d') }}
```
### Partial Backup

```yaml
automation:
  - alias: Weekly Partial Backup, Friday 03:00
    initial_state: 'on'
    trigger:
      platform: time
      at: '03:00:00'
    condition:
    - condition: time
      weekday:
        - fri
    action:
    - service: hassio.snapshot_partial
      data_template:
        name: Automatic Partial Backup {{ now().strftime('%Y-%m-%d') }}
        addons:
          - a0d7b954_jupyterlablite
          - a0d7b954_motioneye
          - a0d7b954_nodered
          - 3833edd4_googlebackup
          - core_check_config
          - core_configurator
          - core_samba
          - core_ssh
        folders:
          - homeassistant
          - share
          - ssl
          - addons_local.tar
```

### Methods to geht the identifiers for addons and folders:

#### Method 1:
Do a full backup, copy the tar to your PC and unpack it. It contains sub-tars. Their names are the identifiers, but you have to guess a bit which ones are folders and which ones addons.

#### Method 2 (addons only):
Go to the addons config page (Hass.io --> Dashboard --> click an addon). The last path segment of the URL is the identifyer. 

#### Method 3 (addons only):
Do a full backup and check the system log (Hass.io --> SYSTEM).  
You will find entries that and with the identifiers of all addons. 
```log
19-02-09 17:55:29 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on core_ssh
19-02-09 17:55:29 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on core_check_config
19-02-09 17:55:30 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on a0d7b954_jupyterlablite
19-02-09 17:55:30 INFO (MainThread) [hassio.addons.addon] Build snapshot for add-on a0d7b954_nodered
```
The folders are in there too but with correct folder names instead of identifiers.

**Comment by robbinjanssen** [comment]
@Jpsy quick question, is `- addons_local.tar` something for your setup specific? Or is this something the snapshot service creates and saves?

**Comment by Jpsy** [comment]
@robbinjanssen to be honest, I don't remember. Looks strange to me too, now that I read it again.

**Comment by robbinjanssen** [comment]
@Jpsy looks like it's `addons/local` now. This seems to work for me:

```yaml
script:
  hassio_create_backup:
    alias: "Create snapshot"
    sequence:
      - service: hassio.snapshot_partial
        data_template:
          name: "{{ now().strftime('%Y_%m_%d') }}_hassio"
          password: !secret snapshot_password
          addons: 
            - 8aef3602_dropbox_upload
            - core_mariadb
            - core_mosquitto
            - a0d7b954_nodered
            - core_ssh
          folders:
            - homeassistant
            # - share
            - ssl
            - addons/local
```
