### ISSUE TITLE
Lovelace picture-glance improvement

### ISSUE THREAD

**Issue by FrankXLT** [home-assistant/home-assistant.github.io#8354]
I would like to suggest the following improvements to the lovelace picture-glance card.  Incorporate an entity's attribute list that you want to be displayed.  For example, my cameras (synology proxy) show recording as their state, hence why they are included as an entity, however motion detection is an attribute and I have no way of including that as a status icon in the picture-glance card.  For each attribute, allow us to include an icon for the different values.  Here is an example of where I see this could go.

```
- type: picture-glance
  title: Driveway
  entities:
    - camera.driveway
  camera_image: camera.driveway
  state_icon:
    "Recording": mdi:record
    "Not Recording": mdi:stop
  attributes_icon:
    - motion_detection: 
        "True" : mdi:run-fast
```

Thanks!

V/R,
Frank
