### ISSUE TITLE
picture-elements with state-icon element style issue

### ISSUE THREAD

**Issue by damyanor** [home-assistant/home-assistant.github.io#8638]
When state-icon is used with style which changes the icon size (--iron-icon-width and --iron-icon-height), the icon is not placed as expected.  Example:
```
- image: /local/background.jpg
  type: picture-elements
  elements:
    - type: state-icon
      entity: sensor.ha_update
      style:
        '--iron-icon-width': 100px
        '--iron-icon-height': 100px
        top: 50%
        left: 50%
      tap_action: more-info
    - type: state-label
      entity: sensor.ha_update
      style:
        top: 90%
        left: 50%
```
results in:
![notok](https://user-images.githubusercontent.com/46784312/53021215-fd1fd900-3458-11e9-81e1-279cec0e1290.jpg)
Without --iron-icon-width and  --iron-icon-height params it is centered correctly.

Testing the same style with a static icon like `type: icon` works fine:
```
- image: /local/background.jpg
          type: picture-elements
          elements:
            - type: icon
              icon: mdi:checkbox-marked-circle-outline
              style:
                '--iron-icon-width': 100px
                '--iron-icon-height': 100px
                top: 50%
                left: 50%
              tap_action: more-info
            - type: state-label
              entity: sensor.ha_update
              style:
                top: 90%
                left: 50%
```
![ok](https://user-images.githubusercontent.com/46784312/53021454-8800d380-3459-11e9-9053-54242ef33cd4.jpg)
but it is not a solution in some use cases (in my case - sensor template which changes icon depending on HA update availability, but also entities which require more complex conditions for state definition).
