### ISSUE TITLE
Frontend bug with multiple cards horizontal

### ISSUE THREAD

**Issue by pimoon** [home-assistant/home-assistant.github.io#8736]
If I have multiple light cards in an horizontal card, they are shrink : 
![capture d ecran 2019-02-25 a 23 53 46](https://user-images.githubusercontent.com/46498300/53374445-a3d41000-3958-11e9-82c2-94481f3157e7.png)

```
      - type: horizontal-stack
        cards:
        - type: light
          entity: light.salon_1
        - type: light
          entity: light.salon_2
        - type: light
          entity: light.chambre_1
        - type: light
          entity: light.chambre_2
        - type: light
          entity: light.toilette
        - type: light
          entity: light.sdb
        - type: light
          entity: light.bureau
```
