### ISSUE TITLE
Light entity icon disappears when overwriting brightness state attribute via API or dev-state

### ISSUE THREAD

**Issue by ronschaeffer** [home-assistant/home-assistant.github.io#8783]
Raising an issue here, because it seems to have stumped the Community.

Using curl via a terminal, the dev-service page and a rest_command to overwrite the brightness attribute of a light results in the light entity icon in the frontend disappearing. The behavior is the same in Lovelace and States. Simply setting on or off state without brightness toggles the icon between blue and yellow as expected.

I have tried this with both rfxtrx: and mqtt: lights.

Examples:

```
curl -X POST -H "Authorization: Bearer MYTOKEN" \
-H "Content-Type: application/json" \
-d '{"state": "on", "attributes": {"brightness": "100"}}' \
"http://192.168.xxx.xxx:8123/api/states/light.office_light"
```
![image](https://user-images.githubusercontent.com/12379923/53583150-e411d900-3b78-11e9-8827-2c1761e6416b.png)

```
set_office_light_on_brightness:
  url: http://localhost:8123/api/states/light.office_light
  method: POST
  headers: 
    authorization: !secret api-token-with-bearer
    content-type: 'application/json'
  payload: '{"state": "on", "attributes": {"brightness": "100"}}'
```

All three commands are successful with the same result in the dev-state panel:

![image](https://user-images.githubusercontent.com/12379923/53583188-f8ee6c80-3b78-11e9-89c8-df934b74888d.png)

However, the on/off light bulb icon indicator disappears (actually goes white, I think) in all of the UI views I’ve tried:

Lovelace Light Card
```
entity: light.office_light
name: Office
type: light
```
Lovelace Entity Card
```
entity: light.office_light
hold_action:
  action: more-info
name: Office
tap_action:
  action: toggle
type: entity-button
```
and the States UI.

Here is an example of what the Lovelace Light Card looks like after issuing the API call:

![image](https://user-images.githubusercontent.com/12379923/53583421-74501e00-3b79-11e9-9a4a-2c4fff3750bc.png)

The brightness slider displays the value correctly, but the light bulb is missing.

Happy to provide more info and/or test as needed.
