### ISSUE TITLE
DSMR documentation incorrect

### ISSUE THREAD

**Issue by JanLankhorst** [home-assistant/home-assistant.github.io#9366]
The next release will no longer support the current setup of the DSMR compnent. A change in the documentation is required; Home assistant frontend reports: 'group', 'meter readings' etc are no longer valid.

`group:
  meter_readings:
    name: Meter readings
    entities:
      - sensor.power_consumption_low
      - sensor.power_consumption_normal
      - sensor.power_production_low
      - sensor.power_production_normal
      - sensor.gas_consumption`

[https://www.home-assistant.io/components/dsmr/](url)

**Comment by klaasnicolaas** [comment]
I think this is due to a typo in your own config. Nothing changes with the dsmr component

**Comment by JanLankhorst** [comment]
Well it all started with this warning message..

![Capture](https://user-images.githubusercontent.com/38151193/57141564-c6e8c900-6dba-11e9-976d-e9f0dbef0090.JPG)

This is the code that still works but triggers the warning message:
`- platform: dsmr
  port: /dev/ttyUSB0
  dsmr_version: 5
  group:
    meter_readings:
      name: Meter readings
      entities:
        - sensor.power_consumption_low
        - sensor.power_consumption_normal
        - sensor.power_production_low
        - sensor.power_production_normal
        - sensor.gas_consumption`
I really don't have a clue what is wrong here..
thanks

**Comment by JanLankhorst** [comment]
```
- platform: dsmr
  port: /dev/ttyUSB0
  dsmr_version: 5
  group:
    meter_readings:
      name: Meter readings
      entities:
        - sensor.power_consumption_low
        - sensor.power_consumption_normal
        - sensor.power_production_low
        - sensor.power_production_normal
        - sensor.gas_consumption
```

**Comment by klaasnicolaas** [comment]
You are wrong in your own config.

The first 3 lines belong to the DSMR component. The rest is a separate block from the group component. This is how you must do it:

```yaml
sensor:
  - platform: dsmr
    port: /dev/ttyUSB1
    dsmr_version: 5

group:
  meter_readings:
    name: Meter readings
    entities:
      - sensor.power_consumption_low
      - sensor.power_consumption_normal
      - sensor.power_production_low
      - sensor.power_production_normal
      - sensor.gas_consumption
```
