### ISSUE TITLE
GCP pub/sub config description error

### ISSUE THREAD

**Issue by robmarkcole** [home-assistant/home-assistant.github.io#9465]
The [pub/sub docs](https://www.home-assistant.io/components/google_pubsub/) list filter as `optional` but it is in fact required. Also an example of filter config should be included as [it is required](https://github.com/home-assistant/home-assistant/blob/6b359c95daaa50876d574c5168ddaf57afb37a08/homeassistant/components/google_pubsub/__init__.py#L30), e.g.
```yaml
google_pubsub:
  project_id: stretchpi-169512
  topic_name: stretchhass
  credentials_json: stretchbuntu-8fd573d38582.json
  filter:
    include_domains:
      - light
      - media_player
```
Ping @timvancann
