### ISSUE TITLE
How to use 2 base url for http

### ISSUE THREAD

**Issue by RexS98** [home-assistant/home-assistant.github.io#9749]
According to the instruction, should be 
```
http:
  ssl_certificate: /config/ssl/fullchain.pem
  ssl_key: /config/ssl/privkey.pem
  base_url: https://xxxx:8123
```

But think is it possible to include 2 base url. 
Trying to write like
```
 base_url: 
  - https://xxxx:8123
  - https://yyyy:8123
```
But failed. 
for SSL file, already include both domain. 
Any suggestions?
