### ISSUE TITLE
Typo in Mi Flora docs

### ISSUE THREAD

**Issue by Anonym-tsk** [home-assistant/home-assistant.github.io#9908]
https://www.home-assistant.io/components/miflora/
Typo in example:
```
sensor:
  - platform: miflora
    mac: 'xx:xx:xx:xx:xx:xx'
    name: Flower 1
    force_up    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
```
